/*
	SELECT 
		*
	FROM LY_ITEM_LANC 
	WHERE
		cobranca IN (47567)
		and descricao like 'Mens%'
	GROUP BY COBRANCA

	select * from ly_aluno where aluno in('C201700096')
	select * from ly_cobranca where cobranca IN (74568)
	select * from VW_FCAV_COBRANCA_DEB_CRED where cobranca IN ( 47567)
	select * from VW_FCAV_RELAT_BOLETOS_EMITIDOS_CONTAB where cobranca IN ( 47567)
	select * from VW_FCAV_BOLETOS_EMITIDOS_CONTAB where cobranca IN ( 47567)

*/
ALTER VIEW VW_FCAV_RELAT_BOLETOS_EMITIDOS_CONTAB
AS

WITH ALUNOS_BOLETOS AS
(
	SELECT
		AL.ALUNO, 
		AL.NOME_COMPL, 
		AL.SIT_ALUNO, 
		CS.CURSO,
		il.NATUREZA,
		CO.COBRANCA, 
		IL.DATA DATA_DE_VENCIMENTO, 
		IL.DESCRICAO, 
		CO.DATA_DE_GERACAO AS DATA_DE_EMISSAO, 
		BO.NUMERO_RPS,
		BO.DATA_EMISSAO_RPS, 
		CASE WHEN DC.ACORDO != 0 THEN 'Baixa por Acordo'
			 WHEN DC.ACORDO = 0 AND DC.SALDO = 0 THEN 'Boleto Pago'
			 WHEN (DC.PAGAR < ABS(DC.PAGO) AND DC.PAGAR > 0) THEN 'Valor pago a mais'
			 WHEN (DC.PAGAR < 0) THEN 'Ajustar no Sistema'
			 WHEN (CO.DATA_DE_VENCIMENTO >= GETDATE() AND DC.SALDO > 0) THEN 'A Vencer'
			 WHEN (CO.DATA_DE_VENCIMENTO < GETDATE() AND DC.SALDO > 0) THEN 'Vencido'
			 WHEN (DC.PAGAR >  DC.PAGO AND DC.SALDO > 0) THEN 'Boleto parcialmente pago'
		END AS SITUACAO_BOLETO, 
		DC.DEBITO AS VALOR_FATURADO, 
		DC.MULTA_JUROS, 
		DC.ACRESC_IGPM,
		DC.DESCONTO,
		DC.ACORDO,
		DC.BOLSA, 
		DC.PAGAR AS VALOR_PAGAR, 
		DC.PAGO AS VALOR_PAGO, 
		DC.SALDO
	FROM 
		LY_ALUNO AL
		LEFT JOIN LY_COBRANCA CO
			ON CO.ALUNO = AL.ALUNO
		inner JOIN LY_ITEM_LANC IL
			ON IL.COBRANCA = CO.COBRANCA
			AND IL.DESCRICAO like '%Mens%'
		LEFT JOIN LY_BOLETO BO
			ON BO.BOLETO = IL.BOLETO
		LEFT JOIN VW_FCAV_COBRANCA_DEB_CRED DC
			ON DC.COBRANCA = CO.COBRANCA
		INNER JOIN LY_CURSO CS
			ON CS.CURSO = AL.CURSO
		--	AND CS.FACULDADE IN ('ATUAL','ESPEC','CAPAC','DIFUS')
		where il.COBRANCA in (47567)
	GROUP BY
		AL.ALUNO, 
		AL.NOME_COMPL, 
		AL.SIT_ALUNO,
		CS.CURSO, 
		il.NATUREZA,
		CO.COBRANCA, 
		CO.DATA_DE_GERACAO,
		IL.DATA, 
		IL.DESCRICAO, 
		CO.DATA_DE_FATURAMENTO, 
		BO.NUMERO_RPS,
		BO.DATA_EMISSAO_RPS, 
		CO.DATA_DE_VENCIMENTO,
		DC.DEBITO, 
		DC.MULTA_JUROS, 
		DC.ACRESC_IGPM,
		DC.DESCONTO,
		DC.ACORDO,
		DC.BOLSA, 
		DC.PAGAR, 
		DC.PAGO, 
		DC.SALDO	

),
ALUNOS_TURMAS 
AS (
	SELECT
		pm.ALUNO,
		pm.TURMA,
		pm.CURRICULO,
		TU.CENTRO_DE_CUSTO,
		pm.DT_MATRICULA as DT_ULTALT
	FROM 
		VW_FCAV_MATRICULA_E_PRE_MATRICULA PM 
		left join LY_TURMA TU
			on tu.TURMA  = pm.TURMA
			and tu.SERIE = 1
		where SIT_DETALHE = 'Curricular'
		and tu.UNIDADE_RESPONSAVEL not like 'PALES'
	group by pm.ALUNO,
		pm.TURMA,
		pm.CURRICULO,
		TU.CENTRO_DE_CUSTO,
		PM.DT_MATRICULA

	union all

	SELECT
		pm.ALUNO,
		pm.TURMA,
		pm.CURRICULO,
		TU.CENTRO_DE_CUSTO,
		pm.DT_MATRICULA as DT_ULTALT
	FROM 
		VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA PM 
		left join LY_TURMA TU
			on tu.TURMA  = pm.TURMA
			and tu.SERIE = 1
	where SIT_MATRICULA = 'Cancelado'
		AND PM.NOME_COMPL != 'Aluno Editor de Tela'
	group by pm.ALUNO,
		pm.TURMA,
		pm.CURRICULO,
		TU.CENTRO_DE_CUSTO,
		PM.DT_MATRICULA
)

--Consulta final
SELECT
	AB.ALUNO,
	AB.NOME_COMPL,
	AB.SIT_ALUNO,
	AB.CURSO,
	AL.CENTRO_DE_CUSTO,
	AB.COBRANCA,
	AB.DATA_DE_VENCIMENTO,
	AB.DESCRICAO,
	AB.DATA_DE_EMISSAO,
	AB.NUMERO_RPS,
	AB.DATA_EMISSAO_RPS,
	AB.SITUACAO_BOLETO,
	AB.VALOR_FATURADO,
	AB.MULTA_JUROS,
	AB.ACRESC_IGPM,
	AB.DESCONTO,
	AB.ACORDO,
	AB.BOLSA,
	AB.VALOR_PAGAR,
	AB.VALOR_PAGO,
	AB.SALDO
FROM ALUNOS_TURMAS AL
	INNER JOIN ALUNOS_BOLETOS AB
		ON AB.ALUNO = AL.ALUNO
GROUP BY
	AB.ALUNO,
	AB.NOME_COMPL,
	AB.SIT_ALUNO,
	AB.CURSO,
	AL.CENTRO_DE_CUSTO,
	AB.COBRANCA,
	AB.DATA_DE_VENCIMENTO,
	AB.DESCRICAO,
	AB.DATA_DE_EMISSAO,
	AB.NUMERO_RPS,
	AB.DATA_EMISSAO_RPS,
	AB.SITUACAO_BOLETO,
	AB.VALOR_FATURADO,
	AB.MULTA_JUROS,
	AB.ACRESC_IGPM,
	AB.DESCONTO,
	AB.ACORDO,
	AB.BOLSA,
	AB.VALOR_PAGAR,
	AB.VALOR_PAGO,
	AB.SALDO