
/*
	VIEW VW_FCAV_ENTREVISTA_CANDIDATO

Finalidade: Consulta para trazer a relação de candidatos e estão com entrevistas agendadas.
Quem utiliza? Secretaria USP

Autor: Gabriel S. Scalione
Data: 01/10/2019
*/


	
	ALTER VIEW VW_FCAV_ENTREVISTA_CANDIDATO
	AS
		SELECT 
			EC.CONCURSO,
			EC.CANDIDATO,
			CA.NOME_COMPL AS NOME_CANDIDATO,
			ca.SIT_CANDIDATO_VEST as SIT_CANDIDATO,
			FC.DATA_INSC,
			CASE WHEN FC.CONVOCADO = 0 THEN 'Aguardar'
				 WHEN FC.CONVOCADO  = 1 THEN 'Selecionado'
				 WHEN FC.CONVOCADO = 2 THEN 'Recusado'
				 ELSE ''
				END AS SELECAO_COORDENADOR,
			FC.DATA_CONV AS DT_SELECAO,
			EC.ENTREVISTADOR,
			DO.NOME_COMPL AS NOME_ENTREVISTADOR,
			EC.DATA AS DT_ENTREVISTA,
			EC.HORA_INICIO,
			DE.FACULDADE AS UNIDADE_FISICA,
			EC.DEPENDENCIA,
			CASE WHEN SUBSTRING(CA.OBS,CHARINDEX('NÃO CONFIRMADA',CA.OBS COLLATE Latin1_General_CI_AS),LEN('NÃO CONFIRMADA')) != 'NÃO CONFIRMADA' 
					THEN CASE WHEN SUBSTRING(CA.OBS,CHARINDEX('CONFIRMADA',CA.OBS COLLATE Latin1_General_CI_AS),LEN('CONFIRMADA')) != 'CONFIRMADA' THEN ''
					 ELSE SUBSTRING(CA.OBS,CHARINDEX('CONFIRMADA',CA.OBS COLLATE Latin1_General_CI_AS),LEN('CONFIRMADA')) END
					ELSE SUBSTRING(CA.OBS,CHARINDEX('NÃO CONFIRMADA',CA.OBS COLLATE Latin1_General_CI_AS),LEN('NÃO CONFIRMADA'))
			END AS SIT_ENTREVISTA,
			CA.OBS
		FROM 
			LY_CANDIDATO CA
			INNER JOIN LY_ENTREVISTA_CANDIDATO EC 
				ON CA.CANDIDATO = EC.CANDIDATO
				AND CA.CONCURSO = EC.CONCURSO
			INNER JOIN LY_DOCENTE DO
				ON DO.NUM_FUNC = EC.ENTREVISTADOR
			INNER JOIN LY_DEPENDENCIA DE
				ON DE.DEPENDENCIA = EC.DEPENDENCIA
			INNER JOIN FCAV_CANDIDATOS FC
				ON FC.CANDIDATO = CA.CANDIDATO
				AND FC.CONCURSO = CA.CONCURSO

			