
/*
	VIEW VW_FCAV_AVAL_BANCO_QUESTOES

Finalidade: Traz todas questões cadastradas no Lyceum e em qual modalidade será aplicada.


Autor: Gabriel
Data: 13/06/2018

*/

CREATE VIEW VW_FCAV_AVAL_BANCO_QUESTOES
AS
SELECT
	CASE WHEN TIPO_QUESTIONARIO NOT IN ('FORM_AVAL_DOCENTE', 'FORM_AVAL_DISCIPLINA') THEN 'CAPACITACAO'
	ELSE 'ESPECIALIZACAO' END AS MODALIDADE ,
	TIPO_QUESTIONARIO,
	QUESTIONARIO,
	QUESTAO,
	TIPO,
	TIPO_OBJETO,
	ASPECTO,
	CASE WHEN QUESTAO_OBJETIVA IS NOT NULL THEN 'Objetiva'
		 ELSE 'Subjetiva' 
	END AS TIPO_QUESTAO,
	isnull(QUESTAO_OBJETIVA,QUESTAO_SUBJETIVA) AS QUESTOES,
	
	OBRIGATORIA,
	ORDEM 
FROM LY_QUESTAO
WHERE TIPO_QUESTIONARIO IN ('FORM_AVAL_DOCENTE', 'FORM_AVAL_DISCIPLINA','FORM_AVAL_DIS_2018','FORM_AVAL_DOC_2018','FORM_AVAL_INFRA_2018')
and TIPO_OBJETO not like 'OUTROS'

group by
	TIPO_QUESTIONARIO,
	QUESTIONARIO,
	QUESTAO,
	TIPO,
	ASPECTO,
	TIPO_OBJETO,
	QUESTAO_OBJETIVA,
	QUESTAO_SUBJETIVA,
	OBRIGATORIA,
	ORDEM 


