   
ALTER VIEW VW_FCAV_CRONOGRAMA_TURMA_DOCENTE AS    
SELECT
 NULL AS RESPONSAVEL,    
 tur.FACULDADE as UNIDADE,    
 tur.CURSO AS CURSO,    
 CASE WHEN V.CONCURSO IS NULL THEN ''    
   ELSE V.CONCURSO    
 END AS CONCURSO,    
 CASE WHEN CO.DT_FIM < GETDATE() THEN 'Concurso Encerrado'    
   WHEN V.CONCURSO IS NOT NULL THEN 'Em Andamento'    
 END AS SIT_PROC_SELETIVO,    
 TUR.TURMA,    
 V.DT_INICIO AS DT_INICIO_TURMA,    
 V.DT_FIM AS DT_FIM_TURMA,    
 tur.CLASSIFICACAO AS SIT_TURMA,   
 tur.ANO,  
 tur.SEMESTRE AS PERIODO,    
 tur.SERIE,    
 TUR.DISCIPLINA AS DISCIPLINA,    
 (SELECT D.NOME_COMPL FROM LY_DISCIPLINA D WHERE TUR.DISCIPLINA = D.DISCIPLINA) as NOME_DISCIPLINA,  
 AGE.NUM_FUNC,
 dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(LTRIM(RTRIM(doc.NOME_COMPL))) AS DOCENTE,    
 LOWER(E_MAIL) AS E_MAIL,    
 tur.DT_INICIO AS DT_INICIO_DISCIPLINA,  
 CONVERT (VARCHAR,HORA_INICIO,108) AS HORA_ENTRADA,  
 CONVERT (VARCHAR,HORA_FIM,108) AS HORA_SAIDA,  
 CASE WHEN DIA_SEMANA = 1 THEN 'domingo'  
   WHEN DIA_SEMANA = 2 THEN 'segunda-feira'  
   WHEN DIA_SEMANA = 3 THEN 'terça-feira'  
   WHEN DIA_SEMANA = 4 THEN 'quarta-feira'  
   WHEN DIA_SEMANA = 5 THEN 'quinta-feira'  
   WHEN DIA_SEMANA = 6 THEN 'sexta-feira'  
   WHEN DIA_SEMANA = 7 THEN 'sábado'  
 END AS DIA_DA_SEMANA,  
 age.DATA as DIA_AULA,  
 CONVERT (VARCHAR,RANK() OVER(PARTITION BY tur.DISCIPLINA, tur.TURMA, AGE.ANO, AGE.SEMESTRE ORDER BY AGE.ANO, AGE.SEMESTRE,TUR.TURMA, tur.DISCIPLINA, AGE.DATA)) AS NUM_AULA,    
 CARGA_HORARIA,   
 CASE WHEN age.EVENTO_CUMP = 'S' THEN 'SIM'  
   WHEN age.EVENTO_CUMP = 'N' THEN 'NÃO' END AULA_CUMPRIDA,  
 CASE WHEN age.CANCELADA = 'S' THEN 'SIM'  
   WHEN age.CANCELADA = 'N' THEN 'NÃO' END AS AULA_CANCELADA,  
 DBO.FN_FCAV_MATRICULADOS_DISCIPLINA(TUR.TURMA, TUR.DISCIPLINA)AS MATRICULADOS,    
 age.DEPENDENCIA as SALA,  
   
 DATA - 15 as Env_Cronograma, ---Prazo informado pela Luana - Educação  
 DATA - 10 as Rec_Material_Cronog,  
 DATA - 2 as Reprod_Material,  
 DATA - 1 as Rec_Material,
 age.AGENDA  
   
FROM    
 LY_TURMA tur  
 INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA V 
	ON TUR.TURMA = V.TURMA    
	AND TUR.TURNO = V.TURNO
	AND TUR.CURRICULO = V.CURRICULO
 LEFT JOIN LY_CONCURSO CO ON CO.CONCURSO = V.CONCURSO   
 inner JOIN LY_AGENDA age ON tur.TURMA = AGE.TURMA and tur.DISCIPLINA = age.DISCIPLINA   
        AND age.ANO = tur.ANO AND age.SEMESTRE = tur.SEMESTRE  
 INNER JOIN LY_DOCENTE doc ON doc.NUM_FUNC = age.NUM_FUNC       
  
 -- where 
	--tur.DISCIPLINA = 'CEAI-COAC'
	----AND AGE.DATA = '2019-04-25 00:00:00'
GROUP BY     
 tur.CURSO, TUR.FACULDADE, V.CONCURSO,  
 CO.DT_FIM, tur.TURMA,V.DT_INICIO, V.DT_FIM,  
 TUR.CLASSIFICACAO,TUR.ANO, TUR.SEMESTRE, TUR.SERIE, TUR.DT_INICIO, 
 TUR.DISCIPLINA, AGE.NUM_FUNC, doc.NOME_COMPL, doc.E_MAIL,  
 HORA_INICIO,HORA_FIM,  
 AGE.DIA_SEMANA, AGE.DATA, V.CARGA_HORARIA,  
 AGE.EVENTO_CUMP, AGE.CANCELADA,AGE.DEPENDENCIA,
 AGE.AGENDA, AGE.ANO, AGE.SEMESTRE