    
ALTER VIEW VW_FCAV_RELAT_DOCENTE_DISCIPLINA    
AS    
/*    
    
 ESSA VIEW É UTILIZADA PARA TRAZER INFORMAÇÕES DOS DOCENTES POR DISCIPLINA    
 QUEM UTILIZA É O CRISTIANO PARA EMISSÃO DE RELATÓRIO EM PLANILHA EXCEL.    
    
Autor: Gabriel S. Scalione    
Data: 19/04/2016    
*/    
    
SELECT    
 CASE WHEN TUR.CURSO = 'ATUALIZAÇÃO' OR TUR.CURSO = 'PALESTRA'THEN TUR.DISCIPLINA    
 ELSE TUR.CURSO    
 END AS CURSO,        
 TUR.TURMA,        
 --CAST(TUR.ANO AS VARCHAR)+ '/' + CAST(TUR.SEMESTRE AS VARCHAR)AS ANO_SEMESTRE,        
 TUR.DISCIPLINA AS DISCIPLINA,        
 DIS.NOME AS NOME_DISCIPLINA,        
 TUR.DT_INICIO AS INICIO_DISCIPLINA,       
 TUR.DT_FIM AS TERMINO_DISCIPLINA,       
 TUR.CLASSIFICACAO AS STATUS_DISCIPLINA_TURMA,    
 DBO.FN_FCAV_PRIMEIRA_MAIUSCULA(LTRIM(RTRIM(DOC.NOME_COMPL))) AS DOCENTE,  
  CASE WHEN DIA_SEMANA = 1 THEN 'domingo'    
   WHEN DIA_SEMANA = 2 THEN 'segunda-feira'    
   WHEN DIA_SEMANA = 3 THEN 'terça-feira'    
   WHEN DIA_SEMANA = 4 THEN 'quarta-feira'    
   WHEN DIA_SEMANA = 5 THEN 'quinta-feira'    
   WHEN DIA_SEMANA = 6 THEN 'sexta-feira'    
   WHEN DIA_SEMANA = 7 THEN 'sábado'    
 END AS DIA_DA_SEMANA,    
 age.DATA as DIA_AULA,    
 CONVERT (VARCHAR,RANK() OVER(PARTITION BY tur.DISCIPLINA, tur.TURMA ORDER BY tur.DISCIPLINA,AGE.DATA)) AS NUM_AULA,           
 DOC.CATEGORIA,    
 DOC.CELULAR,        
 LOWER(E_MAIL) AS E_MAIL,    
 LOWER(DOC.E_MAIL_COM) AS E_MAIL_COM,        
 LOWER(DOC.E_MAIL_EMP) AS E_MAIL_EMP,        
 TUR.CENTRO_DE_CUSTO,    
 ISNULL(CO.NOME_COMPL,'NAO CADASTRADO') AS COORDENADOR    
 --'Lyceum' AS SISTEMA        
FROM        
 LY_TURMA TUR        
 left JOIN LY_DISCIPLINA DIS ON (TUR.DISCIPLINA = DIS.DISCIPLINA)        
 LEFT JOIN LY_AGENDA age ON tur.TURMA = AGE.TURMA and tur.DISCIPLINA = age.DISCIPLINA       
        AND age.ANO = tur.ANO AND age.SEMESTRE = tur.SEMESTRE      
 left JOIN LY_DOCENTE DOC ON (DOC.NUM_FUNC = AGE.NUM_FUNC)
 left join VW_FCAV_COORDENADOR_TURMA CO
	on CO.TURMA = TUR.TURMA     
      
WHERE     
 TUR.CLASSIFICACAO != 'Cancelada' 
 AND CO.TIPO_COORD = 'COORD'