
ALTER VIEW VW_FCAV_INSCRITOS_CURSO
AS

/***********************************************  
VIEW PARA TRAZER A QUANTIDADE INSCRITOS POR DIA  
************************************************/
SELECT
    CO.CONCURSO,
	CONVERT(DATETIME,CONVERT(CHAR(10),C.DATA_INSC,126)) AS DT_INSCRICAO,
    COUNT(CA.CANDIDATO) AS INSCRITOS

FROM LY_CANDIDATO CA
LEFT JOIN FCAV_CANDIDATOS C
    ON C.CANDIDATO = CA.CANDIDATO
	AND C.CONCURSO = CA.CONCURSO
INNER JOIN LY_CONCURSO CO
    ON CO.CONCURSO = CA.CONCURSO
WHERE UNIDADE_RESPONSAVEL NOT LIKE 'ATUAL'
AND UNIDADE_RESPONSAVEL NOT LIKE 'PALES'
AND YEAR(C.DATA_INSC) >= 2018
GROUP BY CONVERT(DATETIME,CONVERT(CHAR(10),C.DATA_INSC,126)),
         CO.CONCURSO

UNION ALL

SELECT
    OO.TURMA AS CONCURSO,
    CONVERT(DATETIME,CONVERT(CHAR(10),DT_INGRESSO,126))
    AS DT_INSCRICAO,
    COUNT(AL.ALUNO) AS INSCRITOS
FROM LY_ALUNO AL
INNER JOIN LY_OFERTA_CURSO OC
    ON OC.CURSO = AL.CURSO
    AND OC.TURNO = AL.TURNO
    AND OC.CURRICULO = AL.CURRICULO
    AND OC.ANO_INGRESSO = AL.ANO_INGRESSO
    AND OC.PER_INGRESSO = AL.SEM_INGRESSO
    AND OC.TURMA_PREF = AL.TURMA_PREF
INNER JOIN LY_OPCOES_OFERTA OO
	ON OO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
WHERE OC.CONCURSO IS NULL
AND AL.CANDIDATO IS NULL
AND AL.CONCURSO IS NULL
AND YEAR(DT_INGRESSO) >= 2018
GROUP BY CONVERT(DATETIME,CONVERT(CHAR(10),DT_INGRESSO,126)),
         OO.TURMA