  
ALTER VIEW VW_FCAV_CURSOS_CADASTRADOS_LYCEUM  
AS  
  
SELECT    
 CS.FACULDADE AS UNID_RESP,    
 CS.CURSO AS CURSO,    
 DBO.FN_FCAV_PRIMEIRA_MAIUSCULA(CS.NOME) AS NOME_CURSO,
 CS.ATIVO,
 CS.TIPO,
 CS.VAGAS,
 CS.DURACAO_AULA AS DURACAO_AULA_CURSO,
 CS.DEPTO,
     
    ISNULL((SELECT TOP 1  
    NOME_COMPL  
            FROM VW_FCAV_COORDENADOR_TURMA COORD  
            WHERE COORD.TURMA = tu.TURMA  
            AND COORD.TIPO_COORD = 'COORD'  
            GROUP BY NOME_COMPL),'NAO CADASTRADO') AS COORDENADOR,      
    ISNULL((SELECT TOP 1  
    NOME_COMPL  
            FROM VW_FCAV_COORDENADOR_TURMA COORD  
            WHERE COORD.TURMA = tu.TURMA   
            AND COORD.TIPO_COORD != 'COORD'  
            GROUP BY NOME_COMPL),'.') AS VICE_COORD,        
 CR.TURNO,         
 CR.CURRICULO,    
 CR.ANO_INI,
 CR.SEM_INI,
 
 CAST(CR.AULAS_PREVISTAS AS DECIMAL(10,0)) AS CARGA_HORARIA,    
 CAST(CR.PRAZO_CONC_PREV AS VARCHAR) + ' ' + CR.TIPO_PRAZO_CONCL AS PRAZO_CONCLUSAO,    
 CR.SERVICO AS SERVICO_VINCULADO,
 CR.PRAZO_IDEAL AS PERIODO_IDEAL,
 CR.PRAZO_MAX   AS PERIODO_MAXIMO,
 CR.TRANC_INTERV_DATA,
 
 
 GR.DISCIPLINA AS DISCIPLINA_GRADE,    
 GR.SERIE_IDEAL,    
 GR.OBRIGATORIA,    
 
 DI.NOME,    
 DI.TEM_NOTA,    
 DI.TEM_FREQ,    
 (ISNULL(CAST(DI.PERC_PRESMIN AS decimal(3,2)),0) * 100) AS FREQUENCIA,    
 DI.CREDITOS,  
 DI.TIPO AS NIVEL_DISC,  
 DI.VERIFICA_HORARIO,    
 DI.NOTA_MAX,    
 DI.N_CASAS_DEC,    
 DI.FORMULA_MF1,    
 DI.FORMULA_CA1,    
 DI.CONCEITO_MIN_1,    
 CAST(DI.AULAS_SEMANAIS AS DECIMAL) AS AULAS_SEMANAIS,    
 DI.HORAS_AULA,    
 
 TU.TURMA,    
 TU.ANO,    
 TU.SEMESTRE,  
 TU.FACULDADE AS TUR_UNID_FISICA,    
 TU.DISCIPLINA AS DISC_TURMA,  
 TU.DT_INICIO,  
 TU.DT_FIM,  
 TU.SERIE,    
 TU.SIT_TURMA,    
 TU.CLASSIFICACAO,    
 TU.AULAS_PREVISTAS,
 TU.NIVEL,
 TU.MIN_AULAS,
 TU.DURACAO_AULA,
 TU.NUM_ALUNOS,  
 TU.CENTRO_DE_CUSTO,   
 
 CN.CONCURSO,    
 CN.TIPO_INGRESSO,
 CN.DT_INICIO AS DTINI_CONCURSO,    
 CN.DT_FIM AS DTFIM_CONCURSO,  
 CN.ANO AS ANO_INGR_ONLINE,  
 CN.SEMESTRE AS PER_INGR_ONLINE,  
 CN.INGR_DTINI,  
 CN.INGR_DTFIM,   
 CN.INGR_ESCOLHE_PLANO,  
 CN.INGR_MAX_RESP_FINAN,  
 CN.N_DIAS_VENC_BOL_MATR AS INGR_DIAS_VENC_BOLETO,     

 CASE WHEN OC.CONCURSO IS NULL THEN 'ContratoLoja' 
	ELSE CT.CONTRATO
	END AS CONTRATO, 
     
 OC.OFERTA_DE_CURSO,    
 OC.CURSO_OFERTADO,    
 OC.DESCRICAO_ABREV,    
 OC.DESCRICAO_COMPL,
 OC.TURMA_PREF,   
 OC.ANO_INGRESSO,    
 OC.PER_INGRESSO,    
 OC.DTINI AS DTINI_OFERTA,    
 OC.DTFIM AS DTFIM_OFERTA,
 OC.VALOR_A_VISTA_ESTIMADO,    

 OO.TURMA AS OP_OFERTA_TURMA,    
   
 PO.PLANO,  
 PO.PLANOPAG,  
 PO.DESCRICAO,  
 PO.MES_INICIAL,  
 PO.NUM_PARCELAS,  
 PO.TIPO_DESC,  
 PO.DESCONTO,  
 PO.FORMA_PAGAMENTO,  
 PO.NUM_PARCELAS_CARTAO,
 PO.NUM_PARCELAS_INSCR,  
 PO.N_DIAS_VENC_BOL,  

 VS.SERVICO,    
 VS.CUSTO_UNITARIO, 

 --(SELECT TOP 1
 --       GSP.GRUPO
 --   FROM LY_GRUPO_SERV_PERIODO GSP
 --   WHERE CR.SERVICO = GSP.SERVICO
 --       AND OC.ANO_INGRESSO = GSP.ANO
 --       AND OC.PER_INGRESSO = GSP.PERIODO
 --       AND OC.CURRICULO = CR.CURRICULO
 --   ORDER BY GSP.GRUPO DESC) AS GRUPO_DE_ALUNO,
 
 --(SELECT TOP 1
 --       GSP.CUSTO_UNITARIO
 --   FROM LY_GRUPO_SERV_PERIODO GSP
 --   WHERE CR.SERVICO = GSP.SERVICO
 --       AND OC.ANO_INGRESSO = GSP.ANO
 --       AND OC.PER_INGRESSO = GSP.PERIODO
 --       AND OC.CURRICULO = CR.CURRICULO
 --   ORDER BY GSP.GRUPO DESC) AS VALOR_DO_GRUPO,
 
 --CASE WHEN EXISTS (SELECT TOP 1
 --       GSP.CUSTO_UNITARIO
 --   FROM LY_GRUPO_SERV_PERIODO GSP
 --   WHERE CR.SERVICO = GSP.SERVICO
 --       AND OC.ANO_INGRESSO = GSP.ANO
 --       AND OC.PER_INGRESSO = GSP.PERIODO
 --       AND OC.CURRICULO = CR.CURRICULO
 --   ORDER BY GSP.GRUPO DESC) THEN 'UTILIZA GRUPO DE ALUNO'
 --ELSE 'NÃO UTILIZA'
 --END AS UTILIZA_GRUPO,
 
 CS.FL_FIELD_01 AS CSFL01_Apresentacao,    
 CS.FL_FIELD_02 AS CSFL02_Objetivos,    
 CS.FL_FIELD_03 AS CSFL03_Corpo_Docente,    
 CS.FL_FIELD_04 AS CSFL04_Diferencial,    
 CS.FL_FIELD_05 AS CSFL05_Perfil_do_Aluno,    
 CS.FL_FIELD_06 AS CSFL06_Certificacao,    
 CS.FL_FIELD_07 AS CSFL07_Metodologia,    
 CS.FL_FIELD_08 AS CSFL08_Avaliacao,    
 CS.FL_FIELD_09 AS CSFL09_Investimento,    
 CS.FL_FIELD_10 AS CSFL10_Processo_Seletivo,    
     
 --OC.FL_FIELD_01 AS OCFL01_EmailFinanceiro,    
 --OC.FL_FIELD_02 AS OCFL02_EmailSecretaria,    
 --OC.FL_FIELD_03 AS OCFL03_AtualizaPortal,     
 OC.FL_FIELD_04 AS OCFL04_Programa,    
 OC.FL_FIELD_05 AS OCFL05_ValorTotalCurso,    
 OC.FL_FIELD_06 AS OCFL06_ValorParcela,    
 OC.FL_FIELD_07 AS OCFL07_QtdeParcelas,    
 OC.FL_FIELD_08 AS OCFL08_DescontoAVista,    
 OC.FL_FIELD_09 AS OCFL09_DiasVenctoBoleto1,    
 OC.FL_FIELD_10 AS OCFL10_DiaVenctoMensais,    
     
 CN.FL_FIELD_01 AS CNFL01_Analise_Curricular,    
 CN.FL_FIELD_02 AS CNFL02_Entrevista,    
 CN.FL_FIELD_03 AS CNFL03_Prova,    
 CN.FL_FIELD_04 AS CNFL04_Redacao,    
 CN.FL_FIELD_05 AS CNFL05_Alteracao_Conteudo,    
 CN.FL_FIELD_06 AS CNFL06_Dia_Horario_Aulas,    
 CN.FL_FIELD_07 AS CNFL07_RelacaoDocumentos   
 --CN.FL_FIELD_08 AS CNFL08_LIVRE,    
 --CN.FL_FIELD_09 AS CNFL09_LIVRE,    
 --CN.FL_FIELD_10 AS CNFL10_LIVRE    
FROM    
 LY_CURSO CS    
   
 LEFT JOIN LY_CURRICULO CR     
  ON CR.CURSO = CS.CURSO    
      
 LEFT JOIN LY_GRADE GR     
  ON GR.CURSO = CR.CURSO     
  AND GR.TURNO = CR.TURNO    
  AND GR.CURRICULO = CR.CURRICULO    
  
 LEFT JOIN LY_DISCIPLINA DI    
  ON DI.DISCIPLINA = GR.DISCIPLINA     
    
 LEFT JOIN LY_TURMA TU    
  ON TU.CURSO = CR.CURSO     
  AND TU.TURNO = CR.TURNO    
  AND TU.CURRICULO = CR.CURRICULO    
  AND TU.DISCIPLINA = DI.DISCIPLINA
  AND GR.SERIE_IDEAL = TU.SERIE

      
 LEFT JOIN LY_OPCOES_OFERTA OO     
  ON OO.TURMA = TU.TURMA    
     
 INNER JOIN LY_OFERTA_CURSO OC    
  ON OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO
  AND OC.CURSO = CR.CURSO
  AND OC.TURNO = CR.TURNO    
  AND OC.CURRICULO = CR.CURRICULO
   
 LEFT JOIN LY_PLANOS_OFERTADOS PO  
 ON PO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO  
      
 LEFT JOIN LY_CONCURSO CN    
  ON CN.CONCURSO = OC.CONCURSO    
      
 LEFT JOIN LY_CURRICULO_CONTRATO CT     
  ON CT.CURSO = OC.CURSO     
  AND CT.TURNO = OC.TURNO    
  AND CT.CURRICULO = OC.CURRICULO    
  AND CT.UNIDADE_FISICA = OC.UNIDADE_FISICA    
      
 LEFT JOIN LY_VALOR_SERV_PERIODO VS    
  ON VS.SERVICO = CR.SERVICO    
  AND VS.ANO = OC.ANO_INGRESSO    
  AND VS.PERIODO = PER_INGRESSO 

WHERE    
 OC.ANO_INGRESSO >= YEAR(GETDATE())-1
-- --AND CS.CURSO LIKE'CEPSNG%'    
-- --TU.TURMA = 'CEAI T 29'    
-- --cs.faculdade = 'ATUAL'    
GROUP BY    
    
 CS.FACULDADE,    
 CS.CURSO,    
 CS.NOME,    
 CS.ATIVO,
 CS.TIPO,
 CS.VAGAS,
 CS.DURACAO_AULA,
 CS.DEPTO,
 CR.TURNO,    
 CR.CURRICULO,
 CR.ANO_INI,
 CR.SEM_INI,   
 CR.AULAS_PREVISTAS,    
 CR.PRAZO_CONC_PREV,    
 CR.TIPO_PRAZO_CONCL,    
 CR.SERVICO,
 CR.PRAZO_IDEAL ,
 CR.PRAZO_MAX   ,
 CR.TRANC_INTERV_DATA,   
     
 GR.DISCIPLINA,    
 GR.SERIE_IDEAL,    
 GR.OBRIGATORIA,    
     
 DI.NOME,    
 DI.TEM_NOTA,    
 DI.TEM_FREQ,    
 DI.PERC_PRESMIN,    
 DI.CREDITOS, 
 DI.TIPO,   
 DI.VERIFICA_HORARIO,    
 DI.NOTA_MAX,    
 DI.N_CASAS_DEC,    
 DI.FORMULA_MF1,    
 DI.FORMULA_CA1,    
 DI.CONCEITO_MIN_1,    
 DI.AULAS_SEMANAIS,    
 DI.HORAS_AULA,    
     
 TU.TURMA,    
 TU.ANO,    
 TU.SEMESTRE,  
 TU.FACULDADE,    
 TU.DISCIPLINA, 
 TU.NIVEL, 
 TU.DT_INICIO,  
 TU.DT_FIM,  
 TU.SERIE,    
 TU.SIT_TURMA,    
 TU.CLASSIFICACAO, 
 TU.AULAS_PREVISTAS,
 TU.MIN_AULAS,
 TU.DURACAO_AULA,   
 TU.NUM_ALUNOS,  
 TU.CENTRO_DE_CUSTO,    
     
 OO.TURMA,    
     
 OC.OFERTA_DE_CURSO,
 OC.CURRICULO, 
 OC.CONCURSO,   
 OC.CURSO_OFERTADO,    
 OC.DESCRICAO_ABREV,    
 OC.DESCRICAO_COMPL,
 OC.TURMA_PREF,    
 OC.ANO_INGRESSO,    
 OC.PER_INGRESSO,    
 OC.DTINI,    
 OC.DTFIM,  
 OC.VALOR_A_VISTA_ESTIMADO,      
   
 PO.PLANO,  
 PO.PLANOPAG,  
 PO.DESCRICAO,  
 PO.MES_INICIAL,  
 PO.NUM_PARCELAS,  
 PO.TIPO_DESC,  
 PO.DESCONTO,  
 PO.FORMA_PAGAMENTO,
 PO.NUM_PARCELAS_CARTAO,  
 PO.NUM_PARCELAS_INSCR,  
 PO.N_DIAS_VENC_BOL,  
      
 CN.CONCURSO, 
 CN.TIPO_INGRESSO,   
 CN.DT_INICIO,    
 CN.DT_FIM,  
 CN.ANO,  
 CN.SEMESTRE,  
 CN.INGR_DTINI,  
 CN.INGR_DTFIM,   
 CN.INGR_ESCOLHE_PLANO,  
 CN.INGR_MAX_RESP_FINAN,  
 CN.N_DIAS_VENC_BOL_MATR,    
     
 CT.CONTRATO ,    
    
 VS.SERVICO,    
 VS.CUSTO_UNITARIO,    
  
 CS.FL_FIELD_01 ,    
 CS.FL_FIELD_02 ,    
 CS.FL_FIELD_03 ,    
 CS.FL_FIELD_04 ,    
 CS.FL_FIELD_05 ,    
 CS.FL_FIELD_06 ,    
 CS.FL_FIELD_07 ,    
 CS.FL_FIELD_08 ,    
 CS.FL_FIELD_09 ,    
 CS.FL_FIELD_10 ,    
      
 TU.FL_FIELD_01 ,    
 TU.FL_FIELD_02 ,    
 TU.FL_FIELD_03 ,    
 TU.FL_FIELD_04 ,    
 TU.FL_FIELD_05 ,    
 TU.FL_FIELD_06 ,    
 TU.FL_FIELD_07 ,    
 TU.FL_FIELD_08 ,    
 TU.FL_FIELD_09 ,    
 TU.FL_FIELD_10 ,    
 TU.FL_FIELD_11 ,    
 TU.FL_FIELD_12 ,    
 TU.FL_FIELD_13 ,    
 TU.FL_FIELD_14 ,    
 TU.FL_FIELD_15 ,    
 TU.FL_FIELD_16 ,    
 TU.FL_FIELD_17 ,    
 TU.FL_FIELD_18 ,    
 TU.FL_FIELD_19 ,    
 TU.FL_FIELD_20 ,    
    
 --OC.FL_FIELD_01 ,    
 --OC.FL_FIELD_02 ,    
 --OC.FL_FIELD_03 ,    
 OC.FL_FIELD_04 ,    
 OC.FL_FIELD_05 ,    
 OC.FL_FIELD_06 ,    
 OC.FL_FIELD_07 ,    
 OC.FL_FIELD_08 ,    
 OC.FL_FIELD_09 ,    
 OC.FL_FIELD_10 ,    
     
 CN.FL_FIELD_01 ,    
 CN.FL_FIELD_02 ,    
 CN.FL_FIELD_03 ,    
 CN.FL_FIELD_04 ,    
 CN.FL_FIELD_05 ,    
 CN.FL_FIELD_06 ,    
 CN.FL_FIELD_07     
 --CN.FL_FIELD_08 ,    
 --CN.FL_FIELD_09 ,    
 --CN.FL_FIELD_10    
    