ALTER VIEW VW_FCAV_COBRANCA_DIF_ESTORNO AS  
SELECT COBRANCA  
FROM VW_COBRANCA cob  
WHERE  
 cob.VALOR <= 0  
AND NOT EXISTS(  
  SELECT *  
  FROM LY_ITEM_CRED ic  
  WHERE ic.COBRANCA = cob.COBRANCA  
 )  
 -- Acordos estavam entrando e sendo considerados como Dif ou estorno.
 -- Codigo abaixo remove eles dessa view
 AND NOT EXISTS(  
  SELECT *  
  FROM LY_ITEM_LANC ic  
  WHERE ic.COBRANCA = cob.COBRANCA  
  AND DESCRICAO = 'VALOR ACORDADO' AND ACORDO IS NOT NULL
 )  

 -- REMOVER BOLSA100% DOS RESULTADOS
  AND NOT EXISTS(  
  SELECT *  
  FROM LY_ITEM_LANC ic  
	INNER JOIN LY_BOLSA BOLSA ON ic.ALUNO = BOLSA.ALUNO
  WHERE ic.COBRANCA = cob.COBRANCA  
  AND IC.NUM_BOLSA IS NOT NULL
  AND BOLSA.PERC_VALOR = 'Percentual'
  AND BOLSA.VALOR = '1.000000'
 ) 

 -- REMOVER VOUCHER100% DOS RESULTADOS
  AND NOT EXISTS(  
  SELECT *  
  FROM LY_ITEM_LANC ic  
	INNER JOIN LY_COBRANCA CO ON ic.COBRANCA = CO.COBRANCA
	INNER JOIN VW_FCAV_ALUNOS_COM_VOUCHERS VO ON VO.ALUNO = CO.ALUNO
  WHERE CO.COBRANCA = cob.COBRANCA  
  AND IC.NUM_BOLSA IS NOT NULL
  AND VO.DESC_PERC_VALOR = 'Percentual'
  AND VO.DESCONTO = 100.000000
 ) 