

	with dim_descontos_do_aluno as (
	SELECT 
				LD.ALUNO,
				LD.LANC_DEB,
				LD.DESCRICAO,
				LD.MATRICULA,
				LD.ANO_REF,
				LD.PERIODO_REF,
				SUM(ISNULL(DD.VALOR,0)) DESCONTO,
				CAST(SUM((ISNULL(LD.VALOR,0) * ISNULL(BO.VALOR,0))) AS decimal(10,2)) AS BOLSA,
				(SUM(ISNULL(DD.VALOR,0)) + SUM((ISNULL(LD.VALOR,0) * ISNULL(BO.VALOR,0)))) AS TOTAL_DESCONTOS
						
				
			FROM LY_LANC_DEBITO LD
				
			--AND MP.SIT_DETALHE = 'Curricular'

			LEFT JOIN LY_DESCONTO_DEBITO DD
				ON DD.LANC_DEB = LD.LANC_DEB
				AND DD.MOTIVO_DESCONTO != 'Estorno'
		
			left join LY_BOLSA BO
				ON BO.ALUNO = LD.ALUNO
				AND BO.ANOFIM >= YEAR(GETDATE())
				and bo.perc_valor = 'Percentual'
			

			WHERE LD.DESCRICAO != 'Acordo'
				--and ld.ALUNO = 'A202000129'
				AND DD.MOTIVO_DESCONTO != 'Estorno'
			GROUP BY LD.ALUNO,
				
				LD.LANC_DEB,
				LD.DESCRICAO,
				LD.MATRICULA,
				LD.ANO_REF,
				LD.PERIODO_REF
	)


		SELECT 
			MP.TURMA,
			mp.aluno,
			SUM(ISNULL(LD.VALOR,0)) VALOR,
			SUM(ISNULL(DA.TOTAL_DESCONTOS,0)) DESCONTO,
			SUM(ISNULL(DE.DEVOLUCAO,0)) as DEVOLUCAO,
			CAST(SUM(ISNULL(LD.VALOR,0)) - SUM(ISNULL(DA.TOTAL_DESCONTOS,0)) AS DECIMAL(10,2)) - sum(ISNULL(DE.DEVOLUCAO,0)) AS VALOR_CONTRATADO
		FROM 
			VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MP
		
			LEFT JOIN LY_LANC_DEBITO LD
				ON LD.ALUNO = MP.ALUNO
				AND LD.DESCRICAO != 'Acordo'
		
			LEFT JOIN dim_descontos_do_aluno DA
				ON DA.ALUNO = LD.ALUNO
				AND DA.LANC_DEB = LD.LANC_DEB
			
			left join VW_FCAV_DEVOLUCAO_ALUNO DE
					ON DE.ALUNO = LD.ALUNO
		
			WHERE MP.SIT_ALUNO != 'Cancelado'
			AND MP.SIT_DETALHE = 'Curricular'
			AND mp.oferta_de_curso is not null
			and mp.TURMA =	'A-ASMON T 02'
			and ld.ALUNO = 'A202000129'
			GROUP BY 
				MP.TURMA, MP.ALUNO
			