/*  
 VIEW VW_FCAV_AVA_ALUNOS_PARTICIPANTES  
  
Finalidade: Relação de alunos matriculados que participaram da avaliação de curso.  
  
SELECT * FROM VW_FCAV_AVA_ALUNOS_PARTICIPANTES WHERE TURMA = 'CCGP T 49'  
  
SELECT * FROM LY_ALUNO WHERE ALUNO = 'C201700439'  
SELECT * FROM LY_HISTMATRICULA WHERE TURMA = 'CCGP T 49' AND DISCIPLINA = 'CCGP-EPCP' AND SITUACAO_HIST != 'Cancelado'  
  
Autor: Gabriel SS  
Data: 26/06/2018  
*/  
  
  
  
ALTER VIEW VW_FCAV_AVA_ALUNOS_PARTICIPANTES  
AS  
  
  
WITH MATRICULADOS  
AS (SELECT  
		MA.CURSO,  
		MA.TURMA,  
		MA.ANO,  
		MA.SEMESTRE,  
		MA.DISCIPLINA,  
		MA.ALUNO,
		MA.NOME_COMPL,
		MA.SIT_MATRICULA
FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA MA  
 
WHERE MA.SIT_MATRICULA != 'Cancelado'  
  AND MA.DISCIPLINA NOT LIKE 'CEAI-RESERV'  
 AND MA.CURSO NOT LIKE 'CEAI'  
GROUP BY MA.CURSO,  
	MA.TURMA,  
	MA.ANO,  
	MA.SEMESTRE,  
	MA.DISCIPLINA,  
	MA.ALUNO,
	MA.NOME_COMPL,
	MA.SIT_MATRICULA,
	MA.CURSO  
 
UNION ALL  
	SELECT  
		 CURSO,  
		 TURMA_CEAI AS TURMA,  
		 ANO,  
		 SEMESTRE,  
		 DISCIPLINA,  
		 ALUNO,
		 NOME_COMPL,
		 SIT_MATRICULA
	FROM  
		VW_FCAV_ALUNOS_MATRICULADOS_CEAI   
	WHERE   
		DISCIPLINA NOT LIKE 'CEAI-RESERV'  
	GROUP BY  
		 CURSO,  
		 TURMA_CEAI,  
		 ANO,  
		 SEMESTRE,  
		 DISCIPLINA,  
		 ALUNO,
		 NOME_COMPL,
		 SIT_MATRICULA  
 )  
  
--RELAÇÃO DAS TURMAS COM NUMERO DE MATRICULADOS NAS DISCIPLINAS  
SELECT  
    CS.CURSO,  
    CS.NOME AS NOME_CURSO,  
    MA.TURMA,  
    MA.DISCIPLINA,
	MA.ANO,
	MA.SEMESTRE,
    MA.ALUNO,
	MA.NOME_COMPL,
	MA.SIT_MATRICULA

FROM LY_AVALIADOR AV  
INNER JOIN MATRICULADOS MA  
    ON MA.ALUNO = AV.ALUNO  
INNER JOIN LY_CURSO CS  
    ON CS.CURSO = MA.CURSO  
  
GROUP BY CS.CURSO,  
	CS.NOME,  
	MA.TURMA,  
	MA.ANO,  
	MA.SEMESTRE,  
	MA.DISCIPLINA,
	MA.ALUNO,
	MA.NOME_COMPL,
	MA.SIT_MATRICULA
  