--* ***************************************************************  
--*  
--*  ***VIEW VW_FCAV_SITUACAO_ALUNOS_BOLETO_DOC***  
--*   
--* DESCRICAO:  
--* - View utilizada para auxiliar a emissão de relatório em Excel,   
--* trazendo a situação da entregue do Diploma e a pagamento do Boleto.  
--*  
--* PARAMETROS:  
--* - Sem parâmetro  
--*   
--* USO:  
--* - View utilizada para auxiliar a emissão de relatório em Excel para o Cristiano.  
--* Trazendo a situação da entregue do Diploma e a pagamento do Boleto.  
--*  
--* ALTERAÇÕES:  
--* - 08/10/2014 João Paulo  
--* - Feito inclusão do campo SIT_DETALHE  
--*  
--* Autor: Gabriel S. Scalione  
--* Data: 22/05/2014  
--*  
--* ***************************************************************  
CREATE VIEW VW_FCAV_SITUACAO_ALUNOS_BOLETO_DOC  
AS  
SELECT
 ALU.ALUNO,  
 DBO.FN_FCAV_PRIMEIRA_MAIUSCULA(NOME_COMPL) AS NOME,  
 CPF,  
 LOWER(E_MAIL) AS E_MAIL,  
 ALU.DT_MATRICULA,    
 ALU.SIT_MATRICULA,  
 ALU.CURSO AS CURSO,  
 ALU.CURRICULO,  
 ALU.TURMA,  
 T.DT_INICIO,  
 CASE WHEN DI.NOME IS NULL THEN 'Não Informado'  
  ELSE DI.NOME  
 END AS DOCUMENTACAO,  
 CASE WHEN AD.STATUS IS NULL THEN 'Não Informado'  
  ELSE AD.STATUS  
 END AS SIT_DOCUMENTACAO,  
 
 EXF.RESP AS RESP_FINANCEIRO,  
 EXF.TITULAR AS TITULAR,  
 EXF.BOLETO,  
 EXF.DESCRICAO,
 CONVERT(VARCHAR,EXF.DATA_DE_EMISSAO,103) AS DATA_DE_EMISSAO,  
 CONVERT(VARCHAR,EXF.DATA_DE_VENCIMENTO,103) AS DATA_DE_VENCIMENTO,  
 EXF.VALOR_PAGAR,  
 EXF.SITUACAO_BOLETO,  
 EXF.VALOR_PAGO  
FROM  
 VW_FCAV_INFO_ALUNOS_LYCEUM AL
 LEFT JOIN LY_ALUNO_DOC_INGRESSO AD ON (ADI.ALUNO = ALU.ALUNO)  
 LEFT JOIN LY_DOCUMENTOS_INGRESSO DI ON (ADI.DOC = DIN.DOC)  
 LEFT JOIN VW_FCAV_EXTFIN_LY EX
	ON EX.ALUNO = AL.ALUNO
	AND EX.TURMA = AL.TURMA
 LEFT JOIN LY_PLANO_PGTO_PERIODO PP
    ON PP.ALUNO = AL.ALUNO
WHERE 
	 EXF.SITUACAO_BOLETO NOT LIKE 'DIF/ESTORNO'  
 AND EXF.DESCRICAO NOT LIKE '%DIFERENÇA%'  
GROUP BY  
 ALU.ALUNO, PES.NOME_COMPL, PES.CPF, PES.E_MAIL, ALU.DT_MATRICULA, ALU.SIT_MATRICULA, --ALU.SIT_DETALHE, 
 ALU.ANO_INGRESSO,  
 ALU.SEM_INGRESSO, ALU.CURSO, ALU.CURRICULO, ALU.TURMA, T.DT_INICIO, DIN.NOME, ADI.STATUS, CA.CONTRATO_ACEITO,  
 DATA_ACEITE, PL.PLANOPAG , RF.RESP, RF.TITULAR, EXF.BOLETO, EXF.DESCRICAO, EXF.DATA_DE_EMISSAO,  
 EXF.DATA_DE_VENCIMENTO, EXF.VALOR_PAGAR, EXF.SITUACAO_BOLETO, EXF.VALOR_PAGO   