
ALTER VIEW VW_FCAV_FREQ_FALTAS_ALUNOS_DISCIPLINA
AS

SELECT
	AG.TURMA,
	CL.DISCIPLINA,
	ag.ANO,
	ag.SEMESTRE as PERIODO,
	CL.ALUNO,
	AL.NOME_COMPL,
	CASE WHEN tu.SIT_TURMA = 'Desativada' THEN 'Histórico'
		ELSE TU.SIT_TURMA
	END as SIT_DISCIPLINA,
	DO.NOME_COMPL AS NOME_DOCENTE,
	CL.LISTA,
	AG.DATA,
	CL.OCORRENCIA
FROM LY_COMP_LISTA CL
	left JOIN LY_AGENDA AG
		ON AG.LISTA = CL.LISTA
	INNER JOIN LY_ALUNO AL
		ON AL.ALUNO = CL.ALUNO
	left JOIN LY_TURMA TU
		ON TU.TURMA = AG.TURMA
		AND TU.DISCIPLINA = AG.DISCIPLINA
		AND TU.ANO = AG.ANO
		AND TU.SEMESTRE = AG.SEMESTRE
	left JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = AG.NUM_FUNC
GROUP BY
	ag.ANO,
	ag.SEMESTRE ,
	AG.TURMA,
	CL.DISCIPLINA,
	CL.ALUNO,
	AL.NOME_COMPL,
	tu.SIT_TURMA,
	tu.CLASSIFICACAO,
	DO.NOME_COMPL,
	CL.LISTA,
	AG.DATA,
	CL.OCORRENCIA

