/*
	VIEW VW_FCAV_FOLLOW_UP_CANDIDATOS

Finalidade: Utilizada na planilha de Follow-up dos Candidatos do Lyceum para auxiliar a Secretaria.

Autor: Gabriel SS
Data: 13/07/2018
*/


ALTER VIEW VW_FCAV_FOLLOW_UP_CANDIDATOS   
AS  
  
SELECT
	CASE WHEN TU.CONCURSO = 'CEAI-egressos-2018/1' THEN 'ESPEC'
	ELSE TU.UNIDADE_RESPONSAVEL
	END UNIDADE_RESPONSAVEL,
	CASE WHEN TU.CONCURSO = 'CEAI-egressos-2018/1' THEN 'CEAI'
	ELSE TU.CURSO
	END CURSO,
	CASE WHEN TU.CONCURSO = 'CEAI-egressos-2018/1' THEN 'Especialização em Administração Industrial'
	ELSE TU.NOME_CURSO
	END NOME_CURSO,
	CASE WHEN TU.CONCURSO = 'CEAI-egressos-2018/1' THEN CO.CONCURSO
	ELSE TU.TURMA
	END TURMA, 
	CO.CONCURSO,
	OC.ANO_INGRESSO AS ANO,
	OC.PER_INGRESSO AS PERIODO,
	CO.DT_INICIO AS DT_INI_CONCURSO,
	CO.DT_FIM AS DT_FIM_CONCURSO,
	CA.CANDIDATO,  
	CA.NOME_COMPL,  
	CA.E_MAIL,  
	PE.DDD_FONE_CELULAR AS DDD_CELULAR,
	PE.CELULAR,  
	PE.DDD_FONE,
	PE.FONE,  
	PE.DDD_FONE_COMERCIAL AS DDD_FONE_COM,
	PE.FONE_COM,  
	DATA_INSC,  
	SIT_CANDIDATO_VEST, 
	isnull(PM.SIT_MATRICULA, 'Não Matriculado') SIT_MATRICULA,
	CA.OBS AS FOLLOW_UP,  
	FC.OBSERV1,  
	FC.OBSERV2,  
	FC.OBSERV3,  
	FC.OBSERV4,  
	FC.OBSERV5,  
	FC.OBSERV6,  
	FC.OBSERV7,  
	FC.OBSERV8,  
	FC.OBSERV9,  
	FC.OBSERV10  
FROM  
 LY_CONCURSO CO 
 INNER JOIN LY_CANDIDATO CA  ON CO.CONCURSO = CA.CONCURSO
 INNER JOIN FCAV_CANDIDATOS FC ON FC.CANDIDATO = CA.CANDIDATO AND FC.CONCURSO = CA.CONCURSO  
 INNER JOIN LY_PESSOA PE ON PE.PESSOA = CA.PESSOA  
 INNER JOIN LY_OFERTA_CURSO OC ON OC.CONCURSO = CO.CONCURSO
 INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA	TU ON TU.CONCURSO = CO.CONCURSO
 LEFT JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA PM 
	ON PM.CANDIDATO = CA.CANDIDATO
	AND PM.CONCURSO = CA.CONCURSO

WHERE  
 OC.ANO_INGRESSO>=YEAR(GETDATE()-2)
GROUP BY
	TU.UNIDADE_RESPONSAVEL,
	TU.CURSO,
	TU.NOME_CURSO,
	TU.TURMA, 
	CO.CONCURSO,
	TU.CONCURSO,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,
	CO.DT_INICIO,
	CO.DT_FIM,
	CA.CANDIDATO,  
	CA.NOME_COMPL,  
	CA.E_MAIL,  
	PE.DDD_FONE_CELULAR,
	PE.CELULAR,  
	PE.DDD_FONE,
	PE.FONE,  
	PE.DDD_FONE_COMERCIAL,  
	PE.FONE_COM,  
	DATA_INSC,  
	PM.SIT_MATRICULA, 
	SIT_CANDIDATO_VEST,  
	CA.OBS,
	FC.OBSERV1,  
	FC.OBSERV2,  
	FC.OBSERV3,  
	FC.OBSERV4,  
	FC.OBSERV5,  
	FC.OBSERV6,  
	FC.OBSERV7,  
	FC.OBSERV8,  
	FC.OBSERV9,  
	FC.OBSERV10  