/*
	VIEW VW_FCAV_QUESTIONARIO_CANDIDATO

	Finalidade: View para trazer as respostas do questionário informativo que os candidatos respondem ao final da inscrição.

Autor: Gabriel S. Scalione
Data: 17/09/2014

Alteração: 16/10/2020 - Os JOINS foram ajustados para tirar a duplicidade.  Jonatas Souza 

*/

ALTER VIEW VW_FCAV_QUESTIONARIO_CANDIDATO 
AS 


  SELECT
    CA.CANDIDATO, 
    CA.NOME_COMPL, 
    CA.CONCURSO, 
    CA.SIT_CANDIDATO_VEST, 
    FC.DATA_INSC AS DT_INSCRICAO, 
    QE.QUESTAO, 
    RE.RESPOSTA_SUBJETIVA, 
    CO.TIPO, 
    CO.CONCEITO, 
    QE.QUESTAO_OBJETIVA, 
    QE.QUESTAO_SUBJETIVA, 
    QU.DESCRICAO AS RESPOSTA 

  FROM   LY_CANDIDATO CA 

	INNER JOIN LY_PARTICIPACAO_QUEST PQ
	ON CODIGO = CONCAT(CA.CONCURSO,CA.CANDIDATO) 
    INNER JOIN FCAV_CANDIDATOS FC
    ON  FC.CANDIDATO = CA.CANDIDATO
    AND FC.CONCURSO = CA.CONCURSO 
    LEFT JOIN LY_AVALIADOR AV
    ON  PQ.CODIGO = AV.CODIGO
    LEFT JOIN LY_RESPOSTA RE
    ON  AV.CODIGO = RE.AVA_CODIGO
	LEFT JOIN LY_TIPO_QUESTIONARIO TQO
	ON RE.TIPO_QUESTIONARIO = TQO.TIPO_QUESTIONARIO
    LEFT JOIN LY_CONCEITO_RESPOSTA CO 
    ON RE.CHAVE_RESP = CO.CHAVE_RESP 
	  LEFT JOIN LY_QUESTAO QE 
    ON  QE.QUESTAO = RE.QUESTAO 
    AND QE.TIPO_QUESTIONARIO = RE.TIPO_QUESTIONARIO  
	AND QE.QUESTIONARIO = RE.QUESTIONARIO
	AND QE.QUESTAO = RE.QUESTAO
	AND TQO.TIPO_QUESTIONARIO = RE.TIPO_QUESTIONARIO
    INNER JOIN LY_TIPO_QUESTAO TQ 
    ON  TQ.TIPO = QE.TIPO  
    LEFT JOIN LY_CONCEITOS_QUEST QU 
    ON  QU.CONCEITO = CO.CONCEITO
	AND TQ.TIPO = QU.TIPO 
	
    GROUP  BY 
	RE.AVA_CODIGO, 
    QE.QUESTAO, 
    RE.QUESTIONARIO, 
    RE.RESPOSTA_SUBJETIVA, 
    CO.TIPO, 
    CO.CONCEITO, 
    CA.CANDIDATO, 
    CA.NOME_COMPL, 
    CA.CONCURSO, 
    CA.SIT_CANDIDATO_VEST, 
    FC.DATA_INSC, 
    QE.QUESTAO_OBJETIVA, 
    QE.QUESTAO_SUBJETIVA,     
    QU.DESCRICAO,
	TQO.TIPO_QUESTIONARIO





