/*
	VIEW VW_FCAV_DECLARACAO_EGRESSOS_CEAI

Finalidade: View para trazer a relação de alunos de CEAI egressos, com os dados da disciplinas e ementa.

SELECT * FROM VW_FCAV_MEDIA_FINAL_ALUNOS WHERE ALUNO = 'E201710162'
SELECT * FROM VW_FCAV_DECLARACAO_EGRESSOS_CEAI WHERE TURMA = 'CEAI-egressos-2018/1'
SELECT * FROM VW_FCAV_RELAT_DOCENTE_DISCIPLINA WHERE TURMA = 'CEAI-egressos-2018/1'

Autor: Gabriel
Data: 02/08/2018

*/

ALTER VIEW VW_FCAV_DECLARACAO_EGRESSOS_CEAI
AS

	SELECT 
		MF.ALUNO,
		MF.NOME_COMPL,
		PE.RG_NUM,
		dbo.FN_FCAV_formatarCNPJCPF(PE.CPF) as CPF,
		MF.TURMA,
		MF.DISCIPLINA,
		CASE WHEN MF.TURMA LIKE '%egresso%' THEN
		SUBSTRING(SUBSTRING(MF.NOME_DISCIPLINA,1,CHARINDEX(RIGHT(MF.NOME_DISCIPLINA,5),MF.NOME_DISCIPLINA)-1),CHARINDEX('em ',MF.NOME_DISCIPLINA)+3,LEN(MF.NOME_DISCIPLINA))
		ELSE MF.NOME_DISCIPLINA
		END AS NOME_DISCIPLINA,
		LOWER(CONVERT(VARCHAR,dbo.FN_FCAV_MES_EXT(MONTH(RD.INICIO_DISCIPLINA))) + 
		' a ' + CONVERT(VARCHAR,DBO.FN_FCAV_MES_EXT(MONTH(RD.TERMINO_DISCIPLINA))) + 
		' de ' + CONVERT(VARCHAR,YEAR(RD.TERMINO_DISCIPLINA))) AS PERIODO,
		CASE WHEN RD.DIA_DA_SEMANA = 'sábado' THEN 'aos sábados'
		ELSE 'às '+ REPLACE(RD.DIA_DA_SEMANA,'-feira','s') 
		END AS DIA_DA_SEMANA,
		REPLACE(Convert(varchar(05),HA.HORAINI_AULA,108),':','h') AS HORAINI_AULA,
		REPLACE(Convert(varchar(05),HA.HORAFIM_AULA,108),':','h') AS HORAFIM_AULA,
		lower(CONVERT(VARCHAR, CONVERT(INT,DI.HORAS_AULA)) +' ('+ dbo.FN_FCAV_NUM_EXTENSO(DI.HORAS_AULA)+') horas')
		AS CARGA_HORARIA_DISC,
		MF.FREQUENCIA,
		MF.NOTA_FINAL,
		MF.SITUACAO_HIST,
		DO.NOME_COMPL AS RESPONSAVEL,
		ISNULL(DO.TITULACAO,'') AS TITULACAO,
		ISNULL(PL.EMENTA_RESUMO,'') AS EMENTA_RESUMO
	FROM 
		VW_FCAV_MEDIA_FINAL_ALUNOS MF
		left JOIN LY_ALUNO AL
			ON AL.ALUNO = MF.ALUNO
			AND AL.CURSO = MF.CURSO
			
		left JOIN LY_PESSOA PE
			ON PE.PESSOA = AL.PESSOA

		LEFT JOIN VW_FCAV_RELAT_DOCENTE_DISCIPLINA RD
			ON RD.DISCIPLINA = MF.DISCIPLINA
			AND RD.TURMA = MF.TURMA
		
		left JOIN LY_DOCENTE DO
			ON DO.NOME_COMPL = RD.DOCENTE

		LEFT JOIN LY_HOR_AULA HA
			ON HA.TURMA	= MF.TURMA
			AND HA.DISCIPLINA = MF.DISCIPLINA
			AND HA.ANO = MF.ANO
			AND HA.SEMESTRE = MF.SEMESTRE

		left JOIN LY_DISCIPLINA DI
			ON DI.DISCIPLINA = MF.DISCIPLINA
		
		LEFT JOIN LY_PLANO_DID_PED_RESUMO PL
			ON PL.DISCIPLINA = MF.DISCIPLINA

		
	WHERE
		MF.CURSO = 'CEAI'
		AND Lower(MF.TURMA) LIKE '%egresso%'
		AND MF.SITUACAO_HIST = 'Aprovado'
	GROUP BY
		MF.ALUNO,
		MF.NOME_COMPL,
		PE.RG_NUM,
		PE.CPF,
		MF.TURMA,
		MF.DISCIPLINA,
		MF.NOME_DISCIPLINA,
		RD.INICIO_DISCIPLINA,
		RD.TERMINO_DISCIPLINA,
		RD.DIA_DA_SEMANA,
		HA.HORAINI_AULA,
		HA.HORAFIM_AULA,
		DI.HORAS_AULA,
		MF.FREQUENCIA,
		MF.NOTA_FINAL,
		MF.SITUACAO_HIST,
		DO.NOME_COMPL,
		DO.TITULACAO,
		PL.EMENTA_RESUMO 

