/*    
 VIEW PARA TRAZER O VALOR DO SERVIÇO DE MENSALIDADE 
 E SE EXISTIR O SERVIÇO DE MATRICULA QUE ESTÃO VINCULADOS
 PARA OFERTA DE CURSO
    
Autor: Gabriel S.Scalione    
Data: 20/03/2017    

*/  
ALTER VIEW VW_FCAV_VALOR_OFERTA_CURSO  
AS

	SELECT  
		CT.UNIDADE_RESPONSAVEL,
		CT.CURSO,
		CT.TURNO,
		CT.CURRICULO,
        CT.TURMA,
        CT.OFERTA_DE_CURSO,
        VSP.*
    FROM LY_VALOR_SERV_PERIODO VSP  
		INNER JOIN LY_SERVICO_MATRICULA SM  
			ON VSP.SERVICO = SM.SERVICO  
		INNER JOIN LY_OFERTA_CURSO OC
			ON OC.ANO_INGRESSO = SM.ANO
			AND OC.PER_INGRESSO = SM.PERIODO
			AND OC.CURSO = SM.CURSO
			AND OC.TURNO = SM.TURNO
			AND OC.CURRICULO = SM.CURRICULO
		INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT  
			ON CT.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
			AND CT.CURSO = SM.CURSO
			AND CT.TURNO = SM.TURNO
			AND CT.CURRICULO = SM.CURRICULO
    WHERE VSP.SERVICO LIKE 'MATR%'
    
	GROUP BY CT.UNIDADE_RESPONSAVEL,
			CT.CURSO,
			CT.TURNO,
			CT.CURRICULO,
			CT.TURMA,
			CT.OFERTA_DE_CURSO,
			VSP.SERVICO,
			VSP.ANO,
			VSP.PERIODO,
			VSP.CUSTO_UNITARIO
    
    UNION ALL
    
    SELECT  
        ST.UNIDADE_RESPONSAVEL,
		ST.CURSO,
		ST.TURNO,
		ST.CURRICULO,
        ST.TURMA,
        ST.OFERTA_DE_CURSO,
        VSP.*
    FROM LY_VALOR_SERV_PERIODO VSP  
		INNER JOIN VW_FCAV_SERVICO_TURMA ST  
			ON VSP.SERVICO = ST.SERVICO
			AND VSP.ANO = ST.ANO
			AND VSP.PERIODO = ST.SEMESTRE   
    WHERE VSP.SERVICO LIKE 'MENS%' 
	GROUP BY ST.UNIDADE_RESPONSAVEL,
		  ST.CURSO,
		  ST.TURNO,
		  ST.TURMA,
		  ST.OFERTA_DE_CURSO,
		  VSP.SERVICO,
		  VSP.ANO,
		  VSP.PERIODO,
		  VSP.CUSTO_UNITARIO,
		  ST.CURRICULO
