
ALTER VIEW VW_FCAV_AGENDA_ALUNO_DISCIPLINA
AS

/*****************************************************************************  
-- View para retornar os dias das aulas por disciplina e aluno --  
Autor: Gabriel S.S.  
Data: 30/03/2016  
******************************************************************************/

SELECT
    AG.DATA AS DATA,
    dbo.FN_FCAV_DIA_SEMANA_EXT(AG.DATA) AS DIA,
    CONVERT(varchar, AG.HORA_INICIO, 108) AS HORA_INICIO,
    CONVERT(varchar, AG.HORA_FIM, 108) AS HORA_FIM,
    DI.DISCIPLINA,
    dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(DO.NOME_COMPL) AS DOCENTE,
    AG.FACULDADE AS UNIDADE,
    AG.DEPENDENCIA AS SALA,
    DI.NOME_COMPL AS NOME_DISCIPLINA,
    AG.TURMA,
    AG.ANO,
    AG.SEMESTRE,
    TU.UNIDADE_RESPONSAVEL AS CATEGORIA,
    MA.ALUNO,
    MA.SIT_MATRICULA,
    ISNULL(CT.CONCURSO,AG.TURMA) AS CONCURSO,
    AG.CANCELADA
FROM LY_AGENDA AG
INNER JOIN LY_DOCENTE DO
    ON DO.NUM_FUNC = AG.NUM_FUNC
INNER JOIN LY_DISCIPLINA DI
    ON DI.DISCIPLINA = AG.DISCIPLINA
INNER JOIN LY_MATRICULA MA
    ON MA.DISCIPLINA = AG.DISCIPLINA
    AND MA.TURMA = AG.TURMA
    AND MA.ANO = AG.ANO
    AND MA.SEMESTRE = AG.SEMESTRE
LEFT JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT
    ON CT.TURMA = AG.TURMA
INNER JOIN LY_TURMA TU
    ON TU.TURMA = AG.TURMA
    AND TU.DISCIPLINA = AG.DISCIPLINA
WHERE MA.SIT_MATRICULA NOT LIKE 'Cancelado'
AND DI.DISCIPLINA NOT LIKE 'CEAI-RESERV'
--AND AG.TURMA LIKE '%SAB%'
GROUP BY AG.DATA,
         AG.HORA_INICIO,
         AG.HORA_FIM,
         DI.DISCIPLINA,
         DO.NOME_COMPL,
         AG.FACULDADE,
         AG.DEPENDENCIA,
         DI.NOME_COMPL,
         AG.TURMA,
         AG.ANO,
         AG.SEMESTRE,
         TU.UNIDADE_RESPONSAVEL,
         MA.ALUNO,
         MA.SIT_MATRICULA,
         CT.CONCURSO,
         AG.CANCELADA