-----------------------------------------------------------------------
--CONSULTA

CREATE VIEW VW_FCAV_CANDIDATO_ALUNO_SITUACAO_DETALHADA
AS
	SELECT
		TCA.CURSO,
		TCA.TURMA,
		TCA.DT_INICIO_TURMA,
		CASE
			WHEN TCA.CONCURSO IS NULL THEN 'Venda Direta'
			ELSE 'Processo Seletivo'
		END AS TIPO_INGRESSO,
		PE.PESSOA,
		PE.NOME_COMPL, 
		lower(pe.E_MAIL) E_MAIL,
		'(' + pe.DDD_FONE + ') ' + pe.FONE as TELEFONE,
		'(' + pe.DDD_FONE_CELULAR + ') ' + pe.CELULAR as CELULAR,
		TCA.INSCRITO,
		ISNULL(TCA.DT_INSCRICAO,FC.DATA_INSC) AS DT_INSCRICAO,
		CASE
			WHEN TCA.CONCURSO IS NOT NULL THEN TCA.SITUACAO
			ELSE ''
		END AS SIT_CANDIDATO,
		CA.FL_FIELD_01 AS DT_ANALISE_FINAN,
		CA.FL_FIELD_02 AS RESULT_PESSOA_FISICA,
		CA.FL_FIELD_03 AS RESULT_PESSOA_JURIDICA,
		CA.FL_FIELD_04 AS DT_SELECAO_COORD,
		CA.FL_FIELD_05 AS SELECAO_COORD,
		CA.FL_FIELD_06 AS DT_NOTIFICACAO,
		CA.FL_FIELD_07 AS CAUSA_DESISTENCIA,
		CA.FL_FIELD_08 AS MOTIVO_DESISTENCIA,
		CASE
			WHEN EXISTS (SELECT
					1
				FROM LY_CONVOCADOS_VEST
				WHERE CANDIDATO = TCA.INSCRITO
				AND CONCURSO = TCA.CONCURSO) THEN 'CONVOCADO'
			ELSE 'NÃO CONVOCADO'
		END SIT_CONVOCADO,
		AL.DT_INGRESSO,
		AL.ALUNO,
		AL.SIT_ALUNO,
		PM.SIT_MATRICULA ,
		PM.DT_MATRICULA AS DT_EFETIVACAO_MATRICULA,
		CASE
			WHEN EXISTS (SELECT
					1
				FROM LY_H_CURR_ALUNO
				WHERE ALUNO = TCA.INSCRITO) THEN 'Transferido'
			ELSE 'Normal'
		END ORIGEM,
		HC.DT_ENCERRAMENTO,
		HC.MOTIVO,
		HC.CAUSA_ENCERR,
		HC.DT_REABERTURA
		
	FROM VW_FCAV_CANDIDATO_ALUNO_SITUACAO TCA
	LEFT JOIN LY_CANDIDATO CA
		ON CA.CANDIDATO = TCA.INSCRITO
	LEFT JOIN LY_ALUNO AL
		ON  CASE WHEN AL.CANDIDATO IS NULL THEN al.ALUNO
			ELSE AL.CANDIDATO
			END = TCA.INSCRITO
		AND AL.CURSO = TCA.CURSO
		AND AL.TURNO = TCA.TURNO
		AND AL.CURRICULO = TCA.CURRICULO
		AND AL.ANO_INGRESSO = TCA.ANO_INGRESSO
		AND AL.SEM_INGRESSO = TCA.PER_INGRESSO
	
	LEFT JOIN  LY_H_CURSOS_CONCL HC
		ON HC.ALUNO = AL.ALUNO
		AND HC.CURSO = AL.CURSO
		AND HC.TURNO = AL.TURNO
		AND HC.CURRICULO = AL.CURRICULO
		AND HC.ANO_INGRESSO = AL.ANO_INGRESSO
		AND HC.SEM_INGRESSO = AL.SEM_INGRESSO

	LEFT JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA PM
		ON PM.ALUNO = AL.ALUNO
		AND PM.CURSO = AL.CURSO
		AND PM.TURNO = AL.TURNO
		AND PM.CURRICULO = AL.CURRICULO
		AND PM.ANO_INGRESSO = AL.ANO_INGRESSO
		AND PM.SEM_INGRESSO = AL.SEM_INGRESSO

	LEFT JOIN FCAV_CANDIDATOS FC
		ON FC.CANDIDATO = TCA.INSCRITO
		AND FC.CONCURSO = TCA.CONCURSO
	
	INNER JOIN  LY_PESSOA PE
		ON PE.PESSOA = TCA.PESSOA

	GROUP BY 
		TCA.DT_INICIO_TURMA,
		TCA.CURSO,
		TCA.TURMA,
		TCA.CONCURSO,
		PE.PESSOA,
		PE.NOME_COMPL,
		pe.E_MAIL,
		pe.DDD_FONE ,
		pe.FONE,
		pe.DDD_FONE_CELULAR,
		pe.CELULAR,
		TCA.INSCRITO,
		TCA.DT_INSCRICAO,
		FC.DATA_INSC,
		AL.DT_INGRESSO,
		TCA.SITUACAO,
		CA.FL_FIELD_01,
		CA.FL_FIELD_02,
		CA.FL_FIELD_03,
		CA.FL_FIELD_04,
		CA.FL_FIELD_05,
		CA.FL_FIELD_06,
		CA.FL_FIELD_07,
		CA.FL_FIELD_08,
		AL.ALUNO,
		AL.SIT_ALUNO,
		PM.SIT_MATRICULA ,
		PM.DT_MATRICULA,
		HC.DT_ENCERRAMENTO,
		HC.MOTIVO,
		HC.CAUSA_ENCERR,
		HC.DT_REABERTURA