/*

	SELECT * FROM VW_FCAV_AVAL_INDICES_GERAL WHERE TURMA LIKE 'CEAI%2020%1' AND DISC_AVALIADA LIKE 'CEAI%TCC%'  ORDER BY CURSO,TURMA,ASPECTO,COD_AVAL,QUESTAO
*/


ALTER VIEW VW_FCAV_AVAL_INDICES_GERAL
AS

SELECT 
	CURSO,
	DISC_AVALIADA,
	TURMA,
	ASPECTO,
	AVALIADO,
	NOME_AVALIADO,
	COD_AVAL,
	QUESTAO,
	PERGUNTAS,
	AVG(QTDE_PREENCHIDA) QTDE_PREENCHIDA,
	SUM(EXCELENTE) AS EXCELENTE,
	SUM(BOM) AS BOM,
	SUM(REGULAR) AS REGULAR,
	SUM(RUIM) AS RUIM,
	SUM(PESSIMO) AS PESSIMO,
	CONVERT(DECIMAL(10,2),((CAST(SUM(BOM)AS decimal(10,2))+SUM(EXCELENTE))/SUM(QTDE_PREENCHIDA))) AS INDICE_APROVACAO,
	CONVERT(DECIMAL(10,2),((CAST(SUM(REGULAR)AS decimal(10,2))+SUM(RUIM)+SUM(PESSIMO))/SUM(QTDE_PREENCHIDA))) AS INDICE_REJEICAO
	
FROM VW_FCAV_AVAL_RESULTADO AR


GROUP BY CURSO,
	DISC_AVALIADA,
	TURMA,
	ASPECTO,
	AVALIADO,
	NOME_AVALIADO,
	COD_AVAL,
	QUESTAO,
	PERGUNTAS

