
ALTER VIEW VW_FCAV_VERIFICA_CENTRO_CUSTO
AS

SELECT
	T.CURSO,
	CONCURSO,
	OFERTA_DE_CURSO,
	T.TURMA,
	DISCIPLINA,
	T.CENTRO_DE_CUSTO AS C_CUSTO_DISCIPLINA,
	DESCR AS DESCR_HADES,
	ITEM AS CENTRO_CUSTO_HADES
FROM LY_TURMA T
LEFT JOIN VW_FCAV_INI_FIM_CURSO_TURMA V 
	ON (V.TURMA = T.TURMA)
LEFT JOIN HADES.dbo.ITEMTABELA
	ON (REPLACE(REPLACE(REPLACE(CONCURSO, ' ', ''), '-', ''), ':', '') = REPLACE(REPLACE(REPLACE(DESCR, ' ', ''), '-', ''), ':', '')
	OR REPLACE(REPLACE(REPLACE(REPLACE(T.TURMA, ' ', ''), '-', ''), ':', ''),'SAB','') = REPLACE(REPLACE(REPLACE(DESCR, ' ', ''), '-', ''), ':', ''))
WHERE TAB = 'CentroCusto'
-- AND T.TURMA = 'A-CCW T 02'
GROUP BY
	T.CURSO,
	CONCURSO,
	OFERTA_DE_CURSO,
	T.TURMA,
	DISCIPLINA,
	T.CENTRO_DE_CUSTO,
	DESCR,
	ITEM