


ALTER VIEW VW_FCAV_FECHAMENTO_TURMA 
AS


WITH ALUNOS_CONTRATANTES
AS(
	SELECT TURMA,
		ALUNO,
		VALOR_CONTRATADO
	FROM 
		VW_FCAV_DASHBOARD_FINANCEIRO
	WHERE
		YEAR(DT_INICIO) >= 2018
	GROUP BY 
		TURMA,
		ALUNO,
		VALOR_CONTRATADO
),
ALUNOS_PAGANTES AS 
(
	SELECT TURMA,
		ALUNO
	FROM 
		VW_FCAV_DASHBOARD_FINANCEIRO
	WHERE SIT_ALUNO != 'Cancelado'
		  AND VALOR_PAGO > 0
		  AND YEAR(DT_INICIO) >= 2018
	GROUP BY 
		TURMA,
		ALUNO
)


SELECT 
	DM.UNID_RESP,
	DM.CURSO,
	DM.NOME_CURSO,
	DM.OFERTA_DE_CURSO,
	DM.ANO_INICIO AS ANO_INGRESSO,
	DM.PER_INGRESSO,
	DM.INSCRICOES,
	DM.TURMA,
	DM.DT_INICIO,
	DM.SITUACAO_TURMA,
	DM.REALIZACAO,
	isnull((SELECT  
        SUM(CAST(VS.VALOR_CURSO AS money))  
    FROM VW_FCAV_VALOR_SERVICOS_CURRICULOS VS  
		INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
			ON VT.CURSO = VS.CURSO
			AND VT.CURRICULO = VS.CURRICULO
			AND VT.TURNO = VS.TURNO
			AND VT.TURMA = VS.TURMA
    WHERE VT.TURMA = DM.TURMA) ,0)
    AS VALOR_CURSO, 
	isnull(DM.TOTAL_INSCRITOS,0) AS NUM_INSCRITOS,
	isnull(DESISTENTES,0) AS DESISTENTES,
	isnull(MATRICULADOS,0) AS MATRICULADOS,
	isnull((SELECT Count(VD.ALUNO) 
        FROM   ALUNOS_PAGANTES VD 
        WHERE  VD.TURMA = DM.TURMA 
			   
        GROUP  BY TURMA),0)	AS NUM_PAGANTES,
	isnull((SELECT COUNT(ALUNO) FROM VW_FCAV_ALUNOS_COM_VOUCHERS WHERE OFERTA_DE_CURSO = DM.OFERTA_DE_CURSO
		AND TURMA = DM.TURMA AND DESC_PERC_VALOR = 'Percentual' AND DESCONTO = 100.000000),0) AS NUM_VOUCHERS_100,
	isnull((SELECT COUNT(ALUNO) 
        FROM   VW_FCAV_ALUNOS_BOLSISTAS BO 
        WHERE  BO.TURMA = DM.TURMA 
               AND BO.PERC_VALOR = 'Percentual' 
               AND BO.VALOR = 1.000000
			   AND BO.SIT_ALUNO != 'Cancelado'
        GROUP  BY TURMA),0)
		            AS NUM_CORTESIAS_100_PERC ,
	isnull((SUM(CAST(AC.VALOR_CONTRATADO AS money)))
			 ,0) AS TOTAL_VENDIDO
FROM 
	VW_FCAV_DASHBOARD_FECHAMENTO_MATRICULA DM
	LEFT JOIN ALUNOS_CONTRATANTES AC
		ON AC.TURMA = DM.TURMA		
GROUP BY
	DM.UNID_RESP,
	DM.CURSO,
	DM.NOME_CURSO,
	DM.OFERTA_DE_CURSO,
	DM.ANO_INICIO,
	DM.PER_INGRESSO,
	DM.INSCRICOES,
	DM.TURMA,
	DM.SITUACAO_TURMA,
	DM.DT_INICIO,
	DM.REALIZACAO,
	DM.TOTAL_INSCRITOS,
	MATRICULADOS,
	DESISTENTES
	
