
/*
	VIEW VW_FCAV_INSCRITOS_PALESTRAS

Finalidade: Utilizada para trazer as informações dos inscritos nas palestras. Alimenta a planilha INFO_ALUNOS_VENDA_DIRETA.xlsx folha PALESTRA.

Autor: Gabriel S. Scalione
Data: 10/07/2018

*/

ALTER VIEW VW_FCAV_INSCRITOS_PALESTRAS
AS

--IDENTIFICA A ÚLTIMA OCORRENCIA CADASTRADA
WITH DT_ULTIMA_OCORRENCIA AS 
(
	SELECT 
		ALUNO,
		MAX(DATA) AS UltimaData
    FROM 
		LY_OCORRENCIA
	GROUP BY 
		ALUNO
)
--TRAZ A INFORMAÇÃO DA ÚLTIMA OCORRENCIA
,ULTIMA_OCORRENCIA AS 
(
	SELECT DISTINCT
		OC.ALUNO,
		OC.DATA,
		OC.TIPO,
		OC.DESCRICAO,
		OC.USUARIO
	FROM 
		LY_OCORRENCIA OC
		INNER JOIN DT_ULTIMA_OCORRENCIA DU
			ON DU.ALUNO = OC.ALUNO
			AND DU.UltimaData = OC.DATA

	GROUP BY
		OC.ALUNO,
		OC.DATA,
		OC.TIPO,
		OC.DESCRICAO,
		OC.USUARIO
)
	
--RETORNA OS DADOS DOS INSCRITOS COM A ÚLTIMA OCORRENCIA TRATADA.
SELECT 
	AL.UNIDADE_RESPONSAVEL,
	AL.TURMA,
	AL.DATA_INICIAL AS INICIO_OFERTA,
	AL.DATA_FIM AS FIM_OFERTA,
	AL.DESCRICAO AS NOME_CURSO,
	AL.INICIO_DO_CURSO,
	AL.FIM_DO_CURSO,
	AL.TIPO_INSCRICAO,
	AL.ALUNO,
	AL.NOME_COMPL,
	AL.DT_INGRESSO,
	CASE WHEN AL.ALOCADO = 'S'  THEN 'Confirmado'
		 WHEN AL.ALOCADO = 'N'  THEN 'Em Espera'
		 WHEN AL.ALOCADO = 'NA' THEN 'Cancelado'
	END AS SIT_INSCRICAO,
	AL.SIT_MATRICULA,
	AL.FONE,
	AL.FONE_COM,
	AL.CELULAR,
	AL.E_MAIL,
	AL.RG_NUM,
	AL.CPF,
	AL.CIDADE,
	AL.UF,
	OC.DATA AS DT_OCORRENCIA,
	OC.TIPO,
	OC.DESCRICAO,
	OC.USUARIO
FROM 
	VW_FCAV_ALUNOS_VENDA_DIRETA AL
	LEFT JOIN ULTIMA_OCORRENCIA OC
		ON OC.ALUNO = AL.ALUNO

WHERE 
	YEAR(INICIO_DO_CURSO) >= YEAR(GETDATE()-1)
	AND UNIDADE_RESPONSAVEL = 'PALES'



