/*
	VIEW VW_FCAV_ALUNOS_COM_VOUCHERS

Finalidade: Traz a relação de alunos que possuem voucher cadastrados

Autor: Gabriel Serrano Scalione
Data: 11/06/2018

*/

ALTER VIEW VW_FCAV_ALUNOS_COM_VOUCHERS
AS
		  SELECT 
			AL.ALUNO,
			AL.NOME_COMPL,
			CO.OFERTA_DE_CURSO,
			CT.TURMA,
			AL.DT_INGRESSO,
			LV.ID_LOTE_VOUCHER,
			VOUCHER,
			DESCRICAO,
			DESC_PERC_VALOR,
			LV.DESCONTO,
			CO.DATA_INCLUSAO as DT_UTILIZACAO

			
		  FROM LY_LOTE_VOUCHER LV
			INNER JOIN LY_VOUCHER VO
				ON VO.ID_LOTE_VOUCHER = LV.ID_LOTE_VOUCHER
			INNER JOIN LY_COMPRA_OFERTA CO
				ON CO.ID_LOTE_VOUCHER = VO.ID_LOTE_VOUCHER
				AND CO.ID_VOUCHER = VO.ID_VOUCHER
			INNER JOIN LY_ALUNO AL
				ON AL.ALUNO = CO.ALUNO
			INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT
				ON CT.OFERTA_DE_CURSO = CO.OFERTA_DE_CURSO