/*
	VW_FCAV_MATR_PRE_E_HIST_SERIE

FINALIDADE: UTILIZADA PARA TRAZER OS ALUNOS QUE ESTÃO MATRICULADOS E HISTORICOS


select * from VW_FCAV_MATR_PRE_E_HIST_SERIE v2 where v2.ALUNO = 'E201720014'

*/


ALTER VIEW VW_FCAV_MATR_PRE_E_HIST_SERIE
AS
SELECT
    VW.ANO,
    VW.SEMESTRE,
    VW.DISCIPLINA,
    VW.TURMA,
    T.SERIE,
    ALUNO,
    SIT_MATRICULA,
    LANC_DEB,
    VW.DT_ULTALT,
    SERIE_CALCULO,
    COBRANCA_SEP,
    SIT_DETALHE,
    GRUPO_ELETIVA
FROM VW_MATRICULA_E_PRE_MATRICULA VW
INNER JOIN LY_TURMA T
    ON VW.TURMA=T.TURMA
    AND VW.ANO=T.ANO
    AND VW.SEMESTRE=T.SEMESTRE
    AND VW.DISCIPLINA != 'CEAI-RESERV'
UNION ALL
SELECT
    ANO,
    SEMESTRE,
    DISCIPLINA,
    TURMA,
    SERIE,
    ALUNO,
    SITUACAO_HIST AS 'SIT_MATRICULA',
    LANC_DEB,
    DT_ULTALT,
    SERIE AS 'SERIE_CALCULO',
    COBRANCA_SEP,
    SIT_DETALHE,
    GRUPO_ELETIVA
FROM LY_HISTMATRICULA
WHERE DISCIPLINA != 'CEAI-RESERV'