/*
	SELECT 
		*
	FROM ly_item_cred 
	WHERE
		cobranca IN (201080)
		and descricao like 'Mens%'
	GROUP BY COBRANCA
	select * from ly_turma where turma = 'CEAI T 41'
	select * from ly_aluno where aluno in('E202120020')
	select * from ly_cobranca where cobranca IN (218798)
	select * from ly_item_lanc where cobranca IN (218798)
	select * from FCAV_IMPCONT_CAD where turma like 'CEAI t 41%'
	select * from VW_FCAV_COBRANCA_DEB_CRED where cobranca IN ( 218798)
	select * from VW_FCAV_BOLETOS_EMITIDOS_CONTAB where COBRANCA in (218798)

*/

ALTER VIEW VW_FCAV_BOLETOS_EMITIDOS_CONTAB
AS

WITH ALUNOS_BOLETOS AS
(
	SELECT
		AL.ALUNO, 
		AL.NOME_COMPL, 
		AL.SIT_ALUNO, 
		CS.CURSO,
		AL.TURMA_PREF AS NATUREZA,
		CO.COBRANCA, 
		CO.DATA_DE_VENCIMENTO AS DATA_DE_VENCIMENTO, 
		IL.DESCRICAO, 
		CO.DATA_DE_GERACAO AS DATA_DE_EMISSAO, 
		BO.NUMERO_RPS,
		BO.DATA_EMISSAO_RPS, 
		CASE WHEN DC.ACORDO != 0 THEN 'Baixa por Acordo'
			 WHEN DC.ACORDO = 0 AND DC.SALDO = 0 THEN 'Boleto Pago'
			 WHEN (DC.PAGAR < ABS(DC.PAGO) AND DC.PAGAR > 0) THEN 'Valor pago a mais'
			 WHEN (DC.PAGAR < 0) THEN 'Ajustar no Sistema'
			 WHEN (CO.DATA_DE_VENCIMENTO >= GETDATE() AND DC.SALDO > 0) THEN 'A Vencer'
			 WHEN (CO.DATA_DE_VENCIMENTO < GETDATE() AND DC.SALDO > 0) THEN 'Vencido'
			 WHEN (DC.PAGAR >  DC.PAGO AND DC.SALDO > 0) THEN 'Boleto parcialmente pago'
		END AS SITUACAO_BOLETO, 
		DC.DEBITO AS VALOR_FATURADO, 
		DC.MULTA_JUROS, 
		DC.ACRESC_IGPM,
		DC.DESCONTO,
		DC.ACORDO,
		DC.BOLSA, 
		DC.PAGAR AS VALOR_PAGAR, 
		DC.PAGO AS VALOR_PAGO, 
		DC.SALDO
	FROM 
		LY_ALUNO AL
		LEFT JOIN LY_COBRANCA CO
			ON	CO.ALUNO = AL.ALUNO
		LEFT JOIN LY_ITEM_LANC IL
			ON	IL.COBRANCA = CO.COBRANCA
				AND IL.DESCRICAO not like '%IGPM%'
		LEFT JOIN LY_BOLETO BO
			ON	BO.BOLETO = IL.BOLETO
		LEFT JOIN VW_FCAV_COBRANCA_DEB_CRED DC
			ON	DC.COBRANCA = CO.COBRANCA
		LEFT JOIN LY_CURSO CS
			ON	CS.CURSO = AL.CURSO
	where exists(select 1 from ly_boleto bo2 where bo2.boleto = bo.BOLETO)

	GROUP BY
		AL.ALUNO, 
		AL.NOME_COMPL, 
		AL.SIT_ALUNO,
		CS.CURSO,
		AL.TURMA_PREF,
		CO.COBRANCA, 
		CO.DATA_DE_GERACAO,
		CO.DATA_DE_VENCIMENTO , 
		IL.DESCRICAO, 
		CO.DATA_DE_FATURAMENTO, 
		BO.NUMERO_RPS,
		BO.DATA_EMISSAO_RPS, 
		CO.DATA_DE_VENCIMENTO,
		DC.DEBITO, 
		DC.MULTA_JUROS, 
		DC.ACRESC_IGPM,
		DC.DESCONTO,
		DC.ACORDO,
		DC.BOLSA, 
		DC.PAGAR, 
		DC.PAGO, 
		DC.SALDO	
)

, ALUNOS_TURMAS 
AS (
	SELECT
		pm.ALUNO,
		CCT.TURMA,
		pm.CURRICULO,
		CCT.TURMA_CC AS CENTRO_DE_CUSTO
	FROM 
		VW_ALUNO_CURSO PM 
		left join VW_FCAV_CENTRO_CUSTO_TURMA_HADES_SIGA CCT
			on CCT.TURMA  = pm.TURMA_PREF
	where PM.NOME_COMPL != 'Aluno Editor de Tela'
		and PM.FACULDADE not like 'PALES'
	group by pm.ALUNO,
		pm.TURMA_PREF,
		CCT.TURMA,
		pm.CURRICULO,
		CCT.TURMA_CC
)
--Consulta final
SELECT
	AB.ALUNO,
	AB.NOME_COMPL,
	AB.SIT_ALUNO,
	AB.CURSO,
	AL.CENTRO_DE_CUSTO,
	AB.COBRANCA,
	AB.DATA_DE_VENCIMENTO,
	AB.DESCRICAO,
	AB.DATA_DE_EMISSAO,
	AB.NUMERO_RPS,
	AB.DATA_EMISSAO_RPS,
	AB.SITUACAO_BOLETO,
	AB.VALOR_FATURADO,
	AB.MULTA_JUROS,
	AB.ACRESC_IGPM,
	AB.DESCONTO,
	AB.ACORDO,
	AB.BOLSA,
	AB.VALOR_PAGAR,
	abs(AB.VALOR_PAGO) as VALOR_PAGO,
	AB.SALDO
FROM ALUNOS_TURMAS AL
	INNER JOIN ALUNOS_BOLETOS AB
		ON AB.ALUNO = AL.ALUNO
where 
	 VALOR_PAGAR >= 0	--  //As cobrancas que tinham acordo não estavam aparecendo no relatório. chamado 28765
	-- and COBRANCA in (218798)
GROUP BY
	AB.ALUNO,
	AB.NOME_COMPL,
	AB.SIT_ALUNO,
	AB.CURSO,
	AL.CENTRO_DE_CUSTO,
	AB.COBRANCA,
	AB.DATA_DE_VENCIMENTO,
	AB.DESCRICAO,
	AB.DATA_DE_EMISSAO,
	AB.NUMERO_RPS,
	AB.DATA_EMISSAO_RPS,
	AB.SITUACAO_BOLETO,
	AB.VALOR_FATURADO,
	AB.MULTA_JUROS,
	AB.ACRESC_IGPM,
	AB.DESCONTO,
	AB.ACORDO,
	AB.BOLSA,
	AB.VALOR_PAGAR,
	AB.VALOR_PAGO,
	AB.SALDO