/*
	VIEW VW_FCAV_PGTOS_SEM_BOLETO
	
	Finalidade: Relaciona todos os alunos que fizeram o pagamento que não possuem boletos gerados.



*/

ALTER VIEW VW_FCAV_PGTOS_SEM_BOLETOS
AS

-----------------------------------------------------------------------
--CONSULTA

SELECT
	TCA.CURSO,
	TCA.TURNO,
	TCA.CURRICULO,
	TCA.OFERTA_DE_CURSO AS OFERTA,
	TCA.CONCURSO,
    PE.PESSOA,
    PE.NOME_COMPL,
    PE.CPF,
    PE.E_MAIL,   
    AL.ALUNO,
    AL.SIT_ALUNO,
    CASE
        WHEN TCA.CONCURSO IS NULL THEN 'Venda Direta'
        ELSE 'Processo Seletivo'
    END AS TIPO_INGRESSO,
    (SELECT top 1 SIT_MATRICULA 
	 FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MA 
	 WHERE MA.ALUNO = AL.ALUNO GROUP BY SIT_MATRICULA
	 ) AS SIT_MATRICULA,
	(SELECT top 1 TURMA 
	 FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MA 
	 WHERE MA.ALUNO = AL.ALUNO GROUP BY TURMA
	 ) AS TURMA,
    PP.PLANOPAG AS PLANO_PGTO_PERIODO,
    IC.DESCRICAO AS FORMA_PAGAMENTO,
	LD.LANC_DEB,
	LD.GRUPO,
    CASE
        WHEN RE.CGC_TITULAR IS NULL THEN RE.CPF_TITULAR
        WHEN RE.CPF_TITULAR IS NULL THEN RE.CGC_TITULAR
        ELSE NULL
    END AS DOC_TITULAR,
    RE.TITULAR,
    PP.PERCENT_DIVIDA_ALUNO,
    BL.TIPO_BOLSA,
    BL.NUM_BOLSA,
    BL.PERC_VALOR,
	IL.ITEMCOBRANCA,
	IL.COBRANCA,
	CB.BOLETO,
	CB.DATA_DE_VENCIMENTO,
    BL.VALOR as VALOR_BOLSA,
    BL.MOTIVO,
    (SELECT DISTINCT
        SUM(VALOR)
    FROM LY_ITEM_LANC IIL
    WHERE IIL.ALUNO = AL.ALUNO
    AND (IIL.DESCRICAO != 'VALOR ACORDADO'
    AND IIL.ACORDO IS NULL))
    AS VALOR_PAGAR,
	NF.NUMERO_RPS,
	NF.DATA_EMISSAO_RPS,
	NF.DATA_ENVIO_RPS,
	NF.LINK_RPS,
	NF.VALOR_SERVICO_RPS,
	NF.NUMERO_NFE,
	NF.DATA_EMISSAO_NFE,
	VO.VOUCHER,
	VO.DESC_PERC_VALOR,
	VO.DESCONTO

FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA TCA

inner JOIN LY_ALUNO AL
    ON  al.ALUNO = TCA.ALUNO


LEFT JOIN LY_PLANO_PGTO_PERIODO PP
    ON PP.ALUNO = AL.ALUNO

LEFT JOIN LY_RESP_FINAN RE
    ON RE.RESP = PP.RESP

LEFT JOIN LY_BOLSA BL
    ON BL.ALUNO = AL.ALUNO
    
INNER JOIN  LY_PESSOA PE
    ON PE.PESSOA = TCA.PESSOA

INNER JOIN VW_COBRANCA_BOLETO CB
	ON CB.ALUNO = AL.ALUNO

LEFT JOIN LY_CARTAO_LOG CL
	ON CL.ALUNO = AL.ALUNO
	AND CL.COBRANCA = CB.COBRANCA

LEFT JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
	ON VT.OFERTA_DE_CURSO = TCA.OFERTA_DE_CURSO

LEFT JOIN LY_ITEM_LANC IL 
	ON IL.ALUNO = AL.ALUNO
	AND IL.COBRANCA = CB.COBRANCA
	OR IL.MOTIVO_DESCONTO = 'Voucher'

LEFT JOIN LY_ITEM_CRED IC
	ON IC.COBRANCA = IL.COBRANCA
	and IC.DESCRICAO like 'Cartão%'

LEFT JOIN LY_COBRANCA_NOTA_FISCAL NF
	ON NF.COBRANCA = IL.COBRANCA

LEFT JOIN VW_FCAV_ALUNOS_COM_VOUCHERS VO
	ON VO.ALUNO = AL.ALUNO
	AND VO.OFERTA_DE_CURSO = TCA.OFERTA_DE_CURSO

INNER JOIN LY_LANC_DEBITO LD
	ON LD.ALUNO = IL.ALUNO
	
WHERE
--	PC.EMPRESA IS NOT NULL
AL.SIT_ALUNO = 'Ativo' AND
CB.BOLETO IS NULL AND
AL.DT_INGRESSO  >= DATEADD(month,-3,GETDATE())
AND IL.ITEMCOBRANCA = 1
AND NOT EXISTS (SELECT 1 FROM LY_ITEM_LANC IL2 WHERE IL.COBRANCA = IL2.COBRANCA AND IL2.ITEM_ESTORNADO IS NOT NULL)

