/*
	select * from vw_fcav_alunos_matriculados_ceai where aluno = 'E201720013'
*/



ALTER VIEW VW_FCAV_ALUNOS_MATRICULADOS_CEAI
AS

SELECT 
	CURSO,
	UPPER(CURSO) +' - '+CONVERT(VARCHAR,MAX(ANO))+'/'+CONVERT(VARCHAR,MAX(SEMESTRE)) AS TURMA_CEAI,
	MAX(ANO) as ANO,
	MAX(SEMESTRE) as SEMESTRE,
	DISCIPLINA,
	TURMA AS TURMA_ORIGEM,
	ALUNO,
	NOME_COMPL,
	SIT_MATRICULA
 FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA
WHERE
	CURSO = 'CEAI'
	AND DISCIPLINA != 'CEAI-RESERV'
	AND SIT_MATRICULA = 'Matriculado'

GROUP BY 
	CURSO,
	ANO,
	SEMESTRE,
	DISCIPLINA,
	ALUNO,
	NOME_COMPL,
	SIT_MATRICULA,
	TURMA


