/*
	VIEW VW_FCAV_CANDIDATOS_E_ALUNOS

	VIEW PARA TRAZER RELACAO DE INSCRITOS TANTO PROCESSO SELETIVO COMO VENDA DIRETA

	Utilização: 
		- Script para o Dashboard de Refugo;

Autor: Gabriel Scalione
Data: 13/03/2018

*/
ALTER VIEW VW_FCAV_CANDIDATOS_E_ALUNOS
AS

SELECT
    CA.PESSOA,
    CA.CANDIDATO AS INSCRITO,
    CA.SIT_CANDIDATO_VEST AS SITUACAO,
    ISNULL(CA.DT_INSCRICAO, FC.DATA_INSC) AS DT_INSCRICAO,
    OC.OFERTA_DE_CURSO,
	OC.CONCURSO AS CONCURSO,
    OC.CURSO,
    OC.TURNO,
    OC.CURRICULO,
    OC.ANO_INGRESSO,
    OC.PER_INGRESSO,
	OO.TURMA

FROM LY_CANDIDATO CA
INNER JOIN LY_OFERTA_CURSO OC
    ON OC.CONCURSO = CA.CONCURSO
INNER JOIN LY_OPCOES_OFERTA OO
	ON OO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
INNER JOIN FCAV_CANDIDATOS FC
	ON FC.CANDIDATO = CA.CANDIDATO
	AND FC.CONCURSO = CA.CONCURSO
WHERE OC.CONCURSO IS NOT NULL
--	AND CA.SIT_CANDIDATO_VEST !='Cancelado'
GROUP BY CA.PESSOA,
         CA.CANDIDATO,
         CA.CPF,
		 CA.RG_NUM,
		 CA.RG_TIPO,
		 CA.PASSAPORTE,
         CA.SIT_CANDIDATO_VEST,
         CA.DT_INSCRICAO,
		 FC.DATA_INSC,
         OC.CONCURSO,
         OC.OFERTA_DE_CURSO,
         OC.CURSO,
         OC.TURNO,
         OC.CURRICULO,
         OC.ANO_INGRESSO,
         OC.PER_INGRESSO,
		 OO.TURMA

UNION ALL

SELECT
    AL.PESSOA,
    AL.ALUNO AS INSCRITO,
    AL.SIT_ALUNO AS SITUACAO,
    AL.DT_INGRESSO AS DT_INSCRICAO,
	OC.OFERTA_DE_CURSO,
    ISNULL(OC.CONCURSO, 'VENDA DIRETA') CONCURSO,
    OC.CURSO,
    OC.TURNO,
    OC.CURRICULO,
    OC.ANO_INGRESSO,
    OC.PER_INGRESSO,
	AV.TURMA
FROM LY_ALUNO AL

INNER JOIN LY_COMPRA_OFERTA CM
	ON CM.ALUNO = AL.ALUNO
INNER JOIN VW_FCAV_ALUNOS_VENDA_DIRETA AV
    ON AV.ALUNO = AL.ALUNO
INNER JOIN LY_OFERTA_CURSO OC
	ON OC.OFERTA_DE_CURSO = CM.OFERTA_DE_CURSO
--WHERE OC.CONCURSO IS NULL
--AND AL.CANDIDATO IS NULL
--AND AL.CONCURSO IS NULL
--AND AL.SIT_ALUNO = 'Ativo'
GROUP BY AL.PESSOA,
         AL.ALUNO,
         AL.SIT_ALUNO,
         AL.DT_INGRESSO,
         OC.CONCURSO,
         OC.OFERTA_DE_CURSO,
         OC.CURSO,
         OC.TURNO,
         OC.CURRICULO,
         OC.ANO_INGRESSO,
         OC.PER_INGRESSO,
		 AV.TURMA


