IF EXISTS (SELECT * 
           FROM   sys.VIEWS 
           WHERE  NAME = 'VW_FCAV_INFO_ALUNOS_LYCEUM') 
  DROP VIEW VW_FCAV_INFO_ALUNOS_LYCEUM 

go 

  
CREATE VIEW VW_FCAV_INFO_ALUNOS_LYCEUM  
AS  
  
  
SELECT  
	M.UNIDADE_RESPONSAVEL,
    M.CURSO,  
    M.TURMA,  
    CASE  
        WHEN V.DT_FIM <= GETDATE() THEN 'Ex-aluno'  
        ELSE 'Aluno'  
    END SIT_ALUNO,  
    M.ALUNO,  
    P.NOME_COMPL,  
    DT_NASC,  
    YEAR(GETDATE()) - YEAR(DT_NASC) AS IDADE_ATUAL,  
    NACIONALIDADE,  
    SEXO,  
    EST_CIVIL,  
    P.ENDERECO,  
    P.END_NUM,  
    P.END_COMPL,  
    P.BAIRRO,  
    P.END_MUNICIPIO,  
    P.END_PAIS,  
    P.CEP,  
	P.DDD_FONE,
    P.FONE,  
	P.DDD_FONE_CELULAR,
    P.CELULAR,  
    P.E_MAIL,  
    RG_NUM,  
    RG_TIPO,  
    RG_EMISSOR,  
    RG_UF,  
    RG_DTEXP,  
    CPF,  
    PROFISSAO,  
    NOME_EMPRESA,  
    V.DT_INICIO AS DT_INICIO_TURMA,  
    V.DT_FIM AS DT_FIM_TURMA,  
    (SELECT TOP 1  
        CLASSIFICACAO  
		FROM LY_TURMA  
		WHERE SERIE = 1  
		AND CLASSIFICACAO IS NOT NULL  
		AND TURMA = M.TURMA  
		GROUP BY TURMA,  
				 CLASSIFICACAO) AS STATUS_TURMA,  
    M.DT_MATRICULA,  
    M.SIT_MATRICULA,  
    CASE  
        WHEN M.SIT_MATRICULA = 'Matriculado' AND  
            V.DT_FIM < GETDATE() THEN 'Concluído'  
        WHEN M.SIT_MATRICULA = 'Matriculado' AND  
            V.DT_FIM >= GETDATE() THEN 'Cursando'  
    END AS STATUS,  
    RE.TITULAR,  
    CASE  
        WHEN RE.CGC_TITULAR IS NULL THEN RE.CPF_TITULAR  
        ELSE RE.CGC_TITULAR  
    END CPF_CNPJ,  
    BL.TIPO_BOLSA,  
    BL.NUM_BOLSA,  
    BL.PERC_VALOR,  
    BL.VALOR,  
    BL.MOTIVO,
	VO.VOUCHER,
	VO.DESCRICAO,
	VO.DESC_PERC_VALOR,
	VO.DESCONTO,
	M.TURMA_PREF
FROM LY_PESSOA P  
INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA M  
    ON P.PESSOA = M.PESSOA  
INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA V  
    ON V.TURMA = M.TURMA  
LEFT OUTER JOIN LY_PLANO_PGTO_PERIODO PI  
    ON PI.ALUNO = M.ALUNO  
LEFT OUTER JOIN LY_RESP_FINAN RE  
    ON (RE.RESP = PI.RESP)  
LEFT OUTER JOIN LY_BOLSA BL  
    ON BL.ALUNO = M.ALUNO  
LEFT JOIN VW_FCAV_ALUNOS_COM_VOUCHERS VO
	ON VO.ALUNO = M.ALUNO
	AND VO.TURMA = M.TURMA

GROUP BY
	M.UNIDADE_RESPONSAVEL,
    M.CURSO,  
    M.TURMA,  
    M.ALUNO,  
    P.NOME_COMPL,  
    DT_NASC,  
    NACIONALIDADE,  
    SEXO,  
    EST_CIVIL,  
    P.ENDERECO,  
    P.END_NUM,  
    P.END_COMPL,  
    P.BAIRRO,  
    P.END_MUNICIPIO,  
    P.END_PAIS,  
    P.CEP,  
	P.DDD_FONE,
    P.FONE,  
	P.DDD_FONE_CELULAR,
    P.CELULAR,  
    P.E_MAIL,  
    RG_NUM,  
    RG_TIPO,  
    RG_EMISSOR,  
    RG_UF,  
    RG_DTEXP,  
    CPF,  
    PROFISSAO,  
    NOME_EMPRESA,  
    V.DT_INICIO,  
    V.DT_FIM,
	M.DT_MATRICULA,  
    M.SIT_MATRICULA,
	M.DT_MATRICULA,  
    M.SIT_MATRICULA,
	RE.TITULAR,
	RE.CGC_TITULAR,
	RE.CPF_TITULAR,
	BL.TIPO_BOLSA,  
    BL.NUM_BOLSA,  
    BL.PERC_VALOR,  
    BL.VALOR,  
    BL.MOTIVO,
	VO.VOUCHER,
	VO.DESCRICAO,
	VO.DESC_PERC_VALOR,
	VO.DESCONTO,
	M.TURMA_PREF