
ALTER VIEW VW_FCAV_CONFERENCIA_DE_CADASTRADOS_TURMAS
AS

WITH CONFERENCIA_DE_CADASTRADOS_TURMAS
AS (

SELECT
	oc.OFERTA_DE_CURSO as OC,
	tu.TURMA as tur,
    CS.FACULDADE AS UNID_RESP,
    CS.CURSO AS CURSO,
    DBO.FN_FCAV_PRIMEIRA_MAIUSCULA(CS.NOME) AS NOME_CURSO,
    CS.ATIVO,
    CS.TIPO,
    CS.DEPTO,

    ISNULL((SELECT TOP 1
        NOME_COMPL
    FROM VW_FCAV_COORDENADOR_TURMA COORD
    WHERE COORD.TURMA = tu.TURMA
    AND COORD.TIPO_COORD = 'COORD'
    GROUP BY NOME_COMPL), 'NAO CADASTRADO') AS COORDENADOR,
    ISNULL((SELECT TOP 1
        NOME_COMPL
    FROM VW_FCAV_COORDENADOR_TURMA COORD
    WHERE COORD.TURMA = tu.TURMA
    AND COORD.TIPO_COORD != 'COORD'
    GROUP BY NOME_COMPL), '.') AS VICE_COORD,
    
    CR.CURRICULO,
    CR.TURNO,
	CR.ANO_INI,
    CR.SEM_INI,
    CAST(CR.AULAS_PREVISTAS AS decimal(10, 0)) AS CARGA_HORARIA,
    CAST(CR.PRAZO_CONC_PREV AS varchar) + ' ' + CR.TIPO_PRAZO_CONCL AS PRAZO_CONCLUSAO,
    
	ISNULL(CR.SERVICO, 'NAO CADASTRADO') AS SERVICO_VINCULADO,
    CR.PRAZO_IDEAL AS PERIODO_IDEAL,
    CR.PRAZO_MAX AS PERIODO_MAXIMO,
    CR.TRANC_INTERV_DATA,

    ISNULL(GR.DISCIPLINA, 'NAO CADASTRADO') AS DISCIPLINA_GRADE,
    GR.SERIE_IDEAL,
    GR.OBRIGATORIA,

    DI.NOME AS NOME_DISCIPLINA,
    
    DI.CREDITOS,

    CASE WHEN DI.TIPO != TU.NIVEL THEN 'DIFERENTE_TURMA'
	     WHEN DI.TIPO IS NULL THEN '.'
		ELSE DI.TIPO
	END AS NIVEL_DISC,
    
	DI.VERIFICA_HORARIO,
    DI.TEM_FREQ,
    (ISNULL(CAST(DI.PERC_PRESMIN AS decimal(3, 2)), 0) * 100) AS FREQUENCIA,
	
	CASE WHEN DI.TEM_NOTA = 'N' THEN '.'
	 ELSE CAST(DI.NOTA_MAX AS VARCHAR)
	 END NOTA_MAX,
    CASE WHEN DI.TEM_NOTA = 'N' THEN '.'
	 ELSE CAST(DI.N_CASAS_DEC AS VARCHAR)
	 END AS N_CASAS_DEC ,
    CASE WHEN DI.TEM_NOTA = 'N' THEN '.'
	 ELSE CAST(DI.FORMULA_MF1 AS VARCHAR)
	END FORMULA_MF1,
    CASE WHEN DI.TEM_NOTA = 'N' THEN '.'
	 ELSE CAST(DI.FORMULA_CA1 AS VARCHAR)
	 END AS FORMULA_CA1,
    CASE WHEN DI.TEM_NOTA = 'N' THEN '.'
	 ELSE CAST(DI.CONCEITO_MIN_1 AS VARCHAR)
	 END AS CONCEITO_MIN,
	    
	CAST(CAST(DI.AULAS_SEMANAIS AS decimal) AS VARCHAR) AS DIS_AULAS_SEMANAIS,
    
	DI.HORAS_AULA,

    isnull(TU.TURMA, 'NAO CADASTRADO') AS TURMA,
    TU.ANO,
    TU.SEMESTRE,
    TU.FACULDADE AS  UNID_FISICA,
    TU.DISCIPLINA AS TUR_DISCIPLINA,
    TU.DT_INICIO AS DT_INI_TURMA,
    TU.DT_FIM AS DT_FIM_TURMA,
    TU.SERIE,
    TU.SIT_TURMA,
    TU.CLASSIFICACAO,
    TU.AULAS_PREVISTAS,

	CASE WHEN DI.TIPO != TU.NIVEL THEN 'DIFERENTE TURMA'
		 WHEN TU.NIVEL IS NULL THEN '.'
		ELSE TU.NIVEL
    END AS NIVEL,
    
	TU.MIN_AULAS,
    TU.DURACAO_AULA,
	
	CASE WHEN TU.NUM_ALUNOS = 0 OR TU.NUM_ALUNOS IS NULL THEN 'NAO CADASTRADO'
    ELSE CAST(TU.NUM_ALUNOS AS VARCHAR)
	END AS NUM_ALUNOS,

    ISNULL(TU.CENTRO_DE_CUSTO,'NAO CADASTRADO') AS CENTRO_DE_CUSTO,

	CASE WHEN OC.CONCURSO IS NULL THEN CAST(OC.OFERTA_DE_CURSO AS VARCHAR) + ' - ' + OC.TURMA_PREF
	ELSE ISNULL(CN.CONCURSO, 'NAO CADASTRADO') 
	END AS CONCURSO,
	
	CASE WHEN OC.CONCURSO IS NULL THEN '.'
	ELSE ISNULL(CN.TIPO_INGRESSO, 'NAO CADASTRADO')
	END AS TIPO_INGRESSO,
    
	CASE WHEN OC.CONCURSO IS NULL THEN OC.DTINI
	ELSE ISNULL(CN.DT_INICIO,'00/00/0000')
	END AS DTINI_CONCURSO,

	CASE WHEN OC.CONCURSO IS NULL THEN OC.DTFIM
    ELSE ISNULL(CN.DT_FIM, '00/00/0000')
	END AS DTFIM_CONCURSO,
    
	CASE WHEN OC.CONCURSO IS NULL THEN OC.ANO_INGRESSO
	ELSE ISNULL(CN.ANO,1999)
	END AS ANO_INGR_ONLINE,
	
	CASE WHEN OC.CONCURSO IS NULL THEN OC.PER_INGRESSO
	ELSE ISNULL(CN.SEMESTRE,5)
	END AS PER_INGR_ONLINE,
    
	CASE WHEN OC.CONCURSO IS NULL THEN OC.DTINI
	ELSE isnull(CN.INGR_DTINI, '00/00/0000')
	END AS INGR_DTINI,
    
	CASE WHEN OC.CONCURSO IS NULL THEN OC.DTFIM
	ELSE ISNULL(CN.INGR_DTFIM, '00/00/0000')
	END AS INGR_DTFIM,

	CASE WHEN OC.CONCURSO IS NULL THEN 'S'
	ELSE ISNULL(CN.INGR_ESCOLHE_PLANO, 'N')
	END AS INGR_ESCOLHE_PLANO,

	CASE WHEN OC.CONCURSO IS NULL THEN 1
	ELSE ISNULL(CN.INGR_MAX_RESP_FINAN,0)
	END AS INGR_MAX_RESP_FINAN,
    
	CASE WHEN OC.CONCURSO IS NULL THEN 2
	ELSE ISNULL(CN.N_DIAS_VENC_BOL_MATR,0)
	END AS INGR_DIAS_VENC_BOLETO,

    CASE
        WHEN OC.CONCURSO IS NULL THEN 'ContratoLoja'
        ELSE ISNULL(CT.CONTRATO, 'NAO CADASTRADO')
    END AS CONTRATO,

    OC.OFERTA_DE_CURSO,
    OC.CURSO_OFERTADO,
    OC.DESCRICAO_ABREV,
    OC.DESCRICAO_COMPL,
    ISNULL(OC.TURMA_PREF,'NAO CADASTRADO') AS TURMA_PREF,
    OC.ANO_INGRESSO,
    OC.PER_INGRESSO,
    OC.DTINI AS DTINI_OFERTA,
    OC.DTFIM AS DTFIM_OFERTA,
    CASE WHEN OC.CONCURSO IS NULL AND OC.VALOR_A_VISTA_ESTIMADO IS NULL THEN 'NAO CADASTRADO'
	ELSE CAST(OC.VALOR_A_VISTA_ESTIMADO AS VARCHAR)
	END AS VALOR_A_VISTA_ESTIMADO,

    ISNULL(OO.TURMA, 'NAO CADASTRADO') AS OPCOES_OFERTA_TURMA,
    ISNULL(OO.HORARIO_DESCRICAO,'NAO CADASTRADO') AS OPCOES_HORARIO_DESCR,

    ISNULL(PO.PLANO, 'NAO CADASTRADO') AS PLANO,
    ISNULL(PO.PLANOPAG, 'NAO CADASTRADO') AS PLANOPAG,
    ISNULL(PO.DESCRICAO, 'NAO CADASTRADO') AS DESCRICAO,
    ISNULL(CAST(PO.MES_INICIAL AS VARCHAR),'NAO CADASTRADO') AS MES_INICIAL,
    ISNULL(CAST(PO.NUM_PARCELAS AS VARCHAR),'NAO CADASTRADO') AS NUM_PARCELAS,
    ISNULL(CAST(PO.TIPO_DESC AS VARCHAR),'.') AS TIPO_DESC,
    ISNULL(CAST(PO.DESCONTO AS VARCHAR),'.') AS DESCONTO,
    ISNULL(PO.FORMA_PAGAMENTO,'NAO CADASTRADO') AS FORMA_PAGAMENTO,
	CASE WHEN PO.FORMA_PAGAMENTO = 'Cartao' AND PO.NUM_PARCELAS_CARTAO IS NULL THEN 'NAO CADASTRADO'
		 ELSE ISNULL(CAST(PO.NUM_PARCELAS_CARTAO AS VARCHAR),'.') 
	END AS NUM_PARCELAS_CARTAO,
    
    ISNULL(CAST(PO.N_DIAS_VENC_BOL AS VARCHAR) ,'NAO CADASTRADO') AS N_DIAS_VENC_BOL,

    ISNULL(VS.SERVICO,'NAO CADASTRADO') AS SERVICO,
    ISNULL(CAST(VS.CUSTO_UNITARIO AS VARCHAR),'NAO CADASTRADO') AS CUSTO_UNITARIO,

    ISNULL(OC.FL_FIELD_04,'.') AS OCFL04_Programa,
    ISNULL(OC.FL_FIELD_05, '.') AS OCFL05_ValorTotalCurso,
    ISNULL(OC.FL_FIELD_06, '.') AS OCFL06_ValorParcela,
    ISNULL(OC.FL_FIELD_07, '.') AS OCFL07_QtdeParcelas,
    ISNULL(OC.FL_FIELD_08, '.') AS OCFL08_DescontoAVista,
    ISNULL(OC.FL_FIELD_09, '.') AS OCFL09_DiasVenctoBoleto1,
    ISNULL(OC.FL_FIELD_10, '.') AS OCFL10_DiaVenctoMensais,

    ISNULL(CN.FL_FIELD_01, '.') AS CNFL01_Analise_Curricular,
    ISNULL(CN.FL_FIELD_02, '.') AS CNFL02_Entrevista,
    ISNULL(CN.FL_FIELD_03, '.') AS CNFL03_Prova,
    ISNULL(CN.FL_FIELD_04, '.') AS CNFL04_Redacao,
    ISNULL(CN.FL_FIELD_05, '.') AS CNFL05_Alteracao_Conteudo,
    ISNULL(CN.FL_FIELD_06, '.') AS CNFL06_Dia_Horario_Aulas,
    ISNULL(CN.FL_FIELD_07, '.') AS CNFL07_RelacaoDocumentos

FROM LY_CURSO CS

LEFT JOIN LY_CURRICULO CR
    ON CR.CURSO = CS.CURSO

LEFT JOIN LY_GRADE GR
    ON GR.CURSO = CR.CURSO
    AND GR.TURNO = CR.TURNO
    AND GR.CURRICULO = CR.CURRICULO

LEFT JOIN LY_DISCIPLINA DI
    ON DI.DISCIPLINA = GR.DISCIPLINA

LEFT JOIN LY_TURMA TU
    ON TU.CURSO = CR.CURSO
    AND TU.TURNO = CR.TURNO
    AND TU.CURRICULO = CR.CURRICULO
    AND TU.DISCIPLINA = DI.DISCIPLINA
    AND GR.SERIE_IDEAL = TU.SERIE

LEFT JOIN LY_OPCOES_OFERTA OO
    ON OO.TURMA = TU.TURMA
    AND OO.DISCIPLINA = TU.DISCIPLINA

LEFT JOIN LY_OFERTA_CURSO OC
    ON OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO
    AND OC.CURSO = CR.CURSO
    AND OC.TURNO = CR.TURNO
    AND OC.CURRICULO = CR.CURRICULO

LEFT JOIN LY_PLANOS_OFERTADOS PO
    ON PO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO

LEFT JOIN LY_CONCURSO CN
    ON CN.CONCURSO = OC.CONCURSO

LEFT JOIN LY_CURRICULO_CONTRATO CT
    ON CT.CURSO = OC.CURSO
    AND CT.TURNO = OC.TURNO
    AND CT.CURRICULO = OC.CURRICULO
    AND CT.UNIDADE_FISICA = OC.UNIDADE_FISICA

LEFT JOIN LY_VALOR_SERV_PERIODO VS
    ON VS.SERVICO = CR.SERVICO
    AND VS.ANO = OC.ANO_INGRESSO
    AND VS.PERIODO = PER_INGRESSO

WHERE tu.DT_INICIO >= GETDATE() - 1
--AND oc.DTFIM >= GETDATE()

GROUP BY CS.FACULDADE,
         CS.CURSO,
         CS.NOME,
         CS.ATIVO,
         CS.TIPO,
         CS.VAGAS,
        -- CS.DURACAO_AULA,
         CS.DEPTO,
         CR.TURNO,
         CR.CURRICULO,
         CR.ANO_INI,
         CR.SEM_INI,
         CR.AULAS_PREVISTAS,
         CR.PRAZO_CONC_PREV,
         CR.TIPO_PRAZO_CONCL,
         CR.SERVICO,
         CR.PRAZO_IDEAL,
         CR.PRAZO_MAX,
         CR.TRANC_INTERV_DATA,

         GR.DISCIPLINA,
         GR.SERIE_IDEAL,
         GR.OBRIGATORIA,

         DI.NOME,
         DI.TEM_NOTA,
         DI.TEM_FREQ,
         DI.PERC_PRESMIN,
         DI.CREDITOS,
         DI.TIPO,
         DI.VERIFICA_HORARIO,
         DI.NOTA_MAX,
         DI.N_CASAS_DEC,
         DI.FORMULA_MF1,
         DI.FORMULA_CA1,
         DI.CONCEITO_MIN_1,
         DI.AULAS_SEMANAIS,
         DI.HORAS_AULA,

         TU.TURMA,
         TU.ANO,
         TU.SEMESTRE,
         TU.FACULDADE,
         TU.DISCIPLINA,
         TU.NIVEL,
         TU.DT_INICIO,
         TU.DT_FIM,
         TU.SERIE,
         TU.SIT_TURMA,
         TU.CLASSIFICACAO,
         TU.AULAS_PREVISTAS,
         TU.MIN_AULAS,
         TU.DURACAO_AULA,
         TU.NUM_ALUNOS,
         TU.CENTRO_DE_CUSTO,

         OO.TURMA,
         OO.HORARIO_DESCRICAO,

         OC.OFERTA_DE_CURSO,
         OC.CURRICULO,
         OC.CONCURSO,
         OC.CURSO_OFERTADO,
         OC.DESCRICAO_ABREV,
         OC.DESCRICAO_COMPL,
         OC.TURMA_PREF,
         OC.ANO_INGRESSO,
         OC.PER_INGRESSO,
         OC.DTINI,
         OC.DTFIM,
         OC.VALOR_A_VISTA_ESTIMADO,

         PO.PLANO,
         PO.PLANOPAG,
         PO.DESCRICAO,
         PO.MES_INICIAL,
         PO.NUM_PARCELAS,
         PO.TIPO_DESC,
         PO.DESCONTO,
         PO.FORMA_PAGAMENTO,
         PO.NUM_PARCELAS_CARTAO,
         PO.NUM_PARCELAS_INSCR,
         PO.N_DIAS_VENC_BOL,

         CN.CONCURSO,
         CN.TIPO_INGRESSO,
         CN.DT_INICIO,
         CN.DT_FIM,
         CN.ANO,
         CN.SEMESTRE,
         CN.INGR_DTINI,
         CN.INGR_DTFIM,
         CN.INGR_ESCOLHE_PLANO,
         CN.INGR_MAX_RESP_FINAN,
         CN.N_DIAS_VENC_BOL_MATR,

         CT.CONTRATO,

         VS.SERVICO,
         VS.CUSTO_UNITARIO,

         CS.FL_FIELD_01,
         CS.FL_FIELD_02,
         CS.FL_FIELD_03,
         CS.FL_FIELD_04,
         CS.FL_FIELD_05,
         CS.FL_FIELD_06,
         CS.FL_FIELD_07,
         CS.FL_FIELD_08,
         CS.FL_FIELD_09,
         CS.FL_FIELD_10,

         TU.FL_FIELD_01,
         TU.FL_FIELD_02,
         TU.FL_FIELD_03,
         TU.FL_FIELD_04,
         TU.FL_FIELD_05,
         TU.FL_FIELD_06,
         TU.FL_FIELD_07,
         TU.FL_FIELD_08,
         TU.FL_FIELD_09,
         TU.FL_FIELD_10,
         TU.FL_FIELD_11,
         TU.FL_FIELD_12,
         TU.FL_FIELD_13,
         TU.FL_FIELD_14,
         TU.FL_FIELD_15,
         TU.FL_FIELD_16,
         TU.FL_FIELD_17,
         TU.FL_FIELD_18,
         TU.FL_FIELD_19,
         TU.FL_FIELD_20,

         OC.FL_FIELD_04,
         OC.FL_FIELD_05,
         OC.FL_FIELD_06,
         OC.FL_FIELD_07,
         OC.FL_FIELD_08,
         OC.FL_FIELD_09,
         OC.FL_FIELD_10,

         CN.FL_FIELD_01,
         CN.FL_FIELD_02,
         CN.FL_FIELD_03,
         CN.FL_FIELD_04,
         CN.FL_FIELD_05,
         CN.FL_FIELD_06,
         CN.FL_FIELD_07
)


SELECT * FROM CONFERENCIA_DE_CADASTRADOS_TURMAS