/*
		VIEW VW_FCAV_COBRANCA_DEB_CRED

	Finalidade: View utilizada para auxiliar no relatório de boletos emitidos para o contábil.

Autor: Gabriel Serrano Scalione
Data: 26/03/2019
*/

ALTER VIEW VW_FCAV_COBRANCA_DEB_CRED
AS

WITH ITENS_DEBITOS
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS DEBITO
	FROM LY_ITEM_LANC 
	WHERE
		MOTIVO_DESCONTO IS NULL
		AND ACORDO IS NULL
		AND NUM_BOLSA IS NULL
		AND DESCRICAO NOT LIKE '%IGPM%'
	GROUP BY COBRANCA
),
ITENS_CREDITOS
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS CREDITO
	FROM LY_ITEM_CRED 
	WHERE
		TIPO_ENCARGO IS NULL
		AND TIPODESCONTO IS NULL
	GROUP BY COBRANCA
),
ITENS_DESC_DEB
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS DESCONTO
	FROM LY_ITEM_LANC 
	WHERE
		MOTIVO_DESCONTO IS NOT NULL
		AND DESCRICAO NOT LIKE '%IGPM%'
	GROUP BY COBRANCA
),
ITENS_DESC_CRED 
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS DESCONTO
	FROM LY_ITEM_CRED
	WHERE 
		TIPODESCONTO IS NOT NULL
	GROUP BY COBRANCA
),
ITENS_MULTA_JUROS 
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS MULTA_JUROS 
	FROM LY_ITEM_CRED
	WHERE 
		TIPO_ENCARGO IS NOT NULL
	GROUP BY COBRANCA
),
ITENS_BOLSA
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS BOLSA
	FROM LY_ITEM_LANC 
	WHERE
		MOTIVO_DESCONTO IS NULL
		AND NUM_BOLSA IS NOT NULL
	GROUP BY COBRANCA
),
ITENS_ACORDO
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS ACORDO
	FROM LY_ITEM_LANC 
	WHERE
		ACORDO IS NOT NULL
	GROUP BY COBRANCA
),
ITENS_IGPM
AS
(
	SELECT 
		COBRANCA,
		ISNULL(SUM(VALOR),0) AS ACRESC_IGPM
	FROM LY_ITEM_LANC 
	WHERE DESCRICAO LIKE '%IGPM%'
		AND ACORDO IS NULL
		AND NUM_BOLSA IS NULL
		
	GROUP BY COBRANCA
)

SELECT 
	DB.COBRANCA,
	DB.DEBITO,
	ISNULL(MJ.MULTA_JUROS,0) AS MULTA_JUROS,
	ISNULL(ACRESC_IGPM, 0) AS ACRESC_IGPM,
	(ISNULL(DD.DESCONTO,0) + ISNULL(DC.DESCONTO,0)) AS DESCONTO,
	ISNULL(AC.ACORDO, 0) AS ACORDO,
	ISNULL(BO.BOLSA, 0) AS BOLSA,
	ISNULL(CREDITO,0) AS CREDITO
	,
	(DB.DEBITO + ISNULL(ACRESC_IGPM, 0) + ISNULL(MJ.MULTA_JUROS,0)
	+ (
		ISNULL(DD.DESCONTO,0) +
		ISNULL(DC.DESCONTO,0) +
		ISNULL(AC.ACORDO, 0) +
		ISNULL(BO.BOLSA, 0)
	) ) AS PAGAR,

	
	
	(
		ISNULL(CREDITO,0)
	) 
	AS PAGO,
	
	((DB.DEBITO + ISNULL(ACRESC_IGPM, 0)  + ISNULL(MJ.MULTA_JUROS,0)) +
	(ISNULL(DD.DESCONTO,0) +
	ISNULL(DC.DESCONTO,0) +
	ISNULL(AC.ACORDO, 0) +
	ISNULL(BO.BOLSA, 0) +
	ISNULL(CREDITO,0)) 
	) AS SALDO
FROM ITENS_DEBITOS DB
	 LEFT JOIN ITENS_DESC_DEB DD
		ON DD.COBRANCA = DB.COBRANCA
	 LEFT JOIN ITENS_CREDITOS CR
		ON CR.COBRANCA = DB.COBRANCA
	 LEFT JOIN ITENS_DESC_CRED DC
		ON DB.COBRANCA = DC.COBRANCA
	 LEFT JOIN ITENS_MULTA_JUROS MJ
		ON DB.COBRANCA = MJ.COBRANCA
	 LEFT JOIN ITENS_BOLSA BO
		ON BO.COBRANCA = DB.COBRANCA
	 LEFT JOIN ITENS_ACORDO AC
		ON AC.COBRANCA = DB.COBRANCA
	 LEFT JOIN ITENS_IGPM IG
		ON IG.COBRANCA = DB.COBRANCA
