IF EXISTS (SELECT * 
           FROM   sys.VIEWS 
           WHERE  NAME = 'VW_FCAV_ALUNOS_BOLSISTAS') 
  DROP VIEW VW_FCAV_ALUNOS_BOLSISTAS 
 
GO


CREATE VIEW VW_FCAV_ALUNOS_BOLSISTAS
AS  
  
  
SELECT  
	M.UNIDADE_RESPONSAVEL,
    M.CURSO,  
    M.TURMA,  
    M.ALUNO,  
    P.NOME_COMPL,
	M.SIT_ALUNO,  
    M.SIT_MATRICULA,  
    RE.TITULAR,  
    CASE  
        WHEN RE.CGC_TITULAR IS NULL THEN RE.CPF_TITULAR  
        ELSE RE.CGC_TITULAR  
    END CPF_CNPJ,  
    BL.TIPO_BOLSA,  
    BL.NUM_BOLSA,  
    BL.PERC_VALOR,  
    BL.VALOR,  
    BL.MOTIVO
FROM LY_PESSOA P  
INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA M  
    ON P.PESSOA = M.PESSOA  
INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA V  
    ON V.TURMA = M.TURMA  
LEFT OUTER JOIN LY_PLANO_PGTO_PERIODO PI  
    ON PI.ALUNO = M.ALUNO  
LEFT OUTER JOIN LY_RESP_FINAN RE  
    ON (RE.RESP = PI.RESP)  
LEFT OUTER JOIN LY_BOLSA BL  
    ON BL.ALUNO = M.ALUNO  

GROUP BY
	M.UNIDADE_RESPONSAVEL,
    M.CURSO,  
    M.TURMA,  
    M.ALUNO,  
    P.NOME_COMPL,
	M.SIT_ALUNO,  
    M.DT_MATRICULA,  
    M.SIT_MATRICULA,  
    RE.TITULAR,  
    RE.CGC_TITULAR, 
	RE.CPF_TITULAR , 
    BL.TIPO_BOLSA,  
    BL.NUM_BOLSA,  
    BL.PERC_VALOR,  
    BL.VALOR,  
    BL.MOTIVO