/*
	VIEW VW_FCAV_ALUNOS_TCC

	UTILIZADA PARA PLANILHA DE RELAÇÃO DE ALUNOS COM TCC

Autor: Gabriel Scalione
Data: 03/05/2018
*/



ALTER VIEW VW_FCAV_ALUNOS_TCC
AS

SELECT 
	PM.CURSO,
	PM.TURMA,
	PM.STATUS_TURMA,
	ES.ANO,
	ES.SEMESTRE AS PERIODO,
	PM.ALUNO,
	PM.NOME_COMPL,
	PM.SIT_MATRICULA,
	ES.DTINI,
	ES.DTFIM,
	ES.DISCIPLINA,
	DI.NOME AS NOME_DISCIPLINA,
	CAST(ES.TEMA AS VARCHAR(2000)) AS TEMA,
	DO.NOME_COMPL AS ORIENTADOR,
	CAST(ES.OBSERVACAO AS VARCHAR(2000)) AS OBSERVACAO
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA PM
	INNER JOIN LY_ESTAGIO ES
		ON ES.ALUNO = PM.ALUNO
	INNER JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = ES.NUM_FUNC
		OR DO.NUM_FUNC = ES.NUM_FUNC2
	INNER JOIN LY_DISCIPLINA DI
		ON DI.DISCIPLINA = ES.DISCIPLINA
GROUP BY 
	PM.ALUNO,
	PM.NOME_COMPL,
	PM.CURSO,
	PM.TURMA,
	PM.STATUS_TURMA,
	ES.ANO,
	ES.SEMESTRE ,
	PM.SIT_MATRICULA,
	ES.DISCIPLINA,
	DI.NOME,
	CAST(ES.TEMA AS VARCHAR(2000)),
	DO.NOME_COMPL,
	CAST(ES.OBSERVACAO AS VARCHAR(2000)),
	ES.DTINI,
	ES.DTFIM


union all


SELECT 
	PM.CURSO,
	PM.TURMA,
	PM.STATUS_TURMA,
	ES.ANO,
	ES.SEMESTRE AS PERIODO,
	PM.ALUNO,
	PM.NOME_COMPL,
	PM.SIT_MATRICULA,
	ES.DTINI,
	ES.DTFIM,
	ES.DISCIPLINA,
	DI.NOME AS NOME_DISCIPLINA,
	CAST(ES.TEMA AS VARCHAR(2000)) AS TEMA,
	DO.NOME_COMPL AS ORIENTADOR,
	CAST(ES.OBSERVACAO AS VARCHAR(2000)) AS OBSERVACAO
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA PM
	INNER JOIN LY_HISTESTAGIO ES
		ON ES.ALUNO = PM.ALUNO
	INNER JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = ES.NUM_FUNC
		OR DO.NUM_FUNC = ES.NUM_FUNC2
	INNER JOIN LY_DISCIPLINA DI 
		ON DI.DISCIPLINA = ES.DISCIPLINA

GROUP BY 
	PM.ALUNO,
	PM.NOME_COMPL,
	PM.CURSO,
	PM.TURMA,
	PM.STATUS_TURMA,
	ES.ANO,
	ES.SEMESTRE,
	PM.SIT_MATRICULA,
	ES.DISCIPLINA,
	DI.NOME,
	CAST(ES.TEMA AS VARCHAR(2000)),
	DO.NOME_COMPL,
	CAST(ES.OBSERVACAO AS VARCHAR(2000)),
	ES.DTINI,
	ES.DTFIM