/*
	view para trazer serviços vinculados no curriculo do curso por ano e período

Autor: Gabriel S. Scalione

*/


ALTER VIEW VW_FCAV_VALOR_SERVICOS_CURRICULOS
AS

SELECT 
	UPPER(SM.CURSO) AS CURSO,
	SM.TURNO,
	SM.CURRICULO,
	SM.ANO,
	SM.PERIODO,
	VT.TURMA,
	SP.SERVICO,
	SUM(CAST(SP.CUSTO_UNITARIO	AS decimal(10,2))) AS VALOR_CURSO

FROM
	LY_OFERTA_CURSO OC
	INNER JOIN LY_SERVICO_MATRICULA SM
		ON SM.CURSO = OC.CURSO
		AND SM.TURNO = OC.TURNO
		AND SM.CURRICULO = OC.CURRICULO
		AND SM.ANO = OC.ANO_INGRESSO
		AND SM.ANO = OC.PER_INGRESSO
	INNER JOIN LY_VALOR_SERV_PERIODO SP
		ON SP.SERVICO = SM.SERVICO
		AND SP.ANO = SM.ANO
		AND SP.PERIODO = SM.PERIODO
	INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
		ON VT.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
GROUP BY 
	SM.ANO,
	SM.PERIODO,
	SM.CURSO,
	SM.TURNO,
	SM.CURRICULO,
	VT.TURMA,
	SP.SERVICO,
	SP.CUSTO_UNITARIO

UNION ALL

SELECT 
	UPPER(CR.CURSO) AS CURSO,
	OC.TURNO,
	OC.CURRICULO,
	OC.ANO_INGRESSO AS ANO,
	OC.PER_INGRESSO AS PERIODO,
	VT.TURMA,
	SP.SERVICO,
	CAST(SP.CUSTO_UNITARIO	AS decimal(10,2)) AS VALOR_CURSO

FROM LY_OFERTA_CURSO OC
	 INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
		ON VT.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
		AND VT.CURSO = OC.CURSO
		AND VT.TURNO = OC.TURNO
		AND VT.CURRICULO = OC.CURRICULO
	 INNER JOIN LY_CURRICULO CR
		ON CR.CURRICULO = VT.CURRICULO
		AND CR.CURSO = VT.CURSO
		AND CR.TURNO = VT.TURNO
	 INNER JOIN LY_VALOR_SERV_PERIODO SP
	 	ON SP.SERVICO = CR.SERVICO
		AND SP.ANO = OC.ANO_INGRESSO
		AND SP.PERIODO = OC.PER_INGRESSO

GROUP BY 
	CR.CURSO,
	OC.TURNO,
	OC.CURRICULO,
	VT.TURMA,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,
	SP.SERVICO,
	SP.CUSTO_UNITARIO

