
/*  
 VIEW VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR  
   
   select top 10 * from VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR order by oferta_de_curso desc
 UTILIZADA PARA POPULAR A PLANILHA DE CRONOGRAMA COORDENADOR QUE AUXILIA A SECRETARIA ACADEMICA  
 NOS RELATÓRIOS DO DIA A DIA.  
  
Atualizaçao:  
 02/06/2017 - View otimizada.  
  
Autor: Gabriel  
Data: 2014-11-07  
*/

ALTER VIEW VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR
AS

SELECT

    ISNULL(DO.NOME_COMPL, 'NAO_CADASTRADO') AS NOME_COORD,
    ISNULL(CO.TIPO_COORD, 'NAO_CADASTRADO') AS TIPO_COORD,

    CS.FACULDADE AS UNID_RESP,
    CS.CURSO AS CURSO,
    CS.NOME AS NOME_CURSO,

    OC.OFERTA_DE_CURSO,
    ISNULL(OC.CONCURSO, 'VENDA DIRETA') AS CONCURSO,
    OC.ANO_INGRESSO,
    OC.PER_INGRESSO,
    OC.DTINI AS DTINI_OFERTA,
    OC.DTFIM AS DTFIM_OFERTA,
    CASE
        WHEN oc.DTFIM >= GETDATE() THEN 'Abertas'
        WHEN oc.DTFIM <= GETDATE() THEN 'Encerradas'
    END AS INSCRICOES,

    VT.TURMA,
    min(VT.DT_INICIO) AS DT_INICIO,
    MAX(VT.DT_FIM) AS DT_FIM,
    (SELECT TOP 1
        CASE
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND
                VT.DT_INICIO > GETDATE() THEN 'Em Inscrição'
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND
                (GETDATE() BETWEEN VT.DT_INICIO AND VT.DT_FIM) THEN 'Em Andamento'
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND
                VT.DT_FIM <= GETDATE() THEN 'Concluido'
            WHEN CLASSIFICACAO LIKE 'Cancel%' THEN 'Cancelada'
        END
    FROM LY_TURMA TU
    WHERE TU.TURMA = VT.TURMA
    AND TU.SERIE = 1
    GROUP BY CLASSIFICACAO)
    AS SITUACAO_TURMA,
    (SELECT TOP 1
        ISNULL(NUM_ALUNOS, CS.VAGAS)
    FROM LY_TURMA TU
    WHERE TU.CURSO = CS.CURSO
    AND TU.SERIE = 1
    GROUP BY NUM_ALUNOS,
             TURMA)
    AS VAGAS_CURSO,
    VT.CENTRO_DE_CUSTO,

	(SELECT 
		CAST(CUSTO_UNITARIO AS decimal(10,2))
	FROM 
		VW_FCAV_CURSOS_CADASTRADOS_LYCEUM CL 
	WHERE CL.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO 
	GROUP BY CUSTO_UNITARIO
	) AS INVESTIMENTO_A_VISTA,

    CASE
        WHEN OC.CONCURSO IS NULL THEN (SELECT
                COUNT(INSCRITO)
            FROM VW_FCAV_CANDIDATOS_E_ALUNOS
            WHERE TURMA = VT.TURMA)
        ELSE (SELECT
                COUNT(CANDIDATO)
            FROM LY_CANDIDATO CA
            WHERE CA.CONCURSO = OC.CONCURSO
            GROUP BY CA.CONCURSO)
    END AS TOTAL_INSCRITOS,

    (SELECT
        COUNT(CA.CANDIDATO)
    FROM LY_CANDIDATO CA
    WHERE CA.CONCURSO = OC.CONCURSO
    AND SIT_CANDIDATO_VEST = 'Cancelado')
    AS CAND_CANCELADOS,

    (SELECT
        COUNT(CA.CANDIDATO)
    FROM LY_CANDIDATO CA
    INNER JOIN FCAV_CANDIDATOS FC
        ON FC.CANDIDATO = CA.CANDIDATO
        AND FC.CONCURSO = CA.CONCURSO
    INNER JOIN LY_CONVOCADOS_VEST CV
        ON CV.CANDIDATO = CA.CANDIDATO
        AND CV.CONCURSO = CA.CONCURSO
    WHERE CA.CONCURSO = OC.CONCURSO
    AND CV.MATRICULADO = 'N'
    AND SIT_CANDIDATO_VEST != 'Cancelado'
    AND FC.CONVOCADO = '1')
    AS CAND_SELECIONADOS,
    
    (SELECT
        COUNT(CA.CANDIDATO)
    FROM LY_CANDIDATO CA
    INNER JOIN FCAV_CANDIDATOS FC
        ON FC.CANDIDATO = CA.CANDIDATO
        AND FC.CONCURSO = CA.CONCURSO
    WHERE CA.CONCURSO = OC.CONCURSO
    AND SIT_CANDIDATO_VEST != 'Cancelado'
    AND FC.CONVOCADO = '2')
    AS CAND_RECUSADOS,
    
    (SELECT
        COUNT(CA.CANDIDATO)
    FROM LY_CANDIDATO CA
    INNER JOIN LY_CONVOCADOS_VEST CV
        ON CV.CANDIDATO = CA.CANDIDATO
        AND CV.CONCURSO = CA.CONCURSO
    WHERE CA.CONCURSO = OC.CONCURSO
    AND CV.MATRICULADO = 'N'
    AND SIT_CANDIDATO_VEST != 'Cancelado')
    AS CAND_CONVOCADOS,

    (SELECT
        COUNT(CA.CANDIDATO)
    FROM LY_CANDIDATO CA
    INNER JOIN FCAV_CANDIDATOS FC
        ON FC.CANDIDATO = CA.CANDIDATO
        AND FC.CONCURSO = CA.CONCURSO
    WHERE CA.CONCURSO = OC.CONCURSO
    AND SIT_CANDIDATO_VEST != 'Cancelado'
    AND FC.CONVOCADO IS NULL)
    AS CAND_NAO_TRATADOS,


    (SELECT
        COUNT(ALUNO)
    FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
    WHERE TURMA = VT.TURMA)
    AS TOTAL_ALUNOS,

    CASE
        WHEN VT.UNIDADE_RESPONSAVEL IN ('PALES', 'ATUAL') THEN (SELECT
                COUNT(ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
            WHERE SIT_MATRICULA = 'Pre-Matriculado'
            AND TURMA = VT.TURMA)
        ELSE (SELECT
                COUNT(ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
            WHERE SIT_MATRICULA = 'Pre-Matriculado'
            AND VT.TP_INGRESSO  = 'PS'
            AND CANDIDATO IS NOT NULL
            AND TURMA = VT.TURMA)
    END AS PRE_MATRICULADOS,

    CASE
        WHEN VT.UNIDADE_RESPONSAVEL IN ('PALES', 'ATUAL') THEN (SELECT
                COUNT(ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
            WHERE SIT_MATRICULA = 'Matriculado'
            AND TURMA = VT.TURMA)
        ELSE (SELECT
                COUNT(ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
            WHERE SIT_MATRICULA = 'Matriculado'
            --AND VT.TP_INGRESSO  = 'PS'
            AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')
            AND CANDIDATO IS NOT NULL
            AND TURMA = VT.TURMA)
    END AS MATRICULADOS_INSCRITOS,

    CASE
        WHEN VT.UNIDADE_RESPONSAVEL IN ('PALES', 'ATUAL') THEN (SELECT
                COUNT(ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
            WHERE SIT_ALUNO = 'Cancelado'
            AND TURMA = VT.TURMA)
        ELSE (SELECT
                COUNT(PM.ALUNO)
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2 PM
            INNER JOIN LY_CANDIDATO CA
                ON CA.CANDIDATO = PM.CANDIDATO
                AND CA.CONCURSO = PM.CONCURSO
            WHERE SIT_ALUNO = 'Cancelado'
            AND SIT_CANDIDATO_VEST = 'Cancelado'
            AND VT.TP_INGRESSO  = 'PS'
            AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')
            AND TURMA = VT.TURMA)
    END AS ALU_CANCELADOS_INSCRITOS,

    (SELECT
        COUNT(PM.ALUNO)
    FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2 PM
    INNER JOIN LY_CANDIDATO CA
        ON CA.CANDIDATO = PM.CANDIDATO
        AND CA.CONCURSO = PM.CONCURSO
    WHERE SIT_ALUNO = 'Cancelado'
    AND SIT_CANDIDATO_VEST != 'Cancelado'
    AND VT.TP_INGRESSO  = 'PS'
    AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')
        AND TURMA = VT.TURMA)
    AS INSCRICOES_NAO_CANCELADAS,


    (SELECT
        COUNT(ALUNO)
    FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
    WHERE SIT_MATRICULA = 'Matriculado'
    AND VT.TP_INGRESSO  = 'PS'
    AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')
    AND TURMA = VT.TURMA)
    AS MATRICULADOS_OUTROS,

    (SELECT
        COUNT(ALUNO)
    FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA2
    WHERE SIT_ALUNO = 'Cancelado'
    AND VT.TP_INGRESSO  = 'PS'
    AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')
    AND TURMA = VT.TURMA)
    AS ALU_CANCELADOS_OUTROS

FROM VW_FCAV_INI_FIM_CURSO_TURMA VT

INNER JOIN LY_CURSO CS
    ON CS.CURSO = VT.COD_CURSO

INNER JOIN LY_COORDENACAO CO
    ON CO.CURSO = CS.CURSO

INNER JOIN LY_DOCENTE DO
    ON DO.NUM_FUNC = CO.NUM_FUNC

INNER JOIN LY_OFERTA_CURSO OC
    ON OC.OFERTA_DE_CURSO = VT.OFERTA_DE_CURSO

WHERE CO.TIPO_COORD = 'COORD'

GROUP BY OC.OFERTA_DE_CURSO,
         OC.ANO_INGRESSO,
         OC.PER_INGRESSO,
         OC.DTINI,
         OC.DTFIM,
         OC.CONCURSO,

         CS.FACULDADE,
         CS.CURSO,
         CS.NOME,
         CS.VAGAS,
		 VT.DT_INICIO, 
		 VT.DT_FIM,
         VT.TURMA,
         VT.CENTRO_DE_CUSTO,
         VT.UNIDADE_RESPONSAVEL,
		 VT.TP_INGRESSO,

         DO.NOME_COMPL,
         CO.TIPO_COORD