/*
	VIEW VW_FCAV_AVAL_RESULTADO

	Finalidade: Retorna o resultado das avaliações docentes aplicadas

Autor: Gabriel S. Scalione
Data: 16/05/2019

SELECT * FROM VW_FCAV_AVAL_COMENTARIOS where RESPOSTA != '' AND COD_AVAL = 'CCGBT52LSSMB01' ORDER BY CURSO, TURMA, COD_AVAL

*/



alter VIEW VW_FCAV_AVAL_COMENTARIOS
AS

With RESULTADO_AVALIACAO
as (
SELECT 
	*
FROM 
	FCAV_AVALIACAO_DOCENTE

	)

	SELECT
		CURSO,
		NOME_CURSO,
		TURMA,
		CASE WHEN ASPECTO = 'INFRAESTRUTURA' THEN  'DISCIPLINA'
		ELSE ASPECTO END ASPECTO,
		COD_AVAL,
		PERGUNTAS,
		RESPOSTA

	FROM 
		RESULTADO_AVALIACAO ra
	WHERE TIPO_QUESTAO = 'SUBJETIVA'
	GROUP BY CURSO,
		NOME_CURSO,
		TURMA,
		ASPECTO,
		COD_AVAL,
		PERGUNTAS,
		RESPOSTA
