CREATE VIEW VW_FCAV_INFO_CURSO_PORTAL    
AS    
    
-- **** INICIO DO ORIGINAL ****    
--SELECT DISTINCT    
-- VW.*, T.FL_FIELD_15 AS DATA_ULT_IMPORT,CAST(T2.SEQUENCIAL AS NUMERIC) AS SEQUENCIAL    
--FROM    
-- VW_FCAV_INFO_CURSO_PORTAL2 VW INNER JOIN LY_TURMA T ON (VW.TURMA = T.TURMA AND VW.CURSO = T.CURSO AND VW.CURRICULO = T.CURRICULO AND VW.TURNO = T.TURNO AND VW.GRADE_CURRICULAR = T.DISCIPLINA)    
-- INNER JOIN FCAV_INFO_CURSO_PORTAL T2 ON (VW.TURMA = T2.TURMA AND VW.CURSO = T2.CURSO AND VW.CURRICULO = T2.CURRICULO AND VW.TURNO = T2.TURNO AND VW.GRADE_CURRICULAR = T2.DISCIPLINA AND ISNULL(VW.NUM_FUNC,'0000') = ISNULL(T2.NUM_FUNC,'0000') AND VW.PERIODO = T2.PERIODO)    
--WHERE VW.ANO >= '2016'    
----ORDER BY SEQUENCIAL    
    
-- FINAL DO ORIGINAL ****    
    
    
SELECT   
FACULDADE,  
COORDENADOR,  
VICE_COORD,  
CURSO,  
CURRICULO,  
OFERTA,  
CURSO_OFERTADO,  
DESCRICAO_COMPL,  
DTINI_OFERTA,  
DTFIM_OFERTA,  
CONCURSO,  
TURMA_PREF,  
TURMA,  
ANO,  
PERIODO,  
DISCIPLINA,  
DT_INICIO,  
DT_FIM,  
DOCENTE,  
ATUACAO_PROFIS,  
SIT_TURMA,  
CARGA_HORARIA,  
VALOR_CURSO,  
APRESENTACAO_CURSO,  
DIFERENCIAL,  
PERFIL_ALUNO,  
CERTIFICACAO,  
METODOLOGIA,  
SISTEMA_AVALIACAO,  
PROCESSO_SELETIVO,  
OBJETIVOS,  
CORPO_DOCENTE,  
INVESTIMENTO,  
PUBLICO_ALVO,  
PROGRAMA,  
DIA_HORARIO_AULAS,  
RELACAO_DOCUMENTOS,  
CAST (LINK AS varchar(255)) AS LINK,  
DT_IMPORT,  
SEQUENCIAL  
FROM FCAV_INFO_CURSO_PORTAL2