/*
	VIEW VW_FCAV_LINK_OFERTA_CURSO

	Finalidade: Utilizada para trazer o resumo dos cursos com inscrição aberta no ApoioWeb


Autor: Gabriel Scalione
Data: 2016-07-21

*/

    
ALTER VIEW VW_FCAV_LINK_OFERTA_CURSO AS    
    
SELECT  
 CASE WHEN CURSO.FACULDADE = 'ATUAL' THEN 'Atualização'    
  WHEN CURSO.FACULDADE = 'CAPAC' THEN 'Capacitação'    
  WHEN CURSO.FACULDADE = 'ESPEC' THEN 'Especialização'    
  WHEN CURSO.FACULDADE = 'PALES' THEN 'Palestra'    
  WHEN CURSO.FACULDADE = 'DIFUS' THEN 'Difusão'  
   END AS AREA,  
  CASE WHEN  OFERTA.CONCURSO IS NULL THEN V.TURMA  
    ELSE OFERTA.CONCURSO END AS CONCURSO,   
 CURSO.NOME AS NOME_CURSO,
 OFERTA.OFERTA_DE_CURSO,   
 CASE WHEN  OFERTA.CONCURSO IS NULL THEN 'VD'  
   ELSE 'PS'END AS TIPO_INSCRICAO,  
 isnull(OFERTA.DTINI,'2014-01-01 00:00:00.000') AS DATA_INICIAL,    
 isnull(OFERTA.DTFIM,'2014-12-01 00:00:00.000') AS DATA_FIM,    
 isnull(V.DT_INICIO,'1900-01-01 00:00:00.000')  AS INICIO_DO_CURSO,
 CASE WHEN DATEDIFF(day, GETDATE(), V.DT_INICIO) < 0 THEN 0
 ELSE DATEDIFF(day, GETDATE(), V.DT_INICIO) 
 END AS DIAS_RESTANTES,
 'http://sga.vanzolini.org.br:8080/web/converte_link_portal.asp' +  
 '?OFERTA_DE_CURSO=' + CONVERT(VARCHAR, OFERTA.OFERTA_DE_CURSO) +  
 '&tagturma=' + REPLACE(ISNULL(V.TURMA, OFERTA.CONCURSO), ' ', '%20') AS LINK,
 V.COD_CURSO AS CURSO

FROM    
 LY_OFERTA_CURSO AS OFERTA    
 INNER JOIN LY_CURSO AS CURSO ON (OFERTA.CURSO = CURSO.CURSO)    
 INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA AS V ON  V.OFERTA_DE_CURSO = OFERTA.OFERTA_DE_CURSO  
 --INNER JOIN LY_CONCURSO AS CONCURSO ON (OFERTA.CONCURSO = CONCURSO.CONCURSO)    
    
WHERE    
 oferta.ANO_INGRESSO >= 2020
