/*  
 VIEW VW_FCAV_DECLARACAO_MATR_CEAI   
  
Finalidade: Trazer a relação de alunos do CEAI para o relatório de Atestado e Declaração de Matrícula emitido pelo Lyceum.
  
Alterações:  Foi retirado a relaçao dos Alunos do CEAI, pois o período é diferente. Gabriel 30/08/2019
  
Autor: Gabriel S.S. 
Data: 2019-08-30 
  
  
SELECT * FROM VW_FCAV_DECLARACAO_MATR_CEAI WHERE aluno in ('E201730002') order by aluno, ano, semestre  

*/  
   
  
ALTER VIEW VW_FCAV_DECLARACAO_MATR_CEAI AS  
  
WITH PERIODO_CURSO AS  
(  
 SELECT   
  TU.TURMA,
  MIN(TU.DT_INICIO) AS INICIO,  
  MAX(TU.DT_FIM) AS FIM  
 FROM   
  LY_TURMA TU  
 WHERE  
  TU.UNIDADE_RESPONSAVEL = 'ESPEC'
  AND TU.CURSO = 'CEAI'
 GROUP BY 
  TU.TURMA
)  

 
SELECT distinct--top 1  
 DENSE_RANK() OVER (PARTITION BY VW.ALUNO ORDER BY VW.ANO, VW.SEMESTRE) AS PERIODO1,   
 VW.ALUNO, 
 AL.NOME_COMPL AS ALU_NOME,  
 VW.ANO, 
 VW.SEMESTRE,  
 PES.RG_NUM, CPF, CURSO.NOME,  
 TUR.CURSO,  
 CASE WHEN CURSO.FACULDADE = 'ATUAL' THEN 'Atualização'  
  WHEN CURSO.FACULDADE = 'CAPAC' THEN 'Capacitação'  
  WHEN CURSO.FACULDADE = 'ESPEC' THEN 'Especialização'  
 END AS UNID_RESP,  
 TUR.TURNO,  
 TUR.CURRICULO,  
 TUR.TURMA,  
 CAST(CURR.AULAS_PREVISTAS AS numeric) AS CARGA_HOR,  
 dbo.FN_FCAV_NUM_EXTENSO(CURR.AULAS_PREVISTAS) AS CARGA_HOR_EXT,  
 LOWER(CONVERT(VARCHAR,dbo.FN_FCAV_MES_EXT(MONTH(TUR.DT_INICIO))) +     
  ' à ' + CONVERT(VARCHAR,DBO.FN_FCAV_MES_EXT(MONTH(TUR.DT_FIM))) +     
  ' de ' + CONVERT(VARCHAR,YEAR(TUR.DT_FIM))) AS PERIODO,  
   
  LOWER(CONVERT(VARCHAR,dbo.FN_FCAV_MES_EXT(MONTH(PER.INICIO))) +   
 ' de ' + CONVERT(VARCHAR,YEAR(PER.INICIO))  +  
 ' à ' + CONVERT(VARCHAR,DBO.FN_FCAV_MES_EXT(MONTH(PER.FIM))) +     
 ' de ' + CONVERT(VARCHAR,YEAR(PER.FIM)))   
  AS PERIODO_CURSO,  
  
   (SELECT DESCR FROM HADES.dbo.HD_TABELAITEM WHERE TABELA = 'Gerentes' and ITEM = 'Educação') as GERENTE  
FROM VW_FCAV_MATR_PRE_E_HIST_SERIE VW  
INNER JOIN LY_ALUNO AL ON VW.ALUNO = AL.ALUNO AND AL.CURSO = 'CEAI' 
INNER JOIN LY_PESSOA PES ON AL.PESSOA = PES.PESSOA  
INNER JOIN LY_CURSO CURSO ON AL.CURSO = CURSO.CURSO AND CURSO.CURSO IN ('CEAI')  
INNER JOIN LY_TURMA TUR ON VW.TURMA = TUR.TURMA AND VW.ANO = TUR.ANO AND VW.SEMESTRE = TUR.SEMESTRE  
INNER JOIN LY_CURRICULO CURR ON CURR.CURSO = TUR.CURSO AND CURR.TURNO = TUR.TURNO AND CURR.CURRICULO = TUR.CURRICULO  
INNER JOIN PERIODO_CURSO PER ON TUR.TURMA = PER.TURMA 
  
GROUP BY   
 VW.ALUNO, AL.NOME_COMPL,  
 VW.ANO, VW.SEMESTRE, VW.TURMA,  
 PES.RG_NUM, CPF, CURSO.NOME,  
 TUR.CURSO,  
 TUR.TURNO,  
 tur.UNIDADE_RESPONSAVEL,  
 CURSO.FACULDADE,  
 TUR.CURRICULO,  
 TUR.TURMA,  
 TUR.DT_INICIO,  
 TUR.DT_FIM,  
 CURR.AULAS_PREVISTAS,  
 PER.INICIO,  
 PER.FIM  
--ORDER BY PERIODO1 DESC,  
--  TUR.DT_FIM DESC  