/*
	VIEW VW_FCAV_CERTIFICADO_EGRESSOS_CEAI

Finalidade: View usada exclusivamente para trazer os alunos do CEAI-Egressos 
			para emissão do Certificado. Arquivo: FCAV_Certificado_Egressos_CEAI.rpt

Autor: Gabriel S Scalione
Data: 18/07/2018
*/


CREATE VIEW VW_FCAV_CERTIFICADO_EGRESSOS_CEAI
AS

SELECT 
	MA.ALUNO,
	MA.NOME_COMPL,
	AL.SIT_ALUNO,
	MA.SITUACAO_HIST AS SIT_MATRICULA,
	CASE WHEN CT.TURMA LIKE '%egressos%' THEN
		SUBSTRING(MA.NOME_DISCIPLINA,1,CHARINDEX('-',MA.NOME_DISCIPLINA)-1)
	ELSE CT.NOME_CURSO
	END AS NOME_CURSO,
	MA.CURSO,
	CO.NOME_COMPL AS NOME_COORD,
	MA.TURMA,
	CT.DT_INICIO,
	CT.DT_FIM,
	CT.CARGA_HORARIA
FROM 
	VW_FCAV_MEDIA_FINAL_ALUNOS MA 
	INNER JOIN VW_FCAV_COORDENADOR_TURMA CO 
		ON CO.TURMA = MA.TURMA
	INNER JOIN LY_ALUNO AL
		ON AL.ALUNO = MA.ALUNO
	INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT
		ON CT.TURMA = MA.TURMA
WHERE CT.TURMA LIKE '%EGRESSOS%'
GROUP BY
	MA.ALUNO,
	MA.NOME_COMPL,
	AL.SIT_ALUNO,
	MA.SITUACAO_HIST,
	MA.NOME_DISCIPLINA,
	CT.NOME_CURSO,
	MA.CURSO,
	CO.NOME_COMPL,
	MA.TURMA,
	CT.TURMA,
	CT.DT_INICIO,
	CT.DT_FIM,
	CT.CARGA_HORARIA