/*  
 VIEW VW_FCAV_PGTOS_CARTAO_SEM_BOLETO  
   
 Finalidade: Relaciona todos os alunos que fizeram o pagamento por cartão que não possui boleto gerado.  
  
  
  
*/  
  
ALTER VIEW VW_FCAV_PGTOS_CARTAO_SEM_BOLETO  
AS  
  
-----------------------------------------------------------------------  
--CONSULTA  
  
SELECT  distinct
	AL.CURSO,  
	AL.TURNO,  
	AL.CURRICULO,  
	AL.OFERTA_DE_CURSO AS OFERTA,  
	AL.CONCURSO,  
	PE.PESSOA,  
	AL.ALUNO,  
	PE.NOME_COMPL,  
	PE.CPF,  
	PE.E_MAIL,     
	AL.SIT_ALUNO,  
	CASE  
	WHEN al.CONCURSO IS NULL THEN 'Venda Direta'  
	ELSE 'Processo Seletivo'  
	END AS TIPO_INGRESSO,  
	SIT_MATRICULA,  
	al.TURMA,  
	PP.PLANOPAG AS PLANO_PGTO_PERIODO,  
	IC.DESCRICAO AS FORMA_PAGAMENTO,  
	LD.LANC_DEB,  
	LD.GRUPO,  
	CASE  
		WHEN RE.CGC_TITULAR IS NULL THEN RE.CPF_TITULAR  
		WHEN RE.CPF_TITULAR IS NULL THEN RE.CGC_TITULAR  
		ELSE NULL  
	END AS DOC_TITULAR,  
	RE.TITULAR,  
	PP.PERCENT_DIVIDA_ALUNO,  
	BL.TIPO_BOLSA,  
	BL.NUM_BOLSA,  
	BL.PERC_VALOR,  
	IL.ITEMCOBRANCA,  
	IL.COBRANCA,  
	CB.BOLETO,  
	CB.DATA_DE_VENCIMENTO,  
	BL.VALOR as VALOR_BOLSA,  
	BL.MOTIVO,  
	(SELECT DISTINCT  
		SUM(VALOR)  
	FROM LY_ITEM_LANC IIL  
	WHERE IIL.ALUNO = AL.ALUNO  
	AND (IIL.DESCRICAO != 'VALOR ACORDADO'  
	AND IIL.ACORDO IS NULL))  
	AS VALOR_PAGAR,  
	NF.NUMERO_RPS,  
	NF.DATA_EMISSAO_RPS,  
	NF.DATA_ENVIO_RPS,  
	NF.LINK_RPS,  
	NF.VALOR_SERVICO_RPS,  
	NF.NUMERO_NFE,  
	NF.DATA_EMISSAO_NFE,  
	VO.VOUCHER,  
	VO.DESC_PERC_VALOR,  
	VO.DESCONTO  
  
FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA AL  
  
LEFT JOIN LY_PLANO_PGTO_PERIODO PP  
    ON PP.ALUNO = AL.ALUNO  
  
LEFT JOIN LY_RESP_FINAN RE  
    ON RE.RESP = PP.RESP  
  
LEFT JOIN LY_BOLSA BL  
    ON BL.ALUNO = AL.ALUNO  
      
FULL JOIN  LY_PESSOA PE  
    ON PE.PESSOA = AL.PESSOA  
  
LEFT JOIN LY_PROSPECTO_CAPTACAO PC  
    ON PC.PESSOA = PE.PESSOA  
  
INNER JOIN VW_COBRANCA_BOLETO CB  
 ON CB.ALUNO = AL.ALUNO  
  
LEFT JOIN LY_CARTAO_LOG CL  
 ON CL.ALUNO = AL.ALUNO  
 AND CL.COBRANCA = CB.COBRANCA  
  
 
LEFT JOIN LY_ITEM_LANC IL   
 ON IL.ALUNO = AL.ALUNO  
 AND IL.COBRANCA = CB.COBRANCA  
  
LEFT JOIN LY_ITEM_CRED IC  
 ON IC.COBRANCA = IL.COBRANCA  
  
LEFT JOIN LY_COBRANCA_NOTA_FISCAL NF  
 ON NF.COBRANCA = IL.COBRANCA  
  
LEFT JOIN VW_FCAV_ALUNOS_COM_VOUCHERS VO  
 ON VO.ALUNO = AL.ALUNO  
 AND VO.OFERTA_DE_CURSO = AL.OFERTA_DE_CURSO  
  
INNER JOIN LY_LANC_DEBITO LD  
 ON LD.ALUNO = IL.ALUNO  
   
WHERE  
-- PC.EMPRESA IS NOT NULL  
AL.SIT_ALUNO = 'Ativo' AND  
CB.BOLETO IS NULL AND  
IC.DESCRICAO LIKE '%Cartão de Crédito%' AND  
AL.DT_MATRICULA >= '2018-11-01 00:00:00.000' AND  
IL.ITEMCOBRANCA = 1  
AND NOT EXISTS (SELECT 1 FROM LY_ITEM_LANC IL2 WHERE IL.COBRANCA = IL2.COBRANCA AND IL2.ITEM_ESTORNADO IS NOT NULL)  
  