/*
	VIEW VW_FCAV_AVAL_INDICE_GERAL

	Finalidade: Trazer o indice geral das avaliações das disciplinas e docentes.

Autor: Gabriel S. Scalione
Data: 23/08/2018

*/
/*
	SELECT * FROM VW_FCAV_AVAL_DOCENTE_INDICES WHERE TURMA = 'CCGQ T 01'
	SELECT * FROM VW_FCAV_AVAL_DISCIPLINA_INDICES WHERE TURMA = 'CCGQ T 01'
	SELECT * FROM VW_FCAV_AVAL_INDICE_GERAL WHERE nome_docente is null
	SELECT turma, titulo, tipo_avaliado, avaliado, Nome_avaliado FROM VW_FCAV_RESPOSTAS_AVAL_DOCENTE_DISCIPLINA WHERE turma in (SELECT turma, disciplina FROM VW_FCAV_AVAL_INDICE_GERAL WHERE nome_docente is null)
	group by turma, titulo, tipo_avaliado, avaliado, Nome_avaliado


	select * from vw_fcav_matricula_e_pre_matricula where turma = 'CCGQ T 01'
*/

ALTER VIEW VW_FCAV_AVAL_INDICE_GERAL 
AS

WITH AVA_DISCIPLINA AS (
SELECT
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	AVG(DI.INDICE_APROVACAO) AS INDICE_APROVACAO_DISCIPLINA,
	AVG(DI.INDICE_REJEICAO) AS INDICE_REJEICAO_DISCIPLINA
FROM 
	VW_FCAV_AVAL_DISCIPLINA_INDICES DI
	
GROUP BY
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA
),
AVA_DOCENTE AS (
SELECT
	DO.CURSO,
	DO.TURMA,
	DO.DISCIPLINA,
	DO.NOME_DOCENTE,
	AVG(DO.INDICE_APROVACAO) AS INDICE_APROVACAO_DOCENTE,
	AVG(DO.INDICE_REJEICAO) AS INDICE_REJEICAO_DOCENTE
FROM 
	VW_FCAV_AVAL_DOCENTE_INDICES DO

GROUP BY
	DO.CURSO,
	DO.TURMA,
	DO.DISCIPLINA,
	DO.NOME_DOCENTE
),
AVA_INFRA AS
(
SELECT
	ID.CURSO,
	ID.TURMA,
	ID.AVALIADO AS DISCIPLINA,
	ID.NOME_AVALIADO AS NOME_DISCIPLINA,
	AVG(ISNULL(ID.INDICE_APROVACAO, 0)) AS INDICE_APROVACAO_INFRA,
	AVG(ISNULL(ID.INDICE_REJEICAO, 0)) AS INDICE_REJEICAO_INFRA
FROM 
	VW_FCAV_AVAL_INFRA_INDICES ID

GROUP BY
	ID.CURSO,
	ID.TURMA,
	ID.AVALIADO,
	ID.NOME_AVALIADO
)

SELECT
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	INDICE_APROVACAO_DOCENTE,
	INDICE_REJEICAO_DOCENTE,
	INDICE_APROVACAO_DISCIPLINA,
	INDICE_REJEICAO_DISCIPLINA,
	INDICE_APROVACAO_INFRA,
	INDICE_REJEICAO_INFRA
FROM 
	AVA_DISCIPLINA DI
	LEFT JOIN AVA_DOCENTE DO
		ON DI.TURMA = DO.TURMA
		AND DI.DISCIPLINA = DO.DISCIPLINA
	LEFT JOIN AVA_INFRA ID
		ON ID.TURMA = DI.TURMA
		AND ID.DISCIPLINA = DI.DISCIPLINA
GROUP BY
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	INDICE_APROVACAO_DISCIPLINA,
	INDICE_REJEICAO_DISCIPLINA,
	INDICE_APROVACAO_DOCENTE,
	INDICE_REJEICAO_DOCENTE,
	INDICE_APROVACAO_INFRA,
	INDICE_REJEICAO_INFRA