USE [LYCEUM_MEDIA]
GO

/****** Object:  Table [dbo].[coordenadores]    Script Date: 06/08/2020 16:05:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[coordenadores](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUM_FUNC] [int] NULL,
	[NOME_COORD] [varchar](50) NULL,
	[IMAGEM_ASS] [varbinary](max) NULL,
	[TEM_ASS] [varchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


