USE [LYCEUM_MEDIA]
GO

/****** Object:  Table [dbo].[cursos]    Script Date: 06/08/2020 16:08:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cursos](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CURSO] [nchar](30) NULL,
	[TIPO_CERTIFICADO] [int] NULL,
	[ASSINATURA_ALTERNATIVA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO


