USE [LYCEUM_MEDIA]
GO

/****** Object:  Table [dbo].[parametros]    Script Date: 06/08/2020 16:09:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[parametros](
	[ID] [int] NOT NULL,
	[TABELA] [varchar](2) NULL,
	[CHAVE] [varchar](12) NULL,
	[DESCRI] [varchar](55) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO
