USE [LYCEUM_MEDIA]
GO

/****** Object:  Table [dbo].[turmas]    Script Date: 06/08/2020 16:10:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[turmas](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CURSO] [nchar](30) NULL,
	[TURMA] [nchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO
