
SELECT 
	ZZCRO_HISTTRANS.ID NUMERO, ZZCRO_HISTTRANS.TRANSACAO, CONVERT(CHAR,ZZCRO_HIST.STAMP,103) AS DATA_ALTERACAO,
	CONVERT(CHAR,ZZCRO_HISTTRANS.STAMP,108) AS HORA_ALTERACAO,
	ZZCRO_HIST.STATUS as OPERACAO, ZZCRO_HISTTRANS.USUARIO, ZZCRO_HISTTRANS.ESTACAO MACHINE,
	USUARIO.SETOR, ZZCRO_HIST.TABELA ESTRUTURA, ZZCRO_HISTCAMPO.CAMPO, ZZCRO_HISTCAMPO.valorant VALOR1,
	ZZCRO_HISTCAMPO.valorpos ALTERADO
FROM 
	ZZCRO_HISTTRANS AS ZZCRO_HISTTRANS WITH (NOLOCK)
	LEFT JOIN ZZCRO_HIST AS ZZCRO_HIST WITH (NOLOCK) ON ZZCRO_HISTTRANS.ID = ZZCRO_HIST.TRANSID
	LEFT JOIN ZZCRO_HISTCAMPO AS ZZCRO_HISTCAMPO WITH (NOLOCK) ON ZZCRO_HIST.ID = ZZCRO_HISTCAMPO.HISTID
	LEFT JOIN USUARIO WITH (NOLOCK) ON ZZCRO_HISTTRANS.USUARIO = USUARIO.USUARIO
WHERE
    ZZCRO_HIST.TABELA IN ('ly_pEssoa') -- TABELA A SER CONSULTADA
--AND ZZCRO_HISTTRANS.STAMP BETWEEN '2018-06-01 00:00:00.000' AND '2018-06-05 23:59:59.000' -- PERIODO ONDE HOUVE A ALTERAÇÃO
--AND ZZCRO_HISTCAMPO.CAMPO = 'DT_INICIO' -- CAMPO A SER IDENTIFICADO
--AND ZZCRO_HISTTRANS.ID in (4282278, 4281774)
AND (ZZCRO_HISTCAMPO.ValorPos LIKE ('129485') OR ZZCRO_HISTCAMPO.ValorAnt LIKE ('129485')) -- VALOR DO CAMPO
--AND (ZZCRO_HISTCAMPO.ValorPos LIKE ('CELOG-SMQCS') OR ZZCRO_HISTCAMPO.ValorAnt LIKE ('CELOG-SMQCS')) -- VALOR DO CAMPO
--AND ZZCRO_HIST.STATUS = 'ALTERADO'
--AND ZZCRO_HISTTRANS.ESTACAO = 'AN1001'
--AND ZZCRO_HISTTRANS.ID IN (40120918,40120918)  --  APÓS A CONSULTA INSERIR VALORES DO CAMPO ID_NUMERO


ORDER BY --ZZCRO_HIST.ID,
ZZCRO_HISTTRANS.ID desc


-- ========================================================================================================================

/*
SELECT ZZCRO_HISTTRANS.ID NUMERO, ZZCRO_HISTTRANS.TRANSACAO, CONVERT(CHAR,ZZCRO_HISTTRANS.STAMP,103) AS DATA_ALTERACAO,
CONVERT(CHAR,ZZCRO_HISTTRANS.STAMP,108) AS HORA_ALTERACAO,
ZZCRO_HIST.STATUS as OPERACAO, ZZCRO_HISTTRANS.USUARIO, ZZCRO_HISTTRANS.ESTACAO MACHINE,
USUARIO.SETOR, ZZCRO_HIST.TABELA ESTRUTURA, ZZCRO_HISTCAMPO.CAMPO, ZZCRO_HISTCAMPO.valorant VALOR1,
ZZCRO_HISTCAMPO.valorpos VALOR2
FROM ZZCRO_HISTTRANS AS ZZCRO_HISTTRANS WITH (NOLOCK)
	INNER JOIN ZZCRO_HIST AS ZZCRO_HIST WITH (NOLOCK) ON ZZCRO_HISTTRANS.ID = ZZCRO_HIST.TRANSID
	INNER JOIN ZZCRO_HISTCAMPO AS ZZCRO_HISTCAMPO WITH (NOLOCK) ON ZZCRO_HIST.ID = ZZCRO_HISTCAMPO.HISTID
		LEFT JOIN  USUARIO ON ZZCRO_HISTTRANS.USUARIO = USUARIO.USUARIO
WHERE ZZCRO_HISTTRANS.ID IN (19374095,19470949) -- APÓS A CONSULTA ANTERIOR INSERIR OS VALORES DO CAMPO ID_NUMERO
ORDER BY ZZCRO_HISTTRANS.ID

*/