
 SELECT DISTINCT 
	 LY_DOCENTE.NOME_COMPL,
	 LY_AGENDA.DATA, 
	 LY_AGENDA.DISCIPLINA, 
	 LY_AGENDA.TURMA, 
	 LY_AGENDA.DEPENDENCIA, 
	 LY_ALUNO.ALUNO, 
	 LY_ALUNO.NOME_COMPL, 
	 LY_MATRICULA.SIT_MATRICULA, 
	 LY_MATRICULA.SIT_DETALHE, 
	 LY_AGENDA.LISTA, 
	 LY_AGENDA.HORA_INICIO, 
	 LY_AGENDA.HORA_FIM, 
	 VW_FCAV_MONITOR_AULA.MONITOR_1, 
	 VW_FCAV_MONITOR_AULA.MONITOR_2, 
	 VW_FCAV_REPOSICAO_AULA.REPOSICAO_DO_DIA,
	 VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.NUM_AULA
 FROM   ((((LYCEUM.dbo.VW_FCAV_CRONOGRAMA_TURMA_DOCENTE VW_FCAV_CRONOGRAMA_TURMA_DOCENTE 
	LEFT OUTER JOIN LYCEUM.dbo.LY_AGENDA LY_AGENDA 
		ON ((((VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.TURMA=LY_AGENDA.TURMA) 
		AND (VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.DIA_AULA=LY_AGENDA.DATA)) 
		AND (VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.DISCIPLINA=LY_AGENDA.DISCIPLINA)) 
		AND (VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.ANO=LY_AGENDA.ANO)) 
		AND (VW_FCAV_CRONOGRAMA_TURMA_DOCENTE.PERIODO=LY_AGENDA.SEMESTRE)) 
	INNER JOIN (LYCEUM.dbo.LY_ALUNO LY_ALUNO 
	INNER JOIN LYCEUM.dbo.LY_MATRICULA LY_MATRICULA 
		ON LY_ALUNO.ALUNO=LY_MATRICULA.ALUNO) 
		ON (LY_AGENDA.DISCIPLINA=LY_MATRICULA.DISCIPLINA) 
		AND (LY_AGENDA.TURMA=LY_MATRICULA.TURMA)) 
	LEFT OUTER JOIN LYCEUM.dbo.LY_DOCENTE LY_DOCENTE 
		ON LY_AGENDA.NUM_FUNC=LY_DOCENTE.NUM_FUNC) 
	LEFT OUTER JOIN LYCEUM.dbo.VW_FCAV_MONITOR_AULA VW_FCAV_MONITOR_AULA 
		ON ((LY_AGENDA.AGENDA=VW_FCAV_MONITOR_AULA.AGENDA) 
		AND (LY_AGENDA.DISCIPLINA=VW_FCAV_MONITOR_AULA.DISCIPLINA)) 
		AND (LY_AGENDA.TURMA=VW_FCAV_MONITOR_AULA.TURMA))
	LEFT OUTER JOIN LYCEUM.dbo.VW_FCAV_REPOSICAO_AULA VW_FCAV_REPOSICAO_AULA 
		ON (LY_AGENDA.REPOSICAO=VW_FCAV_REPOSICAO_AULA.REPOSICAO) 
		AND (LY_AGENDA.AGENDA=VW_FCAV_REPOSICAO_AULA.AGENDA)
 WHERE  LY_AGENDA.DISCIPLINA='MBA-EE-DTEE' AND LY_AGENDA.TURMA='MBA-EE T 01' AND LY_MATRICULA.SIT_MATRICULA='Matriculado' AND LY_AGENDA.LISTA>0
 ORDER BY LY_ALUNO.NOME_COMPL


 SELECT * FROM VW_FCAV_FECHAMENTO_TURMA WHERE TURMA = 'CCGB T 48'


SELECT * FROM  VW_FCAV_DASHBOARD_FECHAMENTO_MATRICULA WHERE TURMA ='A-14001.15 T 18'
SELECT * FROM  VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA WHERE TURMA_PREF ='A-GPMP T 105' 

VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR


SELECT DISTINCT
	TURMA,
	ALUNO,
	VALOR_CONTRATADO
FROM 
	VW_FCAV_DASHBOARD_FINANCEIRO BO 
WHERE
	TURMA = 'CCGB T 48'
	AND SIT_ALUNO != 'Cancelado'
GROUP BY 
	TURMA,
	ALUNO,
	VALOR_CONTRATADO


SELECT SUM(CAST(VALOR_CONTRATADO AS money)) 
			FROM VW_FCAV_DASHBOARD_FINANCEIRO DF
			WHERE DF.TURMA = 'CCGB T 48'
				AND MONTH(DATA_DE_VENCIMENTO) <=DT_INICIO
				GROUP BY TURMA

SELECT *  FROM VW_fCAV_RESUMO_MATRICULA_E_PRE_MATRICULA WHERE TURMA  = 'CCGB T 48' AND SIT_ALUNO != 'CANCELADO'