CREATE TABLE [dbo].[LY_SISTEMA_DESTINO_INTEGRACAO](
	[ID_SISTEMA_DESTINO] [dbo].[T_NUMERO] NOT NULL,
	[SISTEMA_DESTINO] [dbo].[T_ALFAMEDIUM] NOT NULL,
	[DESCRICAO] [dbo].[T_ALFAMEDIUM] NOT NULL,
 CONSTRAINT [PK_LY_SISTEMA_DESTINO_INTEGRACAO] PRIMARY KEY CLUSTERED 
(
	[ID_SISTEMA_DESTINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
