***************************

 SELECT 
	OC.CONCURSO, 
	ANO_INGRESSO, 
	PER_INGRESSO, 
	OM.DTINICIO,
	OM.DTFIM, 
	'S' AS INGR_ESCOLHE_PLANO, 
	'1' AS INGR_MAX_RESP_FINAN, 
	PO.N_DIAS_VENC_BOL
 FROM LY_CONCURSO C
		INNER JOIN LY_OFERTA_CURSO OC ON C.CONCURSO = OC.CONCURSO
		INNER JOIN LY_OPCOES_MATRICULA OM ON	 OC.CURSO		 = OM.CURSO 
											 AND OC.ANO_INGRESSO = OM.ANO 
											 AND OC.PER_INGRESSO = OM.PERIODO
		INNER JOIN LY_PLANOS_OFERTADOS PO ON  OC.OFERTA_DE_CURSO = PO.OFERTA_DE_CURSO
WHERE
	OC.ANO_INGRESSO        = 2017
AND OC.CURSO		NOT LIKE 'A%'
AND OC.CONCURSO  IS NOT NULL

**************************
 
 UPDATE LY_CONCURSO
 SET 
 --SELECT 
	--OC.CONCURSO, 
	ANO					 = ANO_INGRESSO, 
	SEMESTRE			 = PER_INGRESSO, 
	INGR_DTINI			 = OM.DTINICIO,
	INGR_DTFIM			 = OM.DTFIM, 
	INGR_ESCOLHE_PLANO	 = 'S', 
	INGR_MAX_RESP_FINAN	 = '1', 
	N_DIAS_VENC_BOL_MATR = PO.N_DIAS_VENC_BOL
 FROM LY_CONCURSO C
		INNER JOIN LY_OFERTA_CURSO OC ON C.CONCURSO = OC.CONCURSO
		INNER JOIN LY_OPCOES_MATRICULA OM ON	 OC.CURSO		 = OM.CURSO 
											 AND OC.ANO_INGRESSO = OM.ANO 
											 AND OC.PER_INGRESSO = OM.PERIODO
		INNER JOIN LY_PLANOS_OFERTADOS PO ON  OC.OFERTA_DE_CURSO = PO.OFERTA_DE_CURSO
WHERE
	OC.ANO_INGRESSO        = 2017
AND OC.CURSO		NOT LIKE 'A%'
AND OC.CONCURSO  IS NOT NULL
