/*

*/


/************************************************************	
	1 - CRIAR FILTRO DOS AVALIADORES
*************************************************************/
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'MBA-EP T 01' AND DISCIPLINA = 'MBA-EP-DES'  AND SIT_MATRICULA = 'Matriculado'
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'MBA-EP T 01' AND DISCIPLINA = 'MBA-EP-PD'  AND SIT_MATRICULA = 'Matriculado'

INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUMBAEPT01DES',NULL,NULL,NULL,NULL,'Alunos Matriculados - DES - MBA-EP T 01','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = ''MBA-EP T 01'' AND DISCIPLINA = ''MBA-EP-DES''  AND SIT_MATRICULA = ''Matriculado''')
INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUMBAEPT01PD',NULL,NULL,NULL,NULL,'Alunos Matriculados - PD - MBA-EP T 01','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = ''MBA-EP T 01'' AND DISCIPLINA = ''MBA-EP-PD''  AND SIT_MATRICULA = ''Matriculado''')

/************************************************************
	2 - FILTRO DAS DISCIPLINAS AVALIADAS
*************************************************************/
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'MBA-EP-DES'
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'MBA-EP-PD'

INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISMBAEPT01DESJFN','Disciplina - DES - João Ferreira Netto - MBA-EP T 01','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''MBA-EP-DES''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISMBAEPT01PDPRd','Disciplina - PD - Paulo Roberto dos Santos - MBA-EP T 01','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''MBA-EP-PD''')
/************************************************************	
	3 - FILTRO DOS DOCENTES AVALIADOS 
*************************************************************/
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111117
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111211

INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOMBAEPT01DESJFN','Docente - João Ferreira Netto - DES - MBA-EP T 01','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111117')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOMBAEPT01PDPRd','Docente - Paulo Roberto dos Santos - PD - MBA-EP T 01','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111211')

/************************************************************	
	FILTRO INFRA-ESTRUTURA DOS CURSOS AVALIADOS 
*************************************************************/



/*************************************************************/