CCGB T 50

UPGRADE T 25 E 26


SELECT * FROM VW_FCAV_INI_FIM_CURSO_TURMA WHERE TURMA IN ('CCUPGRADE T 26','CCUPGRADE T 25','CCGB T 50')
SELECT * FROM LY_BLOCO_INSC_OFERTA_CURSO WHERE OFERTA_DE_CURSO = 1794

--------
UPDATE LY_BLOCO_INSC_OFERTA_CURSO
SET
	OPCIONAL = 'S'
WHERE
	ID_BLOCO_INSC_ONLINE = 6
	AND OFERTA_DE_CURSO IN (1793,1794,1837)