select 
	TURMA,
	ALUNO,
	NOME_COMPL
from VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA
where 
	TURMA = 'CEGP T 74'
ORDER BY ALUNO


select 
	TURMA,
	ALUNO,
	NOME_COMPL
from VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA
where 
	ALUNO like 'E20%212'
ORDER BY ALUNO



SELECT * FROM LY_APLIC_QUESTIONARIO WHERE TIPO_QUESTIONARIO  = 'FORM_AVAL_DIS_MOD_3' 

delete LY_PARTICIPACAO_QUEST where  TIPO_QUESTIONARIO  = 'FORM_AVAL_DIS_MOD_3' and APLICACAO like '%Aval_Disciplina_Mod'
delete LY_FAPLIC_QUEST_APLIC where APLICACAO like '%Aval_Disciplina_Mod'
delete LY_QUESTAO_APLICADA where APLICACAO like '%Aval_Disciplina_Mod'
delete LY_PUB_ALVO_APLIC where APLICACAO like '%Aval_Disciplina_Mod'

delete LY_APLIC_QUESTIONARIO WHERE TIPO_QUESTIONARIO  = 'FORM_AVAL_DIS_MOD_3' and APLICACAO like '%Aval_Disciplina_Mod'

UPDATE LY_APLIC_QUESTIONARIO 
SET
	ATIVO = 'N'
WHERE TIPO_QUESTIONARIO  = 'FORM_AVAL_DIS_MOD_3' AND TITULO = 'Aval. Disc. PD - Paulo Santos - MBA-EP T 01'


