SELECT 
	EC.CONCURSO,
	EC.CANDIDATO,
	CA.NOME_COMPL AS NOME_CANDIDATO,
	EC.ENTREVISTADOR,
	DO.NOME_COMPL AS NOME_ENTREVISTADOR,
	EC.DATA AS DT_ENTREVISTA,
	EC.HORA_INICIO,
	DE.FACULDADE AS UNIDADE_FISICA,
	EC.DEPENDENCIA
FROM 
	LY_ENTREVISTA_CANDIDATO EC 
	INNER JOIN LY_CANDIDATO CA
		ON CA.CANDIDATO = EC.CANDIDATO
		AND CA.CONCURSO = EC.CONCURSO
	INNER JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = EC.ENTREVISTADOR
	INNER JOIN LY_DEPENDENCIA DE
		ON DE.DEPENDENCIA = EC.DEPENDENCIA
