select * from LY_PARTICIPACAO_QUEST where APLICACAO = 'DICCBPONT01PACA'	and DATA_PART is null

-- IDENTIFICAR QUAIS SÃO AS AVALIAÇÕES QUE NÃO ESTÃO IDENTIFICADAS
SELECT 
	* 
FROM 
	LY_RESPOSTA 
WHERE 
	APLICACAO = 'DICCBPONT01PACA'		-- FILTRO PELO CÓDIGO DA AVALIAÇÃO.
GO

DECLARE @errorMsg VARCHAR(MAX) = ''

BEGIN TRAN
	BEGIN TRY
		-- PREENCHER OS CAMPOS AVA_TIPO_OBJETO E AVA_CODIGO
		UPDATE LY_RESPOSTA 
		SET
			AVA_TIPO_OBJETO = 'ALUNO',	-- PREENCHER O COM O TIPO ALUNO
			AVA_CODIGO = ''				-- PREENCHER COM O CÓDIGO DO ALUNO
		WHERE
			APLICACAO = ''		-- FILTRO PELO CÓDIGO DA AVALIAÇÃO
			AND CHAVE_RESP IN ()					-- FILTRO PELAS CHAVES RESP
	END TRY
	BEGIN CATCH

		SET @errorMsg = CONVERT(varchar,ERROR_NUMBER()) + ' - ' + ERROR_MESSAGE()
		
		ROLLBACK
	END CATCH

IF @@TRANCOUNT > 0
	COMMIT
