

SELECT * FROM LY_OPCOES_BOLETO

DELETE LY_BANCO_PREMATR WHERE CHAVE = 8


SELECT CURSO FROM LY_CURSO WHERE FACULDADE = 'ESPEC' and ATIVO = 's' and CURSO not like 'CE_322'
dfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfg


SELECT CURSO FROM LY_TURMA WHERE CENTRO_DE_CUSTO LIKE '416%' AND CURSO NOT LIKE 'ATUALIZACAO'
GROUP BY CURSO


-------------------------------------
-- CURSO DA QUALIDADE
SELECT 
	CURSO 
FROM 
	LY_TURMA 
WHERE	CENTRO_DE_CUSTO LIKE '416%' 
	AND CURSO NOT LIKE 'ATUALIZACAO'
	AND CURSO IN ('A-AN14001.15','A-9001.15', 'A-GPMP')
GROUP BY CURSO
order by CURSO

---------------------------------
--CURSOS DE CAPACITACAO E ATUALIZACAO NÃO QUALIDADE
SELECT 
	CURSO 
FROM 
	LY_TURMA 
WHERE	CENTRO_DE_CUSTO NOT LIKE '416%' 
	AND UNIDADE_RESPONSAVEL NOT IN ('ESPEC','PALES')
	AND CURSO NOT LIKE 'ATUALIZACAO'
	AND CURSO IN ('A-AN14001.15','A-9001.15', 'A-GPMP')
GROUP BY CURSO
ORDER BY CURSO

---------------------------------
--CURSOS DE ESPECIALIZACAO
SELECT 
	CURSO 
FROM 
	LY_TURMA 
WHERE	UNIDADE_RESPONSAVEL IN ('ESPEC')
	
GROUP BY CURSO


---------------------------------
--CURSOS DE ESPECIALIZACAO
INSERT INTO LY_BANCO_PREMATR  (CHAVE, CURSO, CONVENIO)
       SELECT 7, 
			CURSO,
			2112116
       FROM LY_TURMA 
	WHERE	UNIDADE_RESPONSAVEL IN ('ESPEC')
	GROUP BY CURSO


---------------------------------
--CURSOS DE CAPACITACAO E ATUALIZACAO NÃO QUALIDADE
INSERT INTO LY_BANCO_PREMATR  (CHAVE, CURSO, CONVENIO)
       SELECT 8, 
			CURSO,
			2112140
       FROM LY_TURMA 
WHERE	CENTRO_DE_CUSTO NOT LIKE '416%' 
	AND UNIDADE_RESPONSAVEL NOT IN ('ESPEC','PALES')
	AND CURSO NOT LIKE 'ATUALIZACAO'
GROUP BY CURSO

-------------------------------------
-- CURSO DA QUALIDADE
INSERT INTO LY_BANCO_PREMATR  (CHAVE, CURSO, CONVENIO)
       SELECT 9, 
			CURSO,
			2112124
       FROM LY_TURMA 
WHERE	CENTRO_DE_CUSTO LIKE '416%' 
	AND CURSO NOT LIKE 'ATUALIZACAO'
GROUP BY CURSO