/*
	- SCRIPT PARA ALTERAR A DATA FINAL DA TURMA/DISCIPLINA.
	
	SELECT DISTINCT 
		TURMA, T.DISCIPLINA, D.NOME_COMPL, T.DT_INICIO,	T.DT_FIM
	FROM 
		LY_TURMA T
		INNER JOIN LY_DISCIPLINA D ON T.DISCIPLINA = D.DISCIPLINA
	WHERE T.TURMA = 'CCAPE T 10' 
*/

DECLARE @DISCIPLINA VARCHAR(20)
DECLARE @TURMA VARCHAR(20)
DECLARE @DT_FIM DATETIME
DECLARE @DT_INCIO DATETIME

SET @DISCIPLINA = 'CCAPE-EEC'
SET @TURMA		= 'CCAPE T 10'
SET @DT_INCIO	= '2018-04-27 00:00:00.000'
SET @DT_FIM		= '2018-06-30 00:00:00.000'
------------------------------------------------------
SELECT 
DT_INICIO DT_INI_ANTIGA,
DT_FIM AS DT_FIM_ANTIGA,
* 
FROM 
	LY_TURMA 
WHERE 
	DISCIPLINA = @DISCIPLINA
	AND TURMA  = @TURMA
------------------------------------------------------
ALTER TABLE LY_TURMA DISABLE TRIGGER ALL

UPDATE LY_TURMA 
SET
	--DT_INICIO = @DT_INCIO,
	DT_FIM = @DT_FIM
where 
	DISCIPLINA = @DISCIPLINA
	AND TURMA  = @TURMA
	
ALTER TABLE LY_TURMA ENABLE TRIGGER ALL
------------------------------------------------------	
SELECT 
	DT_INICIO as DT_INI_ALTERADO,
	DT_FIM AS DT_FIM_ALTERADO,
	* 
FROM 
	LY_TURMA 
WHERE 
	DISCIPLINA = @DISCIPLINA
	AND TURMA  = @TURMA
------------------------------------------------------