/*
	VIEW VW_FCAV_MONITOR_AULA

FINALIDADE: Retornar os monitores das aulas com o e-mails para serem exibidos nas listas de presenças e lanches

Autor:	Gabriel Serrano Scalione
Data:	19/12/2017

*/



CREATE VIEW VW_FCAV_MONITOR_AULA
AS

WITH monitores as 
(SELECT 
	AGENDA,
	LISTA,
	DISCIPLINA,
	TURMA,
	AG.NUM_FUNC,
	CASE  
        WHEN CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))) > 0 THEN LEFT(dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(LTRIM(RTRIM(AG.DESCRICAO))), CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))) - 1)  
        ELSE dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(LTRIM(RTRIM(AG.DESCRICAO)))  
    END AS MONITOR_1,  
    CASE  
        WHEN CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))) > 0 THEN REPLACE(DBO.FN_FCAV_EXTRAIR_NUMEROS(LEFT(LTRIM(RTRIM(AG.DESCRICAO)), CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))))),'-','') 
		else REPLACE(DBO.FN_FCAV_EXTRAIR_NUMEROS(SUBSTRING(LTRIM(RTRIM(AG.DESCRICAO)), CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))), LEN(LTRIM(RTRIM(AG.DESCRICAO))))),'-','')
	end AS COD_MONITOR_1,
    CASE  
        WHEN CHARINDEX('/', REVERSE(LTRIM(RTRIM(AG.DESCRICAO)))) > 0 THEN SUBSTRING(dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(LTRIM(RTRIM(AG.DESCRICAO))), CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO)))+2, LEN(LTRIM(RTRIM(AG.DESCRICAO))))  
        ELSE '-'  
    END AS MONITOR_2,
    CASE  
        WHEN CHARINDEX('/', REVERSE(LTRIM(RTRIM(AG.DESCRICAO)))) > 0 then REPLACE(DBO.FN_FCAV_EXTRAIR_NUMEROS(SUBSTRING(LTRIM(RTRIM(AG.DESCRICAO)), CHARINDEX('/', LTRIM(RTRIM(AG.DESCRICAO))), LEN(LTRIM(RTRIM(AG.DESCRICAO))))),'-','')
		ELSE '-'
	END  AS COD_MONITOR_2

FROM 
	LY_AGENDA AG

WHERE 
	AG.DESCRICAO like 'Monitor%'
)	

SELECT 
	mo.AGENDA,
	LISTA,
	DISCIPLINA,
	TURMA,
	NUM_FUNC,
	MONITOR_1,
	COD_MONITOR_1,
	(select e_mail from LY_PESSOA where PESSOA = convert(numeric,isnull(mo.COD_MONITOR_1,9999))) E_MAIL_MONITOR_1,
	MONITOR_2,
	COD_MONITOR_2,
	CASE WHEN COD_MONITOR_2 = '-' THEN '-'
		ELSE (select e_mail from LY_PESSOA where PESSOA = convert(numeric,mo.COD_MONITOR_2))
	END AS E_MAIL_MONITOR_2
	--(select e_mail from LY_PESSOA where PESSOA = convert(numeric,mo.COD_MONITOR_2))
FROM 
	monitores mo
