--SELECT
	
--	CHARINDEX(' ',HISTORICO,1),
--	CHARINDEX(' - ',HISTORICO,1),
--	LTRIM(RTRIM(SUBSTRING(HISTORICO,CHARINDEX(' ',HISTORICO,1)+1,CHARINDEX(' - ',HISTORICO,1) - (CHARINDEX(' ',HISTORICO,1)+1)))) AS COBRANCA,
--	SUBSTRING(HISTORICO,1,16) AS HIST,
--	* 
--FROM FCAV_IMPORTCONTABIL
----WHERE HISTORICO LIKE '%estorno%'


WITH CONF_DEBITO AS 
		(SELECT
			IMP_COBRANCA,-- VALOR , CAST(VALOR AS MONEY) AS VALOR_2--
			SUM(CAST(VALOR AS MONEY)) AS VALOR
		FROM	 FCAV_IMPORT_DEB_CRED
		WHERE	 TIPO_LANC = '1' 
		GROUP BY IMP_COBRANCA
	),

	CONF_CRED AS 
		(SELECT
			IMP_COBRANCA,-- VALOR , CAST(VALOR AS MONEY) AS VALOR_2--
			SUM(CAST(VALOR AS MONEY)) * -1 AS VALOR
		FROM	 FCAV_IMPORT_DEB_CRED
		WHERE	 TIPO_LANC = '2' 
		GROUP BY IMP_COBRANCA
	),

	CONF_SUM AS
		(SELECT 
			CD.IMP_COBRANCA,
			SUM(ISNULL(CD.VALOR,'0,00') + ISNULL(CC.VALOR,'0,00')) AS CALC
		FROM CONF_DEBITO CD
			LEFT OUTER JOIN CONF_CRED CC ON CD.IMP_COBRANCA = CC.IMP_COBRANCA
		GROUP BY
			CD.IMP_COBRANCA
		)

	SELECT 
		TEMP.*
	FROM 
		FCAV_IMPORT_DEB_CRED TEMP
		INNER JOIN CONF_SUM CONF ON TEMP.IMP_COBRANCA = CONF.IMP_COBRANCA
	WHERE 
		CONF.CALC <> 0