SELECT * FROM LY_COBRANCA WHERE COBRANCA = 212392

SELECT * FROM LY_ITEM_LANC WHERE COBRANCA = 212392


INSERT INTO LY_ITEM_LANC 
(COBRANCA,ITEMCOBRANCA,LANC_DEB,CODIGO_LANC,ALUNO,NUM_BOLSA,RESP,MOTIVO_DESCONTO,DEVOLUCAO,
BOLETO,PARCELA,DATA,VALOR,DESCRICAO,ACORDO,COBRANCA_ORIG,ITEMCOBRANCA_ORIG,CENTRO_DE_CUSTO,
NATUREZA,ANO_REF_BOLSA,MES_REF_BOLSA,NUM_FINANCIAMENTO,ENCERR_PROCESSADO,EVENTO,EVENTO_COMPL,
DATA_CONTABIL,DT_ENVIO_CONTAB,CURSO,TURNO,CURRICULO,UNID_FISICA,DATA_DISPUTA,DATA_DECISAO_DISPUTA,
DISPUTA_ACEITA,DISPUTA_AJUSTADA,MOTIVO_DECISAO,LOTE_CONTABIL,DATA_PERDA,ORIGEM,ITEM_ESTORNADO)

VALUES(
212392,
30,
NULL,
'MS',
'E201910116',
NULL,NULL,NULL,	NULL,
198797,
21,	
'2020-09-11 00:00:00.000',
-8.93,
'Estorno de Cobrança: Estorno de Acrescimo de IGPM',
NULL, NULL,	NULL,	NULL,	
'CEAI T 34',
2020,
9,
NULL,
'N',
NULL,
NULL,	
NULL,	
'2020-09-11 00:00:00.000',
'CEAI',
'NOTURNO',
'CEAI 2019/1',	
'USP',
NULL,
NULL,	
'N',	
'N',
NULL,	
NULL,	
NULL,	
NULL,	
29)