SELECT * FROM LY_LANC_DEBITO WHERE ALUNO IN (

SELECT 
	ALUNO 
FROM 
	VW_FCAV_EXTFIN_LY 
WHERE 
	CONTA_BANCO LIKE '%5006%'
	AND ANO = 2018
	AND SITUACAO_BOLETO NOT LIKE 'Boleto pago'
	and BOLETO in (select BOLETO from LY_BOLETO where CONTA_BANCO LIKE '%5006%')
	and SIT_ALUNO = 'Ativo')
ORDER BY 
	ALUNO DESC 
	
select BOLETO from LY_BOLETO where CONTA_BANCO LIKE '%5006%' order by BOLETO desc


SELECT * FROM LY_LANC_DEBITO WHERE ALUNO = 'C201800169'