SELECT 
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	DI.INDICE_APROVACAO AS INDICE_APROVACAO_DISCIPLINA,
	DI.INDICE_REJEICAO AS INDICE_REJEICAO_DISCIPLINA,
	DO.INDICE_APROVACAO AS INDICE_APROVACAO_DOCENTE,
	DO.INDICE_REJEICAO AS INDICE_REJEICAO_DOCENTE,
	ISNULL(ID.INDICE_APROVACAO, 0) AS INDICE_APROVACAO_INFRA,
	ISNULL(ID.INDICE_REJEICAO, 0) AS INDICE_REJEICAO_INFRA
FROM 
	VW_FCAV_AVAL_DISCIPLINA_INDICES DI
	INNER JOIN VW_FCAV_AVAL_DOCENTE_INDICES DO
		ON DI.TURMA = DO.TURMA
		AND DI.DISCIPLINA = DO.DISCIPLINA
	LEFT JOIN VW_FCAV_AVAL_INFRA_INDICES ID
		ON ID.TURMA = DI.TURMA
GROUP BY
DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	DI.INDICE_APROVACAO,
	DI.INDICE_REJEICAO,
	DO.INDICE_APROVACAO,
	DO.INDICE_REJEICAO ,
	ID.INDICE_APROVACAO,
	ID.INDICE_REJEICAO