/*
SELECT * FROM VW_FCAV_STATUS_ALUNOS
*/

---------------------------------------------------------
-- ALUNOS APROVADOS --
SELECT 
	--COUNT(SIT_MATRICULA)
	TURMA
FROM 
	VW_FCAV_STATUS_ALUNO ST
WHERE
	ST.SIT_MATRICULA NOT LIKE 'Cancelado'
	AND ST.SIT_MATRICULA = 'Aprovado'
	 
GROUP BY CURSO, TURMA, ALUNO
HAVING COUNT(ALUNO) = 1

---------------------------------------------------------
-- ALUNOS REPROVADOS POR NOTA --
SELECT 
	COUNT(SIT_MATRICULA)
FROM 
	VW_FCAV_STATUS_ALUNO ST
WHERE
	ST.SIT_MATRICULA NOT LIKE 'Cancelado'
	AND ST.SIT_MATRICULA = 'Rep Nota'
GROUP BY CURSO, TURMA
	
---------------------------------------------------------
-- ALUNOS REPROVADOS POR FREQUENCIA --
SELECT 
	COUNT(SIT_MATRICULA)
FROM 
	VW_FCAV_STATUS_ALUNO ST
WHERE
	ST.SIT_MATRICULA NOT LIKE 'Cancelado'
	AND ST.SIT_MATRICULA = 'Rep Freq'
GROUP BY CURSO, TURMA

---------------------------------------------------------
-- CONSULTA DAS TURMA --

SELECT 
	VT.UNIDADE_RESPONSAVEL,
	VT.CURSO,
	VT.TURMA,
	VT.DT_INICIO,
	VT.DT_FIM,
	(SELECT TOP 1
		CLASSIFICACAO
		FROM LY_TURMA TU
	 WHERE
		SERIE = 1
		AND SERIE IS NOT NULL
		AND VT.TURMA = TU.TURMA
	 GROUP BY TU.TURMA, CLASSIFICACAO)	AS SIT_TURMA,
	
	(SELECT 
		COUNT(SIT_MATRICULA)
	FROM 
		VW_FCAV_STATUS_ALUNO ST
	WHERE
		ST.SIT_MATRICULA = 'Aprovado'
		AND ST.TURMA = VT.TURMA
	GROUP BY CURSO, TURMA
	)	AS APROVADOS,
	
	(SELECT 
		COUNT(SIT_MATRICULA)
	FROM 
		VW_FCAV_STATUS_ALUNO ST
	WHERE
		ST.SIT_MATRICULA = 'Rep Nota'
		AND ST.TURMA = VT.TURMA
	GROUP BY CURSO, TURMA
	)	AS REPR_NOTA,
	
	(SELECT 
		COUNT(SIT_MATRICULA)
	FROM 
		VW_FCAV_STATUS_ALUNO ST
	WHERE
		ST.SIT_MATRICULA = 'Rep Freq'
		AND ST.TURMA = VT.TURMA
	GROUP BY CURSO, TURMA
	)	AS REPR_FREQ
	
FROM
	VW_FCAV_INI_FIM_CURSO_TURMA VT
WHERE VT.TURMA IS NOT NULL
	AND VT.CURSO NOT IN ('PALESTRA VIVI','PALESTRA TAY')
	AND 
	(SELECT TOP 1
			CLASSIFICACAO
		 FROM LY_TURMA TU
		 WHERE
			SERIE = 1
			AND SERIE IS NOT NULL
			AND VT.TURMA = TU.TURMA
		 GROUP BY TU.TURMA, CLASSIFICACAO) = 'Concluido'
ORDER BY  vt.UNIDADE_RESPONSAVEL,vt.CURSO,CONVERT(VARCHAR,VT.DT_INICIO,112)
