SELECT * FROM LY_ALUNO WHERE CURSO = 'ccgbon'


SELECT TOP 1    
        GSP.GRUPO    
    FROM LY_ALUNO A    
    INNER JOIN LY_CURRICULO C    
        ON A.CURRICULO = C.CURRICULO    
        AND A.TURNO = C.TURNO    
        AND A.CURSO = C.CURSO    
    INNER JOIN LY_OFERTA_CURSO OC    
        ON OC.CURRICULO = A.CURRICULO    
        AND OC.ANO_INGRESSO = A.ANO_INGRESSO    
        AND OC.PER_INGRESSO = A.SEM_INGRESSO    
    INNER JOIN LY_GRUPO_SERV_PERIODO GSP    
        ON C.SERVICO = GSP.SERVICO    
        AND OC.ANO_INGRESSO = GSP.ANO    
        AND OC.PER_INGRESSO = GSP.PERIODO    
    WHERE A.ALUNO = 'C202100148'
    ORDER BY GSP.GRUPO DESC    