SELECT 
	CB.COBRANCA,
	BO.BOLETO,
	RE.RESP,
	RE.TITULAR,
	CGC_TITULAR CNPJ,
	DATA_REGISTRO
	FROM LY_BOLETO BO
	INNER JOIN VW_COBRANCA_BOLETO CB
		ON BO.BOLETO = CB.BOLETO
	INNER JOIN LY_RESP_FINAN RE
		ON RE.RESP = CB.RESP
	INNER JOIN LY_ITEM_LANC IL
		ON IL.COBRANCA = CB.COBRANCA

WHERE 
	CB.BOLETO = 172620
ORDER BY BO.BOLETO DESC

