/*

*/


/************************************************************	
	1 - CRIAR FILTRO DOS AVALIADORES
*************************************************************/
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 29' AND DISCIPLINA = 'CELOG-SMQCS'  AND SIT_MATRICULA = 'Matriculado'
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 29' AND DISCIPLINA = 'CELOG-TCC'  AND SIT_MATRICULA = 'Matriculado'
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 31' AND DISCIPLINA = 'CELOG-SADL'  AND SIT_MATRICULA = 'Matriculado'
SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 31' AND DISCIPLINA = 'CELOG-TM'  AND SIT_MATRICULA = 'Matriculado'

INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUCELOGT29SMQCS',NULL,NULL,NULL,NULL,'Alunos Matriculados - SMQCS - CELOG T 29','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 29' AND DISCIPLINA = 'CELOG-SMQCS'  AND SIT_MATRICULA = 'Matriculado'')
INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUCELOGT29TCC',NULL,NULL,NULL,NULL,'Alunos Matriculados - TCC - CELOG T 29','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 29' AND DISCIPLINA = 'CELOG-TCC'  AND SIT_MATRICULA = 'Matriculado'')
INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUCELOGT31SADL',NULL,NULL,NULL,NULL,'Alunos Matriculados - SADL - CELOG T 31','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 31' AND DISCIPLINA = 'CELOG-SADL'  AND SIT_MATRICULA = 'Matriculado'')
INSERT INTO LY_FILTRO_PUB_ALVO (TIPO_OBJETO,FILTRO_PUB_ALVO,CHAVE1,CHAVE2,CHAVE3,CHAVE4,DESCRICAO,QUERY)VALUES('ALUNO','ALUCELOGT31TM',NULL,NULL,NULL,NULL,'Alunos Matriculados - TM - CELOG T 31','SELECT ALUNO FROM VW_FCAV_MATRICULA_E_PRE_MATRICULA  WHERE  TURMA = 'CELOG T 31' AND DISCIPLINA = 'CELOG-TM'  AND SIT_MATRICULA = 'Matriculado'')


/************************************************************
	2 - FILTRO DAS DISCIPLINAS AVALIADAS
*************************************************************/
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'CELOG-SMQCS'
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'CELOG-TCC'
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'CELOG-SADL'
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'CELOG-TM'
SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = 'CELOG-TM'

INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISCELOGT29SMQCSLM','Disciplina - SMQCS - Luciano Mazza - CELOG T 29','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''CELOG-SMQCS''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISCELOGT29TCCDdO','Disciplina - TCC - Daniel de Oliveira Mota - CELOG T 29','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''CELOG-TCC''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISCELOGT31SADLCMH','Disciplina - SADL - Celso Mitsuo Hino - CELOG T 31','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''CELOG-SADL''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISCELOGT31TMDT','Disciplina - TM - Douglas Tacla - CELOG T 31','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''CELOG-TM''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','DISCELOGT31TMFGS','Disciplina - TM - Fabiano Gadini Stringher - CELOG T 31','SELECT DISCIPLINA FROM LY_DISCIPLINA WHERE DISCIPLINA = ''CELOG-TM''')


/************************************************************	
	3 - FILTRO DOS DOCENTES AVALIADOS 
*************************************************************/
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 20032500
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111134
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 900232
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111216
SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 900264

INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOCELOGT29SMQCSLM','Docente - Luciano Mazza - SMQCS - CELOG T 29','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 20032500')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOCELOGT29TCCDdO','Docente - Daniel de Oliveira Mota - TCC - CELOG T 29','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111134')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOCELOGT31SADLCMH','Docente - Celso Mitsuo Hino - SADL - CELOG T 31','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 900232')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOCELOGT31TMDT','Docente - Douglas Tacla - TM - CELOG T 31','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 9111216')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DOCENTE','DOCELOGT31TMFGS','Docente - Fabiano Gadini Stringher - TM - CELOG T 31','SELECT NUM_FUNC FROM LY_DOCENTE WHERE NUM_FUNC = 900264')

/************************************************************	
	FILTRO INFRA-ESTRUTURA DOS CURSOS AVALIADOS 
*************************************************************/
SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = 'CELOG-SMQCS'
SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = 'CELOG-TCC'
SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = 'CELOG-SADL'
SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = 'CELOG-TM'
SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = 'CELOG-TM'

INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','INFCELOGT29SMQCSLM','Infra - SMQCS - Luciano Mazza - CELOG T 29','SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = ''CELOG-SMQCS''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','INFCELOGT29TCCDdO','Infra - TCC - Daniel de Oliveira Mota - CELOG T 29','SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = ''CELOG-TCC''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','INFCELOGT31SADLCMH','Infra - SADL - Celso Mitsuo Hino - CELOG T 31','SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = ''CELOG-SADL''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','INFCELOGT31TMDT','Infra - TM - Douglas Tacla - CELOG T 31','SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = ''CELOG-TM''')
INSERT INTO LY_FILTRO_APLIC_QUEST (TIPO_OBJETO_AVAL,TIPO_OBJETO,FILTRO_APLIC_QUEST,DESCRICAO,QUERY)VALUES('ALUNO','DISCIPLINA','INFCELOGT31TMFGS','Infra - TM - Fabiano Gadini Stringher - CELOG T 31','SELECT A.DISCIPLINA FROM LY_DISCIPLINA A  WHERE A.DISCIPLINA = ''CELOG-TM''')


/*************************************************************/