/*
	REMOÇAO DOS DADOS DE RPS

	SELECT * FROM ly_boleto where boleto in (197100,196130,195599)
	select 
		* from vw_cobranca_boleto 
	where 
		cobranca = 205761
		boleto = '188135'
 SELECT 1      
  FROM VW_COBRANCA_BOLETO B 
	inner JOIN LY_COBRANCA C 
		ON B.COBRANCA = C.COBRANCA      
	inner JOIN LY_ALUNO A 
		ON C.ALUNO = A.ALUNO      
	inner JOIN LY_RESP_FINAN R
		ON C.RESP = R.RESP      
  WHERE a.aluno = 'A202001520'
	B.BOLETO = 184638     
  AND (A.NOME_COMPL LIKE '%TESTE%' 
	   OR R.TITULAR LIKE '%TESTE%')

*/


DECLARE @boleto T_NUMERO

SET @boleto = 196130

	SELECT BOLETO,
		OBS ,
		NUMERO_RPS ,
		DATA_ENVIO_RPS ,
		VALOR_SERVICO_RPS ,
		VALOR_DEDUCAO_RPS ,
		NUMERO_NFE ,
		DATA_EMISSAO_NFE ,
		VALOR_ISS ,
		DATA_EMISSAO_RPS ,
		LINK_RPS ,
		NOTA_FISCAL_SERIE ,
		VALOR_DESCONTO_RPS ,
		COD_VERIFICACAO ,
		VALOR_PIS ,
		VALOR_COFINS ,
		VALOR_CSLL ,
		VALOR_IR ,
		VALOR_INSS ,
		DT_SOLICITA_CANCEL_RPS ,
		MOTIVO_CANCEL_RPS  
	FROM LY_BOLETO
	WHERE BOLETO in (@boleto)


UPDATE LY_BOLETO
SET
	OBS =					NULL
,	NUMERO_RPS =			NULL
,	DATA_ENVIO_RPS =		NULL
,	VALOR_SERVICO_RPS =		NULL
,	VALOR_DEDUCAO_RPS =		NULL
,	NUMERO_NFE =			NULL
,	DATA_EMISSAO_NFE =		NULL
,	VALOR_ISS =				NULL
,	DATA_EMISSAO_RPS =		NULL
,	LINK_RPS =				NULL
,	NOTA_FISCAL_SERIE =		NULL
,	VALOR_DESCONTO_RPS =	NULL
,	COD_VERIFICACAO =		NULL
,	VALOR_PIS =				NULL
,	VALOR_COFINS =			NULL
,	VALOR_CSLL =			NULL
,	VALOR_IR =				NULL
,	VALOR_INSS =			NULL
,	DT_SOLICITA_CANCEL_RPS = NULL
,	MOTIVO_CANCEL_RPS =		NULL
WHERE
	BOLETO = @boleto

	SELECT BOLETO,
		OBS ,
		NUMERO_RPS ,
		DATA_ENVIO_RPS ,
		VALOR_SERVICO_RPS ,
		VALOR_DEDUCAO_RPS ,
		NUMERO_NFE ,
		DATA_EMISSAO_NFE ,
		VALOR_ISS ,
		DATA_EMISSAO_RPS ,
		LINK_RPS ,
		NOTA_FISCAL_SERIE ,
		VALOR_DESCONTO_RPS ,
		COD_VERIFICACAO ,
		VALOR_PIS ,
		VALOR_COFINS ,
		VALOR_CSLL ,
		VALOR_IR ,
		VALOR_INSS ,
		DT_SOLICITA_CANCEL_RPS ,
		MOTIVO_CANCEL_RPS  
	FROM LY_BOLETO
	WHERE BOLETO in (@boleto)