
SELECT 
	CURSO,
	NOME_CURSO,
	TURMA,
	AVALIADO,
	NOME_AVALIADO,
	COD_AVAL,
	QUESTAO,
	PERGUNTAS,
	AVG(QTDE_PREENCHIDA) QTDE_PREENCHIDA,
	SUM(EXCELENTE) AS EXCELENTE,
	SUM(BOM) AS BOM,
	SUM(REGULAR) AS REGULAR,
	SUM(RUIM) AS RUIM,
	SUM(PESSIMO) AS PESSIMO,
	CONVERT(DECIMAL(10,2),((CAST(SUM(BOM)AS decimal(10,2))+SUM(EXCELENTE))/SUM(QTDE_PREENCHIDA))) AS INDICE_APROVACAO,
	CONVERT(DECIMAL(10,2),((CAST(SUM(REGULAR)AS decimal(10,2))+SUM(RUIM)+SUM(PESSIMO))/SUM(QTDE_PREENCHIDA))) AS INDICE_REJEICAO
	
FROM VW_FCAV_AVAL_RESULTADO

--WHERE TURMA = 'MBA-EE T 01'
--AND DISCIPLINA = 'MBA-EE-ARIEE'
GROUP BY CURSO,
	NOME_CURSO,
	TURMA,
	AVALIADO,
	NOME_AVALIADO,
	COD_AVAL,
	QUESTAO,
	PERGUNTAS

	order by curso,TURMA,COD_AVAL,QUESTAO