declare @codigoaval varchar(100)

set @codigoaval = '%AGOONT04%'

--select * from LY_APLIC_QUESTIONARIO where APLICACAO like @codigoaval
--select * from LY_APLIC_QUESTIONARIO where convert(date,DT_FIM + 30) >= convert(date,getdate())

--select * from LY_PARTICIPACAO_QUEST where APLICACAO like @codigoaval order by CODIGO

--select APLICACAO, count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like @codigoaval group by APLICACAO

--select APLICACAO , count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like @codigoaval  AND DATA_PART is null group by APLICACAO

--select APLICACAO , count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like @codigoaval  AND DATA_PART is not null group by APLICACAO

--select APLICACAO , count(ALUNO) as QTDE_ALUNOS from FCAV_AVALIACAO_DOCENTE where APLICACAO like @codigoaval AND QUESTAO = 1 group by APLICACAO



 SELECT   
   CS.FACULDADE UNIDADE_RESPONSAVEL,  
   CS.CURSO,  
   CS.NOME AS NOME_CURSO,  
   CASE WHEN CS.CURSO = 'CEAI' AND AL.TURMA != 'CEAI T 34 SAB' THEN AC.TURMA_CEAI  
   ELSE AL.TURMA END AS TURMA,  
   AL.ALUNO,  
   AL.NOME_COMPL NOME_AVALIADOR,  
   AL.SIT_MATRICULA,   
   AL.DISCIPLINA,  
   AL.ANO,  
   AL.SEMESTRE,  
   CASE WHEN CS.CURSO = 'CEAI' AND AL.TURMA != 'CEAI T 34 SAB' THEN REPLACE(REPLACE(REPLACE(AC.TURMA_CEAI,' ',''),'/',''),'-','')   
    ELSE REPLACE(REPLACE(REPLACE(AL.TURMA,' ',''),'/',''),'-','')   
   END AS CODTUR  
   
  FROM   
   VW_FCAV_MATRICULA_E_PRE_MATRICULA AL   
   LEFT JOIN VW_FCAV_ALUNOS_MATRICULADOS_CEAI AC  
    ON AC.DISCIPLINA = AL.DISCIPLINA  
    AND AC.ANO = AL.ANO   
    AND AC.SEMESTRE = AL.SEMESTRE  
   INNER JOIN LY_CURSO CS  
    ON CS.CURSO = AL.CURSO  
   WHERE   
    AL.CONCURSO IS NOT NULL  
    AND AL.ANO >= 2018  
    AND AL.SIT_MATRICULA = 'Matriculado'  
	AND CASE WHEN CS.CURSO = 'CEAI' AND AL.TURMA != 'CEAI T 34 SAB' THEN REPLACE(REPLACE(REPLACE(AC.TURMA_CEAI,' ',''),'/',''),'-','')   
    ELSE REPLACE(REPLACE(REPLACE(AL.TURMA,' ',''),'/',''),'-','')   
   END like @codigoaval

