SELECT
	CA.CANDIDATO,
	CA.CONCURSO,
	MC.PESSOA,
	DOCUMENTO_CURRICULO,
	EXTENSAO,
	DATALENGTH(DOCUMENTO_CURRICULO) as tamanho_bytes,
	CAST((DATALENGTH(DOCUMENTO_CURRICULO)/1000.00)AS DECIMAL(10,3)) as tamanho_KB
FROM
	LY_MINI_CURRICULO MC
	INNER JOIN LY_CANDIDATO CA 
		ON CA.PESSOA = MC.PESSOA
WHERE CAST(DATALENGTH(DOCUMENTO_CURRICULO) AS NUMERIC) < 1000  --menor que 1 KB
ORDER BY 
	PESSOA DESC

	/*
		201800353	CCGP T 49
	*/