


---CONDICAO PARA VERIFICAR O DIA ÚTIL
DECLARE @DIAUTIL  DATETIME
SET @DIAUTIL = CONVERT(DATE,LYCEUM.DBO.FN_FCAV_GETDIAUTIL(GETDATE()-1,1),103)

DECLARE @HOJE  DATETIME
SET @HOJE = CONVERT(DATE,GETDATE(),103)

DECLARE @NUM_RPS  VARCHAR (9)
SET @NUM_RPS = '000005042'




SELECT	
		@HOJE AS DIA,
		CASE WHEN @DIAUTIL = @HOJE  THEN 'É DIA ÚTIL'
			ELSE 'NÃO É DIA ÚTIL'
		END VALIDA_DIA,
		@DIAUTIL AS PROX_DIA_UTIL,
		E1_NUM AS TITULO_RPS,
		E1_NOMCLI AS EMPRESA,
		DATEDIFF(DAY,@DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) AS DIAS_A_VENCER,
		CASE WHEN DATEDIFF(DAY,@DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) IN ('7','15')
		THEN 'DISPARA O E-MAIL'
		ELSE 'NÃO DISPARA' END STATUS_EMAIL,
		R_E_C_N_O_
FROM	SE1010
WHERE	D_E_L_E_T_ = ''
	AND (E1_CATIV IN ('401','402','403') OR E1_CATIV BETWEEN '800' AND '899')
	AND E1_BAIXA = ''
	AND E1_NUM = @NUM_RPS 
--PARA NF A VENCER ENTRE 7 E 15 DIAS
	--AND DATEDIFF(DAY,@DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) IN ('7','15')


SELECT	
		@HOJE AS DIA,
		CASE WHEN @DIAUTIL = @HOJE  THEN 'É DIA ÚTIL'
		ELSE 'NÃO É DIA ÚTIL'
		END VALIDA_DIA,
		@DIAUTIL AS PROX_DIA_UTIL,
		E1_NUM AS TITULO_RPS,
		E1_NOMCLI AS EMPRESA,
		DATEDIFF(DAY,@DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) AS DIAS_VENCIDA ,
		CASE WHEN DATEDIFF(DAY, @DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) IN ('-3' , '-5' , '-10' , '-15', '-20' ,'-25', '-30', '-45', '-60', '-90')
		THEN 'DISPARA O E-MAIL'
		ELSE 'NÃO DISPARA' END STATUS_EMAIL,
		R_E_C_N_O_
FROM	SE1010
WHERE	D_E_L_E_T_ = ''
	AND (E1_CATIV IN ('401','402','403') OR E1_CATIV BETWEEN '800' AND '899')
	AND E1_BAIXA = ''
	AND E1_NUM = @NUM_RPS 
	--AND E1_NOMCLI LIKE @EMPRESA
----PARA NF JÁ VENCIDAS EM 03, 05, 10, 15 ,20, 25, 30, 45, 60 E 90 DIAS
	--AND DATEDIFF(DAY, @DIAUTIL,CONVERT(DATE,E1_VENCREA,103)) IN ('-3' , '-5' , '-10' , '-15', '-20' ,'-25', '-30', '-45', '-60', '-90')