SELECT 
	UNID_RESP,
	CURSO,
	TURMA,
	DT_INICIO,
	DT_FIM,
	SITUACAO_TURMA,
	CASE  
    WHEN VT.UNID_RESP IN ('PALES', 'ATUAL') THEN (SELECT  
            COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Matriculado'  
        AND TURMA = VT.TURMA)  
    ELSE (SELECT  
            COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Matriculado'  
        AND TIPO_INGRESSO IN ('Processo Seletivo', 'Inscricao_Site')  
        AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')  
        AND CANDIDATO IS NOT NULL  
        AND TURMA = VT.TURMA
        AND DT_MATRICULA <= (VT.DT_INICIO + 5))  
	END AS MATRICULADOS,
	COUNT(ALUNO) FORMANDOS
FROM VW_FCAV_DASHBOARD_CONCLUINTES VT
WHERE
	SITUACAO_FINAL  = 'APROVADO'
GROUP BY 
	UNID_RESP,
	CURSO,
	TURMA,
	DT_INICIO,
	DT_FIM,
	SITUACAO_TURMA
ORDER BY
	UNID_RESP, CURSO, TURMA, DT_INICIO