SELECT 
	LV.VOUCHER,
	LV.DESCRICAO,
	LV.DESC_PERC_VALOR,
	LV.DESCONTO,
	LV.QUANTIDADE,
	LV.DT_INI,
	LV.DT_FIM,
	ISNULL(VC.CURSO,'TODOS') UTILIZADO_NO_CURSO
FROM LY_LOTE_VOUCHER LV
	LEFT JOIN LY_VOUCHER_CURSO VC
	ON LV.ID_LOTE_VOUCHER = VC.ID_LOTE_VOUCHER
GROUP BY LV.VOUCHER,
	LV.DESCRICAO,
	LV.DESC_PERC_VALOR,
	LV.DESCONTO,
	LV.QUANTIDADE,
	LV.DT_INI,
	LV.DT_FIM,
	VC.CURSO