SELECT
 CASE WHEN AL.UNIDADE_RESPONSAVEL = 'ATUAL' THEN 'ATUALIZACAO'
		 WHEN AL.UNIDADE_RESPONSAVEL = 'CAPAC' THEN 'CAPACITACAO'
		 WHEN AL.UNIDADE_RESPONSAVEL = 'DIFUS' THEN 'DIFUSAO'
		 WHEN AL.UNIDADE_RESPONSAVEL = 'ESPEC' THEN 'ESPECIALIZACAO'
		 WHEN AL.UNIDADE_RESPONSAVEL = 'PALES' THEN 'PALESTRA'
	END UNID_RESPONSAVEL,
	CASE WHEN AU.CONCURSO IS NULL THEN 'Venda Direta'
		 ELSE 'Processo Seletivo'
	 END TIPO_INGRESSO,
    AL.CURSO,
	CS.NOME AS NOME_CURSO,
    AL.TURMA,
	AL.DT_INICIO_TURMA,
    AL.DT_FIM_TURMA,
	AU.ANO_INGRESSO,
	AU.SEM_INGRESSO AS PERIODO,
    AL.SIT_ALUNO,
    AL.ALUNO,
    AL.NOME_COMPL,
    AL.DT_NASC,
    AL.IDADE_ATUAL,
    AL.NACIONALIDADE,
    AL.SEXO,
    AL.EST_CIVIL,
    AL.ENDERECO,
    AL.END_NUM,
    AL.END_COMPL,
    AL.BAIRRO,
    AL.END_MUNICIPIO,
    AL.END_PAIS,
    AL.CEP,
    '(' + al.DDD_FONE + ') ' + AL.FONE as TELEFONE,
    '(' + al.DDD_FONE_CELULAR + ') ' + AL.CELULAR as CELULAR,
    AL.E_MAIL,
    AL.RG_NUM,
    AL.RG_TIPO,
    AL.RG_EMISSOR,
    AL.RG_UF,
    AL.RG_DTEXP,
    AL.CPF,
    AL.PROFISSAO,
    AL.NOME_EMPRESA,
    AL.STATUS_TURMA,
    AL.DT_MATRICULA,
    AL.SIT_MATRICULA,
    AL.STATUS,
    AL.TITULAR,
    AL.CPF_CNPJ,
    AL.TIPO_BOLSA,
    AL.NUM_BOLSA,
    AL.PERC_VALOR,
    AL.VALOR,
    AL.MOTIVO AS MOTIVO_BOLSA,
    CASE
        WHEN TR.DT_INI IS NOT NULL AND
            TR.DT_REABERTURA IS NULL THEN 'TRANCADO'
        WHEN TR.DT_INI IS NOT NULL AND
            TR.DT_REABERTURA IS NOT NULL THEN 'RETORNO TRANCAMENTO'
        ELSE ''
    END
    AS SIT_TRANCAMENTO,
    CASE
        WHEN TR.DT_INI IS NOT NULL AND
            MT.DESCRICAO IS NULL THEN 'NÃO INFORMADO'
        ELSE MT.DESCRICAO
    END
    AS MOTIVO_TRANC,
    TR.DT_INI,
    TR.DT_FIM,
    TR.DT_REABERTURA AS RETORNO_TRANCAMENTO,
    hc.ANO_ENCERRAMENTO,
    hc.SEM_ENCERRAMENTO,
    hc.DT_ENCERRAMENTO,
    hc.MOTIVO AS MOTIVO_CANCEL,
    hc.CAUSA_ENCERR,
    hc.DT_REABERTURA AS RETORNO_CANCELAMENTO


FROM VW_FCAV_INFO_ALUNOS_LYCEUM AL
INNER JOIN LY_ALUNO AU
	ON AU.ALUNO = AL.ALUNO
INNER JOIN LY_CURSO CS
	ON CS.CURSO = AL.CURSO
LEFT JOIN LY_TRANC_INTERV_DATA TR
    ON TR.ALUNO = AL.ALUNO
LEFT JOIN LY_MOTIVO_TRANCAMENTO MT
    ON MT.MOTIVO_TRANC = TR.MOTIVO_TRANC
LEFT JOIN LY_CAUSA_TRANCAMENTO CT
    ON CT.CAUSA_TRANC = TR.CAUSA_TRANC
LEFT JOIN LY_H_CURSOS_CONCL HC
    ON HC.ALUNO = AL.ALUNO
    AND HC.CURSO = AL.CURSO
LEFT JOIN LY_CAUSA_ENCERR CE
    ON CE.CAUSA_ENCERR = HC.CAUSA_ENCERR

GROUP BY AL.UNIDADE_RESPONSAVEL,
	AU.CONCURSO,
   AL.CURSO,
   CS.NOME,
         AL.TURMA,
		 AU.ANO_INGRESSO,
	     AU.SEM_INGRESSO,
         AL.SIT_ALUNO,
         AL.ALUNO,
         AL.NOME_COMPL,
         AL.DT_NASC,
         AL.IDADE_ATUAL,
         AL.NACIONALIDADE,
         AL.SEXO,
         AL.EST_CIVIL,
         AL.ENDERECO,
         AL.END_NUM,
         AL.END_COMPL,
         AL.BAIRRO,
         AL.END_MUNICIPIO,
         AL.END_PAIS,
         AL.CEP,
		 al.DDD_FONE,
		 al.DDD_FONE_CELULAR,
         AL.FONE,
         AL.CELULAR,
         AL.E_MAIL,
         AL.RG_NUM,
         AL.RG_TIPO,
         AL.RG_EMISSOR,
         AL.RG_UF,
         AL.RG_DTEXP,
         AL.CPF,
         AL.PROFISSAO,
         AL.NOME_EMPRESA,
         AL.DT_INICIO_TURMA,
         AL.DT_FIM_TURMA,
         AL.STATUS_TURMA,
         AL.DT_MATRICULA,
         AL.SIT_MATRICULA,
         AL.STATUS,
         AL.TITULAR,
         AL.CPF_CNPJ,
         AL.TIPO_BOLSA,
         AL.NUM_BOLSA,
         AL.PERC_VALOR,
         AL.VALOR,
         AL.MOTIVO,
         MT.DESCRICAO,
         TR.DT_INI,
         TR.DT_FIM,
         TR.DT_REABERTURA,
         HC.ANO_ENCERRAMENTO,
         HC.SEM_ENCERRAMENTO,
         HC.DT_ENCERRAMENTO,
         HC.CAUSA_ENCERR,
         HC.MOTIVO,
         HC.DT_REABERTURA

ORDER BY AL.UNIDADE_RESPONSAVEL,  AL.CURSO,  AL.TURMA