SELECT
	MA.CURSO,
	CS.NOME,
	MA.TURMA,
	MA.ALUNO,
	MA.NOME_COMPL,
	LOWER(PE.E_MAIL) AS E_MAIL,
	MA.ANO_INGRESSO,
	MA.SEM_INGRESSO,
	CC.ANO_ENCERRAMENTO,
	CC.SEM_ENCERRAMENTO,
	CC.DT_ENCERRAMENTO,
	ISNULL(CC.DT_ENVIO_INST_EXT, CC.DT_CONFECCAO) AS DT_SOLICITACAO,
	CC.DT_DIPLOMA AS DT_DISPONIBILIZACAO,
	CC.DT_RETIRA_DIP AS DT_RETIRADA
FROM
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MA
	LEFT JOIN LY_H_CURSOS_CONCL CC
		ON CC.ALUNO = MA.ALUNO
		AND CC.CURSO = MA.CURSO
		AND CC.TURNO = MA.TURNO
		AND CC.CURRICULO = MA.CURRICULO
	INNER JOIN LY_CURSO CS
		ON CS.CURSO = MA.CURSO
	INNER JOIN LY_PESSOA PE
		ON PE.PESSOA = MA.PESSOA
WHERE
	SIT_ALUNO != 'Cancelado'
	and SIT_ALUNO != 'Ativo'
	AND MOTIVO = 'Conclusao'
--	AND MA.ALUNO = 'C201800137'
group by
	MA.CURSO,
	CS.NOME,
	MA.TURMA,
	MA.ALUNO,
	MA.NOME_COMPL,
	PE.E_MAIL,
	MA.ANO_INGRESSO,
	MA.SEM_INGRESSO,
	CC.ANO_ENCERRAMENTO,
	CC.SEM_ENCERRAMENTO,
	CC.DT_ENCERRAMENTO,
	CC.DT_ENVIO_INST_EXT,
	CC.DT_CONFECCAO,
	CC.DT_DIPLOMA,
	CC.DT_RETIRA_DIP
ORDER BY
	MA.CURSO,
	MA.TURMA,
	MA.ALUNO