
SELECT TOP 1
	PARCELA
FROM 
	LY_ITEM_LANC
WHERE ALUNO LIKE 'E201720009%'
ORDER BY COBRANCA DESC

select top 10 * from 
VW_FCAV_EXTFIN_LY EX
	INNER JOIN LY_CURSO CS
		ON CS.CURSO = EX.CURSO
WHERE CS.FACULDADE = 'ESPEC'
AND CONVERT(VARCHAR, DATA_DE_VENCIMENTO,112) < CONVERT(VARCHAR, GETDATE(),112)
AND DATA_DE_PAGAMENTO IS NULL
AND SITUACAO_BOLETO != 'Baixa por Acordo'
AND ALUNO = 'E201720009'


EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'E201720009'

SELECT * FROM VW_FCAV_INI_FIM_CURSO_TURMA WHERE TURMA = 'CEGP T 67'