declare @cobranca numeric
declare @DATA_INI date
declare @DATA_FIM date


set @cobranca = 206125

--select * from LY_ITEM_LANC where COBRANCA = 203795


SELECT DISTINCT  
-- '1 - FAT',
 ILAN.DATA AS DATA_PROC,  
 '008870' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ILAN.ITEMCOBRANCA AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,  
 CASE 
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '31402003' 
   WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '31401001'  
   WHEN ILAN.DESCRICAO LIKE 'BOLSA%' THEN '31401003'
   WHEN ILAN.DESCRICAO LIKE '%IGPM%BOLSA%' THEN '31401003'
   WHEN ILAN.DESCRICAO LIKE '% do Acordo %' THEN '11204008'  
   ELSE '11204001' END AS CONTA_DEB,  
 CASE 
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'BOLSA%' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE '%IGPM%BOLSA%' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE '% do Acordo %' THEN '11204005'  
   WHEN CUR.FACULDADE = 'ESPEC' THEN '31102024'  
  ELSE '31102025' END AS CONTA_CRED,  
   
 REPLACE (ILAN.VALOR,'-','') AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+PES.NOME_COMPL AS ORIGEM,  
  --CASE WHEN ILAN.MOTIVO_DESCONTO = 'Estorno'   
  --THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR)  
  --ELSE 
  'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ISNULL(ILAN.DESCRICAO,'Sem Descricao de baixa'),';',',') AS VARCHAR) 
  --END 
  AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 BOL.BOLETO AS IMP_BOLETO,  
 COB.COBRANCA AS IMP_COBRANCA  
  

   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_CURSO AS CUR ON (ILAN.CURSO = CUR.CURSO)
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)

WHERE  ILAN.DATA >= '2019-06-01'
--AND ILAN.DATA <= ('2019-09-09' +' 23:59:59.000')  
--AND ILAN.DT_ENVIO_CONTAB IS NULL
AND ILAN.ITEM_ESTORNADO IS NULL 
--AND (ILAN.MOTIVO_DESCONTO != 'Estorno'  or ILAN.CODIGO_LANC = 'ACORDO')
AND ILAN.DESCRICAO NOT LIKE '%REMOCAO%'
AND ILAN.COBRANCA IN (@cobranca)

UNION ALL
  
-- BLOCO PARA TRAZER OS ESTORNOS FEITOS NA ITEM_LANC EXCLUSIVAMENTE  
SELECT DISTINCT  
-- '2 - FAT',
 ILAN.DATA AS DATA_PROC,  
 '008870' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ILAN.ITEMCOBRANCA AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,  
   CASE  WHEN CUR.FACULDADE = 'ESPEC' THEN '31401002'
		WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '11204001' 
 ELSE '31402002' END AS CONTA_DEB,    
 CASE WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'Estorno de Cobrança: Estorno de Bolsa%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'Estorno de Cobrança: Estorno de Desconto%' THEN '11204001'
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '31402003'   
  ELSE '11204001' END AS CONTA_CRED,  
   
 REPLACE (ILAN.VALOR,'-','') AS VALOR,  
 'Titulo Rem Estorno'+' - '+PES.NOME_COMPL AS ORIGEM,  
 CASE 
	WHEN ILAN.DESCRICAO LIKE '%Estorno de Desconto%' 
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Estorno de Desconto'  
	WHEN ILAN.MOTIVO_DESCONTO = 'Estorno'   
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR)  
	WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' and ILAN.ITEM_ESTORNADO is not null  
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Estorno de '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR) 
	ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ISNULL(ILAN.DESCRICAO,'Estorno'),';',',') AS VARCHAR) 
	END AS HISTORICO,  
	
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 BOL.BOLETO AS IMP_BOLETO,  
 COB.COBRANCA AS IMP_COBRANCA  
  

FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_CURSO AS CUR ON (ILAN.CURSO = CUR.CURSO)
 LEFT OUTER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
WHERE   
	COB.COBRANCA in (@cobranca)
	AND (ILAN.MOTIVO_DESCONTO = 'Estorno' OR ILAN.ITEM_ESTORNADO IS NOT NULL)

UNION ALL
---------------------------------------------------------------------------------
--- SELECT PARA TRATAR DE BAIXAS POR PERDAS - DEVEDORES INCOBRÁVEIS	41101152  ---
---------------------------------------------------------------------------------

SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101152' AS CONTA_DEB,  
 '41101152' AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 COB.COBRANCA in (@cobranca)
AND ICRED.LANC_CRED IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)



UNION ALL
---------------------------------------------------------------------------------
--- SELECT PARA TRATAR DE BAIXAS POR PERDAS - DEVEDORES INCOBRÁVEIS	41101152  ---
---------------------------------------------------------------------------------

SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '11204002' AS CONTA_DEB,  
 '41101098' AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 COB.COBRANCA in (@cobranca)
AND ICRED.LANC_CRED IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)



union all

SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
    
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  --WHEN ICRED.DESCRICAO like 'Cart%'		 -- Pagamento por cartão de crédito
  --THEN '1' 
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Desconto%'  --OR ICRED.TIPODESCONTO IS NOT NULL-- Descontos concedidos   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno   
  THEN '1'
  WHEN ICRED.TIPODESCONTO = 'Concedido'-- Descontos concedidos   
  THEN '1'  
  ELSE '2' END AS TIPO_LANC,   
   
 CASE 
   WHEN ICRED.DESCRICAO like '%7080-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102004'
  WHEN ICRED.DESCRICAO like '%4436-7%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102013'
  WHEN ICRED.DESCRICAO like '%18605-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102018'
  WHEN ICRED.DESCRICAO like '%44537-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102021'
  WHEN ICRED.DESCRICAO like '%50904-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102024'
  WHEN ICRED.DESCRICAO like '%57611-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102025'
  WHEN ICRED.DESCRICAO like '%57611-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102025'
  WHEN ICRED.DESCRICAO like '%25373-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102032'
  WHEN ICRED.DESCRICAO like '%68-X%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102035'
  WHEN ICRED.DESCRICAO like '%69-8%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102036'
  WHEN ICRED.DESCRICAO like '%98-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102038'
  WHEN ICRED.DESCRICAO like '%34700-0%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102043'
  WHEN ICRED.DESCRICAO like '%34701-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102044'
  WHEN ICRED.DESCRICAO like '%37570-5%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102049'
  WHEN ICRED.DESCRICAO like '%102002-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102053'
  WHEN ICRED.DESCRICAO like '%27217-5%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102075'
  WHEN ICRED.DESCRICAO like '%7798-8%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102077'
  WHEN ICRED.DESCRICAO like '%7094-3%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102094'
  WHEN ICRED.DESCRICAO like '%7095-0%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102095'
  WHEN ICRED.DESCRICAO like '%7096-7%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102096'
  WHEN ICRED.DESCRICAO like '%7132-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102098'
  WHEN ICRED.DESCRICAO like '%29322-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102122'
  WHEN ICRED.DESCRICAO like '%6324-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102123'
 
  WHEN ICRED.DESCRICAO LIKE 'Desc%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN '51201002'  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno  
  THEN '31401004'
  
  WHEN BOL.CONTA_BANCO = '130050062' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta   
  THEN '11102001'  
  WHEN BOL.CONTA_BANCO = '130070943' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102094'  
  WHEN BOL.CONTA_BANCO = '130070967' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102096'  
  WHEN BOL.CONTA_BANCO = '130071322' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102098'  
  WHEN BOL.CONTA_BANCO = '130070802' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102004'  
    
  WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN '11102001'  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Baixa Manual  
  THEN '11102001'  

  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN '11102001'  
  
  WHEN ICRED.TIPODESCONTO = 'Concedido'
  THEN '51201002'
  
  ELSE NULL END AS CONTA_DEB,  
 CASE WHEN ICRED.DESCRICAO LIKE 'Encargo do tipo%'  
  THEN '51101004'   
  WHEN ICRED.DESCRICAO LIKE 'Desc%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Baixa Manual  
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno  
  THEN NULL  
  WHEN ICRED.TIPO_ENCARGO like 'Custas%' -- Custas de Agência de Cobrança  
  THEN '31501002'  
  WHEN ICRED.TIPO_ENCARGO like 'Honor%' -- Custas de Agência de Cobrança  
  THEN '31501002'  
  
  WHEN ICRED.TIPODESCONTO = 'Concedido'
  THEN '51201002'
  
  ELSE '11204001' END AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CENTRO_CUSTO  
  ELSE NULL END AS CC_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL 
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL 
  WHEN ICRED.TIPO_ENCARGO like 'Honor%' -- CC para custas de Agência de Cobrança  
  THEN '051'
  ELSE FCAD.CENTRO_CUSTO END AS CC_CRED,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CENTRO_ATIV  
  ELSE NULL END AS ITEM_CONTAB_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL 
  ELSE FCAD.CENTRO_ATIV END AS ITEM_CONTAB_CRED,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CLASSE_VALOR  
  ELSE NULL END AS CLASSE_VALOR_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL
  ELSE FCAD.CLASSE_VALOR END AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
	cob.COBRANCA in (@cobranca)
and ICRED.DESCRICAO NOT LIKE 'Cart%'
AND COB.COBRANCA IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (199695,199962,199311))
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

