

SELECT BOLETO,
		OBS ,
		NUMERO_RPS ,
		DATA_ENVIO_RPS ,
		VALOR_SERVICO_RPS ,
		VALOR_DEDUCAO_RPS ,
		NUMERO_NFE ,
		DATA_EMISSAO_NFE ,
		VALOR_ISS ,
		DATA_EMISSAO_RPS ,
		LINK_RPS ,
		NOTA_FISCAL_SERIE ,
		VALOR_DESCONTO_RPS ,
		COD_VERIFICACAO ,
		VALOR_PIS ,
		VALOR_COFINS ,
		VALOR_CSLL ,
		VALOR_IR ,
		VALOR_INSS ,
		DT_SOLICITA_CANCEL_RPS ,
		MOTIVO_CANCEL_RPS  
	FROM LY_BOLETO
	WHERE DATA_EMISSAO_RPS = '2010-10-22 00:00:00.000'


update LY_BOLETO
set
	DATA_EMISSAO_RPS = '2020-10-22 00:00:00.000'
WHERE DATA_EMISSAO_RPS = '2010-10-22 00:00:00.000'