
SELECT
	CL.ALUNO,
	AL.NOME_COMPL,
	AG.TURMA,
	CL.DISCIPLINA,
	CASE WHEN tu.SIT_TURMA = 'Desativada' THEN 'Histórico'
		ELSE TU.SIT_TURMA
	END as SIT_DISCIPLINA,
	CL.ANO,
	CL.SEMESTRE AS PERIODO,
	DO.NOME_COMPL AS NOME_DOCENTE,
	CL.LISTA,
	AG.DATA,
	CL.OCORRENCIA
FROM LY_COMP_LISTA CL
	INNER JOIN LY_AGENDA AG
		ON AG.LISTA = CL.LISTA
	INNER JOIN LY_ALUNO AL
		ON AL.ALUNO = CL.ALUNO
	INNER JOIN LY_TURMA TU
		ON TU.TURMA = AG.TURMA
		AND TU.DISCIPLINA = AG.DISCIPLINA
		AND TU.ANO = AG.ANO
		AND TU.SEMESTRE = AG.SEMESTRE
	INNER JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = AG.NUM_FUNC

WHERE 
	AL.ALUNO = 'E202010136'
GROUP BY
	CL.ALUNO,
	AL.NOME_COMPL,
	AG.TURMA,
	CL.DISCIPLINA,
	tu.SIT_TURMA,
	CL.ANO,
	CL.SEMESTRE,
	DO.NOME_COMPL,
	CL.LISTA,
	AG.DATA,
	CL.OCORRENCIA



