/*

	SCRIPT UTILIZADO NA PLANILHA DA TATI PARA TRAZER AS RPA DE 3 MESES PRA TRAZ ATÉ A DATA DE HOJE.

	a PLANILHA ESTÁ SALVA NA REDE:

	\\Financeiro\Contas_Pagar\Operacional\CAP\PROPAY\RPA_FORNECEDORES.XLXS


*/


SELECT 
	E2_FV_RATE		AS RATEIO,
	E2_NUM			AS NRO_TIRULO,
	E2_TIPO			AS TIPO,
	E2_CC			AS CTO_CUSTO,
	E2_CATIV		AS CTO_ATIV,
	E2_FORNECE		AS FORNECEDOR,
	A2_NOME			AS NOME_FORNECEDOR,
	A2_FV_PIS		AS INSS_PIS,
	E2_CONTAD		AS CONTA,
	SUBSTRING(E2_EMISSAO,7,2)+'/'+SUBSTRING(E2_EMISSAO,5,2)+'/'+SUBSTRING(E2_EMISSAO,1,4)	AS EMISSAO,
	SUBSTRING(E2_VENCTO,7,2)+'/'+SUBSTRING(E2_VENCTO,5,2)+'/'+SUBSTRING(E2_VENCTO,1,4)		AS VENCTO,
	SUBSTRING(E2_VENCREA,7,2)+'/'+SUBSTRING(E2_VENCREA,5,2)+'/'+SUBSTRING(E2_VENCREA,1,4)	AS VENCTO_REAL,
	CAST(E2_VALOR AS money)		AS VALOR,
	CAST(E2_IRRF AS money)		AS IRRF,
	CAST(E2_ISS AS money)		AS ISS,
	CAST(E2_INSS AS money)		AS INSS,
	CAST(E2_FV_INSE AS money)	AS INSS_EMP,
	CAST(E2_FV_INSA AS money)	AS INSS_AUT,
	E2_HIST			AS HISTORICO,
	SUBSTRING(A2_DTNASC,7,2)+'/'+SUBSTRING(A2_DTNASC,5,2)+'/'+SUBSTRING(A2_DTNASC,1,4)		AS DT_NASC,
	A2_PFISICA		AS RG,
                A2_CGC			AS CPF,
	A2_INSCRM		AS INSCRICAO,
	A2_END			AS ENDERECO,
	A2_CEP			AS CEP,
	A2_EST			AS ESTADO
FROM 
	SE2010
	INNER JOIN SA2010 ON E2_FORNECE = A2_COD
WHERE	
	SE2010.D_E_L_E_T_ = ''
AND SA2010.D_E_L_E_T_ = ''
AND E2_TIPO = 'RPA'
-- CONDIÇÃO ABAIXO PARA FAZER A COMPARAÇÃO COM A DATA DE 3 MESES ATRAS E A PARTIR DO DIA 01
AND E2_EMISSAO BETWEEN CAST(YEAR(DATEADD(MONTH,-3, GETDATE()))AS VARCHAR) + RIGHT('00'+CAST(MONTH(DATEADD(MONTH,-3, GETDATE()))AS VARCHAR),2)  +'01'  AND GETDATE()
ORDER BY
E2_FORNECE,
E2_NUM,
E2_VENCREA