
---------------------------------------------------------------------------------
--- SELECT PARA TRATAR DE BAIXAS POR PERDAS - DEVEDORES INCOBRÁVEIS	41101152  ---
---------------------------------------------------------------------------------

SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101152' AS CONTA_DEB,  
 '41101152' AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND (ICRED.DESCRICAO not like 'Credito%' OR ICRED.DESCRICAO not like 'Cart%' OR ICRED.DESCRICAO not like 'Pagamento%' OR ICRED.DESCRICAO not like 'Depósito%' OR ICRED.DESCRICAO not like 'Deposito%')-- Crédito Bancário ou crédito de depósito   
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (200407))
AND ICRED.LANC_CRED IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)



UNION ALL
---------------------------------------------------------------------------------
--- SELECT PARA TRATAR DE BAIXAS POR PERDAS - DEVEDORES INCOBRÁVEIS	11204002 41101098  ---
---------------------------------------------------------------------------------

SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '11204002' AS CONTA_DEB,  
 '41101098' AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND (ICRED.DESCRICAO not like 'Credito%' OR ICRED.DESCRICAO not like 'Cart%' OR ICRED.DESCRICAO not like 'Pagamento%' OR ICRED.DESCRICAO not like 'Depósito%' OR ICRED.DESCRICAO not like 'Deposito%')-- Crédito Bancário ou crédito de depósito   
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (200407))
AND ICRED.LANC_CRED IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)
