select * from LY_APLIC_QUESTIONARIO where APLICACAO like '%CCLGPONT04CIICS2%'
select * from LY_APLIC_QUESTIONARIO where APLICACAO like '%CCQPONT08GRMFP%'

select * from LY_PARTICIPACAO_QUEST where APLICACAO like '%CCQPONT08GRMFP%' order by CODIGO

select APLICACAO, count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like '%CCQPONT08GRMFP%' group by APLICACAO

select APLICACAO , count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like '%CCQPONT08GRMFP%'  AND DATA_PART is null group by APLICACAO

select APLICACAO , count(CODIGO) as QTDE_ALUNOS from LY_PARTICIPACAO_QUEST where APLICACAO like '%CCQPONT08GRMFP%'  AND DATA_PART is not null group by APLICACAO

select APLICACAO , count(ALUNO) as QTDE_ALUNOS from FCAV_AVALIACAO_DOCENTE where APLICACAO like '%CCQPONT08GRMFP%' AND QUESTAO = 1	AND DT_PREENCHIMENTO is not null group by APLICACAO
