select 
DATA_INCLUSAO,
ALUNO,
oc.OFERTA_DE_CURSO,
oc.CURSO,
oc.TURMA_PREF,
FORMA_PAGAMENTO,
BANDEIRA_CARTAO,
NUMERO_PARCELAS,
VALOR
from LY_COMPRA_OFERTA co
inner join LY_OFERTA_CURSO oc
	on oc.OFERTA_DE_CURSO = co.OFERTA_DE_CURSO
where FORMA_PAGAMENTO = 'cartao'
order by ID_COMPRA_OFERTA desc