 select 
	sum(VALOR_PAGAR) as PAGAR, 
	SUM(ISNULL(VALOR_PAGO,0)) AS PAGO,
	UPPER(SITUACAO_BOLETO) as SITBOL 
 
 from 
	VW_FCAV_EXTFIN_LY 
 WHERE 
	CENTRO_DE_CUSTO = '506037118' 
	and VALOR_PAGAR > 0 
	AND DT_ENVIO_CONTAB IS NOT NULL 
group by 
	SITUACAO_BOLETO



Select * from VW_FCAV_EXTFIN_LY 
 WHERE 
	CENTRO_DE_CUSTO = '506037118' 
	and VALOR_PAGAR > 0 
	AND DT_ENVIO_CONTAB IS NOT NULL 
order by DATA_DE_VENCIMENTO



Select CURSO, TURMA, CENTRO_DE_CUSTO, LANC_DEB, COBRANCA, DATA_DE_EMISSAO,
	DATA_DE_VENCIMENTO, VALOR_PAGAR, DATA_DE_PAGAMENTO, VALOR_PAGO, JUROS_MULTA, DESCONT from VW_FCAV_EXTFIN_LY 
 WHERE 
	CENTRO_DE_CUSTO = '506037118' 
--	and VALOR_PAGO = 0 
	AND DT_ENVIO_CONTAB IS NOT NULL 
order by DATA_DE_VENCIMENTO



SELECT * FROM LY_ITEM_LANC WHERE COBRANCA = 215059

SELECT * FROM LY_ITEM_cred WHERE COBRANCA = 141564