
/*
	CONSULTA PARA TRAZER OS CANDIDATOS QUE NÃO POSSUEM ENDEREÇO VÁLIDO
	
*/


SELECT 
	CA.CONCURSO,
	CO.DT_INICIO,
	CO.DT_FIM, 
	CA.CANDIDATO,
	PE.NOME_COMPL,
	PE.CPF,
	PE.ENDERECO,
	PE.BAIRRO,
	PE.CEP,
	MU.NOME AS MUNICIPIO,
	MU.UF,
	ca.SIT_CANDIDATO_VEST,
	ca.DT_INSCRICAO,
	AL.ALUNO,
	aL.SIT_ALUNO,
	IL.COBRANCA,
	IL.ITEMCOBRANCA,
	IL.BOLETO,
	IC.DESCRICAO DESCR_CRED
FROM
	LY_PESSOA PE
	INNER JOIN LY_CANDIDATO CA
		ON CA.PESSOA = PE.PESSOA
	INNER JOIN LY_CONCURSO CO
		ON CO.CONCURSO = CA.CONCURSO
	INNER JOIN HD_MUNICIPIO MU
		ON MU.MUNICIPIO = PE.END_MUNICIPIO
	inner join LY_ALUNO AL
		ON AL.CANDIDATO = CA.CANDIDATO
		AND AL.CONCURSO = CA.CONCURSO
		and al.PESSOA = pe.PESSOA
	INNER JOIN LY_ITEM_LANC IL
		ON IL.ALUNO = AL.ALUNO
	LEFT JOIN LY_ITEM_CRED IC
		ON IC.COBRANCA= IL.COBRANCA
WHERE	
	pe.ENDERECO LIKE '%informado%'
	AND CO.DT_FIM > GETDATE() 
order by ca.DT_INSCRICAO desc
	

