SELECT * FROM HD_PADTRANS WHERE PADACES = 'FCAV_EDUCACAO' and TRANS IN ('TLOV046D','TCONF129D')


TLOV046D - Buscar Questionários
TCONF129D - Tabela Geral

INSERT INTO HD_TRANSACAO (SIS, TRANS, NOME, PUBLICA, ACESSOANONIMO, PAGINAWEB, FORM, ITEMMENU, AUDITAR, MODULO)
VALUES(
	'Secretaria',    
	'TCONF129D',  
	'Tabela Geral',
	'N',
	'N',
	NULL,
	NULL,
	NULL,
	'S',
	NULL
	)

INSERT INTO HD_PADTRANS (PADACES, SIS, TRANS, PODEALT, PODECAD, PODEREM)
VALUES(
	'FCAV_EDUCACAO' -- PADACES
	,'Secretaria' -- SIS
	,'TCONF129D' -- TRANS
	,'S' -- PODEALT
	,'S' -- PODECAD
	,'S' -- PODEREM
	)


INSERT INTO HD_TRANSACAO (SIS, TRANS, NOME, PUBLICA, ACESSOANONIMO, PAGINAWEB, FORM, ITEMMENU, AUDITAR, MODULO)
VALUES(
	'Secretaria'	-- SIS
	,'TLOV046D'		-- TRANS
	,'Tabela Geral' -- NOME
	,'N'			-- PUBLICA
	,'N'			-- ACESSOANOMINO
	,NULL			-- PAGINAWEB
	,NULL			-- FORM
	,NULL			-- ITEMMENU
	,'S'			-- AUDITAR
	,NULL			-- MODULO
	)

INSERT INTO HD_PADTRANS (PADACES, SIS, TRANS, PODEALT, PODECAD, PODEREM)
VALUES(
	'FCAV_EDUCACAO' -- PADACES
	,'Secretaria' -- SIS
	,'TLOV046D' -- TRANS
	,'S' -- PODEALT
	,'S' -- PODECAD
	,'S' -- PODEREM
	)


