WITH CURSO_COORDENADOR AS 
(
	SELECT 
		CS.FACULDADE AS UNID_RESPONSAVEL,
		CS.CURSO, 
		CS.NOME AS NOME_CURSO,
		CO.TIPO_COORD,
		DO.NOME_COMPL AS NOME_COORDENADOR
	FROM LY_CURSO CS
	INNER JOIN LY_COORDENACAO CO
		ON CS.CURSO = CO.CURSO
	INNER JOIN LY_DOCENTE DO
		ON DO.NUM_FUNC = CO.NUM_FUNC
),
TURMA_OFERTA AS 
(
	SELECT DISTINCT
		 TU.CURSO,
		 TU.CURRICULO,
		 TU.TURMA,
		 TU.FACULDADE AS UNID_FISICA,
		 OC.ANO_INGRESSO,
		 OC.PER_INGRESSO
	FROM 
		LY_TURMA TU
	INNER JOIN LY_OPCOES_OFERTA OO
		ON OO.TURMA = TU.TURMA
	INNER JOIN LY_OFERTA_CURSO OC
		ON OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO
),
VALOR_CURRICULO AS (
	SELECT DISTINCT
		CR.CURSO,
		CR.TURNO,
		CR.CURRICULO,
		VA.SERVICO,
		VA.ANO,
		VA.PERIODO,
		VA.CUSTO_UNITARIO AS VALOR_CURSO
	FROM 
		LY_VALOR_SERV_PERIODO VA
	INNER JOIN LY_CURRICULO CR
		ON CR.SERVICO = VA.SERVICO
	INNER JOIN LY_OFERTA_CURSO OC
		ON OC.CURRICULO = CR.CURRICULO
		AND OC.ANO_INGRESSO = VA.ANO
		AND OC.PER_INGRESSO = VA.PERIODO
)


SELECT 
	UNID_RESPONSAVEL,
	CC.CURSO,
	CC.NOME_CURSO,
	CC.TIPO_COORD,
	CC.NOME_COORDENADOR,
	TU.TURMA,
	TU.ANO_INGRESSO AS ANO,
	TU.PER_INGRESSO AS PERIODO,
	VC.VALOR_CURSO
FROM 
	CURSO_COORDENADOR CC
INNER JOIN TURMA_OFERTA TU
	ON TU.CURSO = CC.CURSO
INNER JOIN VALOR_CURRICULO VC
	ON VC.CURSO = TU.CURSO
	AND VC.CURRICULO = TU.CURRICULO

GROUP BY UNID_RESPONSAVEL,
	CC.CURSO,
	CC.NOME_CURSO,
	CC.TIPO_COORD,
	CC.NOME_COORDENADOR,
	TU.TURMA,
	TU.ANO_INGRESSO,
	TU.PER_INGRESSO,
	VC.VALOR_CURSO

ORDER BY CC.CURSO