EXEC a_APoI_Ly_aluno ''
,'E202110004'							--	@aluno varchar(20), 
,'CEIN T 17'							--@concurso varchar(20), 
,'202110036'							--@candidato varchar(20), 
,'CEIN'									--@curso varchar(20),    
,'INTEGRAL'								--@turno varchar(20), 
,'CEIN-17'								--@curriculo varchar(20), 
,1										--@serie numeric(3), 
,'Levi Henry Murilo Gonçalves'			--@nome_compl varchar(100),    
,'Levi Henry Murilo Gonçalves'			--@nome_abrev varchar(50), 
,1900									--@anoconcl_2g numeric(4), 
,'Processo Seletivo'					--@tipo_ingresso varchar(20), 
,2021									--@ano_ingresso numeric(4),    
,1										--@sem_ingresso numeric(2), 
,'Ativo'								--@sit_aluno varchar(15), 
,NULL									--@cred_educativo varchar(1), 
,'CEINT T 17'							--@turma_pref varchar(20),    
,NULL									--@grupo varchar(20), 
,NULL									--@areacnpq varchar(20), 
,NULL									--@discipoutraserie varchar(1), 
,NULL	--@ref_aluno_ant varchar(20),    
,NULL	--@sit_aprov varchar(1), 
,NULL	--@cod_cartao varchar(20), 
,'2020-11-13 13:51:37.280'	--@dt_ingresso datetime, 
,NULL	--@e_mail_interno varchar(100),    
,NULL	--@num_chamada numeric(10), 
,NULL	--@curso_ant varchar(100), 
,'Paulista'	--@unidade_fisica varchar(20), 
,129202	--@pessoa numeric(10),    
,NULL	--@outra_faculdade varchar(100), 
,NULL	--@cidade_2g varchar(50), 
,NULL	--@pais_2g varchar(50), 
,NULL	--@creditos numeric(3),    
,NULL	--@obs_aluno_finan varchar(3000), 
,NULL	--@representante_turma varchar(1), 
,NULL	--@tipo_aluno varchar(50),    
,NULL	--@faculdade_conveniada varchar(20), 
,NULL	--@stamp_atualizacao datetime, 
,'ESPEC'	--@unidade_ensino varchar(20),    
,NULL	--@instituicao varchar(20), 
,NULL	--@classif_aluno varchar(40), 
,NULL	--@dist_aluno_unidade numeric(15), 
,NULL	--@nome_social varchar(100)    



	SELECT * FROM Ly_ALUNO WHERE UNIDADE_ENSINO = 'ESPEC' ORDER BY ALUNO DESC