/*######################################################
		DASHBOARD - MASSA DE DADOS 
######################################################*/

--SELECT * FROM VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR

--INDICE DE VAGAS PREENCHIDAS POR PERÍODO POR UNIDADE RESPONSAVEL

SELECT  
  
    CS.FACULDADE AS UNID_RESP,  
    CS.CURSO AS CURSO,  
    CS.NOME AS NOME_CURSO,  
	
    OC.OFERTA_DE_CURSO,
    CASE WHEN VT.TP_INGRESSO = 'VD' THEN 'Venda Direta'
		 WHEN VT.TP_INGRESSO = 'PS' THEN 'Processo Seletivo'
    END AS  TIPO_INGRESSO,
    ISNULL(OC.CONCURSO, 'VENDA DIRETA') AS CONCURSO,
    OC.DTINI AS DTINI_INSCRICAO,  
    OC.DTFIM AS DTFIM_INSCRICAO,  
    CASE  
        WHEN oc.DTFIM >= GETDATE() THEN 'Abertas'  
        WHEN oc.DTFIM <= GETDATE() THEN 'Encerradas'  
    END AS INSCRICOES,  
    OC.ANO_INGRESSO AS ANO_INICIO,  
    OC.PER_INGRESSO,  
    VT.TURMA,  
    VT.DT_INICIO,  
    VT.DT_FIM,  
    (SELECT TOP 1  
        CASE  
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND  
                VT.DT_INICIO > GETDATE() THEN 'Em Inscrição'  
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND  
                (GETDATE() BETWEEN VT.DT_INICIO AND VT.DT_FIM) THEN 'Em Andamento'  
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND  
                VT.DT_FIM <= GETDATE() THEN 'Concluido'  
            WHEN CLASSIFICACAO LIKE 'Cancel%' THEN 'Cancelada'  
        END  
    FROM LY_TURMA TU  
    WHERE TU.TURMA = VT.TURMA  
    AND TU.SERIE = 1  
    GROUP BY CLASSIFICACAO)  
    AS SITUACAO_TURMA,  
    (SELECT TOP 1  
        CASE  
            WHEN CLASSIFICACAO LIKE 'Cancel%' THEN 'Cancelada' 
            WHEN CLASSIFICACAO NOT LIKE 'Cancel%' AND  
                VT.DT_INICIO > GETDATE() THEN 'Em Inscrição'  
            ELSE 'Realizada'
        END  
    FROM LY_TURMA TU  
    WHERE TU.TURMA = VT.TURMA  
    AND TU.SERIE = 1  
    GROUP BY CLASSIFICACAO)  
    AS REALIZACAO,  
    (SELECT TOP 1 
		CASE WHEN CS.FACULDADE = 'PALES' THEN CS.VAGAS
		ELSE ISNULL(NUM_ALUNOS, CS.VAGAS)  
		END
    FROM LY_TURMA TU  
    WHERE TU.CURSO = CS.CURSO  
    AND TU.SERIE = 1  
    GROUP BY NUM_ALUNOS,  
             TURMA)  
    AS VAGAS_OFERECIDAS,
    ISNULL(CASE  
        WHEN OC.CONCURSO IS NULL THEN (SELECT  
                COUNT(ALUNO)  
            FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
            WHERE TURMA = VT.TURMA)  
        ELSE (SELECT  
                COUNT(CANDIDATO)  
            FROM LY_CANDIDATO CA  
            WHERE CA.CONCURSO = OC.CONCURSO  
            GROUP BY CA.CONCURSO)  
    END,0) AS TOTAL_INSCRITOS,
    
    (SELECT  
        COUNT(CA.CANDIDATO)  
    FROM LY_CANDIDATO CA  
    INNER JOIN FCAV_CANDIDATOS FC  
        ON FC.CANDIDATO = CA.CANDIDATO  
        AND FC.CONCURSO = CA.CONCURSO  
    WHERE CA.CONCURSO = OC.CONCURSO  
    AND SIT_CANDIDATO_VEST != 'Cancelado'  
    AND FC.CONVOCADO = '2')  
    AS RECUSADOS,  
    CASE  
    WHEN VT.UNIDADE_RESPONSAVEL IN ('PALES', 'ATUAL') THEN (SELECT  
            COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Matriculado'  
        AND TURMA = VT.TURMA)  
    ELSE (SELECT  
            COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Matriculado'  
        AND TIPO_INGRESSO IN ('Processo Seletivo', 'Inscricao_Site')  
        AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')  
        AND CANDIDATO IS NOT NULL  
        AND TURMA = VT.TURMA
        AND DT_MATRICULA <= VT.DT_INICIO)  
	END AS MATRICULADOS,
	
	CASE  
    WHEN VT.UNIDADE_RESPONSAVEL IN ('PALES', 'ATUAL') THEN (SELECT  
            COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Cancelado'  
        AND TURMA = VT.TURMA)  
    ELSE (SELECT  
           COUNT(ALUNO)  
        FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA  
        WHERE SIT_MATRICULA = 'Cancelado'  
        AND TIPO_INGRESSO IN ('Processo Seletivo', 'Inscricao_Site')  
        AND UNIDADE_RESPONSAVEL IN ('ESPEC', 'CAPAC')  
        AND CANDIDATO IS NOT NULL  
        AND TURMA = VT.TURMA
        AND DT_MATRICULA <= VT.DT_INICIO)  
	END +
	(SELECT  
        COUNT(CA.CANDIDATO)  
    FROM LY_CANDIDATO CA  
    WHERE CA.CONCURSO = VT.CONCURSO  
    AND SIT_CANDIDATO_VEST = 'Cancelado')  AS DESISTENTES,
	
	((SELECT 	
		COUNT(HC.ALUNO)
	FROM 
		LY_H_CURSOS_CONCL HC
		INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MP
			ON MP.ALUNO = HC.ALUNO
	WHERE
		HC.DT_REABERTURA IS NULL
		AND HC.DT_ENCERRAMENTO > VT.DT_INICIO
		AND MP.TURMA = VT.TURMA) 	
	+ ---soma alunos cancelados e trancados pós inicio da turma
	(SELECT
		COUNT(TR.ALUNO)
	 FROM
		LY_TRANC_INTERV_DATA TR
		INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MP
			ON MP.ALUNO = TR.ALUNO
	 WHERE 
		TR.DT_REABERTURA IS NULL
		AND TR.DT_INI > VT.DT_INICIO
		AND MP.TURMA = VT.TURMA)) AS EVADIDOS
    
FROM VW_FCAV_INI_FIM_CURSO_TURMA VT  
  
INNER JOIN LY_CURSO CS  
    ON CS.CURSO = VT.COD_CURSO  
  
INNER JOIN LY_COORDENACAO CO  
    ON CO.CURSO = CS.CURSO  
  
INNER JOIN LY_DOCENTE DO  
    ON DO.NUM_FUNC = CO.NUM_FUNC  
  
INNER JOIN LY_OFERTA_CURSO OC  
    ON OC.OFERTA_DE_CURSO = VT.OFERTA_DE_CURSO  
  
WHERE CO.TIPO_COORD = 'COORD'  
  
GROUP BY OC.ANO_INGRESSO,  
         OC.PER_INGRESSO,  
         OC.DTINI,  
         OC.DTFIM,
         OC.OFERTA_DE_CURSO,  
         OC.CONCURSO,  
  
         CS.FACULDADE,  
         CS.CURSO,  
         CS.NOME,  
         CS.VAGAS,  
  
         VT.TURMA,  
         VT.DT_INICIO,  
         VT.DT_FIM,  
         VT.UNIDADE_RESPONSAVEL,
         VT.TP_INGRESSO,
         VT.CONCURSO,
  
         DO.NOME_COMPL,  
         CO.TIPO_COORD
ORDER BY OC.ANO_INGRESSO, CS.FACULDADE, CS.CURSO, VT.TURMA, OC.OFERTA_DE_CURSO