select sum(VALOR_PAGAR) as PAGAR, SUM(ISNULL(VALOR_PAGO,0)) AS PAGO,UPPER(SITUACAO_BOLETO) as SITBOL
from VW_FCAV_EXTFIN_LY
WHERE CENTRO_DE_CUSTO = '511026518'
  and VALOR_PAGAR > 0
  AND DT_ENVIO_CONTAB IS NOT NULL
  AND SITUACAO_BOLETO = 'vENCIDO'
group by SITUACAO_BOLETO
