
SELECT DISTINCT
	AL.ALUNO,
	AL.NOME_COMPL,
	AL.SIT_ALUNO,
	AL.TURMA_PREF AS TURMA,
	pd.DATA_INSERCAO,
	PD.VALOR_TOTAL,
	CO.COBRANCA,
	co.DATA_DE_GERACAO,
	co.DATA_DE_VENCIMENTO,
	co.ESTORNO,
	co.DT_ESTORNO,
	BO.BOLETO,
	BO.DATA_PROC,
	PD.STATUS_PROCESSAMENTO,
	pd.MSG_ERRO_GERAL,
	PG.BANDEIRA,
	PG.FINAL_CARTAO,
	PG.VALOR,
	PG.ANO_VALIDADE,
	PG.MES_VALIDADE
FROM 
	LY_PEDIDO_PGTO PD
	LEFT JOIN LY_PEDIDO_PGTO_COBRANCAS PC
		ON PC.ID_PEDIDO_PGTO = PD.ID_PEDIDO_PGTO
	LEFT JOIN LY_COBRANCA CO
		ON CO.COBRANCA = PC.COBRANCA
	LEFT JOIN LY_ITEM_LANC IL
		ON IL.COBRANCA = CO.COBRANCA
	LEFT JOIN LY_BOLETO BO
		ON BO.BOLETO = IL.BOLETO
	LEFT JOIN LY_ALUNO AL
		ON AL.ALUNO = CO.ALUNO
	LEFT JOIN LY_PEDIDO_PGTO_CARTOES PG
		ON PC.COBRANCA = CO.COBRANCA
		AND PG.ID_PEDIDO_PGTO = PD.ID_PEDIDO_PGTO
WHERE 
	AL.NOME_COMPL = 'Alcimeire Alessandra Costa'
	--and STATUS_PROCESSAMENTO = 'Recusado'

order by DATA_INSERCAO