
SELECT 
	AL.ALUNO,
	AL.NOME_COMPL,
	AL.SIT_ALUNO,
	AL.TURMA_PREF AS TURMA,
	CO.COBRANCA,
	co.DATA_DE_VENCIMENTO,
	PD.VALOR_TOTAL,
	PD.STATUS_PROCESSAMENTO
FROM 
	LY_PEDIDO_PGTO PD
	INNER JOIN LY_PEDIDO_PGTO_COBRANCAS PC
		ON PC.ID_PEDIDO_PGTO = PD.ID_PEDIDO_PGTO
	INNER JOIN LY_COBRANCA CO
		ON CO.COBRANCA = PC.COBRANCA
	INNER JOIN LY_ALUNO AL
		ON AL.ALUNO = CO.ALUNO
WHERE 
	pd.ID_PEDIDO_PGTO = 11677
	PD.STATUS_PROCESSAMENTO = 'Pendente'
	AND NOT EXISTS (SELECT 1 FROM LY_ITEM_CRED IC
		WHERE IC.COBRANCA = CO.COBRANCA)