select 
	CASE WHEN CO.NOME_COMPL = 'Renato Moraes' THEN 'Renato de Oliveira Moraes'
	ELSE CO.NOME_COMPL
	END NOME_COORDENADOR,
	LOWER(CASE  WHEN DO.E_MAIL IS NULL THEN PE.E_MAIL
		ELSE DO.E_MAIL
	END) AS E_MAIL
from VW_FCAV_COORDENADOR_TURMA CO
INNER JOIN LY_DOCENTE DO 
	ON DO.NUM_FUNC = CO.NUM_FUNC
INNER JOIN LY_PESSOA PE
	ON PE.PESSOA = DO.PESSOA
WHERE
	(DT_FIM IS NULL OR DT_FIM >= GETDATE())
	AND TIPO_COORD = 'COORD'
	AND PE.E_MAIL IS NOT NULL
GROUP BY CO.NOME_COMPL, DO.E_MAIL, PE.E_MAIL