EXEC a_TAGS_CUSTOM_CONTRATO 'C201900009', 2019, 0, 561, 1957  

SELECT * FROM LY_CURRICULO_CONTRATO WHERE CURSO = 'CCGB' AND CURRICULO = 'CCGB MISTO C6'

SELECT * FROM LY_MATRICULA WHERE TURMA = 'CCGB T 52'

SELECT * FROM LY_OFERTA_CURSO WHERE CONCURSO = 'CCGB T 52'