
SELECT ALUNO, TURMA 
FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE SIT_MATRICULA = 'MATRICULADO' 
AND UNIDADE_RESPONSAVEL NOT IN ('ATUAL','PALES')
ORDER BY TURMA, ALUNO

SELECT CURSO, ALUNO, 
(SELECT 
 DBO.Decrypt(SENHA_TAC)
FROM 
	LY_PESSOA
WHERE
	LY_PESSOA.PESSOA = AL.PESSOA
) SENHA 
FROM LY_ALUNO AL
	INNER JOIN LY_PARTICIPACAO_QUEST PQ 
		ON PQ.CODIGO = AL.ALUNO
WHERE 
 PQ.DATA_PART IS NULL
and AL.ALUNO IN (SELECT ALUNO FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA WHERE TURMA in ('CEAI T 28','CEGP T 65','CCGB T 42', 'CCGP T 47') AND SIT_MATRICULA = 'MATRICULADO')

GROUP BY CURSO, ALUNO, PESSOA

SELECT 
	NOME_AVALIADO AS NOME_DOCENTE
FROM
	VW_FCAV_RESPOSTAS_AVAL_DOCENTE_DISCIPLINA
WHERE
	TIPO_AVALIADO = 'DOCENTE'
	AND TURMA = 'CCGB T 42'
	AND RESPOSTA IS NOT NULL
GROUP BY NOME_AVALIADO,AVALIADO

SELECT 
	DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	DI.INDICE_APROVACAO AS INDICE_APROVACAO_DISCIPLINA,
	DI.INDICE_REJEICAO AS INDICE_REJEICAO_DISCIPLINA,
	DO.INDICE_APROVACAO AS INDICE_APROVACAO_DOCENTE,
	DO.INDICE_REJEICAO AS INDICE_REJEICAO_DOCENTE,
	ISNULL(ID.INDICE_APROVACAO, 0) AS INDICE_APROVACAO_INFRA,
	ISNULL(ID.INDICE_REJEICAO, 0) AS INDICE_REJEICAO_INFRA
FROM 
	VW_FCAV_AVAL_DISCIPLINA_INDICES DI
	INNER JOIN VW_FCAV_AVAL_DOCENTE_INDICES DO
		ON DI.TURMA = DO.TURMA
		AND DI.DISCIPLINA = DO.DISCIPLINA
	LEFT JOIN VW_FCAV_AVAL_INFRA_INDICES ID
		ON ID.TURMA = DI.TURMA
GROUP BY
DI.CURSO,
	DI.TURMA,
	DI.DISCIPLINA,
	DI.NOME_DISCIPLINA,
	DO.NOME_DOCENTE,
	DI.INDICE_APROVACAO,
	DI.INDICE_REJEICAO,
	DO.INDICE_APROVACAO,
	DO.INDICE_REJEICAO ,
	ID.INDICE_APROVACAO,
	ID.INDICE_REJEICAO


SELECT * FROM VW_FCAV_CRONOGRAMA_TURMA_DOCENTE WHERE TURMA = 'CEGP T 65' AND NUM_FUNC IN (900043,900242)

SELECT DISTINCT A.NUM_FUNC  FROM   LY_AGENDA A,   LY_MATRICULA M  WHERE   A.ANO = M.ANO   AND A.SEMESTRE = M.SEMESTRE  AND A.DISCIPLINA = M.DISCIPLINA   AND A.TURMA = 'CEAI T 28'    AND M.SIT_MATRICULA = 'Matriculado'   AND NUM_FUNC IN (900043,83484) GROUP BY A.NUM_FUNC

SELECT A.DISCIPLINA FROM LY_AGENDA A,   LY_MATRICULA M  WHERE   A.ANO = M.ANO AND A.SEMESTRE = M.SEMESTRE AND A.DISCIPLINA = M.DISCIPLINA AND A.TURMA = 'CEAI T 28' AND M.SIT_MATRICULA = 'Matriculado' AND A.DISCIPLINA IN ('CEAI-CF','CEAI-EB') GROUP BY A.DISCIPLINA

SELECT  A.NUM_FUNC  FROM   LY_AGENDA A,   LY_MATRICULA M  WHERE   A.ANO = M.ANO       AND A.SEMESTRE = M.SEMESTRE       AND A.DISCIPLINA = M.DISCIPLINA      AND A.TURMA = 'CCGB T 42'  AND M.SIT_MATRICULA = 'Matriculado' AND NUM_FUNC IN (900001,90557)   GROUP BY A.NUM_FUNC

SELECT A.NUM_FUNC  FROM   LY_AGENDA A,   LY_MATRICULA M  WHERE   A.ANO = M.ANO       AND A.SEMESTRE = M.SEMESTRE       AND A.DISCIPLINA = M.DISCIPLINA       AND A.TURMA = 'CEGP T 65'   AND M.SIT_MATRICULA = 'Matriculado'  AND NUM_FUNC IN (900012, 900250) GROUP BY A.NUM_FUNC