
/*
	ATUALIZAÇÃO DO CAMPO SETOR PARA O PESSOAL DA EDUCACAO, DEVIDO AO FLUXO DE ATENDIMENTO ESTAR CONFIGURADO PARA SECR-ATEND
*/

UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'AtendApoUSP'
UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'SecrCurUSP'
UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'AtendApoPaulist'
UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'SecrCurPaulist'
UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'EduPaulista'
UPDATE HD_USUARIO SET SETOR = 'SECR-ATEND' WHERE SETOR = 'EduUSP'