SELECT	 ISNULL(CASE WHEN CO.GRUPO = '-CERT' or co.NOME_COMPL = 'José Joaquim do Amaral Ferreira' THEN 'Certificação'  
	   WHEN VT.UNIDADE_FISICA = 'Online' OR VT.UNIDADE_FISICA = 'Semipresencial' THEN 'Paulista'  
	  ELSE CO.UNID_FISICA  
	 END,'-') AS GRUPO_RESP,  
	ISNULL(CASE WHEN CS.FACULDADE = 'ATUAL' AND VT.UNIDADE_FISICA = 'USP' THEN 'DIFUSAO'  
	  ELSE CS.FACULDADE   
	 END, '-') AS UNID_RESP,   
    AL.CURSO,
    AL.TURMA,
	VT.DT_INICIO,
	vt.DT_FIM,
    AL.ALUNO,
    AL.NOME_COMPL,
    AL.FONE,
    AL.CELULAR,
    AL.E_MAIL,
    AL.SIT_MATRICULA,
    AL.TIPO_BOLSA,
    AL.NUM_BOLSA,
    AL.PERC_VALOR,
    CASE WHEN AL.PERC_VALOR = 'Percentual' THEN CAST(AL.VALOR AS decimal(10,2))*100
	END AS VALOR,
    AL.MOTIVO AS MOTIVO_BOLSA
	

FROM VW_FCAV_INFO_ALUNOS_LYCEUM AL
	INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
		ON VT.TURMA = AL.TURMA
	INNER JOIN LY_CURSO CS    
	    ON CS.CURSO = VT.CURSO    	    
	LEFT JOIN VW_FCAV_COORDENADOR_TURMA CO  
		ON CO.TURMA = VT.TURMA 
		AND CO.TIPO_COORD = 'COORD'
WHERE
	VT.UNIDADE_RESPONSAVEL NOT LIKE 'PALES'
GROUP BY AL.UNIDADE_RESPONSAVEL,
    AL.CURSO,
    AL.TURMA,
    AL.ALUNO,
    AL.NOME_COMPL,
    AL.FONE,
    AL.CELULAR,
    AL.E_MAIL,
    AL.SIT_MATRICULA,
    AL.TIPO_BOLSA,
    AL.NUM_BOLSA,
    AL.PERC_VALOR,
    AL.VALOR,
    AL.MOTIVO,
	CS.FACULDADE,
	CO.GRUPO,
	CO.NOME_COMPL,
	CO.UNID_FISICA,
	VT.UNIDADE_FISICA,
	VT.DT_INICIO,
	vt.DT_FIM
	
ORDER BY AL.UNIDADE_RESPONSAVEL,  AL.CURSO,  AL.TURMA