


SELECT ID_FILA_EVENTOS, DATA_INCLUSAO, SISTEMA_DESTINO,
	OBJETO, OPERACAO, CHAVE_1, CHAVE_2,
	DATA_INTEGRACAO,
	DATA_ERRO,
	MSG_ERRO 
FROM LY_INTEGRACAO_FILA_EVENTOS
WHERE OBJETO = 'INSCRICAO'
ORDER BY ID_FILA_EVENTOS DESC

select * from LY_INTEGRACAO_FILA_EVENTOS where DATA_INTEGRACAO is not null order by ID_FILA_EVENTOS desc
SELECT * FROM LY_INTEGRACAO_FILA_EVENTOS WHERE OBJETO = 'INSCRICAO' AND DATA_INTEGRACAO IS NULL AND DATA_ERRO IS NULL ORDER BY ID_FILA_EVENTOS DESC


select * from LY_INTEGRACAO_FILA_EVENTOS where MSG_ERRO like '%data%response%'order by ID_FILA_EVENTOS desc


UPDATE LY_INTEGRACAO_FILA_EVENTOS 
SET
	DATA_ERRO= NULL,
	MSG_ERRO = NULL
where 
	ID_FILA_EVENTOS in (select top 15 ID_FILA_EVENTOS from LY_INTEGRACAO_FILA_EVENTOS 
						where MSG_ERRO like 'Erro:%'order by ID_FILA_EVENTOS desc)

SELECT * FROM VW_integ_inscricao c  WHERE c.ID_FILA_EVENTOS = 1  AND c.DATA_INTEGRACAO IS NULL  AND c.DATA_ERRO IS NULL


SELECT distinct CHAVE_1 FROM LY_INTEGRACAO_FILA_EVENTOS  where MSG_ERRO like 'Erro:%'

select * from LY_CANDIDATO where CANDIDATO = '202000207'

SELECT * FROM VW_integ_inscricao c  WHERE c.ID_FILA_EVENTOS = 353  AND c.DATA_INTEGRACAO IS NULL  AND c.DATA_ERRO IS NULL 


SELECT          
    CONVERT( DATETIME, FORMAT( c.DT_INSCRICAO, 'yyyy-MM-dd', 'en-US' )) AS DT_INSCRICAO          
    , ife.ID_FILA_EVENTOS          
    , ife.CHAVE_1 AS CONCURSO         
    , ife.CHAVE_2 AS CANDIDATO  
 , ife.CHAVE_3 AS OFERTA  
    , ife.DATA_INCLUSAO                
    , ife.DATA_INTEGRACAO           
    , ife.DATA_ERRO          
    , ife.MSG_ERRO          
    , ISNULL(ife.IGNORAR, 'N') AS IGNORAR   
 , 'INSCRIÇÃO REALIZADA'AS FASE  
    , c.NOME_COMPL          
    , ISNULL(c.CPF, p.CPF) AS CPF          
    , c.E_MAIL   
 , p.FONE   
 , p.CELULAR  
 , o.CURSO  
    , o.TURMA  
 , o.VALOR_A_VISTA_ESTIMADO  
FROM LY_OPCOES_PROC_SELETIVO op          
 INNER JOIN LY_INTEGRACAO_FILA_EVENTOS ife WITH (NOLOCK)          
  ON op.CONCURSO = ife.CHAVE_1  AND          
  op.CANDIDATO = ife.CHAVE_2 AND  
  CONVERT(VARCHAR(50), op.OFERTA_DE_CURSO) = ife.CHAVE_3    
   INNER JOIN LY_OFERTA_CURSO o  WITH (NOLOCK)          
  ON o.OFERTA_DE_CURSO = op.OFERTA_DE_CURSO            
   INNER JOIN LY_CANDIDATO c  WITH (NOLOCK)           
  ON c.CANDIDATO = op.CANDIDATO AND   
  c.CONCURSO = op.CONCURSO                                       
   LEFT JOIN LY_PESSOA p  WITH (NOLOCK)          
  ON c.PESSOA = p.PESSOA   
WHERE  
 ife.SISTEMA_DESTINO = 'SharpSpring' AND ife.OBJETO = 'INSCRICAO'  
 --and  op.CANDIDATO = '202000207'
  order by DATA_INCLUSAO