SELECT 
	AG.AGENDA,
	TU.UNIDADE_RESPONSAVEL AS UNID_RESP,
	TU.CURSO,
	TU.TURMA,
	TU.DISCIPLINA,
	AG.ANO,
	AG.SEMESTRE,
	DO.NOME_COMPL AS DOCENTE,
	AG.FACULDADE AS	UNIDADE_FISICA,
	AG.DEPENDENCIA AS SALA,
	DATA AS DATA_AULA,
	CASE WHEN DIA_SEMANA = 1 THEN 'domingo'    
		 WHEN DIA_SEMANA = 2 THEN 'segunda-feira'    
		 WHEN DIA_SEMANA = 3 THEN 'terça-feira'    
		 WHEN DIA_SEMANA = 4 THEN 'quarta-feira'    
		 WHEN DIA_SEMANA = 5 THEN 'quinta-feira'    
		 WHEN DIA_SEMANA = 6 THEN 'sexta-feira'    
		 WHEN DIA_SEMANA = 7 THEN 'sábado'    
	END AS DIA_SEMANA,
	HORA_INICIO AS HORA_ENTRADA,    
	HORA_FIM AS HORA_SAIDA,    
	CASE WHEN EVENTO_CUMP = 'S' THEN 'SIM'
	ELSE 'NÃO' END AS AULDA_CUMPRIDA,
	CASE WHEN CANCELADA = 'S' THEN 'SIM'
	ELSE 'NÃO' END AS AULDA_CANCELADA

FROM LY_AGENDA AG
INNER JOIN LY_TURMA TU
	ON TU.TURMA = AG.TURMA
	AND TU.DISCIPLINA = AG.DISCIPLINA
	AND TU.ANO = AG.ANO
	AND TU.SEMESTRE = AG.SEMESTRE
INNER JOIN LY_DOCENTE DO
	ON DO.NUM_FUNC = AG.NUM_FUNC
WHERE AG.ANO = YEAR(GETDATE())
AND AG.FACULDADE = 'Paulista'
--AND DATA >= GETDATE()+1
GROUP BY 	DATA,
	HORA_INICIO,
	HORA_FIM,
	AG.AGENDA,
	TU.UNIDADE_RESPONSAVEL,
	TU.CURSO,
	TU.TURMA,
	TU.DISCIPLINA,
	AG.ANO,
	AG.SEMESTRE,
	DO.NUM_FUNC,
	DO.NOME_COMPL,
	AG.FACULDADE,
	AG.DEPENDENCIA,
	DIA_SEMANA,
	EVENTO_CUMP,
	CANCELADA