SELECT * FROM VW_FCAV_BOLETOS_EMITIDOS_CONTAB WHERE COBRANCA in (212441,212438)

select * from LY_ITEM_LANC where COBRANCA in (215942)
select * from LY_ITEM_LANC where COBRANCA in (216753)

INSERT INTO LY_ITEM_LANC 
(COBRANCA,ITEMCOBRANCA,LANC_DEB,CODIGO_LANC,ALUNO,NUM_BOLSA,RESP,MOTIVO_DESCONTO,DEVOLUCAO,
BOLETO,PARCELA,DATA,VALOR,DESCRICAO,ACORDO,COBRANCA_ORIG,ITEMCOBRANCA_ORIG,CENTRO_DE_CUSTO,
NATUREZA,ANO_REF_BOLSA,MES_REF_BOLSA,NUM_FINANCIAMENTO,ENCERR_PROCESSADO,EVENTO,EVENTO_COMPL,
DATA_CONTABIL,DT_ENVIO_CONTAB,CURSO,TURNO,CURRICULO,UNID_FISICA,DATA_DISPUTA,DATA_DECISAO_DISPUTA,
DISPUTA_ACEITA,DISPUTA_AJUSTADA,MOTIVO_DECISAO,LOTE_CONTABIL,DATA_PERDA,ORIGEM,ITEM_ESTORNADO)

			VALUES(
/*COBRANC*/	216753,
/*ITEMCOB*/	14,
			NULL,
/*C_LANC*/	'MS',
/*ALUNO*/	'E202010002',
			NULL,NULL,NULL,	NULL,
/*BOLETO*/	NULL,							
			14,	
			'2021-03-16 00:00:00.000',
			-48.22,
			'Estorno de Cobrança: Estorno de Acrescimo de IGPM',
			NULL, NULL,	NULL,	NULL,	
			'MBA-GP T 03',
			2021,
			3,
			NULL,
			'N',
			NULL,
			NULL,	
			NULL,	
/*ENVCONT*/ NULL,
			'MBA-GP',
			'INTEGRAL',
			'MBA-GP 2020/1',	
			'Paulista',
			NULL,
			NULL,	
			'N',	
			'N',
			NULL,	
			NULL,	
			NULL,	
			NULL,	
			10)