
declare @aluno varchar(20),
		@ano int,
		@periodo int,
		@chave int,
		@ofertaCurso int

SET @aluno = 'C202100049'
SET @ano = 2021
SET @periodo = 0
SET @chave = (SELECT CHAVE FROM LY_CURRICULO_CONTRATO WHERE CURSO = 'CCGBON' AND CURRICULO = 'CCGBON C1')
SET @ofertaCurso = (SELECT OFERTA_DE_CURSO FROM LY_OFERTA_CURSO WHERE CONCURSO = 'CCGBON T 68')


-- Entry-point responsável por trazer as informações que vão no contrato.
EXEC a_TAGS_CUSTOM_CONTRATO @aluno, @ano, @periodo, @chave, @ofertaCurso


SELECT * FROM LY_CURRICULO_CONTRATO WHERE CURSO = 'CCGBON' AND CURRICULO = 'CCGBON C1' 
SELECT * FROM LY_TURMA WHERE CURSO = 'CCGBON' AND CURRICULO = 'CCGBON C1'
SELECT * FROM LY_TURMA WHERE TURMA = 'CCGBON T 68'

SELECT * FROM VW_FCAV_CONFERENCIA_DE_CADASTRADOS_TURMAS WHERE TURMA = 'CCGBON T 68'
SELECT * FROM LY_GRADE WHERE CURSO = 'CCGBON' AND CURRICULO = 'CCGBON C1'
SELECT * FROM LY_OPCOES_OFERTA WHERE OFERTA_DE_CURSO = (SELECT OFERTA_DE_CURSO FROM LY_OFERTA_CURSO WHERE CONCURSO = 'CCGBON T 68')
SELECT * FROM VW_FCAV_INI_FIM_CURSO_TURMA WHERE CURSO = 'CCGBON' AND CURRICULO = 'CCGBON C1'