-- O FILTRO PARA O CADASTRO DAS TURMAS (NOVOS ALUNO) SERÁ INFORMADO PELO PESSOAL DA CODELY
-- Cadastro de Turmas: 
USE LYCEUM 
SELECT 
	CPF AS USERNAME, 
	NOME AS FIRSTNAME, 
	SOBRENOME AS LASTNAME, 
	E_MAIL AS EMAIL, 
	STATUS_MATRICULA 
FROM VW_FCAV_ALUNO_TURMA_DISCIPLINA 
WHERE 
	CURSO = 'CEQP' 
AND TURMA = '67' 
AND STATUS_MATRICULA = 'Matriculado' 

GROUP BY 
	CPF, NOME, SOBRENOME, E_MAIL, STATUS_MATRICULA 

	 
-- A EXTRAÇÃO DAS DISCIPLINAS OCORRE TODAS AS SEGUNDAS FEIRAS COM O PERIODO DA DATA ATUAL MAIS DUAS SEMANAS PARA FRENTE
-- Cadastro de Disciplinas: 
USE LYCEUM 
SELECT 
	CURSO, 
	TURMA, 
	ANO_SEMESTRE,
	DISCIPLINA,  
	NOME_DISCIPLINA, 
	CONVERT(varchar,DATA_INICIO_DISCIPLINA,103) AS DATA_INICIO_DISCIPLINA, 
	DOCENTE, 
	CPF, 
	E_MAIL,  
	SISTEMA
FROM VW_FCAV_DOCENTE_TURMA_DISCIPLINA 
WHERE 
	DATA_INICIO_DISCIPLINA >= CONVERT(date,GETDATE()-1)
AND DATA_INICIO_DISCIPLINA <= DATEADD(WEEK,2,CONVERT(date,GETDATE()))
AND TURMA = 'CCGB T 52'