IF EXISTS (SELECT
        *
    FROM SYS.procedures
    WHERE name = 'PR_FCAV_TURMA_DOCENTE')
    DROP PROCEDURE PR_FCAV_TURMA_DOCENTE
GO

CREATE PROCEDURE PR_FCAV_TURMA_DOCENTE (@turma varchar(20))
AS
    SET NOCOUNT ON
    BEGIN
      
        SELECT
			TD.NUM_FUNC,
			dbo.FN_FCAV_PRIMEIRA_MAIUSCULA(DO.NOME_COMPL) AS NOME_COMPL,
			TD.TURMA,
            TD.DISCIPLINA,
            DI.NOME_COMPL AS NOME_DISCIPLINA,
            ANO,
            PERIODO,
            AVALIACAO_DOCENTE_01,
            AVALIACAO_DOCENTE_02,
            MEDIA_DOCENTE,
            AVALIACAO_DISCIPLINA_01,
            AVALIACAO_DISCIPLINA_02,
            MEDIA_DISCIPLINA,
            TD.MEDIA_DOCENTE_DISCIPLINA,
            TD.COMENTARIO
        FROM FCAV_TURMA_DOCENTE TD
			INNER JOIN LY_DOCENTE DO
				ON DO.NUM_FUNC = TD.NUM_FUNC
			INNER JOIN LY_DISCIPLINA DI
				ON DI.DISCIPLINA = TD.DISCIPLINA
        WHERE TD.NUM_FUNC != 83484
			AND @turma	   = @turma
		ORDER BY 
			DO.NOME_COMPL,ANO DESC, PERIODO,TURMA,TD.DISCIPLINA

    END