
-----------------------------------------------------------------
--ASSOCIANDO O VALOR DO SERVIÇO DE MENSALIDADE AO PERÍODO LETIVO PARA GRUPO/SERVICO
INSERT INTO LY_GRUPO_SERV_PERIODO (SERVICO,GRUPO,ANO,PERIODO,CUSTO_UNITARIO)
SELECT 
	SERVICO_MENSALIDADE,
	GRUPO_TURMA,
	ANO_INGRESSO,
	PER_INGRESSO,
	VALOR_MENS
FROM
	VW_FCAV_CONFIG_PLANO_PGTO

SELECT * FROM LY_GRUPO_SERV_PERIODO