
----Insere plano pagamento padrão caso não exista

INSERT INTO LY_PLANOPAGTOPADRAO (PLANOPAG, MES_INICIAL, DIA_VENCIMENTO, DESC_PERC_VALOR, DESCONTO,
PERCENTENTRADA, NUM_PARCELAS, PADRAO, APLICABOLSA, APARECE_EXTRATO_ALUNO, IMPR_BOL_MATR_WEB,
PLANO_PADRAO_ONLINE, CURSO, TURNO, CURRICULO, DT_INI_VIGENCIA, DT_FIM_VIGENCIA)
    SELECT
        CP.PLANPAGPADRAO_NOVO,
        NULL,
        3,
        NULL,
        NULL,
        NULL,
        1,
        'N',
        'S',
        'S',
        'S',
        'N',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    FROM LY_PLANOPAGTOPADRAO PP
    INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
        ON CP.PARCELAS_MENS = PP.NUM_PARCELAS
        AND CP.PLANOPAG = PP.PLANOPAG

    WHERE NOT EXISTS (SELECT
        1
    FROM LY_PLANOPAGTOPADRAO
    WHERE REPLACE(PLANOPAG, ' ', '') = CP.PLANPAGPADRAO_NOVO)
    AND PP.PLANOPAG LIKE 'MENS%'
    GROUP BY PP.PLANOPAG,
             CP.PLANPAGPADRAO_NOVO
GO
----Consulta os planos ofertados sem a nova configuração.
SELECT
    TURMA,
    CP.OFERTA_DE_CURSO,
    PO.DESCRICAO,
    PO.MES_INICIAL,
    PO.NUM_PARCELAS,
    po.PLANOPAG,
    CP.MES_INI_FINAN_NOVO,
    CP.NUM_PARCELAS_NOVA,
    CP.PLANPAGPADRAO_NOVO
FROM LY_PLANOS_OFERTADOS PO
INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
    ON CP.OFERTA_DE_CURSO = PO.OFERTA_DE_CURSO
WHERE PO.PLANOPAG NOT LIKE 'AVISTA'

GO
----Atualiza os planos ofertados para nova configuração.

UPDATE LY_PLANOS_OFERTADOS
SET MES_INICIAL = CP.MES_INI_FINAN_NOVO,
    NUM_PARCELAS = CP.NUM_PARCELAS_NOVA,
    PLANOPAG = CP.PLANPAGPADRAO_NOVO
FROM LY_PLANOS_OFERTADOS PO
INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
    ON CP.OFERTA_DE_CURSO = PO.OFERTA_DE_CURSO
WHERE PO.PLANOPAG NOT LIKE 'AVISTA'

GO
----Consulta os planos ofertados para nova configuração.
SELECT
    TURMA,
    CP.OFERTA_DE_CURSO,
    PO.DESCRICAO,
    PO.MES_INICIAL,
    PO.NUM_PARCELAS,
    po.PLANOPAG,
    CP.MES_INI_FINAN_NOVO,
    CP.NUM_PARCELAS_NOVA,
    CP.PLANPAGPADRAO_NOVO
FROM LY_PLANOS_OFERTADOS PO
INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
    ON CP.OFERTA_DE_CURSO = PO.OFERTA_DE_CURSO
WHERE PO.PLANOPAG NOT LIKE 'AVISTA'

GO