---FACULDADES E CURSOS COM MATRICULA AVULSA
SELECT
	OFU.FACULDADE,
	OFC.CURSO,
	OPF.OPCAO,
	OPF.ANO,
	OPF.PERIODO,
	OPF.MATRICULA_AVULSA
FROM 
	LY_OPCOES_FINAN OPF
	LEFT JOIN LY_OPCOES_FINAN_UNID OFU
		ON OFU.OPCAO = OPF.OPCAO
	
	LEFT JOIN LY_OPCOES_FINAN_CURSO OFC
		ON OFC.OPCAO = OPF.OPCAO
WHERE
	OPF.ANO >= 2016
	AND OPF.MATRICULA_AVULSA = 'S'

---DESABILITAR MATRICULA AVULSA
UPDATE LY_OPCOES_FINAN
SET
	MATRICULA_AVULSA = 'N'
FROM
	LY_OPCOES_FINAN OPF
	LEFT JOIN LY_OPCOES_FINAN_UNID OFU
		ON OFU.OPCAO = OPF.OPCAO
	
	LEFT JOIN LY_OPCOES_FINAN_CURSO OFC
		ON OFC.OPCAO = OPF.OPCAO
WHERE
	OPF.ANO >= 2016
	AND OPF.MATRICULA_AVULSA = 'S'
 
	
	