
--------------------------------------------            
    --DEFINE O GRUPO DE ALUNO           

    UPDATE LY_ALUNO
    SET 
		GRUPO = CP.GRUPO_TURMA       
    FROM	
		LY_ALUNO AL
		INNER JOIN VW_MATRICULA_E_PRE_MATRICULA MP
			ON MP.ALUNO = AL.ALUNO
		INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
			ON CP.TURMA = MP.TURMA
    WHERE 
		CP.DT_INI_TURMA <= GETDATE()
		
SELECT
	AL.ALUNO,
	AL.GRUPO,
	MP.TURMA
FROM	
	LY_ALUNO AL
	INNER JOIN VW_MATRICULA_E_PRE_MATRICULA MP
		ON MP.ALUNO = AL.ALUNO
	INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
		ON CP.TURMA = MP.TURMA