------------------------------------------------------------------------------------
--DELETAR OS CURSOS QUE ESTÃO COM O SERVIÇO DE MATRICULA ASSOCIADO.
------------------------------------------------------------------------------------
DELETE LY_SERVICO_MATRICULA 
WHERE SERVICO IN (SELECT
	SM.SERVICO
FROM
	LY_SERVICO_MATRICULA SM
	INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
		ON CP.SERVICO_MATRICULA = SM.SERVICO)
	AND
	ANO >= 2016


SELECT
	SM.*
FROM
	LY_SERVICO_MATRICULA SM
	INNER JOIN VW_FCAV_CONFIG_PLANO_PGTO CP
		ON CP.SERVICO_MATRICULA = SM.SERVICO
WHERE
	ANO >= 2016
	