CREATE VIEW VW_FCAV_RELAT_TAXA_FCAV  
AS  
WITH TITULO_TAXA_CT2 AS (  
SELECT CT2_VALOR,   
 SUBSTRING(CT2_HIST, 9, (CHARINDEX(' ',CT2_HIST,9) - 9)) AS TITULO,  
 CT2_HIST,  
 CT2_DATA  
FROM CT2010   
WHERE D_E_L_E_T_ = ''  
AND CT2_DATA > '20180101'  
AND CT2_HIST LIKE 'TX FCAV%'  
AND CT2_DEBITO = '31102032' AND CT2_CREDIT = '31102031'   
  
UNION ALL --AND CT2_CCC = '050'  
SELECT CT2_VALOR,   
 SUBSTRING(CT2_HIST, 11, (CHARINDEX(' ',CT2_HIST,11) - 11)) AS TITULO,  
 CT2_HIST,  
 CT2_DATA  
FROM CT2010   
WHERE D_E_L_E_T_ = ''  
AND CT2_DATA > '20180101'  
AND CT2_HIST LIKE 'Cobranca: %'  
AND CT2_DEBITO = '31102032' AND CT2_CREDIT = '31102031'   
)  
  
-- BASE LYCEUM PARA RELATORIO COM TAXA FCAV  
SELECT DISTINCT  
 SUBSTRING(CT2_CCD,1,3)     AS ATIV,   
 CTT_CUSTO        AS CC,  
 CTT_DESC01        AS DESC_CC,  
 --  
 CASE WHEN CT2_CCD LIKE '5%' THEN '13007094-3'   -- CURSOS DE ESPECIALIZAÇÃO  
   WHEN CT2_CCD LIKE '6%' THEN '13007096-7'   -- CURSOS DE CAPACITAÇÃO  
   WHEN CT2_CCD LIKE '416%' THEN '13007080-2' -- CURSOS DE QUALIDADE  
   WHEN CT2_CCD LIKE '4%' THEN '13007096-7'   -- CURSOS DE ATUALIZAÇÃO  
 ELSE 'NAO_IDENTIF'  
   END        AS CONTA_BANCARIA,  
 --  
 A3_COD         AS VENDEDOR,   
 A3_NREDUZ        AS DESC_TAXA,  
 SUBSTRING(CT2010.CT2_HIST, 11, (CHARINDEX(' ',CT2010.CT2_HIST,11) - 11)) AS COB_TITULO,  
 'LYCEUM'        AS RAZAO_SOCIAL,  
 CAST(FCAD.DATA_DE_PAGAMENTO AS DATE) AS DT_BAIXA,  
 CT2010.CT2_VALOR      AS VL_COMISSAO,  
 FCAD.VALOR_PAGO       AS VL_BASE_COMIS,  
 CT2.CT2_VALOR       AS VL_TAXA_CONTAB,  
 FCAD.NOME_COMPL       AS DESC_PEDIDO,  
 ''          AS DESC_NOTA --(NÃO NECESSARIO PARA O LYCEUM)  
FROM  
 CT2010   
 INNER JOIN CTT010 ON CT2_CCD = CTT_CUSTO  
 INNER JOIN SA3010 ON CTT_FV_VD1 = A3_COD  
 INNER JOIN LYCEUM.dbo.VW_FCAV_EXTRATO_FINANCEIRO2 AS FCAD ON (RTRIM(SUBSTRING(CT2_HIST,11,6)) COLLATE Latin1_General_CI_AI = (CAST(FCAD.COBRANCA AS VARCHAR)))  
 INNER JOIN TITULO_TAXA_CT2  AS CT2 ON FCAD.COBRANCA = CT2.TITULO  
WHERE CT2010.D_E_L_E_T_ = ''  
AND (CT2010.CT2_HIST LIKE 'Cobranca:%' AND CT2010.CT2_HIST LIKE '%TAXA FCAV')  
--AND CT2_CCD <> '050'  
AND CT2010.CT2_DATA >= '20180101'  
--AND FCAD.CENTRO_DE_CUSTO = '519010118'  
UNION ALL  
  
-- BASE PROTHEUS PARA RELATORIO COM TAXA FCAV  
SELECT  
 E3_PREFIXO        AS ATIV,   
 CTT_CUSTO        AS CC,  
 CTT_DESC01        AS DESC_CC,  
 E3_FV_CTA        AS CONTA_BANCARIA,  
 A3_COD         AS VENDEDOR,   
 A3_NREDUZ        AS DESC_TAXA,  
 E3_NUM         AS COB_TITULO,  
 A1_NREDUZ        AS RAZAO_SOCIAL,  
 CAST(E3_EMISSAO COLLATE Latin1_General_CI_AI AS DATE) AS DT_BAIXA,  
 E3_COMIS        AS VL_COMISSAO,  
 E3_BASE         AS VL_BASE_COMIS,  
 CT2.CT2_VALOR       AS VL_TAXA_CONTAB,  
 ISNULL(  
 (SELECT TOP 1 SC6.C6_DESCRI FROM SC6010 SC6  
  WHERE E3_PEDIDO = C6_NUM AND E1_NUM = C6_NOTA  
  ORDER BY SC6.C6_ITEM ),'Título sem pedido')  
 COLLATE Latin1_General_CI_AI    AS DESC_PEDIDO,  
 ISNULL(  
 (SELECT TOP 1 SC6_2.C6_DESC FROM SC6010 SC6_2  
  WHERE E3_PEDIDO = C6_NUM AND E1_NUM = C6_NOTA  
  ORDER BY SC6_2.C6_ITEM ),'Título sem NF')  
           AS DESC_NOTA  
FROM  
 SE3010  
 INNER JOIN CTT010 ON E3_FV_CC = CTT_CUSTO  
 INNER JOIN SA3010 ON E3_VEND = A3_COD  
 INNER JOIN SE1010 ON E3_PREFIXO = E1_PREFIXO AND E3_NUM = E1_NUM AND E3_PARCELA = E1_PARCELA AND E3_TIPO = E1_TIPO AND E3_CODCLI = E1_CLIENTE AND E3_VEND = E1_VEND1  
 INNER JOIN SA1010 ON E3_CODCLI = A1_COD AND E3_LOJA = A1_LOJA  
 left outer JOIN TITULO_TAXA_CT2  AS CT2 ON E1_NUM = CT2.TITULO AND E3_EMISSAO = CT2.CT2_DATA  
  
WHERE SE3010.D_E_L_E_T_ = ''  
AND CTT010.D_E_L_E_T_ = ''  
AND SA3010.D_E_L_E_T_ = ''  
AND SE1010.D_E_L_E_T_ = ''  
AND SA1010.D_E_L_E_T_ = ''  
AND E3_EMISSAO >= '20180101'  