USE LYCEUM
GO


if OBJECT_ID('TempDB.dbo.#lyc_sa1') IS NOT NULL
	begin
		DROP TABLE #lyc_sa1
		--print ('Tabela temporária #lyc_sa1 removida.')
	end
  
DECLARE @DATA_INI DATE
DECLARE @DATA_FIM DATE   

SET @DATA_INI = cast((GETDATE()- 90) as date)
SET @DATA_FIM = cast((GETDATE()+ 90) as date) 


SELECT DISTINCT
 ISNULL (CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END,'')					AS COD_CAV,  
  
 ISNULL (RESP.CPF_TITULAR,'')					AS CPF,  
 ISNULL (RESP.CGC_TITULAR,'')					AS CNPJ,  
 '01'											AS LOJA,  
 ISNULL 
	(REPLACE(CONVERT(VARCHAR,ltrim(RESP.TITULAR),40),';',',')
		,'')									AS NOME,
 ISNULL 
	(REPLACE(CONVERT(VARCHAR,ltrim(RESP.TITULAR),20),';',',')
		,'')									AS NOME_FANT,  
 ISNULL 
	(REPLACE((LTRIM(RESP.ENDERECO)+', '+RESP.END_NUM),';',',') 
		,'')									AS ENDERECO,  
 'F'											AS TIPO_CLI,  
 ISNULL (CASE WHEN MUN.UF = '00' THEN 'SP'
			ELSE MUN.UF END ,'')				AS ESTADO,  
 ISNULL (REPLACE(MUN.NOME,';',','),'')			AS CIDADE,  
 
 ISNULL (RESP.CEP ,'')							AS CEP,  
 ISNULL (CASE WHEN RESP.CEP = '00000000' THEN 'NAO INFORMADO'
			ELSE REPLACE(RESP.BAIRRO,';',',')END 
			,'')								AS BAIRRO,  
 ISNULL 
	(REPLACE(CONVERT(VARCHAR,ltrim(RESP.TITULAR),40),';',',')
		,'')									AS CONTATO,  
 ISNULL (CASE WHEN RESP.CPF_TITULAR IS NULL THEN '501'  
			ELSE '504' END,'')					AS NATUREZA  
  
 INTO #LYC_SA1
FROM  
  LY_ALUNO AS ALU  
 LEFT JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 LEFT JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 LEFT JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 LEFT JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA )--AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 LEFT JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 LEFT OUTER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN HADES.dbo.HD_MUNICIPIO AS MUN ON (RESP.END_MUNICIPIO = MUN.MUNICIPIO)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA) -- OR T.TURMA = FCAD.TURMA OR HIST.TURMA = FCAD.TURMA) 
  
WHERE  
-- *** SE CASO NÃO HOUVER REGISTROS DE CRÉDITOS, O FILTRO SERÁ NO FATURAMENTO  
--ALU.ALUNO = 'C201700389'
 ILAN.DATA >= @DATA_INI  
AND ILAN.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
  
--  ***** FINAL DO COMENTÁRIO DOS DADOS DA SA1  
  


-- ******** ABAIXO - AREA DE TESTES  ***********  

SELECT 
	ls.*
FROM #LYC_SA1 LS

where not exists( SELECT A1_CGC FROM DADOSADVP12.dbo.SA1010 SA
		where ls.COD_CAV = sa.A1_CGC collate Latin1_General_CI_AI)

drop table #LYC_SA1