USE LYCEUM
GO
  
DECLARE @DATA_INI DATE
DECLARE @DATA_FIM DATE  


SET @DATA_INI = cast(GETDATE()- 90 as date)
SET @DATA_FIM = cast(GETDATE() as date)
    
BEGIN

--REMOVE TABELAS TEMPORARIAS EXISTENTEs
begin
	if OBJECT_ID('TempDB.dbo.#FCAV_IMPCONT_1') IS NOT NULL
	begin
		DROP TABLE #FCAV_IMPCONT_1
		print ('Tabela temporária #FCAV_IMPCONT_1 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#FCAV_IMPCONT_2') IS NOT NULL
	begin
		DROP TABLE #FCAV_IMPCONT_2
		print ('Tabela temporária #FCAV_IMPCONT_2 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#FCAV_IMPCONT_3') IS NOT NULL
	begin
		DROP TABLE #FCAV_IMPCONT_3
		print ('Tabela temporária #FCAV_IMPCONT_3 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#FCAV_IMPCONT_4') IS NOT NULL
	begin
		DROP TABLE #FCAV_IMPCONT_4
		print ('Tabela temporária #FCAV_IMPCONT_4 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#FCAV_IMPCONT_5') IS NOT NULL
	begin
		DROP TABLE #FCAV_IMPCONT_5
		print ('Tabela temporária #FCAV_IMPCONT_5 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#ULT_DOC_CT2') IS NOT NULL
	begin
		DROP TABLE #ULT_DOC_CT2
		print ('Tabela temporária #ULT_DOC_CT2 removida.')
	end

	if OBJECT_ID('TempDB.dbo.#TMP_IMPCONT_CRED') IS NOT NULL
	begin
		DROP TABLE #TMP_IMPCONT_CRED
		print ('Tabela temporária #TMP_IMPCONT_CRED removida.')
	end
end
--FIM

UPDATE LY_ITEM_CRED
SET DESCRICAO = 'Desconto Concedido'
WHERE 
DESCRICAO IS NULL
AND TIPODESCONTO = 'Concedido'

UPDATE LY_ITEM_CRED
SET DESCRICAO = 'Acréscimo'
WHERE 
DESCRICAO IS NULL
AND (TIPODESCONTO = 'Acréscimo' 
	OR TIPO_ENCARGO = 'Acréscimo')

-----alterado por Gabriel
--UPDATE LY_ITEM_CRED-- WHERE DESCRICAO = 'Ajuste de Titulo'
--SET DESCRICAO = NULL
--WHERE 
--DESCRICAO  = 'Ajuste de titulo' --IS NULL
--AND TIPO_ENCARGO = 'AJUSTE'
--AND 

UPDATE LY_ITEM_LANC
SET DT_ENVIO_CONTAB = GETDATE()
WHERE DESCRICAO  = 'Acrescimo de IGPM'
AND VALOR  < '0.01'
AND DATA BETWEEN @DATA_INI AND @DATA_FIM

--------------------------------------------------------------

-- Este bloco foi comentado, pois o Ajuste de IGPM Bolsa é sempre negativo 
-- e precisa ser importado.
-- verificar chamado 9763

--UPDATE LY_ITEM_LANC
--SET DT_ENVIO_CONTAB = GETDATE()
--WHERE DESCRICAO  = 'Ajuste de IGPM Bolsa'
--AND VALOR  < '0.01'
--AND DATA BETWEEN @DATA_INI AND @DATA_FIM

-------------------------------------------------------------- 
  
-- CURSOR PARA UNIFICAÇÃO DAS DATAS NA TABELA LY_ITEM_CRED EVITANDO QUE JUROS E MULTAS
-- FIQUEM EM UMA DATA E O PAGAMENTO EM OUTRA, SITUAÇÃO PROVENIENTE DE ARRASTOS DE BOLETO.
DECLARE @COBRANCA VARCHAR(10)


-- ************************* REMOÇÃO DO CURSOR PARA UNIFICAÇÃO DA DATA DOS ITENS ****************************


--DECLARE CURSOR_DATA CURSOR FOR

--SELECT COBRANCA
--FROM LY_ITEM_CRED
--WHERE  
--	DATA >= DATEADD(MONTH,-3,@DATA_INI) 
--AND DATA <= DATEADD(MONTH,1,@data_fim)
--GROUP BY COBRANCA
--HAVING COUNT(ITEMCRED)>'1'

--OPEN CURSOR_DATA
--FETCH NEXT FROM CURSOR_DATA INTO @COBRANCA
--WHILE @@FETCH_STATUS = 0
--BEGIN
--	UPDATE LY_ITEM_CRED
--	SET DATA = (
--				SELECT TOP 1 DATA FROM LY_ITEM_CRED WHERE COBRANCA = @COBRANCA ORDER BY DATA DESC 
--				)
--	WHERE COBRANCA = @COBRANCA

--FETCH NEXT FROM CURSOR_DATA INTO @COBRANCA
--END

--CLOSE CURSOR_DATA
--DEALLOCATE CURSOR_DATA


-- *** SELECT PARA IMPORTACAO DOS DADOS CONTABEIS DE FATURAMENTO.  
-- *** TODOS ESTÃO INDO COMO "PARTIDA DOBRADA", TANTO O FATURAMENTO DOS TÍTULOS E DESCONTOS.  
  
SELECT DISTINCT  
-- '1 - FAT',
 ILAN.DATA AS DATA_PROC,  
 '008870' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ILAN.ITEMCOBRANCA AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,  
 CASE 
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '31402003' 
   WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '31401001'  
   WHEN ILAN.DESCRICAO LIKE 'BOLSA%' THEN '31401003'
   WHEN ILAN.DESCRICAO LIKE '%IGPM%BOLSA%' THEN '31401003'
   WHEN ILAN.DESCRICAO LIKE '% do Acordo %' THEN '11204008'  
   ELSE '11204001' END AS CONTA_DEB,  
 CASE 
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'BOLSA%' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE '%IGPM%BOLSA%' THEN '11204001' 
   WHEN ILAN.DESCRICAO LIKE '% do Acordo %' THEN '11204005'  
   WHEN CUR.FACULDADE = 'ESPEC' THEN '31102024'  
  ELSE '31102025' END AS CONTA_CRED,  
   
 REPLACE (ILAN.VALOR,'-','') AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+PES.NOME_COMPL AS ORIGEM,  
  --CASE WHEN ILAN.MOTIVO_DESCONTO = 'Estorno'   
  --THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR)  
  --ELSE 
  'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ISNULL(ILAN.DESCRICAO,'Sem Descricao de baixa'),';',',') AS VARCHAR) 
  --END 
  AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 BOL.BOLETO AS IMP_BOLETO,  
 COB.COBRANCA AS IMP_COBRANCA  
  
INTO #FCAV_IMPCONT_1  
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_CURSO AS CUR ON (ILAN.CURSO = CUR.CURSO)
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)

WHERE   
 ILAN.DATA >= @DATA_INI  
AND ILAN.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ILAN.DT_ENVIO_CONTAB IS NULL
AND ILAN.ITEM_ESTORNADO IS NULL 
-- AND (ILAN.MOTIVO_DESCONTO != 'Estorno'  or ILAN.CODIGO_LANC = 'ACORDO')
-- AND ILAN.DESCRICAO NOT LIKE '%REMOCAO%' -- Retirado essa regra para atender a solicitação do David - chamado 42535

UNION ALL
  
-- BLOCO PARA TRAZER OS ESTORNOS FEITOS NA ITEM_LANC EXCLUSIVAMENTE  
SELECT DISTINCT  
-- '2 - FAT',
 ILAN.DATA AS DATA_PROC,  
 '008870' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ILAN.ITEMCOBRANCA AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,  
 CASE  WHEN CUR.FACULDADE = 'ESPEC' THEN '31401002'
	WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '11204001' 
 ELSE '31402002' END AS CONTA_DEB,  
 CASE WHEN ILAN.DESCRICAO LIKE 'DESCONTO%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'Estorno de Cobrança: Estorno de Bolsa%' THEN '11204001'  
   WHEN ILAN.DESCRICAO LIKE 'Estorno de Cobrança: Estorno de Desconto%' THEN '11204001'  
   WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' THEN '31402003'   
  ELSE '11204001' END AS CONTA_CRED,  
   
 REPLACE (ILAN.VALOR,'-','') AS VALOR,  
 'Titulo Rem Estorno'+' - '+PES.NOME_COMPL AS ORIGEM,  
 CASE 
	WHEN ILAN.DESCRICAO LIKE '%Estorno de Desconto%' 
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Estorno de Desconto'  
	WHEN ILAN.MOTIVO_DESCONTO = 'Estorno'   
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR)  
	WHEN ILAN.MOTIVO_DESCONTO = 'Voucher' and ILAN.ITEM_ESTORNADO is not null  
		THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Estorno de '+CAST(ILAN.MOTIVO_DESCONTO AS VARCHAR) 
	ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ISNULL(ILAN.DESCRICAO,'Estorno'),';',',') AS VARCHAR) 
	END AS HISTORICO,  
	
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 BOL.BOLETO AS IMP_BOLETO,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_CURSO AS CUR ON (ILAN.CURSO = CUR.CURSO)
 LEFT OUTER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
WHERE   
 ILAN.DATA >= @DATA_INI  
 AND ILAN.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
 AND ILAN.DT_ENVIO_CONTAB IS NULL
 AND COB.ESTORNO = 'S' AND ILAN.ITEM_ESTORNADO > 0 
 AND (ILAN.DESCRICAO like '%estorno%' OR ILAN.MOTIVO_DESCONTO = 'Estorno')
 --AND CAST(COB.COBRANCA AS VARCHAR) NOT IN (SELECT VW.COBRANCA FROM DADOSADVP12.dbo.VW_FCAV_CT2LANCTO AS VW WHERE VW.COBRANCA = COB.COBRANCA AND VW.HIST LIKE '%Estorno%') 

ORDER BY ILAN.DATA  
  
  
-- *** SELECT PARA IMPORTACAO DOS DADOS CONTABEIS DE CREDITO (PAGAMENTOS).  
-- *** NENHUM DELES SERÁ COMO "PARTIDA DOBRADA" E TODOS PRECISAM DE REGISTROS DE CREDITO E DEBITO.  
  
SELECT DISTINCT  
-- '01 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
    
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  --WHEN ICRED.DESCRICAO like 'Cart%'		 -- Pagamento por cartão de crédito
  --THEN '1' 
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Desconto%'  --OR ICRED.TIPODESCONTO IS NOT NULL-- Descontos concedidos   
  THEN '1'  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno   
  THEN '1'
  WHEN ICRED.TIPODESCONTO = 'Concedido'-- Descontos concedidos   
  THEN '1'  
  ELSE '2' END AS TIPO_LANC,   
   
 CASE 
   WHEN ICRED.DESCRICAO like '%7080-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102004'
  WHEN ICRED.DESCRICAO like '%4436-7%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102013'
  WHEN ICRED.DESCRICAO like '%18605-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102018'
  WHEN ICRED.DESCRICAO like '%44537-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102021'
  WHEN ICRED.DESCRICAO like '%50904-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102024'
  WHEN ICRED.DESCRICAO like '%57611-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102025'
  WHEN ICRED.DESCRICAO like '%57611-6%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102025'
  WHEN ICRED.DESCRICAO like '%25373-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102032'
  WHEN ICRED.DESCRICAO like '%68-X%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102035'
  WHEN ICRED.DESCRICAO like '%69-8%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102036'
  WHEN ICRED.DESCRICAO like '%98-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102038'
  WHEN ICRED.DESCRICAO like '%34700-0%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102043'
  WHEN ICRED.DESCRICAO like '%34701-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102044'
  WHEN ICRED.DESCRICAO like '%37570-5%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102049'
  WHEN ICRED.DESCRICAO like '%102002-1%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102053'
  WHEN ICRED.DESCRICAO like '%27217-5%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102075'
  WHEN ICRED.DESCRICAO like '%7798-8%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102077'
  WHEN ICRED.DESCRICAO like '%7094-3%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102094'
  WHEN ICRED.DESCRICAO like '%7095-0%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102095'
  WHEN ICRED.DESCRICAO like '%7096-7%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102096'
  WHEN ICRED.DESCRICAO like '%7132-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102098'
  WHEN ICRED.DESCRICAO like '%29322-9%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102122'
  WHEN ICRED.DESCRICAO like '%6324-2%' -- Depósito feito em conta corrente e direcionado para a conta contabil correta
  THEN '11102123'
 
  WHEN ICRED.DESCRICAO LIKE 'Desc%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN '51201002'  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno  
  THEN '31401004'
  
  WHEN BOL.CONTA_BANCO = '130050062' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta   
  THEN '11102001'  
  WHEN BOL.CONTA_BANCO = '130070943' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102094'  
  WHEN BOL.CONTA_BANCO = '130070967' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102096'  
  WHEN BOL.CONTA_BANCO = '130071322' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102098'  
  WHEN BOL.CONTA_BANCO = '130070802' AND ICRED.DESCRICAO NOT IN ('Encargo do tipo: Juros', 'Encargo do tipo: Multa')-- Direcionamento para conta contábil correta
  THEN '11102004'  
    
  WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN '11102001'  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Baixa Manual  
  THEN '11102001'  

  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN '11102001'  
  
  WHEN ICRED.TIPODESCONTO = 'Concedido'
  THEN '51201002'
  
  ELSE NULL END AS CONTA_DEB,  
 CASE WHEN ICRED.DESCRICAO LIKE 'Encargo do tipo%'  
  THEN '51101004'   
  WHEN ICRED.DESCRICAO LIKE 'Desc%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Baixa Manual  
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Estorno%' -- Estorno  
  THEN NULL  
  WHEN ICRED.TIPO_ENCARGO like 'Custas%' -- Custas de Agência de Cobrança  
  THEN '31501002'  
  WHEN ICRED.TIPO_ENCARGO like 'Honor%' -- Custas de Agência de Cobrança  
  THEN '31501002'  
  
  WHEN ICRED.TIPODESCONTO = 'Concedido'
  THEN '51201002'
  
  ELSE '11204001' END AS CONTA_CRED,  
 REPLACE (ICRED.VALOR,'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Desconto Concedido'
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto'
  WHEN ICRED.TIPODESCONTO = 'Concedido' THEN 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Desconto Concedido'   
  ELSE 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - '+CAST(REPLACE(ICRED.DESCRICAO,';',',') AS VARCHAR) END AS HISTORICO,  
  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CENTRO_CUSTO  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CENTRO_CUSTO  
  ELSE NULL END AS CC_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL 
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL 
  WHEN ICRED.TIPO_ENCARGO like 'Honor%' -- CC para custas de Agência de Cobrança  
  THEN '051'
  ELSE FCAD.CENTRO_CUSTO END AS CC_CRED,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CENTRO_ATIV  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CENTRO_ATIV  
  ELSE NULL END AS ITEM_CONTAB_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL 
  ELSE FCAD.CENTRO_ATIV END AS ITEM_CONTAB_CRED,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN FCAD.CLASSE_VALOR  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN FCAD.CLASSE_VALOR  
  ELSE NULL END AS CLASSE_VALOR_DEB,  
 CASE WHEN ICRED.DESCRICAO like 'Credito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO like 'Pagamento%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL
  WHEN ICRED.DESCRICAO like 'Deposito%' -- Crédito Bancário ou crédito de depósito   
  THEN NULL  
  WHEN ICRED.DESCRICAO LIKE 'DESCONTO%' OR ICRED.TIPODESCONTO IS NOT NULL  
  THEN NULL  
  WHEN ICRED.TIPODESCONTO = 'Concedido' 
  THEN NULL
  ELSE FCAD.CLASSE_VALOR END AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA

 INTO #FCAV_IMPCONT_2
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND ICRED.DESCRICAO NOT LIKE 'Cart%'
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (199695,199962,199311,200407,201080))
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

UNION ALL


-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR ORIGINAL DO PAGAMENTO,  
-- *** POR EXEMPLO, SE HOUVE UM PAGAMENTO EM ATRASO, O LYCEUM TRARÁ OS ENCARGOS E O VALOR PAGO,  
-- *** MAS NÃO O VALOR ORIGINAL, ENTÃO ESSE SELECT É PARA ISSO.  
  
SELECT DISTINCT  
-- '02 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 1 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  

 '01' AS MOEDA,  

 '2' AS TIPO_LANC,   

 NULL AS CONTA_DEB,
 CASE WHEN ICRED.DESCRICAO LIKE 'Cart%' 
    THEN '11204001'
	ELSE '11204001' 
 END AS CONTA_CRED,   
 REPLACE ((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA),'-','')  AS VALOR,  
   
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Faturamento Original' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Faturamento Original' AS HISTORICO,  
 NULL AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 NULL AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 NULL AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 'VAL_ORIG' AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE 
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND (ICRED.DESCRICAO like 'Credito%' OR ICRED.DESCRICAO like 'Cart%' OR ICRED.DESCRICAO like 'Pagamento%' OR ICRED.DESCRICAO like 'Depósito%' OR ICRED.DESCRICAO like 'Deposito%')-- Crédito Bancário ou crédito de depósito  
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (200407,201080))
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)


UNION ALL


SELECT DISTINCT  
-- '02 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 1 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  

 '01' AS MOEDA,  

 '2' AS TIPO_LANC,   

 NULL AS CONTA_DEB,  
 CASE WHEN ICRED.DESCRICAO LIKE 'Cart%' 
    THEN '11204001'
	ELSE '11204001' 
 END AS CONTA_CRED,   
 REPLACE ((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA),'-','')  AS VALOR,  
   
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Faturamento Original' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Faturamento Original' AS HISTORICO,  
 NULL AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 NULL AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 NULL AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 'VAL_ORIG' AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE --COB.COBRANCA = '108001'
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND (ICRED.DESCRICAO not like 'Credito%' OR ICRED.DESCRICAO not like 'Cart%' OR ICRED.DESCRICAO not like 'Pagamento%' OR ICRED.DESCRICAO not like 'Depósito%' OR ICRED.DESCRICAO not like 'Deposito%')-- Crédito Bancário ou crédito de depósito   
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA and cob.COBRANCA not in (200407,201080))
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)


UNION ALL

-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR DA TAXA FCAV,  
  
SELECT DISTINCT 
-- '03 - BAIXA', 
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 2 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '31102032' AS CONTA_DEB,  
 '31102031' AS CONTA_CRED,   
 REPLACE (CAST(((CAST((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) AS NUMERIC(10,2)) 
			* (CAST('0.' AS NUMERIC)+CAST(ISNULL(CTT.CTT_TX_GER,0) AS NUMERIC))) /100) AS NUMERIC(10,2)),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - TAXA FCAV' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - TAXA FCAV' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 '050' AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 '301' AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 '53' AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
 LEFT OUTER JOIN DADOSADVP12.dbo.CTT010 AS CTT ON (CAST(FCAD.CENTRO_CUSTO AS VARCHAR)= CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI )  
   
WHERE   
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL 
AND FCAD.CENTRO_CUSTO NOT LIKE '31%'  
AND FCAD.CENTRO_CUSTO <> '406556601'
AND CTT.CTT_TX_GER > '0'
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA )
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

UNION ALL
  
-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR DO REPASSE USP,  
  
SELECT DISTINCT 
-- '04 - BAIXA', 
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 3 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101126' AS CONTA_DEB,  
 '21103005' AS CONTA_CRED,   
 REPLACE (CAST(((CAST((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) AS NUMERIC(10,2)) * 5) /100) AS NUMERIC(10,2)),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - REPASSE USP' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - REPASSE USP' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE   
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')
AND ICRED.DT_ENVIO_CONTAB IS NULL  
AND CUR.FACULDADE = 'ESPEC'  
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA)
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

UNION ALL
  
  
-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR DO REPASSE POLI,  
  
SELECT DISTINCT
-- '05 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 4 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101127' AS CONTA_DEB,  
 '21103006' AS CONTA_CRED,   
 REPLACE (CAST(((CAST((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) AS NUMERIC(10,2)) * 3) /100) AS NUMERIC(10,2)),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - REPASSE POLI' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - REPASSE POLI' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE   
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000') 
AND ICRED.DT_ENVIO_CONTAB IS NULL 
AND CUR.FACULDADE = 'ESPEC'  
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA)
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

UNION ALL


/******************************************************************************    
	-- CONFORME SOLICITAÇAO PELO TICKET https://vanzolini.movidesk.com/Ticket/Edit/11258, 
	-- ESTE BLOCO ESTÁ SENDO COMENTADO PARA QUE NÃO SEJA MAIS GERADO O VALOR DA GARANTIA PRO.

-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR DO GARANTIA PRO,  


SELECT DISTINCT 
-- '07 - BAIXA', 
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 6 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101157' AS CONTA_DEB,  
 '41101157' AS CONTA_CRED,   
 REPLACE (CAST(((CAST((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) AS NUMERIC(10,2)) * 5) /100) AS NUMERIC(10,2)),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - GARANTIA PRO' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - GARANTIA PRO' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 '070' AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 '307' AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 '41' AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE   
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND CUR.FACULDADE = 'ESPEC'   
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA)
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)
AND FCAD.CENTRO_CUSTO <> '519010118'

UNION ALL
 **************************************************************************/ 


-- *** SELECT EXCLUSIVO PARA GERAR UM REGISTRO A MAIS PARA MONTAR O VALOR DO REPASSE PEA,  
  
SELECT DISTINCT 
-- '08 - BAIXA', 
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 (select MAX(IC.ITEMCRED) + 7 from LY_ITEM_CRED as IC where COB.COBRANCA = IC.COBRANCA )AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 '41101180' AS CONTA_DEB,  
 '21103009' AS CONTA_CRED,   
 REPLACE (CAST(((CAST((SELECT SUM(IC.VALOR) FROM LY_ITEM_CRED AS IC WHERE IC.COBRANCA = COB.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL) AS NUMERIC(10,2)) * CAST(CTT.CTT_TX_PEA AS NUMERIC)) /100) AS NUMERIC(10,2)),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - REPASSE PEA' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - REPASSE PEA' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA AND TIPO_ENCARGO IS NULL AND TIPODESCONTO IS NULL)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
 INNER JOIN DADOSADVP12.dbo.CTT010 AS CTT ON (CAST(FCAD.CENTRO_CUSTO AS VARCHAR)= CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI )  
   
WHERE   
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND CUR.FACULDADE = 'ESPEC'  
AND COB.COBRANCA NOT IN (SELECT COBRANCA FROM LY_ITEM_LANC WHERE DESCRICAO = 'VALOR ACORDADO' AND COBRANCA = COB.COBRANCA)
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)
AND CTT.CTT_TX_PEA > '0'

UNION ALL
  
-- *** SELECT EXCLUSIVO PARA FAZER A BAIXA POR ACORDO  
  
SELECT DISTINCT  
--'9 - BAIXA',
 CAST(ILAN.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ILAN.ITEMCOBRANCA AS LINHA,  
 '01' AS MOEDA,  
 '3' AS TIPO_LANC,   
 CASE WHEN ILAN.CURSO LIKE 'CE%' THEN '31102024' 
	ELSE '11204005' END AS CONTA_DEB,  
 '11204001' AS CONTA_CRED,   
 REPLACE ((SELECT SUM(VALOR) FROM LY_ITEM_LANC IIL WHERE IIL.COBRANCA = COB.COBRANCA AND (IIL.DESCRICAO = 'VALOR ACORDADO' /*AND IIL.ACORDO IS NULL*/ )),'-','')   AS VALOR,  
 'Titulo: '+CONVERT(VARCHAR,(SELECT DISTINCT IL.BOLETO FROM LY_ITEM_LANC AS IL WHERE IL.COBRANCA = COB.COBRANCA AND IL.BOLETO > 1),20)+' - BAIXA POR ACORDO' AS ORIGEM,  
 'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - BAIXA POR ACORDO' AS HISTORICO,  
 FCAD.CENTRO_CUSTO AS CC_DEB,  
 FCAD.CENTRO_CUSTO AS CC_CRED,  
 FCAD.CENTRO_ATIV AS ITEM_CONTAB_DEB,  
 '307' AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR AS CLASSE_VALOR_DEB,  
 '41' AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 NULL AS IMP_AUX,  
 COB.COBRANCA AS IMP_COBRANCA  
  
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_CURSO AS CUR ON (COB.CURSO = CUR.CURSO)  
 LEFT JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA )
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 LEFT OUTER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN HADES.dbo.HD_MUNICIPIO AS MUN ON (RESP.END_MUNICIPIO = MUN.MUNICIPIO)  
 LEFT OUTER JOIN VW_MATRICULA_E_PRE_MATRICULA AS VW_MAT ON (ALU.ALUNO = VW_MAT.ALUNO AND VW_MAT.SIT_DETALHE in ('Curricular','Adaptacao','Dependencia','Normal') AND VW_MAT.TURMA IS NOT NULL)  
 LEFT OUTER JOIN LY_HISTMATRICULA AS HIST ON (ALU.ALUNO = HIST.ALUNO)  
 LEFT OUTER JOIN LY_H_CURSOS_CONCL AS H ON (H.ALUNO = ALU.ALUNO AND H.CURSO = ALU.CURSO AND H.TURNO = ALU.TURNO AND H.CURRICULO = ALU.CURRICULO)  
 LEFT OUTER JOIN LY_TURMA AS T ON (H.CURSO = T.CURSO AND H.CURRICULO = T.CURRICULO AND H.SEM_INGRESSO = T.SEMESTRE and H.ANO_INGRESSO = T.ANO and VW_MAT.TURMA = T.TURMA)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (VW_MAT.TURMA = FCAD.TURMA OR T.TURMA = FCAD.TURMA OR HIST.TURMA = FCAD.TURMA)   

      
WHERE   
 ILAN.DATA >= @DATA_INI  
AND ILAN.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ILAN.DT_ENVIO_CONTAB IS NULL
AND ILAN.DESCRICAO = 'VALOR ACORDADO'
AND CAST(COB.COBRANCA AS VARCHAR) NOT IN (SELECT VW.COBRANCA FROM DADOSADVP12.dbo.VW_FCAV_CT2PAGTO AS VW WHERE VW.COBRANCA = CAST(COB.COBRANCA AS VARCHAR) AND VW.HIST LIKE '%BAIXA POR ACORDO%')  
AND ICRED.LANC_CRED NOT IN (SELECT LANC_CRED FROM LY_LANC_CREDITO WHERE TIPO_CRED = 'PERDADEVEDORES' AND LANC_CRED = ICRED.LANC_CRED)

----------------------------------------------------------------------------------------------------------------------------

BEGIN -- PREPARAÇÃO PARA REGISTROS DA BAIXA POR CARTÃO
DECLARE @NUM_PARCELAS VARCHAR (2)

SELECT DISTINCT  
-- '10 - BAIXA',
 CAST(ICRED.DATA AS DATE) AS DATA_PROC,  
 '008871' AS LOTE,  
 NULL AS DOC,  
 '01' AS FILIAL,  
 ICRED.ITEMCRED AS LINHA,  
 '01' AS MOEDA,  
 '1' AS TIPO_LANC,   
   
 '11204004' AS CONTA_DEB,  
 NULL AS CONTA_CRED,  
 
 REPLACE ((CAST(ICRED.VALOR / CC.NUM_PARCELAS AS NUMERIC (10,2)) ),'-','') AS VALOR,  
  
 CASE WHEN ICRED.DESCRICAO IS NULL  THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+(CASE WHEN ICRED.TIPO_ENCARGO IS NULL THEN 'Desconto '+ICRED.TIPODESCONTO ELSE 'Acrescimo '+ICRED.TIPO_ENCARGO END)  
  WHEN ICRED.DESCRICAO like 'Credito%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - Credito Bancario'  
  WHEN ICRED.DESCRICAO LIKE 'Desconto%' THEN 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+CAST(ICRED.TIPODESCONTO AS VARCHAR)  
  ELSE 'Titulo: '+CONVERT(VARCHAR,BOL.BOLETO,20)+' - '+REPLACE(ICRED.DESCRICAO,';',',') END AS ORIGEM,  
  
  'Cobranca: '+CAST(COB.COBRANCA AS VARCHAR)+' - Cartao '+ CONVERT(VARCHAR,CC.NUM_PARCELAS,2)+'X Parcela: ' AS HISTORICO,  
  
 FCAD.CENTRO_CUSTO	AS CC_DEB,  
 NULL				AS CC_CRED,  
 FCAD.CENTRO_ATIV	AS ITEM_CONTAB_DEB,  
 NULL				AS ITEM_CONTAB_CRED,  
 FCAD.CLASSE_VALOR	AS CLASSE_VALOR_DEB,  
 NULL				AS CLASSE_VALOR_CRED,  
 CASE WHEN RESP.CPF_TITULAR IS NULL  
  THEN RESP.CGC_TITULAR  
  ELSE RESP.CPF_TITULAR END AS COD_CAV,  
 '01' AS LOJA_CLIENTE,  
 NULL AS COD_FORNEC,  
 '01' AS LOJA_FORNEC,  
 ALU.ALUNO AS IMP_ALUNO,  
 ALU.CANDIDATO AS IMP_CANIDATO,  
 PES.PESSOA AS IMP_PESSOA,  
 CC.NUM_PARCELAS AS NUM_PARCELAS,  
  COB.COBRANCA AS IMP_COBRANCA  
  
INTO #TMP_IMPCONT_CRED
   
FROM  
 LY_ALUNO AS ALU  
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)  
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)  
 INNER JOIN LY_ITEM_CRED AS ICRED ON (COB.COBRANCA = ICRED.COBRANCA)  
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)  
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)  
 INNER JOIN LY_CRED_CARTAO AS CC ON ICRED.LANC_CRED = CC.LANC_CRED
 LEFT OUTER JOIN LY_RESP_FINAN AS RESP ON (COB.RESP = RESP.RESP)  
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)
   
WHERE  
 ICRED.DATA >= @DATA_INI  
AND ICRED.DATA <= (select cast(@data_fim as varchar)+' 23:59:59.000')  
AND ICRED.DT_ENVIO_CONTAB IS NULL
AND ICRED.DESCRICAO LIKE 'Cart%'

DECLARE @COB VARCHAR(10)
DECLARE CURSOR_FRACIONAMENTO CURSOR FOR

SELECT 
	IMP_COBRANCA
FROM #TMP_IMPCONT_CRED

OPEN CURSOR_FRACIONAMENTO
FETCH NEXT FROM CURSOR_FRACIONAMENTO INTO @COB
WHILE @@FETCH_STATUS = 0
BEGIN 
	SET @NUM_PARCELAS = (SELECT NUM_PARCELAS FROM #TMP_IMPCONT_CRED WHERE IMP_COBRANCA = @COB)
	
    DECLARE @i INT
    SET @i = @NUM_PARCELAS
    WHILE @i > 0
    BEGIN
        INSERT INTO #FCAV_IMPCONT_2
        	SELECT
        		DATA_PROC, LOTE, DOC, FILIAL, LINHA, MOEDA, TIPO_LANC,  CONTA_DEB, CONTA_CRED, VALOR, ORIGEM, 
        		HISTORICO + CONVERT(VARCHAR,@i,2),
        		CC_DEB, CC_CRED, ITEM_CONTAB_DEB, ITEM_CONTAB_CRED, CLASSE_VALOR_DEB, CLASSE_VALOR_CRED, COD_CAV, LOJA_CLIENTE, COD_FORNEC, LOJA_FORNEC, IMP_ALUNO, IMP_CANIDATO, IMP_PESSOA, 'PARC', IMP_COBRANCA
        	FROM #TMP_IMPCONT_CRED
			WHERE IMP_COBRANCA = @COB		

        SET @i = @i - 1
    END
    
-- *********************************

--*************************************
    
FETCH NEXT FROM CURSOR_FRACIONAMENTO INTO @COB
END

CLOSE CURSOR_FRACIONAMENTO 
DEALLOCATE CURSOR_FRACIONAMENTO 

--DROP TABLE TMP_IMPCONT_CRED

END

BEGIN -- *** AJUSTE PARA O PARCELAMENTO PELO CARTÃO DE CRÉDITO EM QUE É GERADA UMA DÍZIMA PERIÓDICA *** INÍCIO

DECLARE @DIFERENCA NUMERIC (8,2)
DECLARE @COBRANCA2 VARCHAR(10)
DECLARE COB_CART CURSOR FOR

SELECT	IMP_COBRANCA
FROM	#FCAV_IMPCONT_2
WHERE	IMP_AUX = 'PARC'
GROUP BY IMP_COBRANCA

OPEN COB_CART
FETCH NEXT FROM COB_CART INTO @COBRANCA2
WHILE @@FETCH_STATUS = 0
BEGIN

WITH	
VAL_ORIG AS (
	SELECT	IMP_COBRANCA AS COBRANCA, VALOR
	FROM	#FCAV_IMPCONT_2
	WHERE IMP_AUX = 'VAL_ORIG'
				),
				
TOT_PARC AS (
	SELECT	IMP_COBRANCA AS COBRANCA, SUM(CAST(VALOR AS NUMERIC (8,2))) AS VALOR
	FROM	#FCAV_IMPCONT_2
	WHERE IMP_AUX = 'PARC'
	GROUP BY IMP_COBRANCA, IMP_AUX
				)

SELECT		@DIFERENCA = VO.VALOR - TP.VALOR
FROM		VAL_ORIG VO
			INNER JOIN TOT_PARC TP ON VO.COBRANCA = TP.COBRANCA
WHERE		VO.COBRANCA = @COBRANCA2
ORDER BY 	VO.COBRANCA

--IF @DIFERENCA <> 0

BEGIN
	
WITH UPDATE_FCAV_IMPCONT_2 AS 
	(
SELECT TOP 1 IMP_COBRANCA, VALOR
FROM #FCAV_IMPCONT_2
WHERE IMP_COBRANCA = @COBRANCA2
AND IMP_AUX = 'PARC'
	)

UPDATE UPDATE_FCAV_IMPCONT_2
SET VALOR = VALOR + @DIFERENCA
WHERE IMP_COBRANCA = @COBRANCA2

END

--ELSE


FETCH NEXT FROM COB_CART INTO @COBRANCA2
END

CLOSE COB_CART
DEALLOCATE COB_CART

END 
-- *** AJUSTE PARA O PARCELAMENTO PELO CARTÃO DE CRÉDITO EM QUE É GERADA UMA DÍZIMA PERIÓDICA *** FIM


-- *** SELECT NA TABELA AUXILIAR PARA AJUSTAR O FORMATO DA DATA, CRIAR A ORDENAÇÃO DO CAMPO "DOC"  
-- *** E CONVERTER TODOS OS CAMPOS UTILIZADOS PARA "VARCHAR".  
-- *** EXCLUSIVO PARA DADOS DE FATURAMENTO  
  
SELECT DISTINCT  
 CONVERT(VARCHAR,DATA_PROC,112) AS DATA_PROC,  
 LOTE,  
 CAST((DENSE_RANK() OVER(PARTITION BY DATA_PROC ORDER BY IMP_COBRANCA)) AS VARCHAR (20)) AS DOC,  
 CAST(FILIAL AS VARCHAR (20)) AS FILIAL,  
 CAST(LINHA AS VARCHAR (20)) AS LINHA,  
 CAST(MOEDA AS VARCHAR (20)) AS MOEDA,  
 CAST(TIPO_LANC AS VARCHAR (20)) AS TIPO_LANC,  
 CAST(CONTA_DEB AS VARCHAR (20)) AS CONTA_DEB,  
 CAST(CONTA_CRED AS VARCHAR (20)) AS CONTA_CRED,  
 CAST(VALOR AS VARCHAR (20)) AS VALOR,  
 CAST(ORIGEM AS VARCHAR (100)) AS ORIGEM,  
 CAST(HISTORICO AS VARCHAR (40)) AS HISTORICO,  
 CAST(CC_DEB AS VARCHAR (20)) AS CC_DEB,  
 CAST(CC_CRED AS VARCHAR (20)) AS CC_CRED,  
 CAST(ITEM_CONTAB_DEB AS VARCHAR (20)) AS ITEM_CONTAB_DEB,  
 CAST(ITEM_CONTAB_CRED AS VARCHAR (20)) AS ITEM_CONTAB_CRED,  
 CAST(CLASSE_VALOR_DEB AS VARCHAR (20)) AS CLASSE_VALOR_DEB,  
 CAST(CLASSE_VALOR_CRED AS VARCHAR (20)) AS CLASSE_VALOR_CRED,  
 CAST(COD_CAV AS VARCHAR (20)) AS COD_CAV,  
 CAST(LOJA_CLIENTE AS VARCHAR (20)) AS LOJA_CLIENTE,  
 CAST(COD_FORNEC AS VARCHAR (20)) AS COD_FORNEC,  
 CAST(LOJA_FORNEC AS VARCHAR (20)) AS LOJA_FORNEC,  
 IMP_ALUNO,  
 IMP_CANIDATO,  
 IMP_PESSOA,  
 IMP_BOLETO,  
 IMP_COBRANCA  
  
INTO #FCAV_IMPCONT_3  
  
FROM #FCAV_IMPCONT_1 AS IMP1 
  
ORDER BY  
 DATA_PROC   
  
-- *** SELECT NA TABELA AUXILIAR PARA AJUSTAR O FORMATO DA DATA, CRIAR A ORDENAÇÃO DO CAMPO "DOC"  
-- *** E CONVERTER TODOS OS CAMPOS UTILIZADOS PARA "VARCHAR".  
-- *** EXCLUSIVO PARA DADOS DE PAGAMENTOS  
   
SELECT DISTINCT  
 CONVERT(VARCHAR,DATA_PROC,112) AS DATA_PROC,  
 LOTE,  
 CAST((DENSE_RANK() OVER(PARTITION BY DATA_PROC ORDER BY IMP_COBRANCA)) AS VARCHAR (20)) AS DOC,  
 CAST(FILIAL AS VARCHAR (20)) AS FILIAL,  
 CAST(LINHA AS VARCHAR (20)) AS LINHA,  
 CAST(MOEDA AS VARCHAR (20)) AS MOEDA,  
 CAST(TIPO_LANC AS VARCHAR (20)) AS TIPO_LANC,  
 CAST(CONTA_DEB AS VARCHAR (20)) AS CONTA_DEB,  
 CAST(CONTA_CRED AS VARCHAR (20)) AS CONTA_CRED,  
 CAST(VALOR AS VARCHAR (20)) AS VALOR,  
 CAST(ORIGEM AS VARCHAR (100)) AS ORIGEM,  
 CAST(HISTORICO AS VARCHAR (40)) AS HISTORICO,  
 CAST(CC_DEB AS VARCHAR (20)) AS CC_DEB,  
 CAST(CC_CRED AS VARCHAR (20)) AS CC_CRED,  
 CAST(ITEM_CONTAB_DEB AS VARCHAR (20)) AS ITEM_CONTAB_DEB,  
 CAST(ITEM_CONTAB_CRED AS VARCHAR (20)) AS ITEM_CONTAB_CRED,  
 CAST(CLASSE_VALOR_DEB AS VARCHAR (20)) AS CLASSE_VALOR_DEB,  
 CAST(CLASSE_VALOR_CRED AS VARCHAR (20)) AS CLASSE_VALOR_CRED,  
 CAST(COD_CAV AS VARCHAR (20)) AS COD_CAV,  
 CAST(LOJA_CLIENTE AS VARCHAR (20)) AS LOJA_CLIENTE,  
 CAST(COD_FORNEC AS VARCHAR (20)) AS COD_FORNEC,  
 CAST(LOJA_FORNEC AS VARCHAR (20)) AS LOJA_FORNEC,  
 IMP_ALUNO,  
 IMP_CANIDATO,  
 IMP_PESSOA,  
 IMP_AUX, 
 IMP_COBRANCA  
  
INTO #FCAV_IMPCONT_4  
  
FROM #FCAV_IMPCONT_2 AS IMP2 

ORDER BY  
 DATA_PROC, IMP_COBRANCA   
  
-- *** SELECT PARA UNIR OS DADOS JÁ TRATADOS DAS TABELAS AUXILIARES E PARA PREENHCER  
-- *** COM ZEROS A ESQUERDA OS CAMPOS "DOC" E "LINHA".  
   
SELECT  
 ISNULL(DATA_PROC,'')				AS DATA_PROC,
 ISNULL(LOTE,'')					AS LOTE,
 ISNULL(RIGHT('000000'+DOC,6),'')	AS DOC,  
 ISNULL(FILIAL,'')					AS FILIAL,
 ISNULL(RIGHT('000000'+LINHA,3),'') AS LINHA,  
 ISNULL(MOEDA,'')					AS MOEDA,
 ISNULL(TIPO_LANC,'')				AS TIPO_LANC,
 ISNULL(
	CASE WHEN CONTA_DEB = '31401001' AND CC_DEB NOT LIKE '5%' THEN '31402001' 
		 WHEN CONTA_DEB = '31401002' AND CC_DEB NOT LIKE '5%' THEN '31402002' 
		 WHEN CONTA_DEB = '31401003' AND CC_DEB NOT LIKE '5%' THEN '31402003' 
		 WHEN CONTA_DEB = '31401004' AND CC_DEB NOT LIKE '5%' THEN '31402004' ELSE CONTA_DEB END
	,'')							AS CONTA_DEB,
 ISNULL(CONTA_CRED,'')				AS CONTA_CRED,
 ISNULL(VALOR,'')					AS VALOR,
 ISNULL(ORIGEM,'')					AS ORIGEM,
 ISNULL(HISTORICO,'')				AS HISTORICO,
 ISNULL(CC_DEB,'')					AS CC_DEB,
 ISNULL(CC_CRED,'')					AS CC_CRED,
 ISNULL(ITEM_CONTAB_DEB,'')			AS ITEM_CONTAB_DEB,
 ISNULL(ITEM_CONTAB_CRED,'')		AS ITEM_CONTAB_CRED,
 ISNULL(CLASSE_VALOR_DEB,'')		AS CLASSE_VALOR_DEB,
 ISNULL(CLASSE_VALOR_CRED,'')		AS CLASSE_VALOR_CRED,
 ISNULL(COD_CAV,'')					AS COD_CAV,
 ISNULL(LOJA_CLIENTE,'')			AS LOJA_CLIENTE,
 ISNULL(COD_FORNEC,'')				AS COD_FORNEC,
 ISNULL(LOJA_FORNEC,'')				AS LOJA_FORNEC

INTO #FCAV_IMPCONT_5
  
FROM #FCAV_IMPCONT_3  
  
UNION  
  
  
SELECT  
 ISNULL(DATA_PROC,'')				AS DATA_PROC,  
 ISNULL(LOTE,'')					AS LOTE,
 ISNULL(RIGHT('000000'+DOC,6),'')	AS DOC,  
 ISNULL(FILIAL,'')					AS FILIAL,
 ISNULL(RIGHT('000000'+LINHA,3),'') AS LINHA,  
 ISNULL(MOEDA,'')					AS MOEDA,
 ISNULL(TIPO_LANC,'')				AS TIPO_LANC,
 ISNULL(
	CASE WHEN CONTA_DEB = '31401001' AND CC_DEB NOT LIKE '5%' THEN '31402001' 
		 WHEN CONTA_DEB = '31401002' AND CC_DEB NOT LIKE '5%' THEN '31402002' 
		 WHEN CONTA_DEB = '31401003' AND CC_DEB NOT LIKE '5%' THEN '31402003' 
		 WHEN CONTA_DEB = '31401004' AND CC_DEB NOT LIKE '5%' THEN '31402004' ELSE CONTA_DEB END
	,'')							AS CONTA_DEB,
 ISNULL(CONTA_CRED,'')				AS CONTA_CRED,
 ISNULL(VALOR,'')					AS VALOR,
 ISNULL(ORIGEM,'')					AS ORIGEM,
 ISNULL(HISTORICO,'')				AS HISTORICO,
 ISNULL(CC_DEB,'')					AS CC_DEB,
 ISNULL(CC_CRED,'')					AS CC_CRED,
 ISNULL(ITEM_CONTAB_DEB,'')			AS ITEM_CONTAB_DEB,
 ISNULL(ITEM_CONTAB_CRED,'')		AS ITEM_CONTAB_CRED,
 ISNULL(CLASSE_VALOR_DEB,'')		AS CLASSE_VALOR_DEB,
 ISNULL(CLASSE_VALOR_CRED,'')		AS CLASSE_VALOR_CRED,
 ISNULL(COD_CAV,'')					AS COD_CAV,
 ISNULL(LOJA_CLIENTE,'')			AS LOJA_CLIENTE,
 ISNULL(COD_FORNEC,'')				AS COD_FORNEC,
 ISNULL(LOJA_FORNEC,'')				AS LOJA_FORNEC
  
FROM #FCAV_IMPCONT_4   
  
ORDER BY DATA_PROC   


-- *** AJUSTE DA COLUNA "DOC" CONSIDERANDO REGISTROS JÁ LANÇADOS NO PROTHEUS PARA A MESA DATA E MESMO LOTE
SELECT 
	TMP5.DATA_PROC,
	TMP5.LOTE,
	ISNULL(MAX(CT2_DOC), '000000')  AS ULT_DOC
INTO #ULT_DOC_CT2
FROM
	#FCAV_IMPCONT_5 AS TMP5
	LEFT OUTER JOIN DADOSADVP12.dbo.CT2010 CT2 ON TMP5.DATA_PROC COLLATE Latin1_General_CI_AI = CT2.CT2_DATA AND CT2.CT2_LOTE IN ('008870','008871')

GROUP BY
	TMP5.DATA_PROC, TMP5.LOTE
ORDER BY 
	TMP5.DATA_PROC, TMP5.LOTE

UPDATE #FCAV_IMPCONT_5
SET DOC =
		RIGHT('000000'+
				CAST(
					(CAST(DOC COLLATE Latin1_General_CI_AI AS NUMERIC) + DOC.ULT_DOC)
				AS VARCHAR(60))
			,6)
FROM
	#FCAV_IMPCONT_5 AS TMP5
	INNER JOIN #ULT_DOC_CT2 DOC ON TMP5.DATA_PROC COLLATE Latin1_General_CI_AI = DOC.DATA_PROC COLLATE Latin1_General_CI_AI AND TMP5.LOTE = DOC.LOTE


SELECT * FROM #FCAV_IMPCONT_5

END


-- ******** ALIMENTA TABELA DE IMPORTACAO  ***********  
BEGIN
	BEGIN TRANSACTION

		TRUNCATE TABLE FCAV_IMPORTCONTABIL

		INSERT INTO FCAV_IMPORTCONTABIL
		SELECT 
			*
		FROM  #FCAV_IMPCONT_5

	COMMIT
END



/***ALIMENTA TABELA FCAV_IMPORT_DEB_CRED***/
BEGIN
	BEGIN TRANSACTION

		TRUNCATE TABLE FCAV_IMPORT_DEB_CRED

		INSERT INTO FCAV_IMPORT_DEB_CRED
		SELECT 
			*
		FROM  #FCAV_IMPCONT_4

	COMMIT
END


/*-- ******** ABAIXO - AREA DE CONFERÊNCIA  ***********  

-- ********* CONFERENCIA DE CENTRO DE CUSTO EXISTENTE *********
BEGIN
	SELECT 
		IMP_COBRANCA, CC_DEB, 'NAO CADASTRADO' AS STATUS
	FROM #FCAV_IMPCONT_4 CC
		LEFT OUTER JOIN DADOSADVP12.dbo.CTT010 CTT ON CC.CC_DEB = CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI and CTT.D_E_L_E_T_ = ''
	WHERE CC_DEB IS NOT NULL
	AND CTT.CTT_CUSTO IS NULL
END


-- ********* CONFERENCIA DE CENTRO DE CUSTO DENTRO DA VALIDADE OU BLOQUEADO *********
BEGIN	
	SELECT
		CTT.CTT_CUSTO,
		'VENCIDO' AS STATUS
		--IMP_COBRANCA, CC_DEB, CTT.CTT_CUSTO, CTT.CTT_STATUS, CTT.CTT_BLOQ, CTT.CTT_DTEXSF
	FROM #FCAV_IMPCONT_4 CC
		LEFT OUTER JOIN DADOSADVP12.dbo.CTT010 CTT ON CC.CC_DEB = CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI AND CC_DEB IS NOT NULL and CTT.D_E_L_E_T_ = ''
	WHERE 
		CAST(CTT.CTT_DTEXSF AS DATE) BETWEEN '2001-01-01' and CONVERT(DATE,DATEADD(DAY,-1,GETDATE()))
	GROUP BY CTT.CTT_CUSTO
UNION ALL
	SELECT
		CTT.CTT_CUSTO,
		'INATIVO' AS STATUS
		--IMP_COBRANCA, CC_DEB, CTT.CTT_CUSTO, CTT.CTT_STATUS, CTT.CTT_BLOQ, CTT.CTT_DTEXSF
	FROM #FCAV_IMPCONT_4 CC
		LEFT OUTER JOIN DADOSADVP12.dbo.CTT010 CTT ON CC.CC_DEB = CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI AND CC_DEB IS NOT NULL and CTT.D_E_L_E_T_ = ''
	WHERE 
		CTT.CTT_STATUS = 'I'
	GROUP BY CTT.CTT_CUSTO
UNION ALL
	SELECT
		CTT.CTT_CUSTO,
		'BLOQUEADO' AS STATUS
		--IMP_COBRANCA, CC_DEB, CTT.CTT_CUSTO, CTT.CTT_STATUS, CTT.CTT_BLOQ, CTT.CTT_DTEXSF
	FROM #FCAV_IMPCONT_4 CC
		LEFT OUTER JOIN DADOSADVP12.dbo.CTT010 CTT ON CC.CC_DEB = CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI AND CC_DEB IS NOT NULL and CTT.D_E_L_E_T_ = ''
	WHERE 
		CTT.CTT_BLOQ = '1'
	GROUP BY CTT.CTT_CUSTO

 END


-- ********* CONFERENCIA DE CREDITOS E DEBITOS BATEREM *********
BEGIN
	WITH CONF_DEBITO AS 
		(SELECT
			IMP_COBRANCA,-- VALOR , CAST(VALOR AS MONEY) AS VALOR_2--
			SUM(CAST(VALOR AS MONEY)) AS VALOR
		FROM	 #FCAV_IMPCONT_4
		WHERE	 TIPO_LANC = '1' 
		GROUP BY IMP_COBRANCA
	),

	CONF_CRED AS 
		(SELECT
			IMP_COBRANCA,-- VALOR , CAST(VALOR AS MONEY) AS VALOR_2--
			SUM(CAST(VALOR AS MONEY)) * -1 AS VALOR
		FROM	 #FCAV_IMPCONT_4
		WHERE	 TIPO_LANC = '2' 
		GROUP BY IMP_COBRANCA
	),

	CONF_SUM AS
		(SELECT 
			CD.IMP_COBRANCA,
			SUM(ISNULL(CD.VALOR,'0,00') + ISNULL(CC.VALOR,'0,00')) AS CALC
		FROM CONF_DEBITO CD
			LEFT OUTER JOIN CONF_CRED CC ON CD.IMP_COBRANCA = CC.IMP_COBRANCA
		GROUP BY
			CD.IMP_COBRANCA
		)

	SELECT 
		TEMP.*
	FROM 
		#FCAV_IMPCONT_4 TEMP
		INNER JOIN CONF_SUM CONF ON TEMP.IMP_COBRANCA = CONF.IMP_COBRANCA
	WHERE 
		CONF.CALC <> 0
	
END 

*/
	
