
USE DADOSADVP12
GO


select * from LYCEUM.DBO.FCAV_IMPORTCONTABIL where HISTORICO like '%estorno%'


SELECT
	 SUBSTRING(HISTORICO,CHARINDEX(' ',HISTORICO,1)+1,6) collate Latin1_General_CI_AI as cobranca,
	D_E_L_E_T_, CT2_DATA, CT2_LOTE, CT2_DOC,CT2_LINHA, CT2_DC,
	CT2_DEBITO,CT2_CREDIT, CT2_HIST,CT2_VALOR, CT2_CCD,CT2_CCC, R_E_C_N_O_
FROM		CT2010
	left join LYCEUM.DBO.FCAV_IMPORTCONTABIL 
		on SUBSTRING(CT2_HIST ,CHARINDEX(' ',CT2_HIST,1)+1,6) = SUBSTRING(HISTORICO,CHARINDEX(' ',HISTORICO,1)+1,6) collate Latin1_General_CI_AI 
WHERE	D_E_L_E_T_ = '' and
  CT2_DATA >= '20190101'
ANd HISTORICO LIKE '%estorno%'
AND			CT2_LOTE in ('008871','008870')
ORDER BY	CT2_LOTE,CT2_DOC DESC,CT2_LINHA


WITH CONF_DEBITO 
AS (SELECT
  IMP_COBRANCA,
  SUM(CAST(VALOR AS money)) AS VALOR 
FROM LYCEUM.DBO.FCAV_IMPORT_DEB_CRED 
WHERE TIPO_LANC = '1' 
GROUP BY IMP_COBRANCA), 

CONF_CRED
AS (SELECT
  IMP_COBRANCA,
  SUM(CAST(VALOR AS money)) * -1 AS VALOR 
FROM LYCEUM.DBO.FCAV_IMPORT_DEB_CRED
 WHERE TIPO_LANC = '2' 
GROUP BY IMP_COBRANCA), 

CONF_SUM
AS (SELECT
  CD.IMP_COBRANCA,
 SUM(ISNULL(CD.VALOR, '0,00') + ISNULL(CC.VALOR, '0,00')) AS CALC
 FROM CONF_DEBITO CD
LEFT OUTER JOIN CONF_CRED CC
 ON CD.IMP_COBRANCA = CC.IMP_COBRANCA
 GROUP BY CD.IMP_COBRANCA)
 SELECT
  TEMP.* 
FROM LYCEUM.DBO.FCAV_IMPORT_DEB_CRED TEMP 
INNER JOIN CONF_SUM CONF
  ON TEMP.IMP_COBRANCA = CONF.IMP_COBRANCA
 WHERE CONF.CALC <> 0

 go

 SELECT * FROM LYCEUM.DBO.FCAV_IMPORTCONTABIL
 WHERE CONTA_DEB = '' 
 AND TIPO_LANC = 1

 union all

 SELECT * FROM LYCEUM.DBO.FCAV_IMPORTCONTABIL
 WHERE CONTA_CRED = '' 
 AND TIPO_LANC = 2  

 union all

 SELECT * FROM LYCEUM.DBO.FCAV_IMPORTCONTABIL
 WHERE (CONTA_DEB = '' OR CONTA_CRED = '')
 AND TIPO_LANC = 3

 	--************************************************************************
	--	VERIFICAR OS LANÇAMENTOS DOS ITENS DA COBRANCA DÉBITO E CREDITO		--
	--************************************************************************
	
	use LYCEUM	
	go
	BEGIN
		DECLARE @cobranca T_NUMERO

		SET @cobranca = 203418   ---DIGITTE O NÚMERO DA COBRANÇA

		--lancamentos dos débitos da cobrança

		SELECT DT_ENVIO_CONTAB, *
		FROM lyceum.dbo.LY_ITEM_LANC
		WHERE COBRANCA IN (@cobranca)


		--lancamentos dos créditos da cobrança

		SELECT DT_ENVIO_CONTAB, *
		FROM LY_ITEM_CRED
		WHERE COBRANCA in (@cobranca)
	

		-- CONSULTA AUXILIAR 
		SELECT 
			* 
		FROM 
			VW_FCAV_BOLETOS_EMITIDOS_CONTAB 
		WHERE COBRANCA = @cobranca
	END
GO


--update LY_ITEM_LANC
--set
--	DT_ENVIO_CONTAB = '2019-12-16 00:00:00.000'
--where 
--	COBRANCA in (SELECT DISTINCT SUBSTRING(HISTORICO,CHARINDEX(' ',HISTORICO,1)+1,6) collate Latin1_General_CI_AI 
--		 FROM LYCEUM.DBO.FCAV_IMPORTCONTABIL 
--		 WHERE HISTORICO LIKE '%estorno%')
--	and DT_ENVIO_CONTAB is null

