/*  
FN_FCAV_LISTLANCH_MON  
  
Função que retorna a quantidade de monitores de uma sala em uma data  
  
Autor: João Paulo 
Data: 09/10/2018  
*/  
  
ALTER FUNCTION FN_FCAV_LISTLANCH_MON  (@DATA DATETIME, @SALA VARCHAR (20)) RETURNS VARCHAR (20)  AS  
BEGIN  

DECLARE @QTD_MON VARCHAR(2)

SELECT
	@QTD_MON = COUNT(MONITOR_1)
FROM
	VW_FCAV_MONITOR_AULA VW
	INNER JOIN LY_AGENDA AG ON VW.AGENDA = AG.AGENDA
WHERE 
	VW.DATA	 = @DATA
AND AG.DEPENDENCIA = @SALA
AND AG.TURMA NOT LIKE 'A-PDT%'

				
RETURN @QTD_MON
END
