CREATE FUNCTION FN_FCAV_CAR_HORARIA_EXT (@CURRICULO VARCHAR(100))  
  
RETURNS VARCHAR (100)  
  
BEGIN   
  
DECLARE @HORAS AS VARCHAR(100),   
  @MINUTOS AS VARCHAR(100),  
  @HOR_EXTENSO AS VARCHAR(100),  
  @MIN_EXTENSO AS VARCHAR(100),  
  @CARGA_HORARIA AS VARCHAR(200)  
    
  
    
SELECT   
   
 @HORAS =   CAST(CAST(AULAS_PREVISTAS AS INT) AS VARCHAR),  
 @MINUTOS = IIF((AULAS_PREVISTAS - CAST(AULAS_PREVISTAS AS INT)) = 0, '00', CAST(CAST((AULAS_PREVISTAS - CAST(AULAS_PREVISTAS AS INT))*100 AS INT) AS VARCHAR)),  
 @HOR_EXTENSO =   DBO.FN_FCAV_NUM_EXTENSO(CAST(AULAS_PREVISTAS AS INT)),  
 @MIN_EXTENSO = DBO.FN_FCAV_NUM_EXTENSO(CAST((AULAS_PREVISTAS - CAST(AULAS_PREVISTAS AS INT))*100 AS INT))  
   
FROM   
 LY_CURRICULO  
WHERE  
 CURRICULO = @CURRICULO  
   
 SELECT   @CARGA_HORARIA = @HORAS + 'h' + @MINUTOS + 'min (' + @HOR_EXTENSO + ' horas e ' + @MIN_EXTENSO + ' minutos)'  
  
 RETURN @CARGA_HORARIA  
  
 END   