/*  
FN_FCAV_LISTLANCH_DOC  
  
Função que retorna a quantidade de professores de uma sala em uma data  
  
Autor: João Paulo 
Data: 09/10/2018  
*/  
  
ALTER FUNCTION FN_FCAV_LISTLANCH_DOC  (@DATA DATETIME, @SALA VARCHAR (20)) RETURNS VARCHAR (20)  AS  
BEGIN  

DECLARE @QTD_PROF VARCHAR(2)

SELECT 
	@QTD_PROF = COUNT(DISTINCT DO.NOME_COMPL)
FROM --VW_FCAV_AGENDA_ALUNO_DISCIPLINA
	LY_AGENDA AG   
		INNER JOIN LY_DOCENTE DO	ON DO.NUM_FUNC  = AG.NUM_FUNC  
		INNER JOIN LY_DISCIPLINA DI ON DI.DISCIPLINA = AG.DISCIPLINA  
		INNER JOIN LY_MATRICULA MA  ON MA.DISCIPLINA = AG.DISCIPLINA  
									AND MA.TURMA = AG.TURMA  
									AND MA.ANO = AG.ANO  
									AND MA.SEMESTRE = AG.SEMESTRE
WHERE
	DATA = @DATA
	AND AG.DEPENDENCIA = @SALA
	AND AG.TURMA NOT LIKE 'A-PDT%'
GROUP BY 
	DATA,
	AG.DEPENDENCIA
				
RETURN @QTD_PROF
END
