SELECT 
	PES_CODTEL AS CODIGO,
	PES_NOME collate Latin1_General_CI_AI As NOME,
	PES_NRODOC1 collate Latin1_General_CI_AI AS CPF,
	--CASE WHEN MAL_SITMAT = 'ATIVO' THEN 'Matriculado'		-- 'MATRICULADO','APROVADO','REP FREQ','REP NOTA','CANCELADO','TRANCADO','DISPENSADO','ESPERA','INCONCLUIDO'
	--	   WHEN MAL_SITMAT = 'CANCEL' THEN 'Cancelado'
	--	   WHEN MAL_SITMAT = 'TRANCA' THEN 'Trancado'
	--	   WHEN MAL_SITMAT = 'DESIST' THEN 'Cancelado'
	--	   WHEN MAL_SITMAT = 'TRAEXT' THEN 'Trancado' 
	--END collate Latin1_General_CI_AI AS STATUS_MATRICULA,
	LOWER(PES_EMAIL) collate Latin1_General_CI_AI AS E_MAIL,
	PES_FONE AS FONE,
	PES_FONCEL AS FONE_CELULAR,
	PES_FONCOM AS FONE_COM,
	CONVERT(VARCHAR,ING_DATENT,103) AS DT_INGRESSO,
	CUR_CODCUR collate Latin1_General_CI_AI AS CURSO,
	LTRIM(TUR_CODTUR) collate Latin1_General_CI_AI AS TURMA
	--PAR_ID
	--PAR_DATVCT AS DATA_VENCIMENTO,
	--PPA_ID,
	--PPA_DATPAG AS DATA_PAGAMENTO
FROM
	LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_PESSOA 
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_INGRESSO ON (ING_PESID=PES_ID)
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_CURSO ON (ING_CURID=CUR_ID)
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_MESTRE_ALUNO ON (MAL_INGID=ING_ID)
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_TURMA ON (TUR_ID = MAL_TURID)
	--INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_CONTRATO_FIN ON (CFI_PESID = PES_ID)
	--INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_PARCELA ON (PAR_CFIID = CFI_ID)
	--LEFT OUTER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_PARCELA_PAG ON (PPA_PARID = PAR_ID)
WHERE
	CUR_CODCUR = 'CEGP'
	or CUR_CODCUR = 'CEGP-TI'
	--AND YEAR(PAR_DATVCT) = 2014
	--AND PPA_DATPAG IS NULL
	--AND PAR_DATVCT <= GETDATE()
--	AND PAR_DATVCT >= '2014-03-01 00:00:00.000'
--	AND MAL_SITMAT = 'ATIVO'	

ORDER BY TUR_CODTUR