SELECT 
	TUR_CODTUR AS TURMA,
	
	PPA_DATPAG AS DATA_PAGAMENTO
FROM
	TB_PESSOA 
	INNER JOIN TB_INGRESSO ON (ING_PESID=PES_ID)
	INNER JOIN TB_CURSO ON (ING_CURID=CUR_ID)
	INNER JOIN TB_MESTRE_ALUNO ON (MAL_INGID=ING_ID)
	INNER JOIN TB_TURMA ON (TUR_ID = MAL_TURID)
	INNER JOIN TB_CONTRATO_FIN ON (CFI_PESID = PES_ID)
	INNER JOIN TB_PARCELA ON (PAR_CFIID = CFI_ID)
	LEFT  JOIN TB_PARCELA_PAG ON (PPA_PARID = PAR_ID)
WHERE
	PPA_DATPAG IS NOT NULL
	--AND PAR_DATVCT <= GETDATE()
	--AND PAR_DATVCT >= '2014-03-01 00:00:00.000'
	AND MAL_SITMAT = 'ATIVO'	

ORDER BY TUR_CODTUR