CREATE VIEW VW_FCAV_CRONO_TURMAS_ICORUJA_LYCEUM
AS


SELECT 
	'Icoruja' as SISTEMA,
	UNIDADE collate Latin1_General_CI_AI UNIDADE,
	CURSO collate Latin1_General_CI_AI CURSO,
	CONCURSO collate Latin1_General_CI_AI CONCURSO,
	SIT_PROC_SELETIVO collate Latin1_General_CI_AI SIT_PROC_SELETIVO ,
	TURMA collate Latin1_General_CI_AI TURMA,
	DT_INICIO_TURMA ,
	DT_FIM_TURMA,
	CASE WHEN DT_FIM_TURMA < GETDATE() THEN 'Finalizada'
	ELSE  'EmAndamento'
	END SIT_TURMA,
	YEAR(DT_INICIO_TURMA) AS ANO,
	CASE WHEN (MONTH(DT_INICIO_TURMA)) IN ('1','2','3') THEN '1' 
		 WHEN (MONTH(DT_INICIO_TURMA)) IN ('4','5','6','7') THEN '2'
		 WHEN (MONTH(DT_INICIO_TURMA)) IN ('8','9','10','11','12') THEN '3'
		END AS SEMESTRE , 
	SERIE,
	DISCIPLINA collate Latin1_General_CI_AI DISCIPLINA,
	NOME_DISCIPLINA collate Latin1_General_CI_AI NOME_DISCIPLINA,
	DOCENTE collate Latin1_General_CI_AI DOCENTE,
	E_MAIL collate Latin1_General_CI_AI E_MAIL,
	DATA_INICIO_DISCIPLINA ,
	DIA_DA_SEMANA,
	NUM_AULA,
	DIA_AULA,
	HORA_ENTRADA,
	HORA_SAIDA,
	CARGA_HORARIA,
	MATRICULADOS,
	SALA collate Latin1_General_CI_AI SALA

FROM 
	VW_FCAV_CRONOGRAMA_TURMA_DOCENTE_ICORUJA 

UNION

SELECT 
	'Lyceum' as SISTEMA,
	UNIDADE ,
	CURSO,
	CONCURSO,
	SIT_PROC_SELETIVO,
	TURMA,
	DT_INICIO_TURMA,
	DT_FIM_TURMA,
	CASE WHEN DT_FIM_TURMA < GETDATE() THEN 'Finalizada'
	ELSE  'EmAndamento'
	END SIT_TURMA,
	ANO,
	PERIODO,
	SERIE,
	DISCIPLINA,
	NOME_DISCIPLINA,
	DOCENTE,
	E_MAIL,
	DT_INICIO_DISCIPLINA,
	DIA_DA_SEMANA,
	NUM_AULA,
	DIA_AULA,
	HORA_ENTRADA,
	HORA_SAIDA,
	CARGA_HORARIA,
	MATRICULADOS,
	SALA 
FROM 
	VW_FCAV_CRONOGRAMA_TURMA_DOCENTE


