

use LYCEUM
go

  
SELECT 
	CURSO,
	TURMA,
	MIN(DT_INICIO) AS DT_INICIO,
	MAX(DT_FIM) AS DT_FIM
FROM  
	LY_TURMA
GROUP BY  
	TURMA, CURSO 

UNION all

SELECT 
	CUR_CODCUR collate Latin1_General_CI_AI as CURSO ,
	TUR_CODTUR collate Latin1_General_CI_AI AS TURMA,
	TUR_DATINI AS DT_INICIO,
	TUR_DATFIN AS DT_FIM
FROM
	LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_CURSO
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_TURMA on (TUR_CURID = CUR_ID)
WHERE
	YEAR(TUR_DATINI) >= 2014
	AND TUR_CODTUR LIKE 'A%'
	
UNION all

SELECT 
	CUR_CODCUR collate Latin1_General_CI_AI as CURSO ,
	TUR_CODTUR collate Latin1_General_CI_AI AS TURMA,
	TUR_DATINI AS DT_INICIO,
	TUR_DATFIN AS DT_FIM
FROM
	LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_CURSO
	INNER JOIN LINKED_ICORUJA.vanzolini_icoruja.dbo.TB_TURMA on (TUR_CURID = CUR_ID)
WHERE
	YEAR(TUR_DATINI) >= 2014
	AND CUR_CODCUR LIKE 'P%'