SELECT 
	'Lyceum' AS SISTEMA,
	A.ALUNO AS ALUNO_COD,
	A.NOME_COMPL AS ALUNO_NOME,
	A.TURMA_PREF,
	B.TIPO_BOLSA,
	B.PERC_VALOR AS TIPO,
	--CASE WHEN B.PERC_VALOR = 'Valor' THEN LEFT ((REVERSE(SUBSTRING((REVERSE(B.VALOR * 100)),8,10))  ),LEN(REVERSE(SUBSTRING((REVERSE(B.VALOR * 100)),8,10))  )-2)+ '.' +RIGHT((REVERSE(SUBSTRING((REVERSE(B.VALOR * 100)),8,10))  ),2)
	CASE WHEN B.PERC_VALOR = 'Valor' THEN REPLACE(CAST(CONVERT(MONEY,VALOR) AS VARCHAR),'.',',')
				--ELSE REVERSE(SUBSTRING((REVERSE(B.VALOR * 100)),8,10))+'%' END AS VALOR,
				ELSE CAST(CONVERT(DECIMAL(10,2),B.VALOR*100)AS VARCHAR)  END AS VALOR,
	ISNULL(B.ANOINI,00) AS ANO_INICIAL,
	ISNULL(B.MESINI,00) AS MES_INICIAL,
	ISNULL(B.ANOFIM,00) AS ANO_FINAL,
	ISNULL(B.MESFIM,00) AS MES_FINAL
FROM LY_ALUNO AS A
	INNER JOIN LY_BOLSA AS B ON (A.ALUNO = B.ALUNO)

UNION

select 
	'Icoruja' AS SISTEMA,
	PE.PES_CODTEL collate Latin1_General_CI_AI AS ALUNO_COD,
	PE.pes_nome collate Latin1_General_CI_AI AS ALUNO_NOME,
	tur_descri collate Latin1_General_CI_AI AS TURMA_PREF,
	des_descri collate Latin1_General_CI_AI  TIPO_BOLSA,
	CASE WHEN pda_percen IS NOT NULL THEN 'Percentual' 
		 WHEN pda_valor IS NOT NULL THEN 'Valor'
	END collate Latin1_General_CI_AI AS TIPO,
	CASE WHEN pda_valor IS NOT NULL  THEN REPLACE(CAST(CONVERT(MONEY,pda_valor) AS VARCHAR),'.',',')
				--ELSE REVERSE(SUBSTRING((REVERSE(B.VALOR * 100)),8,10))+'%' END AS VALOR,
				ELSE CAST(CONVERT(DECIMAL(10,2),pda_percen)AS VARCHAR)  
	END AS VALOR,
	CAST(YEAR(pda_valde) AS VARCHAR) AS ANO_INICIAL,
	CAST(MONTH(pda_valde)AS VARCHAR) AS MES_INICIAL,
	CAST(YEAR(pda_valate)AS VARCHAR) AS ANO_FINAL,
	CAST(MONTH(pda_valate)AS VARCHAR) AS MES_FINAL
 
from
 LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_responsavel_desacr
 inner join LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_responsavel_fin on (pda_rfiid = rfi_id)
 inner join LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_contrato_fin on (rfi_cfiid = cfi_id)
 inner join LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_pessoa PE on (cfi_pesid = PE.pes_id)
 inner join LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_turma on (cfi_turid = tur_id)
 inner join LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.tb_desconto on (pda_desid = des_id)
 INNER JOIN LINKED_ICORUJA.VANZOLINI_ICORUJA.dbo.TB_PESSOA RESP ON (RFI_PESID = RESP.PES_ID)
