ALTER VIEW VW_FCAV_SIT_ALUNOS_ICORUJA  
AS  
SELECT   
 PES_ID AS ALUNO,  
 PES_NOME AS NOME_COMPL,  
 CASE WHEN MAL_SITMAT = 'ATIVO' THEN 'Matriculado'  -- 'MATRICULADO','APROVADO','REP FREQ','REP NOTA','CANCELADO','TRANCADO','DISPENSADO','ESPERA','INCONCLUIDO'  
   WHEN MAL_SITMAT = 'CANCEL' THEN 'Cancelado'  
   WHEN MAL_SITMAT = 'TRANCA' THEN 'Trancado'  
   WHEN MAL_SITMAT = 'DESIST' THEN 'Cancelado'  
   WHEN MAL_SITMAT = 'TRAEXT' THEN 'Trancado'   
 END AS STATUS_MATRICULA,  
 CASE CUR_ARCID   
  WHEN '33' THEN 'ESPEC'  
   WHEN '31' THEN 'CAPAC'  
  WHEN '29' THEN 'ATUAL'   
  WHEN '35' THEN 'PALES'  
  WHEN '36' THEN 'PALES'  
  ELSE CAST(ISNULL(CUR_ARCID, '0') AS VARCHAR(20))  
 END AS UNIDADE_RESPONSAVEL,  
    CUR_CODCUR AS CURSO,  
    TUR_CODTUR AS TURMA,  
 (SELECT MIN(TUR_DATINI) FROM TB_TURMA T2 WHERE T1.TUR_CODTUR = T2.TUR_CODTUR GROUP BY TUR_CODTUR) AS DT_INICIO_TURMA,      
 (SELECT MAX(TUR_DATFIN) FROM TB_TURMA T2 WHERE T1.TUR_CODTUR = T2.TUR_CODTUR GROUP BY TUR_CODTUR) AS DT_FIM_TURMA,   
 DIS_DISTEL AS DISCIPLINA,  
 DIS_DESDIS AS NOME_DISCIPLINA,
 TDI_DATINI AS DT_INI_DISCIPLINA  
  
FROM  
TB_INGRESSO  
 INNER JOIN tb_PESSOA ON (ING_PESID = PES_ID)  
 INNER JOIN TB_CURSO ON (ING_CURID=CUR_ID)  
 INNER JOIN TB_MESTRE_ALUNO ON (MAL_INGID=ING_ID)  
 INNER JOIN TB_TURMA T1 ON (TUR_ID = MAL_TURID)  
 INNER JOIN TB_PERIODO_LETIVO ON (PEL_PERID=TUR_PERID)  
 INNER JOIN TB_MESTRE_DISCIPLINA ON (MDI_MALID = MAL_ID)  
 INNER JOIN TB_TURMA_DISCIP ON (MDI_TURDISID = TDI_TURDISID)   
 INNER JOIN TB_DISCIPLINA ON (TDI_DISCID = DIS_DISID)  
 INNER JOIN TB_CRONOGRAMA_AULA_MESTRE tcam ON (CAM_TDIID = TDI_TURDISID)  
 INNER JOIN TB_CRONOGRAMA_AULA_DATA on (CAM_ID = CAD_CAMID)  
 INNER JOIN TB_CRONOGRAMA_AULA ON (CAU_CADID = CAD_ID)  
WHERE   
 CAU_NROAULA = '1'  
 AND TUR_CODTUR NOT LIKE 'CEAI-S%'  