DROP TRIGGER [dbo].[C_TG_CAP_EVENTO_LY_MINI_CURRICULO] 
GO
CREATE TRIGGER [dbo].[C_TG_CAP_EVENTO_LY_MINI_CURRICULO] ON [dbo].[LY_MINI_CURRICULO] 
FOR INSERT
AS  
BEGIN  
	-- Variaveis  
	DECLARE @v_pessoa				VARCHAR(10)
	DECLARE @v_oferta_de_curso		NUMERIC(10)
	
	-- Buscando valores da chave da tabela   
	SELECT TOP 1 
		@v_pessoa = i.PESSOA
	,	@v_oferta_de_curso = CONVERT(NUMERIC(10), ct.OFERTA_DE_CURSO)
	FROM LY_PROSPECTO_CAPTACAO_CANDIDATO_TMP ct
	INNER JOIN LY_PROSPECTO_CAPTACAO pc WITH (NOLOCK) ON ct.ID_PROSPECTO_CAPTACAO = pc.ID_PROSPECTO_CAPTACAO
	INNER JOIN INSERTED i WITH (NOLOCK) ON pc.PESSOA = i.PESSOA 
	WHERE ct.ORDEM = 1 ORDER BY DT_INCLUSAO DESC
	 
	IF NOT EXISTS (SELECT 1 FROM LY_INTEGRACAO_FILA_EVENTOS 
				   WHERE SISTEMA_DESTINO = 'SharpSpring' AND  OBJETO = 'INSCRICAO' 
					AND OPERACAO = 'I' AND CHAVE_1 = @v_pessoa AND  CHAVE_2 = @v_oferta_de_curso) AND @v_pessoa IS NOT NULL
	BEGIN
		-- Gravando na tabela de integração   
		INSERT INTO LY_INTEGRACAO_FILA_EVENTOS (DATA_INCLUSAO, SISTEMA_DESTINO, OBJETO, OPERACAO, CHAVE_1, CHAVE_2)  
		VALUES (GETDATE(), 'SharpSpring', 'ANEXO DE CURRICULO', 'I', @v_pessoa, @v_oferta_de_curso)  
	END

END 
GO 
