
if object_id('LY_OPCOES_VEST') is not null begin
	drop view LY_OPCOES_VEST end
go
CREATE VIEW LY_OPCOES_VEST AS  
SELECT op.CONCURSO, CURSO_OFERTADO CURSO_VEST, op.CANDIDATO, op.ORDEM, oc.TURNO
from LY_OFERTA_CURSO oc, LY_OPCOES_PROC_SELETIVO op, LY_SUB_GRUPO_OFERTA sgo
where oc.OFERTA_DE_CURSO=op.OFERTA_DE_CURSO
and oc.ID_SUB_GRUPO_OFERTA=sgo.ID_SUB_GRUPO_OFERTA
