SELECT * FROM LY_RESP_FINAN WHERE TITULAR LIKE '%VANZOLINI%'

SELECT * FROM VW_FCAV_VALOR_OFERTA_CURSO order by OFERTA_DE_CURSO desc

update LY_OFERTA_CURSO
set
	VALOR_A_VISTA_ESTIMADO = VALOR_DO_CURSO
FROM 
	LY_OFERTA_CURSO OC
	INNER JOIN VW_FCAV_VALOR_OFERTA_CURSO VO ON OC.OFERTA_DE_CURSO = VO.OFERTA_DE_CURSO
WHERE
	OC.OFERTA_DE_CURSO = 1181
	
select * from VW_FCAV_INI_FIM_CURSO_TURMA where TURMA = 'cepsng t 01'

SELECT * FROM LY_PLANOS_OFERTADOS WHERE OFERTA_DE_CURSO = 1181

update LY_PLANOS_OFERTADOS
set
	PLANO = OFERTA_DE_CURSO
where
	OFERTA_DE_CURSO = 896

UPDATE HD_NUMERACAO
SET
	LASTNUM = 5000
WHERE
	TIPO= 'CANDIDATO'
	
