SELECT 
CO.CONCURSO,
CA.CANDIDATO,
NOME_COMPL,
SIT_CANDIDATO_VEST,
DT_INSCRICAO,
FC.DATA_INSC
FROM
	LY_CANDIDATO CA
	INNER JOIN LY_CONCURSO CO
		ON CO.CONCURSO = CA.CONCURSO
	INNER JOIN FCAV_CANDIDATOS FC
		ON FC.CANDIDATO = CA.CANDIDATO
		AND FC.CONCURSO = CA.CONCURSO
WHERE	
	CO.ANO >= 2016
AND	FC.DATA_INSC IS NULL