SELECT 
	*
FROM
	VW_FCAV_VALOR_OFERTA_CURSO
WHERE
	ANO >=2016
	AND UNIDADE_RESPONSAVEL = 'ESPEC'
	--AND TURMA = 'CEAI T 99'
ORDER BY 
	TURMA


SELECT  
        ST.UNIDADE_RESPONSAVEL,
        ST.TURMA,
        ST.OFERTA_DE_CURSO,
        vsp.*
    FROM LY_VALOR_SERV_PERIODO VSP  
    INNER JOIN VW_FCAV_SERVICO_TURMA ST  
        ON VSP.SERVICO = ST.SERVICO
        AND VSP.ANO = ST.ANO
        AND VSP.PERIODO = ST.SEMESTRE   
    WHERE VSP.SERVICO LIKE 'MENS%'
		AND ST.TURMA = 'CEAI T 20'
	GROUP BY ST.UNIDADE_RESPONSAVEL,
		  ST.TURMA,
		  ST.OFERTA_DE_CURSO,
		  VSP.SERVICO,
		  VSP.ANO,
		  VSP.PERIODO,
		  VSP.CUSTO_UNITARIO