/*
    VIEW VW_FCAV_SERVICO_TURMA
Descrição:
	View para trazer o serviço que está associado a turma.

Autor: Gabriel S. Scalione
Criado: 2014-09-26 15:20:15.767
*/



ALTER VIEW VW_FCAV_SERVICO_TURMA
AS

SELECT
    VT.UNIDADE_RESPONSAVEL,
    VT.CURSO,
    VT.TURNO,
    VT.CURRICULO,
    VT.TURMA,
    OC.ANO_INGRESSO AS ANO,
    OC.PER_INGRESSO AS SEMESTRE,
    VT.OFERTA_DE_CURSO,
    VT.CONCURSO AS CONCURSO,
    ISNULL(CR.SERVICO, D.SERVICO) AS SERVICO
FROM LY_TURMA TU
INNER JOIN LY_CURRICULO CR
    ON (CR.CURSO = TU.CURSO
    AND CR.TURNO = TU.TURNO
    AND CR.CURRICULO = TU.CURRICULO)
INNER JOIN LY_DISCIPLINA D
    ON (TU.DISCIPLINA = D.DISCIPLINA)
INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
    ON (VT.TURMA = TU.TURMA)
INNER JOIN LY_OFERTA_CURSO OC
	ON OC.OFERTA_DE_CURSO = VT.OFERTA_DE_CURSO
GROUP BY VT.UNIDADE_RESPONSAVEL,
		 VT.CURSO,
		 VT.TURNO,
		 VT.CURRICULO,
		 VT.TURMA,
		 OC.ANO_INGRESSO,
		 OC.PER_INGRESSO,
         VT.OFERTA_DE_CURSO,
         VT.CONCURSO,
         CR.SERVICO,
         D.SERVICO