-- SELECT APENAS PARA COMPARAÇÃO ENTRE A TURMA E A OFERTA DE CURSO
SELECT 
	TU.TURMA, 
	TU.FL_FIELD_01 as TF01_ValorCurso,
	TU.FL_FIELD_03 as TF03_ValoParcela,
	TU.FL_FIELD_04 as TF04_QdeParcela,
	TU.FL_FIELD_05 as TF05_DescPlanAvista,
	TU.FL_FIELD_06 as TF06_VenctoBoleto1,
	TU.FL_FIELD_07 AS TF07_DiaVenctoBoleto,
	
	OC.FL_FIELD_05 AS OF05_ValorTotalCurso,  
	OC.FL_FIELD_06 AS OF06_ValorParcela,
	OC.FL_FIELD_07 AS OF07_QtdeParcela,  
	OC.FL_FIELD_08 AS OF08_DescPlanAvista,
	OC.FL_FIELD_09 AS OF09_VenctoBoleto1,  
	OC.FL_FIELD_10 AS OF10_DiaVenctoBoleto
	
FROM 
	LY_TURMA TU
	INNER JOIN LY_OPCOES_OFERTA OO   
		ON OO.TURMA = TU.TURMA  
	INNER JOIN LY_OFERTA_CURSO OC  
		ON OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO  
WHERE 
	TU.SERIE IN ('0','1')
	AND OC.ANO_INGRESSO >= 2016
GROUP BY 
	TU.TURMA, 
	TU.FL_FIELD_01,
	TU.FL_FIELD_03,
	TU.FL_FIELD_04,
	TU.FL_FIELD_05,
	TU.FL_FIELD_06,
	TU.FL_FIELD_07,
	OC.FL_FIELD_05,  
	OC.FL_FIELD_06,
	OC.FL_FIELD_07,  
	OC.FL_FIELD_08,
	OC.FL_FIELD_09,  
	OC.FL_FIELD_10

-- UPDATE NA LY_OFERTA_CURSO TRAZENDO OS VALORES TOTAL DO CURSO E MENSALIDADE CADASTRADOS NA TURMA.
UPDATE
	LY_OFERTA_CURSO
SET
	FL_FIELD_05 = TU.FL_FIELD_01,
	FL_FIELD_06 = TU.FL_FIELD_03,
	FL_FIELD_07 = TU.FL_FIELD_04,
	FL_FIELD_08 = TU.FL_FIELD_05,
	FL_FIELD_09 = TU.FL_FIELD_06,
	FL_FIELD_10 = TU.FL_FIELD_07
FROM
	LY_TURMA TU
	INNER JOIN LY_OPCOES_OFERTA OO   
		ON OO.TURMA = TU.TURMA  
	INNER JOIN LY_OFERTA_CURSO OC  
		ON OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO  
WHERE 
	TU.SERIE IN ('0','1')
	AND OC.ANO_INGRESSO >= 2016
