ALTER TRIGGER [dbo].[TR_FCVA_INSERE_TURMA_SERIE]  
  ON [dbo].[LY_TURMA]  
 FOR INSERT  
AS  
  SET NOCOUNT ON  
    
 -- TRIGGER CRIADA PARA AUTOMATIZAR A CRIAÇÃO DA TURMA SÉRIE PARA OS CURSOS DO TIPO PALESTRA  
 -- ESSA INSERÇÃO É NECESSÁRIO PARA UTILZIAÇÃO CORRETA DO QUADRO DE VAGAS E LISTA DE ESPERA  
   
 DECLARE @v_UNID_RESP T_CODIGO  
   
 SELECT @v_UNID_RESP = UNIDADE_RESPONSAVEL FROM inserted  
   
 IF (@v_UNID_RESP = 'PALES'  
 AND NOT EXISTS (SELECT 1 FROM LY_GRADE_SERIE S JOIN inserted I ON S.CURSO = I.CURSO AND S.TURNO = I.TURNO  
    AND S.CURRICULO = I.CURRICULO AND S.SERIE = I.SERIE AND S.ANO = I.ANO AND S.SEMESTRE = I.SEMESTRE AND S.GRADE = I.TURMA))  
 BEGIN  
   
 INSERT INTO LY_GRADE_SERIE (CURSO,TURNO,CURRICULO,SERIE,ANO,SEMESTRE,GRADE,CAPACIDADE,NUM_FUNC,FACULDADE,DEPENDENCIA,DT_INICIO,DT_FIM,  
  FORMULA_MF1,FORMULA_MF3,FORMULA_MF2,FORMULA_CA1,FORMULA_CA2,FORMULA_CA3,CONCEITO_MIN_1,CONCEITO_MIN_2,CONCEITO_MIN_3,CONCEITO_MIN_EX,  
  CONCEITO_MIN_EX_2,ULT_NUM_CHAMADA,UNIDADE_RESPONSAVEL,DATA_NUMERACAO,FL_FIELD_01,OBS_FORMULA_MF1,OBS_FORMULA_MF2,OBS_FORMULA_MF3,  
  STAMP_ATUALIZACAO,FL_FIELD_02,FL_FIELD_03,FL_FIELD_04,FL_FIELD_05,FL_FIELD_06,FL_FIELD_07,FL_FIELD_08,FL_FIELD_09,FL_FIELD_10)  
  SELECT CURSO,TURNO,CURRICULO,SERIE,ANO,SEMESTRE,  
    TURMA AS GRADE,  
    NUM_ALUNOS AS CAPACIDADE,  
    NUM_FUNC,FACULDADE,DEPENDENCIA,DT_INICIO,DT_FIM,FORMULA_MF1,FORMULA_MF3,FORMULA_MF2,FORMULA_CA1,  
    FORMULA_CA2,FORMULA_CA3,CONCEITO_MIN_1,CONCEITO_MIN_2,CONCEITO_MIN_3,CONCEITO_MIN_EX,CONCEITO_MIN_EX_2,  
    ULT_NUM_CHAMADA,UNIDADE_RESPONSAVEL,  
    NULL AS DATA_NUMERACAO,  
    FL_FIELD_01,OBS_FORMULA_MF1,OBS_FORMULA_MF2,OBS_FORMULA_MF3,STAMP_ATUALIZACAO,FL_FIELD_02,FL_FIELD_03,  
    FL_FIELD_04,FL_FIELD_05,FL_FIELD_06,FL_FIELD_07,FL_FIELD_08,FL_FIELD_09,FL_FIELD_10  
   FROM inserted  
     
 INSERT INTO LY_GRADE_TURMA  
  SELECT DISCIPLINA,TURMA,ANO,SEMESTRE,  
    @@IDENTITY AS GRADE_ID  
   FROM inserted     
    
 END  
   
  SET NOCOUNT OFF