  
ALTER VIEW VW_FCAV_LINK_OFERTA_CURSO AS    
    
SELECT  
 CASE WHEN CURSO.FACULDADE = 'ATUAL' THEN 'Atualização'    
  WHEN CURSO.FACULDADE = 'CAPAC' THEN 'Capacitação'    
  WHEN CURSO.FACULDADE = 'ESPEC' THEN 'Especialização'    
  WHEN CURSO.FACULDADE = 'PALES' THEN 'Palestra'    
   END AS AREA,  
  CASE WHEN  OFERTA.CONCURSO IS NULL THEN V.TURMA  
    ELSE OFERTA.CONCURSO END AS CONCURSO,   
 OFERTA.OFERTA_DE_CURSO,   
 CASE WHEN  OFERTA.CONCURSO IS NULL THEN 'VD'  
   ELSE 'PS'END AS TIPO_INSCRICAO,  
 OFERTA.DESCRICAO_COMPL AS DESCRICAO,   
 CONVERT(VARCHAR,OFERTA.DTINI,103) AS DATA_INICIAL,    
 CONVERT(VARCHAR,OFERTA.DTFIM,103) AS DATA_FIM,    
 CASE WHEN V.DT_INICIO IS null then '01/01/1900'    
  ELSE    
   CONVERT(DATETIME,V.DT_INICIO)  
 END AS INICIO_DO_CURSO,    
 'http://sga.vanzolini.org.br:8080/web/converte_link_portal.asp?OFERTA_DE_CURSO=' + CONVERT(VARCHAR, OFERTA.OFERTA_DE_CURSO) AS LINK  
FROM    
 LY_OFERTA_CURSO AS OFERTA    
 INNER JOIN LY_CURSO AS CURSO ON (OFERTA.CURSO = CURSO.CURSO)    
 INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA AS V ON  V.OFERTA_DE_CURSO = OFERTA.OFERTA_DE_CURSO  
 --INNER JOIN LY_CONCURSO AS CONCURSO ON (OFERTA.CONCURSO = CONCURSO.CONCURSO)    
    
WHERE    
 OFERTA.DTFIM >= DATEADD(DAY,-30,GETDATE()) 