
/*----------- BLOCO UPDATE DOS FLEX_FIELDS DA OFERTA DE CURSO -------------*/
UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 1,
    DESCRICAO_TELA = 'Enviar Formulário para o Financeiro?',
    TIPO_DADO = 'Texto',
    TAMANHO = 3,
    SQL_LISTA_VALORES = 'SELECT ''SIM'' AS VALOR, ''SIM'' AS DESCRICAO'
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_01'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 2,
    DESCRICAO_TELA = 'Enviar Formulário para Secretaria?',
    TIPO_DADO = 'Texto',
    TAMANHO = 3,
    SQL_LISTA_VALORES = 'SELECT ''SIM'' AS VALOR, ''SIM'' AS DESCRICAO'
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_02'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 3,
    DESCRICAO_TELA = 'Atualizar os dados do Portal',
    TIPO_DADO = 'Texto',
    TAMANHO = 3,
    SQL_LISTA_VALORES = 'SELECT ''SIM'' AS VALOR, ''SIM'' AS DESCRICAO'
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_03'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 4,
    DESCRICAO_TELA = 'Programa',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_04'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 5,
    DESCRICAO_TELA = 'Valor Total do Curso sem Desconto',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_05'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 6,
    DESCRICAO_TELA = 'Valor da Parcela',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000

WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_06'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 7,
    DESCRICAO_TELA = 'Quantidade de Parcelas',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_07'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 8,
    DESCRICAO_TELA = 'Desconto p/ Plano À Vista (%)',
    TIPO_DADO = 'Texto',
    TAMANHO = 200
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_08'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 9,
    DESCRICAO_TELA = 'Vencto 1º boleto após aceite (Dias)',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_09'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 10,
    DESCRICAO_TELA = 'Dia para Vencto das próximas Mensalidades',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_OFERTA_CURSO'
AND FLEX_FIELD = 'FL_FIELD_10'


/*----------- BLOCO UPDATE DOS FLEX_FIELDS DO CURSO -------------*/

UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 1,
    DESCRICAO_TELA = 'Apresentação:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_01'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 2,
    DESCRICAO_TELA = 'Objetivos:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_02'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 3,
    DESCRICAO_TELA = 'Corpo Docente:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_03'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 4,
    DESCRICAO_TELA = 'Diferencial:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_04'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 5,
    DESCRICAO_TELA = 'Perfil do Aluno:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_05'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 6,
    DESCRICAO_TELA = 'Certificação:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_06'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 7,
    DESCRICAO_TELA = 'Metodologia:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_07'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 8,
    DESCRICAO_TELA = 'Avaliação:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_08'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 9,
    DESCRICAO_TELA = 'Investimento:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_09'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 10,
    DESCRICAO_TELA = 'Processo Seletivo:',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CURSO'
AND FLEX_FIELD = 'FL_FIELD_10'


/*----------- BLOCO UPDATE DOS FLEX_FIELDS DO CONCURSO -------------*/

UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 1,
    DESCRICAO_TELA = 'CRITÉRIO: Análise Curricular',
    TIPO_DADO = 'Texto',
    TAMANHO = 1
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_01'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 2,
    DESCRICAO_TELA = 'CRITÉRIO: Entrevista',
    TIPO_DADO = 'Texto',
    TAMANHO = 1
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_02'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 3,
    DESCRICAO_TELA = 'CRITÉRIO: Prova',
    TIPO_DADO = 'Texto',
    TAMANHO = 1
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_03'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 4,
    DESCRICAO_TELA = 'CRITÉRIO: Redação',
    TIPO_DADO = 'Texto',
    TAMANHO = 1
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_04'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 5,
    DESCRICAO_TELA = 'Alteração Conteúdo Programático',
    TIPO_DADO = 'Texto',
    TAMANHO = 1
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_05'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 6,
    DESCRICAO_TELA = 'Dia e Horário das Aulas',
    TIPO_DADO = 'Texto',
    TAMANHO = 200
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_06'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 7,
    DESCRICAO_TELA = 'Relação de Documentos',
    TIPO_DADO = 'Texto',
    TAMANHO = 2000
WHERE TABELA = 'LY_CONCURSO'
AND FLEX_FIELD = 'FL_FIELD_07'



/*----------- BLOCO UPDATE DOS FLEX_FIELDS DO CANDIDATO -------------*/

UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 1,
    DESCRICAO_TELA = 'Data Análise Financeira',
    TIPO_DADO = 'Data',
    TAMANHO = 10
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_01'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 2,
    DESCRICAO_TELA = 'Result. Análise Financeira - PF',
    TIPO_DADO = 'Texto',
    TAMANHO = 50,
    SQL_LISTA_VALORES = 'SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = ''LY_CANDIDATO'' AND OPCAO = ''Analise Finan'

WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_02'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 3,
    DESCRICAO_TELA = 'Result. Análise Financeira - PJ',
    TIPO_DADO = 'Texto',
    TAMANHO = 50,
    SQL_LISTA_VALORES = 'SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = ''LY_CANDIDATO'' AND OPCAO = ''Analise Finan'

WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_03'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 4,
    DESCRICAO_TELA = 'Data Seleção Coordenador',
    TIPO_DADO = 'Data',
    TAMANHO = 10
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_04'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 5,
    DESCRICAO_TELA = 'Resultado Seleção Coordenador',
    TIPO_DADO = 'Texto',
    TAMANHO = 50,
    SQL_LISTA_VALORES = 'SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = ''LY_CANDIDATO'' AND OPCAO = ''Resultado Selecao Coord'
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_05'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 6,
    DESCRICAO_TELA = 'Data Notificação Seleção',
    TIPO_DADO = 'Texto',
    TAMANHO = 10
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_06'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 7,
    DESCRICAO_TELA = 'Definição Desistência',
    TIPO_DADO = 'Texto',
    TAMANHO = 50,
    SQL_LISTA_VALORES = 'SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = ''LY_CANDIDATO'' AND OPCAO = ''Definicao Desistencia'
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_07'


UPDATE LY_FLEX_FIELDS
SET ORDEM_TELA = 8,
    DESCRICAO_TELA = 'Motivo Desistência',
    TIPO_DADO = 'Texto',
    TAMANHO = 50,
    SQL_LISTA_VALORES = 'SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = ''LY_CANDIDATO'' AND OPCAO = ''Motivo Desistencia'
WHERE TABELA = 'LY_CANDIDATO'
AND FLEX_FIELD = 'FL_FIELD_08'