SELECT DISTINCT VW_FCAV_INI_FIM_CURSO_TURMA.CONCURSO, 
                LY_AGENDA.DATA, 
                LY_AGENDA.HORA_INICIO, 
                LY_AGENDA.HORA_FIM, 
                LY_AGENDA.DISCIPLINA, 
                LY_DOCENTE.NOME_COMPL, 
                LY_AGENDA.ANO, 
                LY_AGENDA.SEMESTRE, 
                LY_AGENDA.DEPENDENCIA, 
                VW_FCAV_LINK_OFERTA_CURSO_COMPLETA.DESCRICAO, 
                VW_FCAV_VERIFICA_CENTRO_CUSTO.CENTRO_CUSTO_HADES, 
                VW_FCAV_INI_FIM_CURSO_TURMA.DT_INICIO, 
                VW_FCAV_INI_FIM_CURSO_TURMA.DT_FIM, 
                LY_DISCIPLINA.NOME_COMPL, 
                LY_DISCIPLINA.DISCIPLINA, 
                VW_FCAV_INI_FIM_CURSO_TURMA.CURSO, 
                VW_FCAV_INI_FIM_CURSO_TURMA.TURMA, 
                VW_FCAV_MONITOR_AULA.MONITOR_1, 
                VW_FCAV_MONITOR_AULA.MONITOR_2 
FROM   VW_FCAV_INI_FIM_CURSO_TURMA 
       INNER JOIN LY_AGENDA 
               ON VW_FCAV_INI_FIM_CURSO_TURMA.TURMA = LY_AGENDA.TURMA 
       INNER JOIN VW_FCAV_LINK_OFERTA_CURSO_COMPLETA 
               ON VW_FCAV_INI_FIM_CURSO_TURMA.CONCURSO = 
                  VW_FCAV_LINK_OFERTA_CURSO_COMPLETA.CONCURSO 
       INNER JOIN VW_FCAV_VERIFICA_CENTRO_CUSTO 
               ON VW_FCAV_INI_FIM_CURSO_TURMA.CONCURSO = 
                  VW_FCAV_VERIFICA_CENTRO_CUSTO.CONCURSO 
       INNER JOIN LY_DOCENTE 
               ON LY_AGENDA.NUM_FUNC = LY_DOCENTE.NUM_FUNC 
       INNER JOIN LY_DISCIPLINA 
               ON LY_AGENDA.DISCIPLINA = LY_DISCIPLINA.DISCIPLINA 
       LEFT OUTER JOIN VW_FCAV_MONITOR_AULA 
                    ON LY_AGENDA.DISCIPLINA = VW_FCAV_MONITOR_AULA.DISCIPLINA 
                       AND LY_AGENDA.TURMA = VW_FCAV_MONITOR_AULA.TURMA 
                       AND LY_AGENDA.DATA = VW_FCAV_MONITOR_AULA.DATA 
                       AND LY_AGENDA.AGENDA = VW_FCAV_MONITOR_AULA.AGENDA 
WHERE  VW_FCAV_INI_FIM_CURSO_TURMA.CURSO = 'A-PDT' 
       AND LY_AGENDA.ANO = 2018 
       AND LY_AGENDA.SEMESTRE = 0 
       AND VW_FCAV_INI_FIM_CURSO_TURMA.TURMA = 'A-PDT T 02' 
       AND LY_AGENDA.DISCIPLINA = 'A-PDT' 
ORDER  BY VW_FCAV_INI_FIM_CURSO_TURMA.CONCURSO, 
          LY_AGENDA.DISCIPLINA, 
          LY_AGENDA.DATA 