SELECT 
	AL.ANO_INGRESSO,
	COUNT(AL.ALUNO) ALUNOS_RESP_PJ
FROM
 LY_PLANO_PGTO_PERIODO PP
 INNER JOIN LY_RESP_FINAN RF 
	ON PP.RESP = RF.RESP
 INNER JOIN LY_ALUNO AL
	ON AL.ALUNO = PP.ALUNO
WHERE
	CGC_TITULAR IS NOT NULL
    AND AL.SIT_ALUNO = 'Ativo'

 GROUP BY
	AL.ANO_INGRESSO

ORDER BY AL.ANO_INGRESSO
 