SELECT
	CURSO,
	OC.OFERTA_DE_CURSO,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,
	OO.TURMA,
	CASE WHEN BO.EXIBE = 'S' THEN
		'Habilitado'
	ELSE
		'Não Habilitado' 
	END	AS UPLOADCURRICULO,
	BO.EXIBE,
	BO.OBRIGATORIO_INSTITUICAO	
FROM
	LY_OFERTA_CURSO OC
	INNER JOIN LY_OPCOES_OFERTA OO
		ON OO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
	INNER JOIN	LY_BLOCO_INSC_OFERTA_CURSO BI
		ON BI.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
	INNER JOIN LY_BLOCO_INSC_ITENS_OFERTADO BO
		ON BO.ID_BLOCO_INSC_OFERTA_CURSO = BI.ID_BLOCO_INSC_OFERTA_CURSO
WHERE BO.ID_BLOCO_INSC_ITENS = 44
	AND OC.ANO_INGRESSO >=2017
	AND OC.DTFIM >=GETDATE()
GROUP BY
	CURSO,
	OC.OFERTA_DE_CURSO,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,
	OO.TURMA,
	BO.EXIBE,
	BO.OBRIGATORIO_INSTITUICAO	