SELECT 
	CA.CANDIDATO,
	CA.CONCURSO,
	CV.CHAMADA
FROM 
	LY_CANDIDATO CA
	LEFT JOIN LY_CONVOCADOS_VEST CV ON CA.CANDIDATO = CV.CANDIDATO
WHERE CA.CONCURSO = 'CEPSNG T 01'

SELECT
	ca.DT_INSCRICAO,
	PE.PESSOA,
	PE.NOME_COMPL,
	PE.E_MAIL,
	DBO.DECRYPT(PE.SENHA_TAC) SENHA,
	CA.CANDIDATO,
	CA.CONCURSO,
	CA.SIT_CANDIDATO_VEST,
	OC.OFERTA_DE_CURSO,
	AL.ALUNO,
	AL.CURSO,
	AL.TURNO,
	AL.CURRICULO,
	AL.ANO_INGRESSO,
	AL.SEM_INGRESSO
	
FROM
	LY_CANDIDATO CA 
	INNER JOIN LY_PESSOA PE 
		ON PE.PESSOA = CA.PESSOA
	LEFT JOIN LY_ALUNO AL 
		ON AL.CANDIDATO = CA.CANDIDATO 
		AND AL.CONCURSO = CA.CONCURSO
	INNER JOIN LY_OFERTA_CURSO OC
		ON OC.CONCURSO = CA.CONCURSO
order by al.ALUNO desc

VW_PESSOA_OFERTA_CURSO 
go
SELECT * FROM ly_curriculo_contrato where curso = 'CEGP' AND CURRICULO = 'CEGP 2017/2'


SELECT * FROM LY_CONTRATO WHERE aluno ='E201710014' and CONCURSO = 'CEPSNG T 02'
select * from LY_CURRICULO_CONTRATO where CURSO = 'CEGP' and CURRICULO = 'CEGP 2018/1'
select * from ly_pessoa where pessoa = 109088


SELECT * FROM LY_PLANO_PGTO_PERIODO WHERE ALUNO = 'E201710008'


SELECT * FROM LY_OFERTA_CURSO WHERE CONCURSO = 'CCGB T 44'


EXEC a_TAGS_CUSTOM_CONTRATO  'E201810051',2018,1,415,1457

EXEC a_TAGS_CUSTOM_CONTRATO  'C201700084',2017,1,355,1291

SELECT * FROM LY_CONCURSO

SELECT 
 T.name AS Tabela, 
 C.name AS Coluna
FROM 
 sys.sysobjects    AS T (NOLOCK) 
INNER JOIN sys.all_columns AS C (NOLOCK) ON T.id = C.object_id AND T.XTYPE = 'U' 
WHERE 
 C.NAME LIKE '%N_DIAS_VENC_BOL_MATR%'
ORDER BY 
 T.name ASC
