SELECT 
	CONCURSO,
	CANDIDATO,
	DOC_ENTREGUE,
	ISENTO 
FROM 
	LY_CANDIDATO 
WHERE 
	ISENTO = 'N'
    AND CANDIDATO LIKE '2017%'

SELECT CANDIDATO, CONCURSO, SIT_CANDIDATO_VEST FROM LY_CANDIDATO WHERE CANDIDATO = '201700370'