SELECT
    T.TURMA,
    (SELECT
        NOME
    FROM LY_DISCIPLINA D
    WHERE D.DISCIPLINA = T.DISCIPLINA)
    NOME_CURSO,
    CONVERT(varchar, T.DT_INICIO, 103) AS DT_INICIO,
    CONVERT(varchar, T.DT_FIM, 103) AS DT_FIM,
    T.CLASSIFICACAO,
    CASE
        WHEN DATEDIFF(DAY, T.DT_FIM, GETDATE()) > 0 THEN 'Fechada'
        WHEN DATEDIFF(DAY, T.DT_FIM, GETDATE()) = 0 THEN 'EmAndamento'
        WHEN DATEDIFF(DAY, T.DT_FIM, GETDATE()) < 0 THEN 'Aberta'
    END AS SIT_TURMA,
    MAX(NUM_ALUNOS) MAX_ALUNOS,
    C.VAGAS,
    (SELECT
        COUNT(VMP.ALUNO)
    FROM VW_MATRICULA_E_PRE_MATRICULA VMP
    WHERE T.TURMA = VMP.TURMA) AS TOTAL_INSCRITOS,
    (SELECT
        COUNT(PM.ALOCADO)
    FROM LY_PRE_MATRICULA PM
    WHERE ALOCADO = 'S'
    AND T.TURMA = PM.TURMA)  AS ALOCADOS,
    (SELECT
        COUNT(PM.ALOCADO)
    FROM LY_PRE_MATRICULA PM
    WHERE ALOCADO = 'N'
    AND T.TURMA = PM.TURMA)  AS NAO_ALOCADOS
FROM LY_TURMA T
	INNER JOIN LY_CURSO C
		ON C.CURSO = T.CURSO

WHERE T.UNIDADE_RESPONSAVEL = 'PALES'
AND T.CLASSIFICACAO <> 'Concluido'
--AND T.ANO >= 2016
--AND DATEDIFF(DAY, T.DT_FIM, GETDATE()) <= 0
GROUP BY T.DT_INICIO,
         T.DT_FIM,
         T.TURMA,
         NUM_ALUNOS,
         C.VAGAS,
         T.CLASSIFICACAO,
         T.DISCIPLINA
PRINT ('ACOMPANHAMENTO DAS INSCRIÇÕES EM PALESTRAS  ********** ')

GO