SELECT
  ALUNO,
  NOME_COMPL,
  CS.FACULDADE AS UNID_RESP,
  HA.CURSO,
  TURMA,
  DISCIPLINA,
  ANO,
  SEMESTRE,
  DT_INICIO,
  DT_FIM,
  NOTA_FINAL,
  FREQUENCIA,
  SITUACAO_HIST
  INTO #TMP_MEDIA_FINAL_ALUNO_TURMA
FROM VW_FCAV_HISTORICO_ACADEMICO HA
	INNER JOIN LY_CURSO CS
		ON CS.CURSO = HA.CURSO
WHERE 
	CS.FACULDADE IN ('ESPEC', 'CAPAC')
GROUP BY 
	ALUNO,
	NOME_COMPL,
	CS.FACULDADE,
	HA.CURSO,
	TURMA,
	DISCIPLINA,
	ANO,
	SEMESTRE,
	DT_INICIO,
	DT_FIM,
	NOTA_FINAL,
	FREQUENCIA,
	SITUACAO_HIST

DROP TABLE #TMP_MEDIA_FINAL_ALUNO_TURMA

SELECT * FROM LY_TURMA WHERE TURMA = 'CCUPGRADE T 16'	
	
SELECT
    MF.UNID_RESP,
    MF.CURSO,
    MF.TURMA,
    CT.DT_INICIO,
    CT.DT_FIM,
    (SELECT TOP 1
        CASE
            WHEN CLASSIFICACAO != 'Cancelado' AND
               (CONVERT(VARCHAR,CT.DT_INICIO,112) > CONVERT(VARCHAR,GETDATE(),112)) THEN 'Em Inscrição'
            WHEN CLASSIFICACAO != 'Cancelado' AND
                CONVERT(VARCHAR,GETDATE(),112) BETWEEN CONVERT(VARCHAR,CT.DT_INICIO,112) 
													AND CONVERT(VARCHAR,CT.DT_FIM,112) THEN 'Em Andamento'
            WHEN CLASSIFICACAO != 'Cancelado' AND
                (CONVERT(VARCHAR,CT.DT_FIM,112) <= CONVERT(VARCHAR,GETDATE(),112)) THEN 'Concluido'
            WHEN CLASSIFICACAO LIKE 'Cancel%' THEN 'Cancelada'
           
        END
    FROM LY_TURMA TU
    WHERE TU.TURMA = MF.TURMA
    AND TU.SERIE = 1
    AND CLASSIFICACAO IS NOT NULL
    GROUP BY CLASSIFICACAO)  AS STATUS_TURMA,
    MF.ALUNO,
    MF.NOME_COMPL,
    MP.SIT_ALUNO,
    CASE WHEN MF.CURSO = 'CEAI' THEN 11
		WHEN MF.CURSO IN ('CCBB','CCGB','CCUPGRADE') THEN COUNT(MF.DISCIPLINA)
		ELSE(SELECT
			COUNT(DISCIPLINA)
		FROM LY_TURMA TU
		WHERE TU.TURMA = MF.TURMA) 
    END AS DISC_GRADE,
    COUNT(MF.DISCIPLINA) AS DISC_CURSADAS,
    CAST(AVG(MF.NOTA_FINAL) AS decimal(10, 2)) AS MEDIA_NOTA_FINAL,
    CAST(AVG(MF.FREQUENCIA) AS decimal(10, 2)) AS MEDIA_FREQ_FINAL
FROM VW_FCAV_MEDIA_FINAL_ALUNOS MF
INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MP
    ON MP.ALUNO = MF.ALUNO
    AND MP.TURMA = MF.TURMA
INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT
	ON CT.TURMA = MP.TURMA
WHERE
	SIT_ALUNO = 'Ativo'
GROUP BY MF.UNID_RESP,
         MF.CURSO,
         MF.TURMA,
         MP.STATUS_TURMA,
         MF.ALUNO,
         MF.NOME_COMPL,
         MP.SIT_ALUNO,
         CT.DT_INICIO,
         CT.DT_FIM
ORDER BY MF.UNID_RESP, MF.CURSO, MF.TURMA, MF.ALUNO



SELECT
    MF.UNID_RESP,
    MF.CURSO,
    MF.TURMA,
    CT.DT_INICIO,
    CT.DT_FIM,
    (SELECT TOP 1
        CASE
            WHEN CLASSIFICACAO != 'Cancelado' AND
               (CONVERT(VARCHAR,CT.DT_INICIO,112) > CONVERT(VARCHAR,GETDATE(),112)) THEN 'Em Inscrição'
            WHEN CLASSIFICACAO != 'Cancelado' AND
                CONVERT(VARCHAR,GETDATE(),112) BETWEEN CONVERT(VARCHAR,CT.DT_INICIO,112) 
													AND CONVERT(VARCHAR,CT.DT_FIM,112) THEN 'Em Andamento'
            WHEN CLASSIFICACAO != 'Cancelado' AND
                (CONVERT(VARCHAR,CT.DT_FIM,112) <= CONVERT(VARCHAR,GETDATE(),112)) THEN 'Concluido'
            WHEN CLASSIFICACAO LIKE 'Cancel%' THEN 'Cancelada'
           
        END
    FROM LY_TURMA TU
    WHERE TU.TURMA = MF.TURMA
    AND TU.SERIE = 1
    AND CLASSIFICACAO IS NOT NULL
    GROUP BY CLASSIFICACAO)  AS STATUS_TURMA
FROM VW_FCAV_MEDIA_FINAL_ALUNOS MF
INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA MP
    ON MP.ALUNO = MF.ALUNO
    AND MP.TURMA = MF.TURMA
INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA CT
	ON CT.TURMA = MP.TURMA
WHERE
	SIT_ALUNO = 'Ativo'
GROUP BY MF.UNID_RESP,
         MF.CURSO,
         MF.TURMA,
         MP.STATUS_TURMA,
         CT.DT_INICIO,
         CT.DT_FIM
ORDER BY MF.UNID_RESP, MF.CURSO, MF.TURMA