

exec a_Matric_AbreContrato N'C201700121',2017,0,1202,N'LY_PLANO_PGTO_PERIODO'
go

exec a_Matric_AbreContrato N'A201700122',2017,0,1306,N'LY_PLANO_PGTO_PERIODO'
go

exec a_Matric_AbreContrato N'E201710175',2017,1,1194,N'LY_PLANO_PGTO_PERIODO'
go


exec a_Matric_AbreContrato N'C201700080',2017,0,1291,N'LY_PLANO_PGTO_PERIODO'


EXEC PR_FCAV_CONSULTA_PESSOA NULL,'%Lilian De Assis Lago%',NULL,NULL,NULL,NULL
go

SELECT 
	ALUNO, NOME_COMPL, NOME_COMP 
FROM 
	LY_ALUNO A 
	INNER JOIN LY_INSTITUICAO I ON A.OUTRA_FACULDADE = I.OUTRA_FACULDADE
 

SELECT 
	ALUNO, 
	A.TURMA_PREF,
	TURMA,
	OFERTA_DE_CURSO
FROM 
	LY_ALUNO A
	INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA T ON A.TURMA_PREF = T.TURMA_PREF
WHERE 
	TURMA LIKE 'CEGP-TI%'
	AND A.ALUNO LIKE 'A201600683'


SELECT * FROM VW_FCAV_INI_FIM_CURSO_TURMA WHERE TURMA LIKE 'A-an9001.15 t 29'

SELECT * FROM LY_HIST_INSCRONLINE WHERE ALUNO = 'c201600208'

SELECT * FROM LY_PLANO_PGTO_INSCRONLINE P JOIN LY_RESP_FINAN R ON P.RESP = R.RESP
					WHERE R.CGC_TITULAR IS NOT NULL