
/*nome_pessoa   -*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL, '%Leandro Codarin%', NULL, NULL, NULL, NULL


SELECT * FROM LY_ALUNO WHERE ALUNO = 'E201710175' TURMA_PREF = 'A-AT T 08'


SELECT 
	* 
FROM 
	LY_CURRICULO_CONTRATO  CO
	INNER JOIN LY_ALUNO AL 
		ON AL.CURSO = CO.CURSO 
		AND AL.CURRICULO = CO.CURRICULO
		AND AL.TURNO = CO.TURNO
WHERE AL.ALUNO = 'E201710175'

EXEC PR_FCAV_RESET_SENHA_CANDIDATO 106808, NULL

SELECT * FROM LY_CONTRATO_ALUNO_IMG  WHERE ID_CONTRATO_ALUNO = (SELECT ID_CONTRATO_ALUNO FROM LY_CONTRATO_ALUNO  WHERE ALUNO = 'C201600367')

--DELETE LY_CONTRATO_ALUNO  WHERE ALUNO = 'C201600171'
--DELETE LY_CONTRATO_ALUNO_IMG  WHERE ID_CONTRATO_ALUNO = 5837
SELECT * FROM LY_CONVOCADOS_VEST WHERE CANDIDATO = '201600663'

ALTER TABLE [LY_CONTRATO_ALUNO] DISABLE TRIGGER ALL

ALTER TABLE [LY_CONTRATO_ALUNO] ENABLE TRIGGER ALL