USE LYCEUM
GO

SELECT
	SIT_EMAIL_LOTE,
	NUMERO_TENTATIVAS,
	DATA_ULTIMA_TENTATIVA,
	MENSAGEM_ERRO,
	EL.*,
	PESSOA,
	ALUNO,
	EMAIL_DESTINATARIO,
	NOME_DESTINATARIO
FROM LY_EMAIL_LOTE EL 
INNER JOIN LY_EMAIL_LOTE_DEST ED
	ON ED.ID_EMAIL_LOTE = EL.ID_EMAIL_LOTE
ORDER BY EL.ID_EMAIL_LOTE DESC

