SELECT 
 AL.ALUNO,
 MA.TURMA,
 AD.DISCIPLINA,
 AD.DOCENTE,
 QE.QUESTAO, 
 PQ.QUESTIONARIO,
 PQ.APLICACAO,
 PQ.DATA_PART,    
 CO.TIPO,  
 CO.CONCEITO,    
 ISNULL(QE.QUESTAO_OBJETIVA, QE.QUESTAO_SUBJETIVA) AS QUESTAO,    
 isnULL(RE.RESPOSTA_SUBJETIVA,QU.DESCRICAO) AS RESPOSTA
FROM
	LY_ALUNO AL
 LEFT JOIN LY_MATRICULA MA 
	ON MA.ALUNO = AL.ALUNO
 LEFT JOIN LY_AVALIADOR  AV 
	ON AV.ALUNO = MA.ALUNO
 INNER JOIN LY_AVALIADO AD
	ON AD.DISCIPLINA = MA.DISCIPLINA
 LEFT JOIN LY_RESPOSTA RE 
	ON (RE.AVA_CODIGO = AV.CODIGO)    
 LEFT JOIN LY_PARTICIPACAO_QUEST PQ
	ON PQ.TIPO_OBJETO = AV.TIPO_OBJETO
	AND PQ.CODIGO = AV.CODIGO
	AND PQ.TIPO_QUESTIONARIO = RE.TIPO_QUESTIONARIO
 LEFT JOIN LY_CONCEITO_RESPOSTA  CO 
	ON (CO.CHAVE_RESP = RE.CHAVE_RESP 
	AND CO.TIPO_OBJETO = RE.TIPO_OBJETO)    
 LEFT JOIN LY_CONCEITOS_QUEST QU 
	ON (QU.CONCEITO = CO.CONCEITO
	AND QU.TIPO = CO.TIPO)    
 INNER JOIN LY_QUESTAO QE 
	ON (QE.QUESTAO = RE.QUESTAO 
	AND QE.TIPO_QUESTIONARIO = RE.TIPO_QUESTIONARIO
	AND QE.TIPO_OBJETO = RE.TIPO_OBJETO)
 INNER JOIN LY_TIPO_QUESTAO TQ 
	ON (TQ.TIPO = QE.TIPO)
ORDER BY TURMA, TIPO



SELECT
	MP.UNIDADE_RESPONSAVEL,
	mp.CURSO,
	CS.NOME AS NOME_CURSO,
	mp.TURMA,
	MP.STATUS_TURMA,
	MP.FACULDADE AS UNIDADE_FISICA,
	MP.ALUNO,
	PE.NOME_COMPL AS NOME,
	pe.CPF AS CPF,
	LOWER(pe.E_MAIL) AS E_MAIL,
	PE.DDD_FONE_CELULAR,
	pe.CELULAR as CELULAR,
	PE.DDD_FONE,
	pe.FONE AS TELEFONE,
	mp.SIT_MATRICULA AS SIT_MATRICULA,
	CONVERT(VARCHAR,DT_MATRICULA,103)DT_MATRICULA
FROM
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA mp 
	INNER JOIN LY_PESSOA pe on (PE.PESSOA= MP.PESSOA)
	INNER JOIN LY_CURSO CS 
		ON CS.CURSO = MP.CURSO
GROUP BY
	MP.UNIDADE_RESPONSAVEL,
	mp.CURSO,
	CS.NOME,
	mp.TURMA,
	MP.STATUS_TURMA,
	MP.FACULDADE,
	MP.ALUNO,
	PE.NOME_COMPL,
	pe.CPF,
	pe.E_MAIL,
	PE.DDD_FONE_CELULAR,
	pe.CELULAR,
	PE.DDD_FONE,
	pe.FONE,
	mp.SIT_MATRICULA,
	DT_MATRICULA
ORDER BY
	mp.CURSO, mp.TURMA, MP.ALUNO