SELECT 
	*
FROM LY_ANDAMENTO
ORDER BY SOLICITACAO desc

  
SELECT
    sv.SOLICITACAO,
    sv.ITEM_SOLICITACAO,
    sv.SERVICO,
    sv.LANC_DEB,
    sv.QTD,
    sv.OBS,
    a.ALUNO,
    a.NOME_COMPL,
    a.CURSO,
    a.TURMA,
    so.DATA,
    ts.DESCRICAO,
    AN.ANDAMENTO,
    an.STATUS,
    ISNULL((select setor 
	 from ly_fluxo_de_andamento fa
	 where fa.servico = sv.servico
	 group by setor
	),'SECR-ATEND') AS SETOR,
    AN.COMENTARIO,
    AN.USUARIO
FROM LY_ANDAMENTO an
RIGHT JOIN LY_ITENS_SOLICIT_SERV sv
LEFT  JOIN LY_SOLICITACAO_SERV so
    ON sv.SOLICITACAO = so.SOLICITACAO
INNER JOIN LY_TABELA_SERVICOS ts
    ON sv.SERVICO = ts.SERVICO
INNER JOIN VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA a
    ON so.ALUNO = a.ALUNO
    ON an.SOLICITACAO = sv.SOLICITACAO
    AND AN.ANDAMENTO = (SELECT
        MAX(ANDAMENTO)
    FROM ly_andamento AN2 WHERE AN.SOLICITACAO = AN2.SOLICITACAO)
ORDER BY so.SOLICITACAO DESC





SELECT ss.NOME_COMPL, ss.SERVICO, ss.SOLICITACAO, ss.ALUNO, al.CURSO, al.E_MAIL_INTERNO,   
       al.TURNO, al.CURRICULO, al.SERIE, al.SIT_ALUNO, mm.ANDAMENTO  
FROM   SERV_SOLICITACAO ss, LY_ALUNO al, LY_ANDAMENTO mm  
WHERE ss.aluno = al.aluno AND mm.solicitacao = ss.solicitacao  
order by ss.SOLICITACAO desc

SELECT 
	VA.NOME_COMPL, 
	VA.SERVICO, 
	VA.SOLICITACAO, 
	ALUNO, 
	CURSO, 
	E_MAIL_INTERNO, 
	TURNO,
	CURRICULO,
	SERIE, 
	SIT_ALUNO,
	AN.STATUS,
	AN.SETOR
FROM LY_ITENS_SOLICIT_SERV ss
left join VW_ANDAMENTO_BT VA 
	on va.SOLICITACAO = ss.SOLICITACAO
left JOIN LY_ANDAMENTO AN
	ON AN.SOLICITACAO = VA.SOLICITACAO
group by
	AN.SOLICITACAO,
	VA.SOLICITACAO, 
	VA.NOME_COMPL, 
	ALUNO, 
	CURSO, 
	E_MAIL_INTERNO, 
	TURNO,
	CURRICULO,
	SERIE, 
	SIT_ALUNO,
	VA.SERVICO, 
	AN.STATUS,
	AN.SETOR
HAVING
	COUNT(AN.PASSO) = 1
order by AN.SOLICITACAO desc