USE LYCEUM
GO

SELECT
    *
FROM LY_CONFIGURACAO

SELECT
    *
FROM LY_PARAM_CONFIGURACAO
WHERE CHAVE = 3

INSERT INTO LY_PARAM_CONFIGURACAO (CHAVE, NOME, VALOR_TEXTO, VALOR_NUMERICO, VALOR_DATA)
    VALUES (3, 'motivoDescontoPorVoucher', 'Voucher', NULL, NULL)