
SELECT      
 AL.ALUNO,      
 AL.NOME_COMPL,      
 isnull(CONVERT(VARCHAR, PE.DT_NASC, 103),'-') AS DT_NASC,
 PE.RG_NUM,
 AL.CURSO,      
 MA.TURMA,
 (SELECT isnull(CONVERT(VARCHAR, MIN(CT.DT_INICIO), 103),'-') FROM VW_FCAV_INI_FIM_CURSO_TURMA CT
  WHERE CT.TURMA = MA.TURMA) AS DT_INICIO,
 (SELECT isnull(CONVERT(VARCHAR, MAX(CT.DT_FIM), 103),'-')FROM VW_FCAV_INI_FIM_CURSO_TURMA CT
  WHERE CT.TURMA = MA.TURMA) AS DT_FIM,  
 DI.NOME_COMPL AS DISCIPLINA,
 DO.NOME_COMPL AS DOCENTE,
 MA.SIT_MATRICULA AS SITUACAO_HIST,      
 MA.SIT_DETALHE,
 CASE WHEN DI.NOME_COMPL = 'Aula Inaugural'
	  WHEN MA.CONCEITO_FIM = 'A' THEN 10.00
	  WHEN MA.CONCEITO_FIM = 'R' THEN  0.00
	    ELSE CONVERT(DECIMAL(10,2), ISNULL(STR(MA.CONCEITO_FIM,15,2),0)) 
    END as NOTA_FINAL,
 CONVERT(DECIMAL(10,2), ISNULL(MA.PERC_PRESFIM,0)*100) AS FREQUENCIA
FROM       
 LY_MATRICULA MA  
 INNER JOIN LY_ALUNO AL  
	ON AL.ALUNO = MA.ALUNO
 INNER JOIN LY_PESSOA PE
	ON PE.PESSOA = AL.PESSOA
 INNER JOIN LY_AGENDA AG
	ON AG.DISCIPLINA = MA.DISCIPLINA
	AND AG.TURMA = MA.TURMA
	AND AG.ANO = MA.ANO
	AND AG.SEMESTRE = MA.SEMESTRE
 INNER JOIN LY_DOCENTE DO
	ON DO.NUM_FUNC = AG.NUM_FUNC 
 INNER JOIN LY_CURSO CS  
	ON CS.CURSO = AL.CURSO
 INNER JOIN LY_DISCIPLINA DI
	ON DI.DISCIPLINA= MA.DISCIPLINA  
--WHERE    
-- AL.NOME_COMPL = 'André Gouveia Aira'
GROUP BY   
 AL.ALUNO,      
 AL.NOME_COMPL,      
 PE.RG_NUM,
 PE.DT_NASC,
 AL.CURSO,      
 MA.TURMA,
 MA.DISCIPLINA,
 DI.NOME_COMPL,
 DO.NOME_COMPL,
 MA.SIT_MATRICULA,      
 MA.SIT_DETALHE,
 MA.CONCEITO_FIM,
 MA.PERC_PRESFIM      
  
UNION ALL  
  
SELECT   
 AL.ALUNO,        
 AL.NOME_COMPL,
 isnull(CONVERT(VARCHAR, PE.DT_NASC, 103),'-') AS DT_NASC,
 PE.RG_NUM,
 AL.CURSO,        
 HI.TURMA,
 (SELECT isnull(CONVERT(VARCHAR, MIN(CT.DT_INICIO), 103),'-') FROM VW_FCAV_INI_FIM_CURSO_TURMA CT
  WHERE CT.TURMA = HI.TURMA ) AS DT_INICIO,
 (SELECT isnull(CONVERT(VARCHAR, MAX(CT.DT_FIM), 103),'-') FROM VW_FCAV_INI_FIM_CURSO_TURMA CT
  WHERE CT.TURMA = HI.TURMA ) AS DT_FIM, 
 HI.DISCIPLINA,
 DO.NOME_COMPL AS DOCENTE,
 HI.SITUACAO_HIST,        
 HI.SIT_DETALHE,
 CASE WHEN HI.NOTA_FINAL ='A' THEN 10.00
		 WHEN HI.NOTA_FINAL = 'R' THEN 0.00
     ELSE CONVERT(DECIMAL(10,2), STR(HI.NOTA_FINAL,15,2))
    END as NOTA_FINAL,
    CONVERT(DECIMAL(10,2), HI.PERC_PRESENCA*100) AS FREQUENCIA      
FROM         
 LY_HISTMATRICULA HI        
 INNER JOIN LY_ALUNO AL  
	ON AL.ALUNO = HI.ALUNO
 INNER JOIN LY_PESSOA PE
	ON PE.PESSOA = AL.PESSOA
 INNER JOIN LY_AGENDA AG
	ON AG.DISCIPLINA = HI.DISCIPLINA
	AND AG.TURMA = HI.TURMA
	AND AG.ANO = HI.ANO
	AND AG.SEMESTRE = HI.SEMESTRE
 INNER JOIN LY_DOCENTE DO
	ON DO.NUM_FUNC = AG.NUM_FUNC
 INNER JOIN LY_CURSO CS  
	ON CS.CURSO = AL.CURSO
 INNER JOIN LY_DISCIPLINA DI
	ON DI.DISCIPLINA= HI.DISCIPLINA  
--WHERE    
-- AL.NOME_COMPL = 'André Gouveia Aira'
GROUP BY   
  AL.ALUNO,  
  AL.NOME_COMPL,
  PE.RG_NUM,
  PE.DT_NASC,  
  AL.CURSO,  
  HI.TURMA,
  HI.DISCIPLINA,
  DO.NOME_COMPL,
  HI.SITUACAO_HIST,  
  HI.SIT_DETALHE,
  HI.NOTA_FINAL,
  HI.PERC_PRESENCA