
DECLARE @ano_letivo T_ANO
DECLARE @per_letivo T_SEMESTRE2
DECLARE @data		T_DATA

SET @data = GETDATE()

-------------------------------------
--VERIFICA O ANO/PERÍODO LETIVO VIGENTE PELA DATA
SELECT
	@ano_letivo = PL.ANO,
	@per_letivo = PL.PERIODO
FROM
	LY_PERIODO_LETIVO PL
WHERE
	PL.DT_INICIO  <= @data 
	AND PL.DT_FIM >= @data

SELECT
	@ano_letivo ANO,
	@per_letivo PERIODO

------------------------------------
--ALTERA ANO/PERIODO LETIVO PARA OS CURSOS DE ESPECIALIZACAO
UPDATE LY_OPCOES
SET
	ANO_LETIVO = @ano_letivo,
	SEM_LETIVO = @per_letivo 
FROM
	LY_OPCOES OP
	INNER JOIN LY_OPCOES_UNID OU
		ON OU.CHAVE = OP.CHAVE
WHERE
	OU.FACULDADE = 'ESPEC'
	
------------------------------------
--ALTERA ANO LETIVO PARA OS CURSOS DE PERÍODO 0 - FACULDADE IN ('ATUAL','CAPAC','PALES')
UPDATE LY_OPCOES
SET
	ANO_LETIVO = @ano_letivo
FROM
	LY_OPCOES
WHERE
	CHAVE = 4


SELECT * FROM LY_OPCOES

SELECT
	DATEADD(YEAR, +1, DT_INICIO) AS DT_INICIO,
	DATEADD(YEAR, +1, DT_FIM) AS DT_FIM,
	*
FROM
	LY_PERIODO_LETIVO
WHERE
	ANO = YEAR(GETDATE())
GO

SELECT DATEADD(YEAR, +1, GETDATE())