	SELECT
		C.PESSOA,
		NOME_COMPL,
		C.CANDIDATO,
		C.CONCURSO,
		SIT_CANDIDATO_VEST,
		c.fl_field_01,
		c.fl_field_02,
		c.fl_field_03,
		C.FL_FIELD_04 AS DATA_SELEC_COORD,
		C.FL_FIELD_05 AS SELEC_COORD,
		FC.CONVOCADO,
		FC.DATA_CONV,
		FC.DATA_INSC,
		FC.DATA_SECRET,
		FC.LINK_CV
	FROM LYCEUM.DBO.LY_CANDIDATO C
	INNER JOIN FCAV_CANDIDATOS FC
		ON FC.CANDIDATO = C.CANDIDATO
	WHERE C.CONCURSO = 'CEPSNG T 02'
	AND C.CANDIDATO = '201710020'


		IF (SELECT CONVOCADO FROM INSERTED) = '1'
		BEGIN
			ALTER TABLE LY_CANDIDATO DISABLE TRIGGER ALL
				UPDATE LY_CANDIDATO
				SET FL_FIELD_04 = convert(varchar,GETDATE(),102),
					FL_FIELD_05 = 'Selecionado',
					SIT_CANDIDATO_VEST = 'Confirmado'
				WHERE CANDIDATO = '201710017'
				AND CONCURSO = 'CEPSNG T 02'
			ALTER TABLE LY_CANDIDATO ENABLE TRIGGER ALL
		END
