SELECT
    NOME_COORD,
    UNID_RESP,
    CURSO,
    NOME_CURSO,
    INSCRICOES,
    TURMA,
    DT_INICIO,
    DT_FIM,
    SITUACAO_TURMA,
    CENTRO_DE_CUSTO,
    VAGAS_CURSO AS VAGAS_OFERECIDAS,
    CASE
        WHEN TOTAL_INSCRITOS = 0 AND
            UNID_RESP IN ('ATUAL', 'PALES') THEN (MATRICULADOS_INSCRITOS + PRE_MATRICULADOS)
        ELSE TOTAL_INSCRITOS
    END AS TOTAL_INSCRITOS,
    MATRICULADOS_INSCRITOS + PRE_MATRICULADOS AS TOTAL_MATRICULADOS,
    ALUNOS_CANCELADOS AS TOTAL_DESISTENTES,
    CAND_RECUSADOS AS TOTAL_REPROVADOS,
    CASE
        WHEN (CAND_SELECIONADOS - (TOTAL_ALUNOS - MATRICULADOS_OUTROS)) < 0 THEN 0
        ELSE (CAND_SELECIONADOS - (TOTAL_ALUNOS - MATRICULADOS_OUTROS))
    END AS AGUARDANDO_REALIZAR_PRE_MATRICULA
FROM VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR VT
WHERE TURMA = 'CCGB T 38'
GROUP BY NOME_COORD,
         UNID_RESP,
         CURSO,
         NOME_CURSO,
         INSCRICOES,
         TURMA,
         DT_INICIO,
         DT_FIM,
         SITUACAO_TURMA,
         CENTRO_DE_CUSTO,
         VAGAS_CURSO,
         TOTAL_INSCRITOS,
         MATRICULADOS_INSCRITOS,
         PRE_MATRICULADOS,
         CAND_SELECIONADOS,
         ALUNOS_CANCELADOS,
         TOTAL_ALUNOS,
         MATRICULADOS_OUTROS,
         CAND_RECUSADOS,
         DTFIM_OFERTA
ORDER BY DTFIM_OFERTA DESC