SELECT 
	DO.NUM_FUNC,
	DO.NOME_COMPL,
	case when CO.TIPO_COORD = 'Vice' then 'COORD2'
	ELSE CO.TIPO_COORD
	END AS TIPO_COORD,
	CO.CURSO,
	CO.UNID_FISICA
FROM
 LY_COORDENACAO CO
 INNER JOIN LY_DOCENTE DO
	ON DO.NUM_FUNC = CO.NUM_FUNC
GROUP BY
	DO.NUM_FUNC,
	DO.NOME_COMPL,
	CO.TIPO_COORD,
	CO.CURSO,
	CO.UNID_FISICA
order by  UNID_FISICA, NOME_COMPL, CURSO