

/*aluno			-*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'E201630132'
/*aluno			-*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'E201630118'
/*aluno			-*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'E201630112'
/*aluno			-*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'E201630063'
E201630118
E201630112
E201630063

/*aluno			-*/ EXEC PR_FCAV_CONSULTA_PESSOA NULL,NULL,NULL,NULL,NULL,'C201700140'

C201700136
C201700140
C201700144
C201700146

CCGB T 42

SELECT
	QA.PAR_CODIGO,
	QA.CHAVE,
	QA.QUESTIONARIO,
	QA.QUESTAO,
	RE.APLICACAO,
	RE.CODIGO,
	CASE WHEN QA.TIPO_OBJETO = 'DISCIPLINA' THEN DI.NOME
		 WHEN QA.TIPO_OBJETO = 'DOCENTE'	THEN DO.NOME_COMPL
	  ELSE
		'NAO INFORMADO'
	END AS AVALIADO,
	RE.TIPO_OBJETO,
	RE.DATA,
	RE.RESPOSTA_SUBJETIVA
	 
FROM LY_QUESTAO_APLICADA QA
	INNER JOIN LY_QUESTAO QE
		ON QE.QUESTAO = QA.QUESTAO
		AND QE.TIPO_QUESTIONARIO = QA.TIPO_QUESTIONARIO

	INNER JOIN LY_RESPOSTA RE
		ON RE.AVA_CODIGO = QA.PAR_CODIGO
		AND RE.TIPO_OBJETO = QA.TIPO_OBJETO
		AND RE.QUESTAO = QA.QUESTAO
		AND RE.TIPO_QUESTIONARIO = QA.TIPO_QUESTIONARIO
		AND RE.APLICACAO = QA.APLICACAO
		AND RE.CODIGO = QA.CODIGO

	LEFT JOIN LY_DOCENTE DO
		ON CONVERT(VARCHAR,DO.NUM_FUNC) = QA.CODIGO
	LEFT JOIN LY_DISCIPLINA DI
		ON DI.DISCIPLINA = QA.CODIGO
WHERE QA.PAR_CODIGO = 'E201630045'


T_CODIGO2
SELECT * FROM LY_TIPO_QUESTAO 

SELECT * FROM LY_ASPECTO 

SELECT * FROM LY_CONCEITOS_QUEST WHERE TIPO like 'e-FAV_%'

select * from LY_QUESTAO WHERE TIPO_QUESTIONARIO LIKE '%CAPAC' ORDER BY TIPO_OBJETO

SELECT * FROM LY_TIPO_QUESTIONARIO WHERE 

SELECT * FROM LY_QUESTIONARIO

SELECT DISTINCT
	* 
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	UNIDADE_RESPONSAVEL = 'ESPEC' 
	AND TURMA = 'CEGP T 65'
	AND SIT_ALUNO = 'ATIVO' 
	AND SIT_MATRICULA = 'Matriculado' 


SELECT DISTINCT
	ALUNO 
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	UNIDADE_RESPONSAVEL = 'CAPAC' 
	AND TURMA = 'CCGB T 42'
	AND SIT_ALUNO = 'ATIVO' 
	AND SIT_MATRICULA = 'Matriculado' 

SELECT T.CURSO
FROM LY_TURMA T, LY_MATRICULA M 
WHERE T.ANO = M.ANO     
	AND T.SEMESTRE = M.SEMESTRE     
	AND T.DISCIPLINA = M.DISCIPLINA     
	AND T.TURMA = 'CCGB T 42'     
	AND M.SIT_MATRICULA = 'Matriculado'     
GROUP BY T.CURSO


--Trazer o Docente conforme configurado na Agenda
SELECT 
	A.NUM_FUNC 
FROM 
	LY_AGENDA A, 
	LY_MATRICULA M 
WHERE 
	A.ANO = M.ANO     
	AND A.SEMESTRE = M.SEMESTRE     
	AND A.DISCIPLINA = M.DISCIPLINA     
	AND A.TURMA = 'CEGP T 65'  
	AND M.SIT_MATRICULA = 'Matriculado'  
GROUP BY A.NUM_FUNC

--Trazer as disciplina da Turma

SELECT 
	A.DISCIPLINA
FROM 
	LY_AGENDA A, 
	LY_MATRICULA M 
WHERE 
	A.ANO = M.ANO     
	AND A.SEMESTRE = M.SEMESTRE     
	AND A.DISCIPLINA = M.DISCIPLINA     
	AND A.TURMA = 'CCGB T 42'  
	AND M.SIT_MATRICULA = 'Matriculado'  
GROUP BY A.DISCIPLINA

