DECLARE @COBRANCA VARCHAR(10)

DECLARE CURSOR_DATA CURSOR FOR

        
--------------------------------------------------
--conta quantos itens já foram inseridos para atualizar o ultimo item 

asdfasdfasdfasdfasdfasdfasdfasdfasdfas
SELECT COBRANCA
FROM LY_ITEM_LANC
GROUP BY COBRANCA


OPEN CURSOR_DATA
FETCH NEXT FROM CURSOR_DATA INTO @COBRANCA
WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE LY_COBRANCA
	SET ULTIMO_ITEM = (
				SELECT COUNT(*)  
					FROM dbo.LY_ITEM_LANC  
					WHERE COBRANCA = @COBRANCA
				)
	WHERE COBRANCA = @COBRANCA

FETCH NEXT FROM CURSOR_DATA INTO @COBRANCA
END

CLOSE CURSOR_DATA
DEALLOCATE CURSOR_DATA