
SELECT 
	TURMA, 
	COUNT (ALUNO) MATRICULADOS
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	TURMA = 'CEGP T 66'
	AND TIPO_INGRESSO IN ('PROCESSO SELETIVO','Inscricao_Site')
	AND CANDIDATO IS NOT NULL
	AND SIT_MATRICULA = 'MATRICULADO'
	--AND SIT_MATRICULA = 'MATRICULADO'
GROUP BY TURMA



SELECT 
	TURMA, 
	COUNT (ALUNO) PRE_MATRICULADOS
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	TURMA = 'CEGP T 66'
	AND TIPO_INGRESSO IN ('PROCESSO SELETIVO','Inscricao_Site')
	AND CANDIDATO IS NOT NULL
	AND SIT_MATRICULA = 'Pre-Matriculado'
	--AND SIT_MATRICULA = 'MATRICULADO'
GROUP BY TURMA

SELECT 
	TURMA, 
	COUNT (ALUNO) cancelados
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	TURMA = 'CEGP T 66'
	AND TIPO_INGRESSO IN ('PROCESSO SELETIVO','Inscricao_Site')
	AND CANDIDATO IS NOT NULL
	AND SIT_ALUNO = 'Cancelado'
	--AND SIT_MATRICULA = 'MATRICULADO'
GROUP BY TURMA

SELECT
	TURMA, 
	COUNT (ALUNO) ALUNOS
FROM 
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	TURMA = 'CEGP T 66'
GROUP BY TURMA

SELECT 
	*
FROM VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA 
WHERE 
	TURMA = 'CEGP T 66'


SELECT
	*
FROM 
	VW_FCAV_CRONOGRAMA_TURMA_COORDENADOR
WHERE 
	TURMA = 'CEGP T 66'
