SELECT 
	CS.CURSO,
	CASE WHEN CS.NOME = 'ATUALIZACAO' THEN OC.DESCRICAO_COMPL
	ELSE CS.NOME
	END AS NOME_CURSO,
	OC.OFERTA_DE_CURSO,
	ISNULL(OC.CONCURSO, 'VENDA DIRETA') AS CONCURSO,
	OC.DTINI AS DTINI_INSC,
	OC.DTFIM AS DTFIM_INSC,
	CASE WHEN DTFIM >= GETDATE() AND DTINI <= GETDATE() THEN 'Aberta'
		 WHEN DTFIM >= GETDATE() AND DTINI >= GETDATE() THEN 'Não Iniciado'
	ELSE 'Encerrada'
	END AS SIT_INSCRICAO,
	TU.TURMA,
	MIN(TU.DT_INICIO) AS DT_INI_TURMA,
	MAX(TU.DT_FIM) AS DT_FIM_TURMA,
	MONTH(MIN(TU.DT_INICIO)) AS MES_INI_TURMA,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,
	CR.PRAZO_CONC_PREV AS PRAZO_CONCLUSAO,
	CR.TIPO_PRAZO_CONCL,
	ISNULL(PO.DESCRICAO,'NÃO CADASTRADO') AS PLANO_PGTO,
	PO.MES_INICIAL,
	PO.NUM_PARCELAS AS PARCELAS_MENS,
	CASE WHEN SM.SERVICO IS NULL THEN 0
	ELSE
		1
	END AS PARCELA_MATRI,
	CASE WHEN CS.FACULDADE NOT IN ('ATUAL','PALES') THEN 
		ISNULL(SM.SERVICO,'NÃO CADASTRADO')
	ELSE
		'NÃO APLICÁVEL'
	END AS SERVICO_MATRICULA,
	CASE WHEN CS.FACULDADE NOT IN ('ATUAL','PALES') THEN 
	(SELECT CAST(VSP.CUSTO_UNITARIO AS DECIMAL) 
	 FROM LY_VALOR_SERV_PERIODO VSP
		WHERE VSP.SERVICO = SM.SERVICO
		AND VSP.ANO = SM.ANO
		AND VSP.PERIODO = SM.PERIODO) 
	ELSE
		0
	END AS VALOR_MATRI,
	CASE WHEN CS.FACULDADE NOT IN ('PALES') THEN 
		ISNULL(CR.SERVICO,'NÃO VINCULADO') 
	ELSE
		'NÃO APLICÁVEL'
	END AS SERVICO_MENSALIDADE,
	
	(SELECT CAST(VSP.CUSTO_UNITARIO AS DECIMAL) FROM LY_VALOR_SERV_PERIODO VSP
		WHERE VSP.SERVICO = CR.SERVICO
		AND VSP.ANO = OC.ANO_INGRESSO
		AND VSP.PERIODO = OC.PER_INGRESSO) AS VALOR_MENS,
		
	CASE WHEN CS.FACULDADE NOT IN ('ATUAL','PALES') THEN 
		 dbo.FN_FCAV_TOTAL_INSCRITO(OC.CONCURSO) 
		WHEN CS.FACULDADE IN ('ATUAL','PALES') THEN
	     dbo.FN_FCAV_PREMATRICULADO_TURMA(TU.TURMA)
	ELSE 0
	END AS INSCRITOS,
	
	dbo.FN_FCAV_PREMATRICULADO_TURMA(TU.TURMA) AS PRE_MATRICULADOS,
	dbo.FN_FCAV_MATRICULADO_TURMA(TU.TURMA) AS MATRICULADOS
	
FROM 
	LY_OFERTA_CURSO OC
	INNER JOIN LY_OPCOES_OFERTA OO
		ON OO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
	INNER JOIN LY_CURSO CS 
		ON CS.CURSO = OC.CURSO
	INNER JOIN LY_CURRICULO CR
		ON CR.CURRICULO = OC.CURRICULO
	INNER JOIN LY_TURMA TU
		ON TU.TURMA = OO.TURMA
	LEFT JOIN LY_PLANOS_OFERTADOS PO
		ON PO.OFERTA_DE_CURSO = OC.OFERTA_DE_CURSO
	LEFT JOIN LY_SERVICO_MATRICULA SM
		ON SM.CURSO = OC.CURSO
		AND SM.TURNO = OC.TURNO
		AND SM.CURRICULO = OC.CURRICULO
		AND SM.ANO = OC.ANO_INGRESSO
		AND SM.PERIODO = OC.PER_INGRESSO
		AND SM.UNIDADE_FISICA = OC.UNIDADE_FISICA
		
WHERE 
	--tu.TURMA like 'cepsng t 23'
	OC.ANO_INGRESSO >= 2016
	AND OC.CONCURSO IS NOT NULL
	--AND OC.DTFIM >= GETDATE()

GROUP BY 
	CS.CURSO,
	CS.NOME,
	CS.FACULDADE,
	CR.PRAZO_CONC_PREV,
	CR.TIPO_PRAZO_CONCL,
	OC.OFERTA_DE_CURSO,
	OC.DESCRICAO_COMPL,
	OC.CONCURSO,
	OC.DTINI,
	OC.DTFIM,
	OC.ANO_INGRESSO,
	OC.PER_INGRESSO,

	TU.TURMA,

	PO.DESCRICAO,
	PO.NUM_PARCELAS,
	PO.MES_INICIAL,
	
	SM.ANO,
	SM.PERIODO,
	SM.SERVICO,
	CR.SERVICO