

UPDATE LY_CONCURSO
SET
	FL_FIELD_01 = CASE WHEN C.FL_FIELD_01 = 'SIM' THEN 'S'
					WHEN C.FL_FIELD_01 = 'NAO' THEN 'N'
					ELSE C.FL_FIELD_01 END,
	FL_FIELD_02 = CASE WHEN C.FL_FIELD_02 = 'SIM' THEN 'S'
					WHEN C.FL_FIELD_02 = 'NAO' THEN 'N'
					ELSE C.FL_FIELD_02 END,
	FL_FIELD_03 = CASE WHEN C.FL_FIELD_03 = 'SIM' THEN 'S'
					WHEN C.FL_FIELD_03 = 'NAO' THEN 'N'
					ELSE C.FL_FIELD_03 END,
	FL_FIELD_04 = CASE WHEN C.FL_FIELD_04 = 'SIM' THEN 'S'
					WHEN C.FL_FIELD_04 = 'NAO' THEN 'N'
					ELSE C.FL_FIELD_04 END,
	FL_FIELD_05 = CASE WHEN C.FL_FIELD_05 = 'SIM' THEN 'S'
					WHEN C.FL_FIELD_05 = 'NAO' THEN 'N'
					ELSE C.FL_FIELD_05 END				
FROM 
	LY_CONCURSO C

