SELECT 
	OC.CURSO,
	RIGHT(LTRIM(RTRIM(OC.CONCURSO)),2) AS TURMA,
	CAST(OC.ANO_INGRESSO AS VARCHAR)+ '/' + CAST(OC.PER_INGRESSO AS VARCHAR) AS PERÍODO,
	CA.NOME_COMPL AS CANDIDATO,
	CA.OBS AS OBSERVACOES
FROM 
	LY_CANDIDATO CA
	INNER JOIN FCAV_CANDIDATOS FC ON FC.CANDIDATO = CA.CANDIDATO
	INNER JOIN LY_OFERTA_CURSO OC ON OC.CONCURSO = CA.CONCURSO
WHERE
	CA.OBS LIKE '%CONCEDIDO BOLSA INTERNA%'