 SELECT DISTINCT 
	VW_FCAV_LISTA_PRESENCA_UNIF.TURMA_COD, 
	VW_FCAV_LISTA_PRESENCA_UNIF.DISCIP_COD, 
	VW_FCAV_LISTA_PRESENCA_UNIF.ALUNO_COD, 
	VW_FCAV_LISTA_PRESENCA_UNIF.ALUNO_NOME, 
	VW_FCAV_LISTA_PRESENCA_UNIF.STATUS, 
	VW_FCAV_LISTA_PRESENCA_UNIF.DETALHE, 
	VW_FCAV_LISTA_PRESENCA_UNIF.PERIODO
 FROM   
	LYCEUM.dbo.VW_FCAV_LISTA_PRESENCA_UNIF VW_FCAV_LISTA_PRESENCA_UNIF
 WHERE  VW_FCAV_LISTA_PRESENCA_UNIF.DISCIP_COD<>'CEAI-RESERV' 
	AND  NOT (VW_FCAV_LISTA_PRESENCA_UNIF.STATUS='CANCELADO' OR VW_FCAV_LISTA_PRESENCA_UNIF.STATUS='DISPENSADO') 
	AND VW_FCAV_LISTA_PRESENCA_UNIF.PERIODO='2017/1'
 ORDER BY VW_FCAV_LISTA_PRESENCA_UNIF.DISCIP_COD, VW_FCAV_LISTA_PRESENCA_UNIF.ALUNO_NOME
 
 SELECT * FROM LY_TURMA WHERE CURSO = 'CEAI' AND ANO = 2016 AND SEMESTRE = 3
