USE LYCEUM
GO

SELECT
	OC.OFERTA_DE_CURSO AS OC,
	OP.TURMA,
	PC.DT_INSERCAO,
	PC.PESSOA,
	PE.NOME_COMPL,
	PE.DT_NASC,
	PE.SEXO,
	PE.CPF,
	PE.PASSAPORTE,
	PE.E_MAIL,
	--DBO.DECRYPT(PE.SENHA_TAC) AS SENHA_INDIVIDUAL,
	EM.PESSOA AS COD_REPRESENTANTE,
	(SELECT
		NOME_COMPL
	FROM LY_PESSOA
	WHERE PESSOA = em.PESSOA)
	AS REPRESENTANTE,
	PC.EMPRESA,
	EM.CNPJ,
	EM.RAZAO_SOCIAL,
	(SELECT
		E_MAIL
	FROM LY_PESSOA
	WHERE PESSOA = em.PESSOA)
	AS E_MAIL_REPRESENTANTE,
	(SELECT
		DBO.Decrypt(SENHA_TAC)
	FROM LY_PESSOA
	WHERE PESSOA = em.PESSOA)
	AS SENHA_REPRESENTANTE,
	pe.DDD_FONE_CELULAR,
	pe.CELULAR,
	pe.DDD_FONE,
	pe.FONE,
	OC.CURSO_OFERTADO AS CARRINHO,
	OC.CURSO,
	OC.DESCRICAO_COMPL,
	AL.ALUNO,
	AL.NOME_COMPL,
	OP.TURMA,
	CO.DATA_INCLUSAO,
	CO.VALOR,
	--CO.NUM_PEDIDO,
	CO.COBRANCA,
	CO.BOLETO,
	RF.RESP,
	RF.TITULAR,
	ISNULL(RF.CGC_TITULAR, RF.CPF_TITULAR) AS CNPJ_CPF,
	
	--CO.BANDEIRA_CARTAO,
	--CO.NUMERO_CARTAO,
	CO.FORMA_PAGAMENTO AS FORMA_PGTO,
	CO.NUMERO_PARCELAS AS NUM_PARC_PLANO,
	CC.NUM_PARCELAS AS NUM_PARC_CARTAO,
	--IC.LANC_CRED,
	--IC.ITEMCRED,
	--IC.DESCRICAO,
	--IC.COBRANCA,
	IC.VALOR AS VALOR_QUITADO
	
FROM LY_PROSPECTO_CAPTACAO PC
LEFT JOIN LY_PESSOA PE
	ON PE.PESSOA = PC.PESSOA
LEFT JOIN LY_PROSPECTO_CARRINHO PR
	ON PR.ID_PROSPECTO_CAPTACAO = PC.ID_PROSPECTO_CAPTACAO
LEFT JOIN LY_COMPRA_OFERTA CO
	ON CO.ID_PROSPECTO_CAPTACAO = PC.ID_PROSPECTO_CAPTACAO
LEFT JOIN LY_OFERTA_CURSO OC
	ON OC.OFERTA_DE_CURSO = PR.OFERTA_DE_CURSO
	OR OC.OFERTA_DE_CURSO = CO.OFERTA_DE_CURSO
LEFT JOIN LY_OPCOES_OFERTA OP
	ON OP.OFERTA_DE_CURSO = CO.OFERTA_DE_CURSO
LEFT JOIN LY_ALUNO AL
	ON AL.ALUNO = CO.ALUNO
LEFT JOIN LY_PLANO_PGTO_PERIODO PP
	ON PP.ALUNO = AL.ALUNO
LEFT JOIN LY_EMPRESA EM
	ON EM.EMPRESA = PC.EMPRESA
LEFT JOIN LY_ITEM_CRED IC
	ON IC.COBRANCA = CO.COBRANCA
LEFT JOIN LY_CRED_CARTAO CC
	ON CC.LANC_CRED = IC.LANC_CRED
LEFT JOIN LY_RESP_FINAN RF
	ON RF.RESP = PP.RESP
--WHERE
--	EM.CNPJ = '52910023000137'
--	RF.CGC_TITULAR is not NULL
ORDER BY DT_INSERCAO desc--, CO.DATA_INCLUSAO desc
