
USE LYCEUM
GO


SELECT DISTINCT
	VI.CURSO,
	VI.TURMA AS ULTIMA_TURMA,
	VI.APRESENTACAO_CURSO,
	VI.OBJETIVOS,
	VI.CORPO_DOCENTE,
	VI.DIFERENCIAL,
	VI.PERFIL_ALUNO,
	VI.CERTIFICACAO,
	VI.METODOLOGIA,
	VI.SISTEMA_AVALIACAO,
	VI.INVESTIMENTO,
	VI.PROCESSO_SELETIVO
	
	INTO #TMP_CURSO_INFO
	
FROM 
	VW_FCAV_INFO_CURSO_PORTAL VI
	INNER JOIN LY_CURSO CS
		ON CS.CURSO = VI.CURSO
WHERE CS.FACULDADE = 'ATUAL' 
--AND vi.SIT_TURMA not like 'Cancelada'
AND VI.OBJETIVOS NOT LIKE '.'
AND VI.TURMA IN (
		select MAX(turma) from LY_TURMA where UNIDADE_RESPONSAVEL = 'atual' group by CURSO
	)


SELECT DISTINCT
	CURSO,
	TURMA,
	FL_FIELD_13 FL13_Objetivos,
	FL_FIELD_14 FL14_Corpo_Docente,
	FL_FIELD_16 FL16_Investimento,
	FL_FIELD_19 FL19_Publico_Alvo
	
	INTO #TMP_TURMA_INFO
	
from
	LY_TURMA
WHERE
	UNIDADE_RESPONSAVEL = 'ATUAL'
	--AND SIT_TURMA not like 'Cancelada'
	AND FL_FIELD_13 is not null
	AND TURMA IN (
		select MAX(turma) from LY_TURMA where UNIDADE_RESPONSAVEL = 'atual' group by CURSO
	)

SELECT DISTINCT
     CS.CURSO,
     FL_FIELD_01,
     CI.APRESENTACAO_CURSO
	,FL_FIELD_02
	,TU.FL13_Objetivos
	,FL_FIELD_03 
	,TU.FL14_Corpo_Docente
	,FL_FIELD_04 ,
	CI.DIFERENCIAL
	,FL_FIELD_05 
	,TU.FL19_Publico_Alvo
	,FL_FIELD_06 
	,CI.CERTIFICACAO
	,FL_FIELD_07 
	,CI.METODOLOGIA
	,FL_FIELD_08 ,
	CI.SISTEMA_AVALIACAO
	,FL_FIELD_09 
	,TU.FL16_Investimento
	,FL_FIELD_10,
	CI.PROCESSO_SELETIVO
FROM
	#TMP_TURMA_INFO TU
	INNER JOIN #TMP_CURSO_INFO CI
		ON CI.ULTIMA_TURMA = TU.TURMA
	INNER JOIN LY_CURSO CS
		ON TU.CURSO = CS.CURSO
WHERE
	CS.FACULDADE = 'ATUAL'
	AND CS.CURSO NOT LIKE 'ATUALIZACAO'


	
UPDATE LY_CURSO
SET
	 FL_FIELD_01 = CI.APRESENTACAO_CURSO
	,FL_FIELD_02 = TU.FL13_Objetivos
	,FL_FIELD_03 = TU.FL14_Corpo_Docente
	,FL_FIELD_04 = CI.DIFERENCIAL
	,FL_FIELD_05 = TU.FL19_Publico_Alvo
	,FL_FIELD_06 = CI.CERTIFICACAO
	,FL_FIELD_07 = CI.METODOLOGIA
	,FL_FIELD_08 = CI.SISTEMA_AVALIACAO
	,FL_FIELD_09 = TU.FL16_Investimento
	,FL_FIELD_10 = CI.PROCESSO_SELETIVO
FROM
	#TMP_TURMA_INFO TU
	INNER JOIN #TMP_CURSO_INFO CI
		ON CI.ULTIMA_TURMA = TU.TURMA
	INNER JOIN LY_CURSO CS
		ON TU.CURSO = CS.CURSO
WHERE
	CS.FACULDADE = 'ATUAL'
	AND CS.CURSO NOT LIKE 'ATUALIZACAO'
	
DROP table #TMP_CURSO_INFO
DROP table #TMP_TURMA_INFO


SELECT 
	CURSO,
	FL_FIELD_01,
	FL_FIELD_02,
	FL_FIELD_03,
	FL_FIELD_04,
	FL_FIELD_05,
	FL_FIELD_06,
	FL_FIELD_07,
	FL_FIELD_08,
	FL_FIELD_09,
	FL_FIELD_10 
FROM 
	LY_CURSO 
WHERE
	FACULDADE = 'ATUAL'
	AND CURSO NOT LIKE 'ATUALIZACAO'
