/*
--* ***************************************************************    
--*    
--*  ***VIEW VW_FCAV_CANDIDATO_ALUNO_SITUACAO ***    
--*     
--* Finalidade: Consulta para trazer as situações do candidato e aluno com motivo e causa de desistencia e cancelamento
--*    e aluno com motivo e causa de desistencia e cancelamento. Planilha utilizada pelo Cristiano.
--*     
--*  SELECT * FROM VW_FCAV_CANDIDATO_ALUNO_SITUACAO WHERE ALUNO = 'E201420082'    
--*     
--* Autor: Gabriel S. Scalione    
--* Criado: 01/02/2018    
--*    
--* ***************************************************************    

*/

CREATE VIEW VW_FCAV_CANDIDATO_ALUNO_SITUACAO
AS

SELECT 
	AL.CURSO,
	AL.TURMA,
	VT.TP_INGRESSO,
	VT.DT_INICIO AS INICIO_TURMA,
	AL.PESSOA,
	AL.NOME_COMPL,
	AL.CANDIDATO,
	FC.DATA_INSC AS DT_INSCRICAO,
	CA.SIT_CANDIDATO_VEST AS SIT_CANDIDATO,
	CA.FL_FIELD_01 AS DT_ANALISE_FINAN,
	CA.FL_FIELD_02 AS RESULT_PESSOA_FISICA,
	CA.FL_FIELD_03 AS RESULT_PESSOA_JURIDICA,
	CA.FL_FIELD_04 AS DT_SELECAO_COORD,
	CA.FL_FIELD_05 AS SELECAO_COORD,
	CA.FL_FIELD_06 AS DT_NOTIFICACAO,
	CA.FL_FIELD_07 AS CAUSA_DESISTENCIA,
	CA.FL_FIELD_08 AS MOTIVO_DESISTENCIA,
	AL.ALUNO,
	AL.DT_MATRICULA,
	AL.SIT_ALUNO,
	AL.SIT_MATRICULA,
	HC.DT_ENCERRAMENTO,
	HC.MOTIVO,
	HC.CAUSA_ENCERR,
	HC.DT_REABERTURA
FROM
	VW_FCAV_RESUMO_MATRICULA_E_PRE_MATRICULA AL
	LEFT JOIN VW_FCAV_INI_FIM_CURSO_TURMA VT
		ON VT.TURMA = AL.TURMA
		AND VT.OFERTA_DE_CURSO = AL.OFERTA_DE_CURSO
	LEFT JOIN LY_CANDIDATO CA
		ON CA.CANDIDATO = AL.CANDIDATO
		AND CA.CONCURSO = AL.CONCURSO
	LEFT JOIN FCAV_CANDIDATOS FC
		ON FC.CANDIDATO = CA.CANDIDATO
		AND FC.CONCURSO = CA.CONCURSO
	LEFT JOIN  LY_H_CURSOS_CONCL HC
		ON HC.ALUNO = AL.ALUNO
		AND HC.CURSO = AL.CURSO
		AND HC.TURNO = AL.TURNO
		AND HC.CURRICULO = AL.CURRICULO
		AND HC.ANO_INGRESSO = AL.ANO_INGRESSO
		AND HC.SEM_INGRESSO = AL.SEM_INGRESSO
GROUP BY
	AL.CURSO,
	AL.TURMA,
	VT.TP_INGRESSO,
	VT.DT_INICIO,
	AL.PESSOA,
	AL.NOME_COMPL,
	AL.CANDIDATO,
	FC.DATA_INSC,
	CA.SIT_CANDIDATO_VEST,
	CA.FL_FIELD_01,
	CA.FL_FIELD_02,
	CA.FL_FIELD_03,
	CA.FL_FIELD_04,
	CA.FL_FIELD_05,
	CA.FL_FIELD_06,
	CA.FL_FIELD_07,
	CA.FL_FIELD_08,
	AL.ALUNO,
	AL.DT_MATRICULA,
	AL.SIT_ALUNO,
	AL.SIT_MATRICULA,
	HC.DT_ENCERRAMENTO,
	HC.MOTIVO,
	HC.CAUSA_ENCERR,
	HC.DT_REABERTURA
