
/*
	Script para listar os centros de custos do microsiga que estão bloqueados
	
SELECT DISTINCT * FROM LINKED_MICROSIGA.DADOSADVP12.dbo.CTT010 AS CTT WHERE CTT.CTT_CUSTO in ('502012817')
SELECT CENTRO_DE_CUSTO,* FROM LY_TURMA WHERE TURMA = 'ceai t 28 sab'

--IDENTIFICAR O ÚLTIMO DOC DO DIA
	SELECT TOP 10
	 CT2_DATA, CT2_LOTE, CT2_DOC, CT2_LINHA, CT2_HIST
	FROM
	 LINKED_MICROSIGA.DADOSADVP12.dbo.CT2010
	WHERE CT2_DATA = '20170207'
	AND CT2_LOTE IN ('008870','008871')
	AND D_E_L_E_T_ <> '*'

	ORDER BY CT2_DOC DESC


--TAXA FCAV
SELECT
 CTT_TX_GER, CTT_CUSTO, CTT_DESC01
FROM 
 LINKED_MICROSIGA.DADOSADVP12.dbo.CTT010
WHERE 
 CTT_CUSTO = '502012817'

	
*/
USE LYCEUM
GO



DECLARE @data_ini DATE
DECLARE @data_fim DATE  

SET @data_ini = GETDATE()-35		--Período em que o script irá verificar, intervalo de dias atrás até a data atual.

SET @data_fim = GETDATE()


ALTER TABLE LY_TURMA DISABLE TRIGGER ALL
UPDATE LY_TURMA
SET
	CENTRO_DE_CUSTO = '502012215'
WHERE
	TURMA = 'CEAI T 23'
	AND CENTRO_DE_CUSTO = '502022315'

UPDATE LY_TURMA
SET
	CENTRO_DE_CUSTO = '502012817'
WHERE
	TURMA = 'CEAI T 28 SAB'
	--AND CENTRO_DE_CUSTO IS NULL
ALTER TABLE LY_TURMA ENABLE TRIGGER ALL



SELECT DISTINCT  
 T.TURMA,
 T.CENTRO_DE_CUSTO,--CTT_DTEXIS,CTT_DTEXSF,
 CASE WHEN CTT.CTT_CUSTO IS NULL THEN 'NAO CADASTRADO'  
  WHEN CTT_BLOQ = '1' THEN 'BLOQUEADO'  
  WHEN CTT_DTEXIS > CONVERT(VARCHAR,GETDATE(),112) THEN 'AINDA NÃO INICIADO'  
  WHEN CTT_DTEXSF < CONVERT(VARCHAR,GETDATE(),112) THEN 'JÁ FINALIZADO'  
 ELSE 'OK' END AS CC_SIGA
FROM  
   
 LY_ALUNO AS ALU    
 INNER JOIN LY_PESSOA AS PES ON (ALU.PESSOA=PES.PESSOA)    
 INNER JOIN LY_COBRANCA AS COB ON (ALU.ALUNO = COB.ALUNO)    
 INNER JOIN LY_ITEM_LANC AS ILAN ON (COB.COBRANCA = ILAN.COBRANCA)    
 INNER JOIN LY_BOLETO AS BOL ON (ILAN.BOLETO = BOL.BOLETO AND BOL.BOLETO IS NOT NULL)    
 LEFT OUTER JOIN LY_TURMA AS T ON (ALU.TURMA_PREF = T.TURMA)    
 LEFT OUTER JOIN FCAV_IMPCONT_CAD AS FCAD ON (ALU.TURMA_PREF = FCAD.TURMA)  
 LEFT OUTER JOIN LINKED_MICROSIGA.DADOSADVP12.dbo.CTT010 AS CTT ON (T.CENTRO_DE_CUSTO = CTT.CTT_CUSTO COLLATE Latin1_General_CI_AI)  
WHERE
-- CTT.CTT_CUSTO in ('313540257')
 ILAN.DATA >= @DATA_INI   
 and T.TURMA is not null 
 and T.TURMA not like 'CCBB T 38'
 AND ILAN.DATA <= @data_fim
 AND (CTT_DTEXSF < CONVERT(VARCHAR,GETDATE(),112) 
	 OR CTT_DTEXIS > CONVERT(VARCHAR,GETDATE(),112)
	 OR CTT.CTT_CUSTO IS NULL
     OR CTT_BLOQ = '1')
  
ORDER BY T.TURMA  

