select
	*
from
	LY_EMPRESA 
where
	PESSOA = 111012
	
	
SELECT
*
FROM
	LY_PLANOS_OFERTADOS
WHERE
	DESCRICAO_COMPL LIKE 'A-DN T 07%'
	
	
SELECT 
	CA.CONCURSO,
	CA.CANDIDATO,
	CA.NOME_COMPL,
	CA.CPF,
	PE.CPF,
	CA.DT_INSCRICAO,
	FC.*
FROM 
	LY_CANDIDATO CA
	INNER JOIN FCAV_CANDIDATOS FC
		ON FC.CANDIDATO = CA.CANDIDATO
		AND FC.CONCURSO = CA.CONCURSO
	INNER JOIN LY_PESSOA PE
		ON PE.PESSOA = CA.PESSOA
WHERE 
	--NOME_COMPL = 'Jaqueline Ramos'
	
	PE.NOME_COMPL IN ('Reinaldo Gomes da Silva', 'Julio Mignoli do Val')
