USE LYCEUM
GO

SELECT * FROM LY_CURRICULO_CONTRATO
WHERE
	CONTRATO NOT LIKE 'Contrato_ProcSelet'
	AND CONTRATO NOT LIKE 'ContratoLoja'
		
UPDATE LY_CURRICULO_CONTRATO
SET
	CONTRATO = 'Contrato_ProcSelet'
WHERE
	CONTRATO NOT LIKE 'Contrato_ProcSelet'
	AND CONTRATO NOT LIKE 'ContratoLoja'
	
SELECT * FROM LY_CONTRATO	WHERE
	CONTRATO NOT LIKE 'Contrato_ProcSelet'	 
	AND CONTRATO NOT LIKE 'ContratoLoja'

DELETE
	 LY_CONTRATO
WHERE
	CONTRATO NOT LIKE 'Contrato_ProcSelet'	 
	AND CONTRATO NOT LIKE 'ContratoLoja'
