SELECT 
	CANDIDATO, 
	FL_FIELD_01,
	FL_FIELD_02,
	FL_FIELD_03, 
	FL_FIELD_04, 
	FL_FIELD_05, 
	FL_FIELD_06, 
	FL_FIELD_07,
	FL_FIELD_08 
FROM 
	LY_CANDIDATO 
where 
	CANDIDATO = '201635001'
	
	
update LY_CANDIDATO
set
	FL_FIELD_01 = NULL, 
	FL_FIELD_04 = NULL, 
	FL_FIELD_06 = NULL
WHERE
	CANDIDATO = '201635001'	 		




SELECT ITEM FROM FCAV_FLEXFIELD WHERE TABELA = 'LY_PESSOA' AND OPCAO = 'Motivo Desistencia'


SELECT * FROM LY_FL_PESSOA WHERE FL_FIELD_20 IS NOT NULL

'LY_CANDIDATO','FL_FIELD_02'


SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = 'LY_PESSOA' AND OPCAO = 'Definicao Desistencia'ORDER BY ORDEM

SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = 'LY_PESSOA' AND OPCAO = 'Analise Finan' ORDER BY ORDEM

SELECT ITEM AS VALOR, ITEM AS DESCRICAO FROM FCAV_FLEXFIELD WHERE TABELA = 'LY_PESSOA' AND OPCAO = 'Motivo Desistencia'