--* ***************************************************************
--*
--*		***VIEW VW_FCAV_RELACAO_GERAL_DE_CURSOS_LYCEUM ***
--*	
--*	DESCRICAO:
--*	- View para trazer as informações dos cursos cadastrados no Lyceum
--*
--*	PARAMETROS:
--*	- Sem parâmetro
--*	
--*	USO:
--*	- O uso será para a Secretaria Academica, para conferencia de Cadastro
--*
--*	ALTERAÇÕES:
--*		27/02/2015: Acrescentado as informações financeira das turmas cadastradas.
--*		01/02/2017: Otimização da View
--*
--*	Autor: Gabriel S. Scalione
--*	Data de criação:	05/02/2015
--*
--* ***************************************************************

USE LYCEUM
GO

ALTER VIEW VW_FCAV_RELACAO_GERAL_DE_CURSOS_LYCEUM
AS


SELECT DISTINCT  
 ISNULL(TU.FACULDADE,'-') AS FACULDADE,  
 ISNULL(COOR.NOME_COMPL,'-') AS COORDENADOR,
 CASE WHEN COOR.TIPO_COORD = 'COORD' THEN 'Coordenador'
	  WHEN COOR.TIPO_COORD = 'COORD2' THEN 'Vice-Coordenador'
      ELSE '-'
 END AS TIPO_COORD,
 ISNULL(tu.CURSO,'-') AS CURSO,
 ISNULL(tu.TURNO,'-') AS TURNO,
 ISNULL(tu.CURRICULO,'-') AS CURRICULO,
 oc.OFERTA_DE_CURSO AS OFERTA,    
 ISNULL(SO.SUB_GRUPO,'-') AS SUB_GRUPO_OFERTA,  
 ISNULL(oc.CURSO_OFERTADO,'-') AS CURSO_OFERTADO,
 ISNULL(OC.DESCRICAO_COMPL,'-') AS DESCRICAO_COMPL,
 oc.DTINI as DTINI_OFERTA,  
 oc.DTFIM as DTFIM_OFERTA,  
 CASE WHEN OC.CONCURSO IS NULL AND oc.OFERTA_DE_CURSO IS NOT NULL THEN 'VENDA DIRETA'  
   WHEN OC.CONCURSO IS NULL AND oc.OFERTA_DE_CURSO IS NULL THEN NULL  
   ELSE CO.CONCURSO  
 END AS CONCURSO,  
 ISNULL(oc.TURMA_PREF,'-') AS TURMA_PREF,
 CASE WHEN OC.CONCURSO IS NULL THEN oc.DTINI   
  ELSE co.DT_INICIO END AS DTINI_CONCURSO,  
 CASE WHEN OC.CONCURSO IS NULL THEN oc.DTFIM  
  ELSE co.DT_FIM END AS DTFIM_CONCURSO,    
 ISNULL(tu.TURMA,'-') AS TURMA,
 TU.ANO,    
 TU.SEMESTRE AS PERIODO,  
 ISNULL(GR.DISCIPLINA,'-') AS GRADE_CURRICULAR,  
 TU.SERIE,  
 ISNULL(TU.DISCIPLINA,'-') AS DISCIPLINA,
 tu.DT_INICIO AS DT_INICIO,    
 tu.DT_FIM AS DT_FIM,  
 ISNULL(TU.CLASSIFICACAO,'-') AS SIT_TURMA,  
 tu.NUM_ALUNOS AS VAGAS,  
 ISNULL(oo.CARGA_HORARIA,'-') AS CARGA_HORARIA,
 ISNULL(CC.DESCR_HADES,'-') AS TURMA_CC_HADES,  
 ISNULL(CC.CENTRO_CUSTO_HADES,'-') AS CC_HADES,  
 ISNULL(CC.C_CUSTO_DISCIPLINA,'-') AS CC_DISCIPLINA,  
 CASE WHEN tu.UNIDADE_RESPONSAVEL = 'PALES' THEN 'NÃO_APLICÁVEL'
	ELSE ISNULL(SE.SERVICO,'-')
  END AS SERVICO_VINCULADO,  
 CASE WHEN tu.UNIDADE_RESPONSAVEL = 'ATUAL' THEN 'NÃO_APLICÁVEL'  
  ELSE  
  (SELECT  
    ISNULL(SM.SERVICO,'-')
   FROM     
    LY_SERVICO_MATRICULA SM  
    INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA ALU ON   
      (ALU.CURSO = SM.CURSO AND ALU.TURNO = SM.TURNO AND ALU.CURRICULO = SM.CURRICULO)      
   WHERE    
    SM.SERVICO LIKE 'MATR%'      
    AND ALU.TURMA = TU.TURMA)  
 END AS SERVICO_MATRICULA,  
 --PO.PLANO,  
 --PO.PLANOPAG,  
 ISNULL(PO.DESCRICAO,'-')AS DESCRICAO,
 PO.MES_INICIAL,
 NUM_PARCELAS,
 PO.TIPO_DESC AS TIPO_DESC,
 PO.DESCONTO  AS  DESCONTO_CADASTRADO,  
 PO.N_DIAS_VENC_BOL,
 (--VALOR_MATRICULA-------------------------------------------------  
  SELECT     
    REPLACE(CAST(CONVERT(MONEY,ISNULL(CUSTO_UNITARIO,0)) AS VARCHAR),'.',',')   
   FROM     
    LY_VALOR_SERV_PERIODO VSP    
    INNER JOIN LY_SERVICO_MATRICULA SM ON (VSP.SERVICO = SM.SERVICO)  
    INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA ALU ON (ALU.CURSO = SM.CURSO AND ALU.TURNO = SM.TURNO AND ALU.CURRICULO = SM.CURRICULO)      
    INNER JOIN LY_OPCOES_MATRICULA OM ON (OM.ANO = VSP.ANO AND OM.PERIODO = VSP.PERIODO AND OM.CURSO = ALU.CURSO)    
   WHERE    
    VSP.SERVICO LIKE 'MATR%'    
    AND ALU.TURMA = TU.TURMA  
  UNION    
   SELECT     
    '0,00'  
   FROM    
    LY_TURMA  
   WHERE    
    NOT EXISTS    
    (    
     SELECT     
    1    
     FROM     
   LY_VALOR_SERV_PERIODO VSP     
   INNER JOIN LY_SERVICO_MATRICULA SM ON (VSP.SERVICO = SM.SERVICO)  
   INNER JOIN VW_FCAV_INI_FIM_CURSO_TURMA ALU ON (ALU.CURSO = SM.CURSO AND ALU.TURNO = SM.TURNO AND ALU.CURRICULO = SM.CURRICULO)      
   INNER JOIN LY_OPCOES_MATRICULA OM ON (OM.ANO = VSP.ANO AND OM.PERIODO = VSP.PERIODO AND OM.CURSO = ALU.CURSO)    
     WHERE    
   VSP.SERVICO LIKE 'MATR%'    
   AND TURMA = TU.TURMA  
   )AND TURMA = TU.TURMA   
 )AS VALOR_MATRICULA,  
 (--VALOR_MENSALIDADE---------------------------------------------------------  
  SELECT  TOP 1  
    REPLACE(CAST(CONVERT(MONEY,ISNULL(CUSTO_UNITARIO/max(pl.NUM_PARCELAS),0)) AS VARCHAR),'.',',')  
   FROM     
    LY_VALOR_SERV_PERIODO VSP    
    INNER JOIN VW_FCAV_SERVICO_TURMA ST ON (ST.SERVICO = VSP.SERVICO AND ST.ANO = VSP.ANO AND ST.SEMESTRE = VSP.PERIODO)    
    INNER JOIN LY_PLANOS_OFERTADOS pl on (ST.OFERTA_DE_CURSO = pl.OFERTA_DE_CURSO)    
   WHERE    
    VSP.SERVICO LIKE 'MENS%'    
    AND ST.OFERTA_DE_CURSO = oc.OFERTA_DE_CURSO   
    AND ST.TURMA = tu.TURMA   
   group by    
    pl.NUM_PARCELAS, CUSTO_UNITARIO    
  UNION    
   SELECT     
    '0,00'  
   FROM    
    LY_TURMA     
   WHERE    
    NOT EXISTS    
    (    
     SELECT     
    1    
     FROM     
   LY_VALOR_SERV_PERIODO VSP    
   INNER JOIN VW_FCAV_SERVICO_TURMA ST ON (ST.SERVICO = VSP.SERVICO AND ST.ANO = VSP.ANO AND ST.SEMESTRE = VSP.PERIODO)    
   INNER JOIN LY_PLANOS_OFERTADOS pl on (ST.OFERTA_DE_CURSO = pl.OFERTA_DE_CURSO)      
     WHERE    
   VSP.SERVICO LIKE 'MENS%'   
   AND ST.OFERTA_DE_CURSO = oc.OFERTA_DE_CURSO   
   AND ST.TURMA = tu.TURMA    
    )    
   AND TURMA = tu.TURMA     
  ) AS VALOR_MENSALIDADE,  
  ISNULL(CT.CONTRATO,'-') AS CONTRATO,
  ISNULL(L.LINK,'-') AS LINK,
  --TU.DT_ULTALT AS DT_ULT_ALTER_TURMA,  
	 ISNULL(TU.FL_FIELD_01,'NÃO CADASTRADO') AS VALOR_CURSO,
	 ISNULL(TU.FL_FIELD_02,'NÃO CADASTRADO') AS TAXA_MATRICULA,
	 ISNULL(TU.FL_FIELD_03,'NÃO CADASTRADO') AS VALOR_PARCELAS,
	 ISNULL(TU.FL_FIELD_04,'NÃO CADASTRADO') AS QTDE_PARCELAS,
	 ISNULL(TU.FL_FIELD_05,'NÃO CADASTRADO') AS DESCONTO,
	 ISNULL(TU.FL_FIELD_07,'NÃO CADASTRADO') AS VENCTO_MATRICULA,
	 ISNULL(TU.FL_FIELD_08,'NÃO CADASTRADO') AS VENCTO_MENSALIDADE,
	 
	 ISNULL(C.FL_FIELD_01,'NÃO CADASTRADO')  AS APRESENTACAO_CURSO,
	 ISNULL(C.FL_FIELD_04,'NÃO CADASTRADO')  AS DIFERENCIAL,
	 ISNULL(C.FL_FIELD_05,'NÃO CADASTRADO')	 AS PERFIL_ALUNO,
	 ISNULL(C.FL_FIELD_06,'NÃO CADASTRADO')  AS CERTIFICACAO,
	 ISNULL(C.FL_FIELD_07,'NÃO CADASTRADO')  AS METODOLOGIA,
	 ISNULL(C.FL_FIELD_08,'NÃO CADASTRADO')  AS SISTEMA_AVALIACAO,
	 ISNULL(C.FL_FIELD_10,'NÃO CADASTRADO')  AS PROCESSO_SELETIVO,
	 
	 CASE WHEN (C.FACULDADE = 'ESPEC' OR C.FACULDADE = 'CAPAC') THEN ISNULL(C.FL_FIELD_02,'NÃO CADASTRADO') 
		ELSE ISNULL(TU.FL_FIELD_13,'NÃO CADASTRADO') 
	 END AS OBJETIVOS,
	 
	 CASE WHEN (C.FACULDADE = 'ESPEC' OR C.FACULDADE = 'CAPAC') THEN ISNULL(C.FL_FIELD_03,'NÃO CADASTRADO') 
		ELSE ISNULL(TU.FL_FIELD_14,'NÃO CADASTRADO') 
	 END AS CORPO_DOCENTE,
	 
	 CASE WHEN (C.FACULDADE = 'ESPEC' OR C.FACULDADE = 'CAPAC') THEN ISNULL(C.FL_FIELD_09,'NÃO CADASTRADO') 
		ELSE ISNULL(TU.FL_FIELD_16,'NÃO CADASTRADO')
	 END AS INVESTIMENTO,
	 
	 
	 ISNULL(TU.FL_FIELD_19,'NÃO CADASTRADO') AS PUBLICO_ALVO,
	 ISNULL(TU.FL_FIELD_20,'NÃO CADASTRADO') AS PROGRAMA,
	 
	 ISNULL(CO.FL_FIELD_01,'NÃO CADASTRADO') AS ANALISE_CURRICULAR,
	 ISNULL(CO.FL_FIELD_02,'NÃO CADASTRADO') AS ENTREVISTA,
	 ISNULL(CO.FL_FIELD_03,'NÃO CADASTRADO') AS PROVA,
	 ISNULL(CO.FL_FIELD_04,'NÃO CADASTRADO') AS REDACAO,
	 ISNULL(CO.FL_FIELD_05,'NÃO CADASTRADO') AS ALTERACAO_CONTEUDO_PROGRAMATICO,
  CASE WHEN OO.TP_INGRESSO = 'VD' THEN (select top 1 ISNULL(OP.HORARIO_DESCRICAO,'.') from LY_OPCOES_OFERTA op where op.OFERTA_DE_CURSO = oc.OFERTA_DE_CURSO)
		ELSE ISNULL(CO.FL_FIELD_06,'-') 
	 END AS DIA_HORARIO_AULAS,	
  CASE WHEN OC.CONCURSO IS NULL THEN (convert(decimal,dbo.FN_FCAV_MATRICULADO_TURMA(tu.TURMA))+convert(decimal,dbo.FN_FCAV_PREMATRICULADO_TURMA(tu.TURMA)))  
    ELSE dbo.FN_FCAV_TOTAL_INSCRITO(co.CONCURSO)   
  END AS TOTAL_INSCRITOS

FROM      
 LY_TURMA AS tu    
 --FULL JOIN VW_FCAV_INI_FIM_CURSO_TURMA oo ON TU.TURMA = oo.TURMA
 LEFT JOIN LY_CURSO C ON C.CURSO = tu.CURSO
 LEFT JOIN LY_OPCOES_OFERTA OO ON OO.TURMA = TU.TURMA
 LEFT JOIN LY_OFERTA_CURSO OC ON (OC.OFERTA_DE_CURSO = OO.OFERTA_DE_CURSO)  
-- LEFT JOIN LY_SUB_GRUPO_OFERTA SO ON SO.ID_SUB_GRUPO_OFERTA = oc.ID_SUB_GRUPO_OFERTA  
 LEFT JOIN LY_CONCURSO co ON (CO.CONCURSO = OC.CONCURSO)  
 LEFT JOIN VW_FCAV_SERVICO_TURMA SE ON SE.TURMA = TU.TURMA
 LEFT JOIN VW_FCAV_VERIFICA_CENTRO_CUSTO CC ON CC.TURMA = SE.TURMA AND CC.DISCIPLINA = TU.DISCIPLINA  
 LEFT JOIN LY_PLANOS_OFERTADOS PO ON PO.OFERTA_DE_CURSO = oc.OFERTA_DE_CURSO 
 LEFT JOIN LY_CURRICULO_CONTRATO CT ON CT.CURRICULO = oo.CURRICULO
 LEFT JOIN VW_FCAV_COORDENADOR_TURMA COOR ON TU.TURMA = COOR.TURMA
 LEFT JOIN LY_DOCENTE D ON COOR.NUM_FUNC = D.NUM_FUNC  
 LEFT JOIN LY_GRADE GR ON GR.CURRICULO = TU.CURRICULO AND TU.DISCIPLINA = GR.DISCIPLINA  
 LEFT JOIN VW_FCAV_LINK_OFERTA_CURSO_COMPLETA L ON L.OFERTA_DE_CURSO = oc.OFERTA_DE_CURSO  

-------------------------------    
--Apenas para filtro    
--WHERE     
-- oo.OFERTA_DE_CURSO = 1123
 --AND YEAR(oo.DT_INICIO) >= YEAR(GETDATE())  
-------------------------------    
GROUP BY      
 tu.TURMA, tu.CURSO, CO.CONCURSO, OC.OFERTA_DE_CURSO, tu.CURRICULO, tu.ANO,   OO.TP_INGRESSO ,
 tu.SEMESTRE, tu.TURNO, oc.DTINI, oc.DTFIM,co.DT_INICIO,co.DT_FIM,TU.DISCIPLINA,tu.DT_INICIO,  
 tu.DT_FIM, TU.SEMESTRE,TU.SERIE,TU.CLASSIFICACAO, CC.CENTRO_CUSTO_HADES,SO.SUB_GRUPO,CT.CONTRATO,  
 CC.C_CUSTO_DISCIPLINA,CC.DESCR_HADES, SE.SERVICO,TU.FACULDADE,tu.NUM_ALUNOS,oc.TURMA_PREF, oo.CARGA_HORARIA,  
 TU.DT_ULTALT,COOR.NOME_COMPL,oc.CURSO_OFERTADO, GR.DISCIPLINA,oc.CONCURSO,OC.DESCRICAO_COMPL,L.LINK,  
 PO.DESCRICAO, PO.MES_INICIAL,  NUM_PARCELAS,  PO.TIPO_DESC, PO.DESCONTO, PO.N_DIAS_VENC_BOL,  
 TU.FL_FIELD_01, TU.FL_FIELD_02, TU.FL_FIELD_03, TU.FL_FIELD_04, TU.FL_FIELD_05, TU.FL_FIELD_07, TU.FL_FIELD_08,
 TU.FL_FIELD_10, TU.FL_FIELD_11, TU.FL_FIELD_12, TU.FL_FIELD_13, TU.FL_FIELD_14, TU.FL_FIELD_15, TU.FL_FIELD_16,
 TU.FL_FIELD_17, TU.FL_FIELD_18, TU.FL_FIELD_19, TU.FL_FIELD_20, D.ATUACAO_PROFIS,
 CO.FL_FIELD_01,CO.FL_FIELD_02,CO.FL_FIELD_03,CO.FL_FIELD_04,CO.FL_FIELD_05,CO.FL_FIELD_06,CO.FL_FIELD_07,
 C.FL_FIELD_01, C.FL_FIELD_02,C.FL_FIELD_03,  C.FL_FIELD_04, C.FL_FIELD_05, C.FL_FIELD_06, C.FL_FIELD_07, C.FL_FIELD_08, 
 C.FL_FIELD_09, C.FL_FIELD_10,C.FACULDADE,COOR.TIPO_COORD